- src/core/renderers/webgl/WebGLRenderer.js
The behavior is different between Canvas and WebGL renderers. I found more instances of black as default color, so I opted to go for that.
#1325
> Change to black as default renderer color.

- src/core/math/Matrix.js
Caches x and y from point so that the calculation is correct even when pos and newPos is the same PIXI.Point.
> Matrix.applyInverse bug

- src/pixi/renderers/webgl/utils/WebGLFilterManager.js
Weird, I thought if I fixed the branch and force pushed, it should've updated #1397.
Perhaps because it was closed?
Anyways, this has been updated as per the discussion.
And for reference, it fixes #1215
> Fix WebGLFilterManager to use renderSession.resolution

- src/text/BitmapText.js
I needed this feature locally so I thought I might as well submit a pull request in case the feature is appreciated by others.
> Auto line break with max width in BitmapText

- src/core/utils/index.js
Just a small thing that popped up in jshint checks
> fix PIXI vs CONST reference

- package.json
Resolves issue #1449
When using build tools, such as Grunt, alongside Browserify or Uglify it is preferable to target a non-minified PIXI file in order to avoid double minification, since this should be left to an individual's build implementation. So it would be better if the path to the non-minified version of PIXI was set as the value for the 'main' field within the package.json.
> Set pixi.dev.js as value for 'main' within package.json

- src/text/Text.js
Follow up to https://github.com/GoodBoyDigital/pixi.js/issues/1254
I believe the descender was being drawn off the canvas
Calculating the descender could be optimized by scanning backwards for it, since the q is at the end of the string
> Fix temp text fix

- src/core/graphics/Graphics.js
Fixed tinting not working for the graphics object when using the PIXI.CanvasRenderer.
> Graphics tinting not working with canvas Issue #1410

- src/deprecation.js
Hi.
We use "AssetLoader" in 2.x, not "AssetsLoader".
> Fix a typo from "AssetsLoader" to "AssetLoader"

- src/core/math/Point.js
Hello!
I suggest to add `copy` and `equals` methods to the Point.
Why can't we have such useful methods in the Point object?
I followed the development before and saw that you didn't want to overload this object with unnecessary methods and suggested to create own extended Point instead. But...
Maybe it's just me but I use such operations A LOT. For example I use Point to represent position on the tilemap and in this case `equals` method could be very useful. But it seems to be a minor overkill to create own object for that purpose.
Also when you create some object and want to place it on the same position as the "creator" like this:
```
var o = new Entity();
o.x = this.x;
o.y = this.y;
```
I should be more efficent to make it like this
```
o.position.copy(this.position);
```
instead of …
> `copy` and `equals` methods for the Point object

- src/pixi/text/Text.js
LineJoin is now a parameter that can be passed into text style. I left default as it is ('miter') in order to prevent unwanted changes in text rendering. If you are happy with this change I'll issue another PR for v3.
//Edit - I just realised that title won't automatically link to issue, so here it is: #1522 :)
> Fix for #1522

- src/core/particles/ParticleContainer.js
This should resolve one of the bugs / todo's in #1536 
I tried keeping the logic local to the ParticleContainer class and convert from object to array there in the setProperties function. Seemed the best way.
> Make properties to upload for ParticleContainer easier to understand

- src/pixi/extras/PIXISpine.js
Attachments have their own parameters, like alpha or scale. Alpha is used to make attachment not visible regardless of slot animations.
> Spine plugin: sometimes attachments have their own alpha

- bin/pixi.js
It seems to me that even when an object is set with the cacheAsBitmap property, it should be able to respond to changes in its .visible property instantly, just as it already does with the .alpha property. This change checks the .visible property before rendering a cached bitmap, like other objects already do.
> cacheAsBitmap should respect .visible property

- src/core/textures/Texture.js
https://github.com/GoodBoyDigital/pixi.js/issues/1667
- Use `removeListener` over `remove`.
> Use removeListener instead of remove in PIXI.Texture.destroy.

- src/pixi/display/MovieClip.js
It's useful when you create a movieclip from sprites exported by https://www.codeandweb.com/texturepacker or other similar software and all frames for the movie clip are in single json file and has similar frame names. For example: frame0000.png, frame0001.png, frame0002.png, frame0004.png, etc.
Then you can just call PIXI.MovieClip.fromSettings(5, 'frame', '0000', 0, '.png');
Maybe the name "fromSettings" is not the best choise, but I could not think of a better name, so any suggestions for changes in the comment, function name, parameters names, etc are appreciated.
> Another short hand way for creating movieclips

- src/core/textures/RenderTexture.js
- src/extras/MovieClip.js
- src/extras/Ticker.js
This refactor changes ticker to only request frames when necessary. Whether the ticker has been started and has listeners are the conditions that need to be met in order to request a frame.
The API has also changed and the ticker composes itself around an emitter instead of extending the class. This not only minimizes and simplifies the API, it also allows for the previous functionality without being overly complex.
`PIXI.extras.Ticker#autoStart` property was introduced, and `PIXI.extras.Ticker` no longer exports a singleton, but instead exposes `PIXI.extras.Ticker.sharedTicker` which `PIXI.extras.MovieClip` uses. This should allow easier testing (and hopefully general usage) in the future.
> Refactor PIXI.extras.Ticker

- .jshintrc
- src/core/const.js
- src/extras/MovieClip.js
- src/extras/Ticker.js
- src/extras/index.js
- src/index.js
- src/interaction/InteractionManager.js
- src/polyfill/requestAnimationFrame.js
- src/ticker/Ticker.js
- src/ticker/index.js
These additional Ticker refactor changes include:
- Separate update() from requesting an animation frame
- This allows calling update() with a completely separate animation/ticking API if necessary or one chooses
- Complete all TODOs (documentation and more)
- Added const.TARGET_FPMS
- Added readonly property ticker.FPS
- Added readwrite property ticker.minFPS
- added polyfilled "performance" to jshint globals
- removed `global` in usages of it
> More Ticker changes

- src/ticker/Ticker.js
- src/ticker/index.js
Wouldn't consider it a critical bug since this property is really just for convenience anyway, but ticker.FPS was being calculated horribly wrong.
Outside of that... just a bunch more documentation, including examples in `ticker/index.js` docs.
> More ticker fixes

- package.json
- src/ticker/Ticker.js
- src/ticker/index.js
@englercj I'm assuming this should coincide with a resource-loader update, but getting it in here now.
Would like to give another shout out to @3rd-Eden for the enhancements, thank you!
Changes:
- move _tick check inside first started condition
- minor documentation updates
- removes the private api access on the composed emitter
- pass context in remove method
- update package.json to eventemitter3 1.0.0
> EventEmitter3 version1.0.0F, Ticker fixes

- src/filters/blur/SmartBlurFilter.js
- src/filters/blur/smartBlur.frag
Hey there !
I was toying with the SmartBlur filter and I noticed the delta param was used as a const in the fragment shader and I think it should rather be a uniform as you can end up with interesting results playing with this variable. What do you guys think ?
Thanks for the great work, I can't wait for the release of V3 :)
> SmartBlurFilter to use delta as uniform rather than const

- src/core/sprites/Sprite.js
We are using resolution prefixes in a little different way then only for retina displays. We use 0.5 resolution of textures in mobile version and 1 for desktop while renderer resolution is always one. It allows us to use smaller textures on mobile to make low-end devices handle it.
It works fine for WebGL renderer, but in canvas sprites positions were completely wrong.
This change fixes it.
> [v3] Canvas resolution fix

- src/extras/BitmapText.js
Setting a text now use toString(), like PIXI.Text.
Atm, creating a BitmapText from a number fails silently.
Note : first PR ever, so if I did something wrong, let me know.
> Small inconsistency between Text and BitmapText

- src/interaction/InteractionManager.js
When CocoonJS use a scale mode (default), global.x and global.y need to be divided by
the resolution of the interaction manager.
If you specify "no scale", it won't work properly. However, there is to my knowledge no way to detect the scale mode of CocoonJS and by default it is set to "ScaleToFill".
I believe that the default conf should work with PIXI.
Furthermore, CocoonJS defines "No scale" as a "Do it yourself" mode.
> Fix touch datas for cocoonjs default configuration

- src/extras/BitmapText.js
when text has been changed properties width/height had wrong value, to fix it we need to update text first and then calculate local bounds
> updates text before calling getLocalBounds

- src/mesh/webgl/MeshRenderer.js
indices should be updated before drawing, otherwise i get error:
```[.WebGLRenderingContext]GL ERROR :GL_INVALID_OPERATION : glDrawElements: range out of bounds for buffer```
> update indices data before drawing

- src/extras/cacheAsBitmap.js
_originalContainesPoint -> _originalContainsPoint
> Fix typo in cacheAsBitmap.js

- src/extras/MovieClip.js
If you initially set the animationSpeed to a negative value (to play the animation backwards), the current implementation fails. This PR fixes this issue.
See http://jsfiddle.net/xLzgoqbL/ to reproduce the error.
> Fixed MovieClip when using negative animationSpeed

- src/extras/TilingSprite.js
Demonstration: http://www.davidsweetman.com/pixi/demo/
When the tilePosition was set to be greater than the texture
width while a tileScale was applied, taking the tilePosition
modulo the texture width would cause the resulting texture
coordinates to drift off of whole steps of the texture.
This fix takes the tileScale into account while applying the
tilePosition.
> Fix TilingSprite tilePosition + tileScale bug

- package.json
@englercj instead of commenting yet again here https://github.com/GoodBoyDigital/pixi.js/issues/1832
I just made a PR :wink: 
This defines just 2 dirs in files `bin/` and `src/`.
`package.json`, `README.md`, and `LICENSE` are included by default.
Run the following to ensure:
```sh
npm pack
```
Also updated dev dependencies. Again like last time, browserify was a major update, tested new bin with examples repo everything seems a ok, also testem still passes. Build is just slightly faster :rocket:
> Define package files, up devDependencies

- src/core/particles/webgl/ParticleShader.js
On my machine the impact was a 50% fps boost on the bunnymark with 50,000 bunnies:
-Before: 30fps
-After: 45fps
The Improvement makes sense considering that roughly 30% of the pixels of the bunny texture are transparent and the bottleneck is blending the fragments together.
I do not know about other hardware but on my machine I still get 30fps while using completely opaque textures. Meaning that executing ```if (color.a == 0.0) discard;``` has no measurable performance impact and could be added to other fragment shaders.
> Improved Particle Shader performance by discarding transparent pixels

- CONTRIBUTING.md
- package.json
- Removed `grunt` references
- Avoid `gulp` on the guide, since `npm run build` now can do the same.
If there is a need to replace gulp with something else in the future, there is no need to change it in the contributing guide. :)
> Update CONTRIBUTING guide.

- src/core/display/Container.js
- test/unit/core/display/Container.test.js
Hello there,
This is similar to Flash's `Event.ADDED_TO_STAGE` behavior.
I've added a simple test for that. 
**Usage example:**
```javascript
class Something extends PIXI.Container {
constructor () 
{
super();
this.on('added', this.onAdded, this);
this.on('removed', this.onRemoved, this);
}
onAdded (to) 
{
console.log("I'm now attached to some Container!", to)
}
onRemoved (from) 
{
console.log("I was removed from the Container. :(", from)
}
}
```
> Trigger "added" and "removed" events when adding children on Container

- src/extras/TilingSprite.js
...in tillingsprites when using a frame from a spritesheet and a scaled
container. fix https://github.com/GoodBoyDigital/pixi.js/issues/1787
> Added a clamping to prevent gaps

- src/filters/displacement/displacement.frag
Added hack to displacement filter shader to avoid pixelized effect on some devices.
Tested devices that have the issue: iphone4, iphone4s, ipod5, ipad2
Tested devices that do not have the issue: Samsung Galaxy s3/s4, iphone 5s, iphone 6, ipad air
I know this does not look clean in the code but it has the effect of solving a very ugly bug (probably hardware related):
Before the hack:
After the hack:
PS: I stole your bunnies for this small demo but be assured that no harm was done to them (beside being exploded into 10 smaller copies of themselves)
> [Fix/Hack] Displacement filter blurry on iphone4, iphone4s and ipod5

- gulp/util/bundle.js
The sourceMappingURL comment is needed to use the JS source map
> Minifying now adds source map comment

- .gitignore
- src/core/renderers/canvas/CanvasRenderer.js
https://github.com/GoodBoyDigital/pixi.js/issues/1936#issuecomment-118040768
Beside seting roundPixels from options I also added ```.idea``` to ```.gitignore``` - please tell if I shall revert this change, or create another PR for this. I use webstorm, and having ```idea``` in pixi's ```.gitignore``` would be handy for potential future PR.
This is the same change as in my previous https://github.com/GoodBoyDigital/pixi.js/pull/1940, but my previous was to wrong branch, contained built files etc.
> CavasRendered.roundPixels can now be set from options

- src/core/sprites/Sprite.js
- src/core/utils/index.js
- test/unit/core/sprites/Sprite.test.js
- test/unit/core/utils/util.test.js
I found out that sprite.width is negative when sprite.x is negative (same for height and scale.y). Here's a fix for that, and some tests.
This is the same change as in my previous PR - https://github.com/GoodBoyDigital/pixi.js/pull/1942, but my previous was to wrong branch, contained built files etc.
> Ensure that sprite width and height are never negative

- src/core/const.js
- src/core/renderers/canvas/CanvasRenderer.js
Fixed an undefined error that would happen in the canvas renderer if no options were passed into the constructor. Also added roundPixels to the default render options.
> Fixed canvas renderer options undefined error

- src/interaction/InteractionManager.js
Fixes #1837 and #1884
Live example with the patch: https://jsfiddle.net/endel/upz3t2a0/1/
> dispatch mousemove/touchmove event only inside hit area

- src/core/sprites/webgl/SpriteRenderer.js
- src/interaction/InteractionManager.js
Fix https://github.com/GoodBoyDigital/pixi.js/issues/1787
When rendering a tilingsprite, we should use the frame and not the trimmed texture.
Thanks @greewi for this one.
I used tileScale to determine if the sprite is a tilingsprite. Tell me if you know a better way.
> Fix tilingsprite from a spritesheet

- src/core/display/Container.js
- src/core/particles/ParticleContainer.js
- src/core/particles/webgl/ParticleRenderer.js
Whenever a particle was being added or removed, the static data of every particle buffer was being uploaded. Now, only the static data of the children whose index have changed are being uploaded.
This shows good performance boost on the bunnymark when chosing moderate batch size (= 3000). The demo does not lag anymore whenever bunnies are being added.
However, the bunnymark is a perfect showcase for this optimisation as elements are only being added. Therefore only one particle buffer needs to be updated whenever a particle is being added. Actually, in average, half the particle buffer would need to be updated whenever a particle is being either added or removed. And in the worst case all the buffers have to be uploaded, as it was already the case.
> [Enhancement] Improved performance of adding and removing particles

- src/core/graphics/Graphics.js
- src/core/renderers/canvas/CanvasRenderer.js
- src/core/sprites/Sprite.js
- src/extras/TilingSprite.js
Related to pull request: https://github.com/pixijs/pixi.js/pull/2018
"On canvas when masking and changing the compositeOperation, the renderers currentBlendMode property will get out of sync with the compositeOperation (popping the canvas state returns the compositeOperation to it's previous state). 
This fix tracks the compositeOperation variable rather than currentBlendMode."
> Rebased fixes for canvas masking/renderMode

- src/extras/MovieClip.js
- src/polyfill/Math.sign.js
- src/polyfill/index.js
Examle:
var animation = new MovieClip([
{ texture: Texture(...), time: 100 },    // show 100 ms
{ texture: Texture(...), time: 0 },      // skip frame
{ texture: Texture(...), time: 500 }     // show 500 ms
]);
console.log(animation.animatinSpeed);        // --> 1
animation.animationSpeed = 2;                // play animation twice as fast
Like last time feedback is welcome ;)
regards
> Buff MovieClip: Added support for timed frames

- src/extras/BitmapText.js
new member: maxLineHeight
Use Case:
When in single line mode, it is useful the get the exact line height for vertical alignment purposes.
> class: BitmapText

- src/extras/TilingSprite.js
There is a bug in the CanvasRenderer of TilingSprite when
tilePosition + tileScale are both set.
The WebGL version of this fix was in 6d5bedd, however at the
time I didn't realize that it didn't actually fix the
CanvasRenderer version. This resolves the issue, as
demonstrated here:
http://www.davidsweetman.com/pixi/canvas-tiling-sprite-fix/
> Fix TilingSprite offset issue with CanvasRenderer

- src/core/display/DisplayObject.js
- test/lib/pixi/display/DisplayObject.js
- test/unit/core/display/DisplayObject.test.js
Because sometimes I would like to do this:
```
var container = new pixi.Container(),
graphic = new pixi.Graphics().setParent(container);
```
instead of this:
```
var container = new pixi.Container(),
graphic = new pixi.Graphics();
container.addChild(graphic);
```
> Added DisplayObject.setParent

- package.json
object-assign 3.0 contains some bugfixes, del 1.2.0 depended on object-assign 2.0.
Also updated testem, the tests are running and passing.
> updated deps

- src/core/renderers/webgl/WebGLRenderer.js
- src/core/renderers/webgl/managers/FilterManager.js
- src/core/sprites/webgl/SpriteRenderer.js
- src/core/textures/Texture.js
- src/mesh/webgl/MeshRenderer.js
Hi guys,
We've been doing some intensive memory usage testing here, and found that when running our app with Pixi for 12 hours for a KPI test we had some JavaScript memory leaks, some of which we tracked down to Pixi. The problems are:
* Super destructors (destroy) not always being called - this can result in hanging event subscriptions
* Not all managers being destroyed and nulled
* A couple of event subscriptions on Texture not being unsubscribed
What's your thoughts?
> Add calls to super destructors and other extra cleanup work.

- src/core/sprites/webgl/SpriteRenderer.js
- src/mesh/webgl/MeshRenderer.js
Closes pixijs/pixi.js#2086. Trivial fix, so I included another that popped up for `MeshRenderer`. [Fixed jsFiddle](http://jsfiddle.net/ho6qdzxk/4/).
> Fix renderer plugin destruction exceptions

- src/core/renderers/webgl/WebGLRenderer.js
- src/loaders/textureParser.js
[Fixed jsFiddle](http://jsfiddle.net/q3byr0wz/2/) that includes these changes for #1968 on top of those from #2087. While touching every texture's listeners twice can be expensive, destroying a renderer should never be in performance-critical code paths anyway.
The JSHint failure is fixed by #2087.
> WebGLRenderer texture event listener cleanup

- src/core/renderers/webgl/managers/ShaderManager.js
Not doing this causes more shaders to be created then destroyed.
> Cleanup primitive and complex shader during ShaderManager destroy

- src/core/graphics/Graphics.js
Bugfix for https://github.com/pixijs/pixi.js/issues/1844
> Bugfix for arc, always use startX and startY as first point.

- src/core/graphics/Graphics.js
- src/core/renderers/canvas/utils/CanvasGraphics.js
- src/core/textures/RenderTexture.js
Fixed bug #1999 - RenderTexture.render() does not handle Martix when using CanvasRenderer
> Fix bug #1999

- src/core/renderers/webgl/managers/FilterManager.js
- src/core/renderers/webgl/utils/Quad.js
These buffers were remaining after "exiting" Pixi.
> Clean up quad webgl buffers

- src/core/renderers/SystemRenderer.js
Node.parent property is always undefined so the renderer view never gets removed. Change to correct Node.parentNode property.
> Correctly remove renderer view when destroying renderer.

- src/core/renderers/SystemRenderer.js
- src/core/renderers/canvas/CanvasRenderer.js
- src/core/renderers/webgl/WebGLRenderer.js
I have noticed an issue with text being blurry when the anchor was set to 0.5 (iPad 2 - resolution 1)
I managed to fix the issue by setting `roundPixels = true` in both Canvas and WebGL renderers even though the property is only available in `CanvasRenderer`.
I am not sure why `roundPixels` was omitted in WebGLRenderer but any how I moved it to SystemRender so that it can be used for both the renderers.
> roundPixels for WebGL

- src/core/sprites/Sprite.js
Thanks to response issue #2159, @englercj san!
I try to fix this problem, and i confirmed this fix works well in my environment.
But, i am not sure, this fix are best fit to this problem.
As well, https://github.com/pixijs/pixi.js/blob/master/src/core/sprites/Sprite.js#L186 has codes like `utils.sign(this.scale.x)` too, but there are not need to convert zero sign, i seem.
> Issue #2159: Force to sign=1 when scale=0

- src/accessibility/AccessibilityManager.js
- src/core/display/Container.js
- src/core/renderers/webgl/WebGLRenderer.js
- src/core/utils/index.js
- src/extras/BitmapText.js
- test/unit/core/utils/util.test.js
Added a ```removeItems``` function to the ```utils``` module to replace the native Array.splice for removing array items.  Unit tests also added.
Related to #2205. This PR adds the ability to remove multiple items.
> Replace native Array.splice with manual removeItems

- src/core/particles/ParticleContainer.js
When rendering on canvas, the blend mode of the previously rendered object was used. The blend mode of the particle container will now be set correctly.
> Setting blend mode when using CanvasRenderer.

- src/core/text/Text.js
* Adds the canvas' `shadowBlur` feature in order to render blurred shadow behind the text.
* Fixes the constructor so that we can set `dropShadowAngle` and `dropShadowDistance` to `0`. Before it would just overwrite it with the default values.
> Add blurred text shadow; Fix angle and distance never getting set to 0

- src/core/display/DisplayObject.js
For the moment, PIXI.CanvasRenderer doesn't support PIXI.Sprite as mask. #2279
> Add doc hint on using Sprite mask on canvas

- package.json
- src/core/const.js
Currently `const.js` uses require to load in the project's package.json. After Browserify has bundled the source the full contents of the `package.json` file is included into `pixi.js` and `pixi.min.js`. The only reason it's being included is to get the correct version number of the `package.json` file. By including a new Browserify transform `browserify-versionify` and changing the require statement to a unique string we can reduce the size of the bundled file.
```js
},{}],12:[function(require,module,exports){
module.exports={
"name": "pixi.js",
"version": "3.0.9-dev",
"description": "Pixi.js is a fast lightweight 2D library that works across all devices.",
"author": "Mat Groves",
"contributors": [
"Chad Engler <chad@pantherdev.com>",
"Richard Davey <rdavey@gmail.com>"
],
"main": …
```
> Update const.js to use browserify-versionify

- src/core/renderers/webgl/WebGLRenderer.js
**TL;DR** Frees texture memory more quickly (which can reduce crashes on Android) after destroying a WebGLRenderer in chromium-based browsers.
This ensures that all commands are processed in a timely fashion (especially in browsers with multi-process or multi-threaded graphics architectures like chrome). Noteably, this ensures that gl textures are actually deleted around the same time that the renderer is destroyed.
This fix was found to help reduce WebGL-related crashes on older Android-based phones running chromium (in our case, an app using crosswalk to wrap up a chromium webview). This especially helps when renderers are routinely created/destroyed. 
I did some remote memory tracing using chrome's "MemoryInfra" tool. I found that without a flush at the end of the renderer destroy, …
> flush all webgl commands before the renderer is completely destroyed.

- src/loaders/spritesheetParser.js
* This changes the sprite sheet parser to automatically parse a sprite sheet in batches of 1000 frames if it contains more than 1000 frames
* After each batch, the event loop is skipped once to not block the UI
* Not implemented: As discussed in the previous version of this pull request, it might be a good idea to make batching optional via a parameter; as this might influence the interface of the loader, this was not implemented here
* Also fixes a problem where, when calling loader.reset() after loading a sprite sheet JSON has started but before its corresponding image resource has started loading, a left-over …_image resource might remain in loader.resources[], leading to an error message when trying to load the corresponding JSON again
> Proposal for issue #2377, SpritesheetParser middleware may block UI for large spritesheets

- src/filters/color/colorMatrix.frag
I believe this fixes issues #1342 and #2302. Alpha now is handled correctly when applying additive color. Credit to @andrewstart for [this fix](https://github.com/CloudKidStudio/PixiFlash/blob/master/src/ColorMatrixFilter.js).
```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Example</title>
<link rel="stylesheet" href="style.css">
<script src="pixi.js/bin/pixi.js"></script>
</head>
<body>
<canvas id="stage" width="200" height="200"></canvas>
<script>
var renderer = new PIXI.autoDetectRenderer(200, 200, {
view: document.getElementById("stage"),
backgroundColor: 0x000000,
antialias: true
});
var stage = new PIXI.Container();
var filter = new PIXI.filters.ColorMatrixFilter();
filter.matrix = [
0.4, 0, 0, 0, 0.4, 
0, 0.4, 0, 0, 0.4, 
0, 0, 0.4, 0, 0.4, 
0, 0, 0, …
```
> Fixed the alpha for the ColorMatrixFilter

- README.md
The basic example in README breaks on the first call to `animate`. 
These changes alter the scope of the `bunny` variable such that it works as expected.
> Correct a reference error in the basic example

- src/core/renderers/canvas/utils/mapCanvasBlendModesToPixi.js
require was failing on unix based systems
> Renamed Const to const

- src/extras/TilingSprite.js
Tiling sprite doesn't respect pixel ratio when rendering on canvas.
In case of using a single image for the texture it appears bigger.
In case of using atlases the bug is much more severe, as a wrong frame is being cut out from the base texture.
> Using resolution in TilingSprite canvas renderer

- src/accessibility/AccessibilityManager.js
- src/accessibility/accessibleTarget.js
Giving the ability to set the aria-label attribute for screen readers when working with accessibility
- Adding an hint property to the AccessibleTarget
- Setting aria-label attribute on div in AccessibilityManager
- Only setting default title if both `accessibleTitle` and `accessibleHint` are not set
> Adding aria-label to accessiblility

- src/core/sprites/webgl/SpriteRenderer.js
Fix incorrectly destroying the vaos when calling SpriteRenderer.destroy()
> Bugfix - Destroy VertexArrayObjects from SpriteRenderer

- package.json
Previously this wasn't required because `gulp-jshint` would install it. With `gulp-jshint@^2.0.0`  `jshint` is now a peer-dependency.
https://github.com/spalger/gulp-jshint/tree/v2.0.0
> Add jshint to dev-dependencies

- src/deprecation.js
Added support for a collapsable stack trace in deprecation warnings. Makes it easier to track-down usage of deprecated methods/properties/classes. Added some styling to the warning to clearly indicate deprecation (as opposed to WebGL warnings or other console.log warnings). For browsers that don't support `groupCollapsed`, fallback to regular `console.warn`.
**Before**
**After**
```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>Deprecation</title>
<meta name='viewport' content='width=device-width, initial-scale=1.0'>
</head>
<body>
<canvas id="stage" width="550" height="400"></canvas>
<script src="pixi.js/bin/pixi.min.js"></script>
<script>
var renderer = new PIXI.autoDetectRenderer(550, 400, {
view: …
```
> Better, more useable deprecation warnings

- src/core/ticker/Ticker.js
When you start a stopped timer, the very first timeDelta can sometimes be negative. This PR just adds a Math.max to ensure that in this case it would report 0 rather than a negative number.
Example: https://jsfiddle.net/mL4qx95n/9/
Open up the console. It will log when the value of the timeDelta is negative.
> Stop ticker from being able to report a negative deltaTime

- src/core/display/DisplayObject.js
- src/interaction/interactiveTarget.js
Added JSDoc typing to the interactiveTarget.js file
Moved hitArea out as a property from DisplayObject, since it's an interactive only property
Allowed JSDoc to now show within the DisplayObject page that there can be the interactiveTarget mixin. Previously there was no way of knowing these properties existed as interactiveTarget wasn't generated anywhere in the documentation at all.
DisplayObject now shows:
And clicking on that link takes you to:
> JSDoc for interactiveTarget

- src/core/sprites/webgl/SpriteRenderer.js
This PR depends on the acceptance of pixijs/pixi-gl-core#5
- Loop over all vertexes and destroy them.
- Remove renderer listeners
- Remove other references to objects.
Fixes #2459
> Update WebGL SpriteRenderer destroy method

- package.json
Both **async** and **glslify** are using from within the src and are needed for requiring with Node.
**glslify**
* src/core/renderers/webgl/filters/spriteMask/SpriteMaskFilter.js
* src/core/sprites/webgl/generateMultiTextureShader.js
* src/extras/webgl/TilingShader.js
* src/filters/colormatrix/ColorMatrixFilter.js
* src/filters/displacement/DisplacementFilter.js
* src/filters/godray/GodrayFilter.js
* src/filters/gray/GrayFilter.js
* src/filters/twist/TwistFilter.js
**async**
* src/loaders/spritesheetParser.js
> glslify & async should be listed in dependencies

- src/core/text/Text.js
The style.fill property supports a CanvasGradient (https://developer.mozilla.org/en-US/docs/Web/API/CanvasGradient) so it would be good if the documentation reflected that.
> Documentation update in Text.js for style.fill

- src/core/text/Text.js
Getters for width and height already do this.
Fixes problems such as https://github.com/pixijs/pixi.js/issues/2505 and https://github.com/pixijs/pixi.js/issues/2376
> Text: automatically call updateText on setters for width and height

- src/core/text/Text.js
- src/core/text/TextStyle.js
- src/deprecation.js
Instead of just setting font, and having to put the settings for bold / size etc. in the right order, these style settings are split up into the 5 style components, which are joined together automatically for you.
There is now:
fontFamily
fontSize
fontStyle
fontVariant
fontWeight
A re-submit of https://github.com/pixijs/pixi.js/pull/2539 - sorry, my lack of git skills couldn't do the rebasing you asked for, and the resident git expert couldn't help either, so was much easier to just submit a new PR!
> Text: Splitting font setting into it's various style components (take 2)

- src/interaction/InteractionManager.js
Founded and resolved by @POlITIC
> [IE] if interactionDOMElement.getBoundingClientRect doesn't exist use empty rect

- src/core/renderers/webgl/managers/FilterManager.js
#2572 fix. 
when you manually bind a texture, please switch renderer active texture by yourself.
> fix for filterManager texture binds

- package.json
- src/core/renderers/webgl/filters/extractUniformsFromSrc.js
* Updates package.json dependencies to pull from NPM releases instead of git+https.
* Updated **pixi-gl-core** implementation to match the latest publish release.
> Converts git+https dependencies to releases, fixes pixi-gl-core usage

- package.json
Follow-up to #2607 cc: @englercj & @themoonrat
I forked **jaguarjs-jsdoc** here: https://github.com/pixijs/jaguarjs-jsdoc
Also, I emailed with original NPM publisher and got added as an owner: https://www.npmjs.com/package/jaguarjs-jsdoc
I then published version 1.0.0 of the template.
> Fix jaguarjs-jsdoc dependency

- src/core/sprites/canvas/CanvasTinter.js
Also see pixijs/pixi-typescript#60
Relevant code: 
````JavaScript
/**
* Utility methods for Sprite/Texture tinting.
* @static
* @class
* @memberof PIXI
*/
var CanvasTinter = {};
````
CanvasTinter is a plain object, meaning that `new PIXI.CanvasTinter()` will crash. 
But the JSDoc, and the documentation states that it is a class. which is wrong. 
So i changed the JSDoc to reflect that it is a module.
> CanvasTinter is a plain object, not a class.

- src/core/const.js
```
* Handy for mobile devices!
* This property only affects WebGL.
```
The comment was repeated twice.
> Fixed a typo in core/const.js

- src/core/display/ObservablePoint.js
- src/extras/BitmapText.js
Fixes #1769 
```BitmapText``` (unlike ```Text```) is inheriting from ```Container``` rather than ```Sprite``` and therefore ```BitmapText.anchor``` does currently not exist. This is slightly confusing and makes aligning BitmapTexts harder than it needs to be. There are workarounds to add centring behaviour (see #1769), but they all rely on manually changing the position. 
This PR adds an ```anchor``` to ```BitmapText``` that behaves similar to ```anchor``` for ```Text```. 
Since every anchor is a ```PIXI.Point``` we can't just use a getter/setter to set ```dirty``` but instead have to regularly compare ```anchor``` against a private copy. I would have rather avoided this, but it's the only solution that I can currently see to detect those changes. Suggestions welcome!
In case of …
> Add anchor to BitmapText

- src/core/display/Container.js
- src/core/sprites/Sprite.js
- src/core/text/Text.js
- test/unit/core/display/Container.test.js
- test/unit/core/sprites/Sprite.test.js
- test/unit/core/text/Text.test.js
Based on #2536 
This is a breaking change for V4, the signature for ```Container.destroy()```. ```Sprite.destroy()``` and ```Text.destroy()``` will now only accept an optional object with the following fields. Passing a bool in (v3 behaviour) will cause an error to be thrown.
```javascript
var container = new Container();
container.destroy({children: true, texture: true, baseTexture: true});
```
All parameters default to ```false``` and will be passed on in case of ```children == true```.
As an aside, since I couldn't find anything: Is there a changelog or some sort of update instructions where breaking changes are outlined?
> Container destruction API unification

- src/accessibility/AccessibilityManager.js
- src/core/renderers/webgl/TextureManager.js
- src/core/renderers/webgl/WebGLState.js
- src/core/renderers/webgl/managers/MaskManager.js
- src/core/utils/index.js
The *[] syntax to describe a member that is an array of any type throws errors when trying to generate the docs.
I've changed this to a similar meaning Array<*> which it is happy with
> Fixes JSDoc not running to completion

- src/prepare/canvas/CanvasPrepare.js
- src/prepare/webgl/WebGLPrepare.js
Was crashing when trying to destroy renderer because plugin had not destroy method. 
Also, adds support for multiple simultaneous uploads (calling upload twice in a row).
> Adds missing destroy to Prepare, supports multiple simultaneous uploads

- src/core/sprites/Sprite.js
Related to #2623 
#2565, and WRONG FIX #2567.
v3: width,height, localBounds and bounds are outer (no trim)
v4 rc1: width,height arent trimmed, localBounds and bounds trimmed
fix #2467: width,height,localBounds are not trimmed, bounds are trimmed
this fix: like v3, nothing is trimmed.
> sprite fix, again, compatible with v3

- src/filters/colormatrix/ColorMatrixFilter.js
_(I don't want to spam you with this simple commit. My first PR was for the wrong branch, the next based on the master instead of the latest dev, now my last try. I hope this works now)_
The difference:
See here the origin of the PR:
http://www.html5gamedevs.com/topic/22808-problem-with-hue-color-shift/
And the demo (skip the shader, this PR is based on the fixed color matrix):
http://codepen.io/gkey/pen/yJeVVy
> Fix hue operation in ColorMatrixFilter

- src/core/sprites/canvas/CanvasTinter.js
This has already been fixed on the master branch through PR #2069. However, the dev branch does not appear to have the same fix. The tinting code is in a different file from master -> dev so i assume it just got lost when this was transferred. This PR restores that fix in the dev tinting code.
Also see issue #2073
> Fix #2006 by applying texture resolution to crop size

- src/loaders/bitmapFontParser.js
Recreated [pull request](https://github.com/pixijs/pixi.js/pull/2591) this time into the `dev` branch.
PIXI currently fails to load bitmap fonts from data URIs because while it can correctly parse a FNT XML document from a data URI, it fails to load the image specified inside the FNT file because it tries to prepend `xmlUrl` to the file URI.
This will successfully load the FNT file:
```
PIXI.loader.add(['data:application/xml;base64,...'])
```
If the FNT has an embedded data URI in the form:
```
<page id="0" file="/images/font.png"/>
```
This will fail because PIXI will try to prepend the data URI to it when it passes the new URL to the loader.
Fixing this issue will also allow data URIs to be used inside the FNT file to embed the image.
> Fixes loading bitmap fonts from data URIs (both FNT and Image)

- src/core/text/Text.js
Currently, a drop shadow only takes into account the actual text, and not the stroke. This can make the shadow look odd on large stroke thickness as the shadow appears much thinner than it should be.This PR fixes this issue
As a before and after example: especially note the difference on the 'e' of 'Stroke'
http://www.moonrat.co.uk/html5/pixi_before/
http://www.moonrat.co.uk/html5/pixi_after/
> Takes into account stroke thickness when drawing dropShadow

- src/extras/MovieClip.js
That bug appeared in my fork a few month ago, and @GoodBoyDigital made the same mistake with adding texture versions
> fix MovieClip texture update issue

- src/core/const.js
- src/core/display/DisplayObject.js
- src/core/display/Transform.js
- src/core/display/TransformManual.js
- src/core/display/TransformStatic.js
- src/core/graphics/Graphics.js
- src/core/graphics/GraphicsData.js
- src/core/graphics/utils/bezierCurveTo.js
- src/core/graphics/webgl/GraphicsRenderer.js
- src/core/graphics/webgl/WebGLGraphicsData.js
- src/core/graphics/webgl/utils/buildCircle.js
- src/core/graphics/webgl/utils/buildComplexPoly.js
- src/core/graphics/webgl/utils/buildLine.js
- src/core/graphics/webgl/utils/buildPoly.js
- src/core/graphics/webgl/utils/buildRectangle.js
- src/core/graphics/webgl/utils/buildRoundedRectangle.js
- src/core/math/Matrix.js
- src/core/renderers/webgl/WebGLRenderer.js
- src/core/renderers/webgl/WebGLState.js
- src/core/renderers/webgl/managers/StencilManager.js
- src/core/sprites/canvas/CanvasTinter.js
- src/core/textures/BaseTexture.js
- src/core/ticker/Ticker.js
- src/extract/canvas/CanvasExtract.js
- src/extract/webgl/WebGLExtract.js
- src/extras/MovieClip.js
- src/mesh/Plane.js
While working on a JSDoc3 theme meant to generate typescript definition files from JSDoc annotated JavaScript source (https://github.com/englercj/tsd-jsdoc) I found a few documentation errors throughout the source.
This PR is me fixing those, as well as replacing some tabs with spaces.
> Multiple documentation fixes

- src/interaction/InteractionManager.js
Adds global ("stage") input events to the InteractionManager:
* mousedown/rightdown
* mouseup/rightup
* mousemove
* mouseout (mouse leaves the stage)
* mouseover (mouse enters the stage)
* touchstart
* touchend
* touchmove
This should allow for some of the use cases of event bubbling without the performance hit of deep display lists. It should make things like dragging and gestures a little easier to manage. The events for when the mouse leaves and enters the stage should allow for showing and hiding a custom cursor rendered by Pixi without having to attach DOM events oneself.
> Global interaction events

- src/core/renderers/webgl/WebGLState.js
Small fix to resolve build jshint error:
```
src/core/renderers/webgl/WebGLState.js
--------------------------------------
W032  Line 65, Col 2  Unnecessary semicolon.
```
> Fixes jshint error in WebGLState

- src/core/text/Text.js
Was trying to work out how much texture space I was taking up with Text, and noticed that measuring that with a resolution of 1 was the same as resolution of 2. Turns out that realWidth and realHeight weren't being updated, so were always reported the default canvas creation size.
> BaseTexture used for text now reports correct realWidth and realHeight

- src/particles/ParticleContainer.js
Ran into this issue when using fallback canvas rendering during IE testing. This should address #1783.
> Fixed ParticleContainer's use of resolution in its calculations for canvas rendering

- src/core/const.js
- src/core/display/BoundsBuilder.js
- src/core/display/Container.js
- src/core/display/DisplayObject.js
- src/core/graphics/Graphics.js
- src/core/renderers/webgl/WebGLState.js
- src/core/renderers/webgl/managers/FilterManager.js
- src/core/sprites/Sprite.js
- src/core/text/Text.js
- src/core/textures/BaseRenderTexture.js
- src/mesh/Mesh.js
- test/unit/core/Bounds.test.js
- test/unit/core/LocalBounds.test.js
- test/unit/core/toGlobal.test.js
- test/unit/core/toLocal.test.js
Taking Ivans excellent bounds builder PR and simplified things a little.
By default all measurements are done the slow ‘correct’ way, and it is up the user to specify if they want to skip the update transform routine for a performance boost.
Unit tests have been added for getBounds, getLocalBounds, toLocal and toGlobal
> Dev bounds refactor

- src/core/sprites/webgl/generateMultiTextureShader.js
Precision errors can be very strange on some devices. Especially if you are rendering 3d transform. This is part of gameofbombs/pixi.js fork, I did not think that it will be needed in 2D scenes too.
Related to #2734, may be #2731 #2726 too.
> Multitexturing DERP

- src/core/textures/BaseRenderTexture.js
Previously these weren't updated so reported back as 100/100
> Able to find out the real width and height of a base render texture

- src/mesh/NineSlicePlane.js
unused mesh include caused a jsHint error, line has been removed
following @staff0rd s comment in  #2715
> Removed unused Mesh include

- src/core/text/Text.js
fix for lineHeight, canvas is actually too small if the line height is smaller than the font size.
> fix for lineHeight

- src/core/utils/index.js
http://www.html5gamedevs.com/topic/16425-ie11-software-rendering/#comment-92760
https://msdn.microsoft.com/en-us/library/dn798645(v=vs.85).aspx
If IE or Edge shows up the message "WEBGL11258: Temporarily switching to software rendering to display webGL content", WebGL detection should fail because the software rendering is slow as hell.
> Adding performance caveat context option

- src/core/renderers/webgl/managers/MaskManager.js
Currently when applying a mask to a -x2 Sprite, the Sprite resolution is lowered to that of the mask.
> MaskManager - Sprite Mask Resolution

- src/mesh/NineSlicePlane.js
Got an issue of the alpha value of NineSlicePlane. Adding  worldAlpha value to context if rendered via CanvasRenderer.
> Adding CanvasRender worldAlpha

- package.json
- src/deprecation.js
- src/index.js
Updates to [pixify@v1.2.0](https://github.com/pixijs/pixify/releases/tag/v1.2.0) which adds support for using preprocess to add comment blocks.  In the future, this feature could more broadly be used to provide better debugging features in the un-minified library (**bin/pixi.js**) and remove unnecessary code and logging from release library (**bin/pixi.min.js**). 
This PR utilizes this feature to remove the deprecations from the release build of the library.
```js
// @if DEBUG
console.error('only show in debug mode');
// @endif
```
```js
// @if RELEASE
throw 'fail hard';
// @endif
```
> Preprocess

- src/core/renderers/canvas/utils/canUseNewCanvasBlendModes.js
Multiple sites using pixi have been throwing the following error:
`Uncaught TypeError: Cannot read property 'data' of undefined.`
Additional context - I use a few extensions to prevent canvas fingerprinting and they seem to be the cause of my error.
> Add exception handling to `canUseNewCanvasBlendModes`

- src/core/display/TransformStatic.js
@ivanpopelyshev I think this is missing because the conditionals [here](https://github.com/staff0rd/pixi.js/blob/9aa8533338255c0cb9e038364045d0d763b8a778/src/core/display/TransformStatic.js#L78) and [here](https://github.com/staff0rd/pixi.js/blob/9aa8533338255c0cb9e038364045d0d763b8a778/src/core/display/TransformStatic.js#L113) eventually start comparing NaN because `_localID` is undefined.
> initialize _localID

- src/core/graphics/Graphics.js
Compare results for rounded rect the fast one:
```js
var renderer = PIXI.autoDetectRenderer(800, 600, { antialias: true });
document.body.appendChild(renderer.view);
// create the root of the scene graph
var stage = new PIXI.Container();
var clr = [0xFF700B, 0x0000FF];
var step = 0;
stage.interactive = true;
var graphics = new PIXI.Graphics();
stage.addChild(graphics);
// run the render loop
animate();
function animate() {
graphics.clear();
graphics.beginFill(clr[Math.floor(step/5)], 1);
//graphics.drawRoundedRect(50, 250, 120, 120, 5);
graphics.drawRect(50, 250, 120, 120, 5);
graphics.endFill();
step = (step+1)%10;    
renderer.render(stage);
requestAnimationFrame( animate );
}
```
> fastRect problem, again

- src/core/const.js
- src/core/text/Text.js
- src/core/text/TextStyle.js
- Removed eventEmitter from text style in favour of using a styleID. This make things a little lighter
- Removed text resolution as a parameter for text. This is now set by the renderer. So if renderer has a resolution of 2, so will the text. Much easier!
- TextStyle.padding now applies to the width of the text as well as the height.
> A few Text updates

- package.json
Adds support for linting while running watch (via `npm start`).
cc: @GoodBoyDigital
> Supports linting while running `npm start`

- package.json
Simplifies and optimizes the watch command for building (e.g., `npm start`)
* Removes **watchify** dependency
* pixify watch only builds in debug (not release) mode
* Watch now externalizes the source-maps, adds headers and apply preprocess
> Integrates pixify watch command

- src/core/display/TransformStatic.js
- src/core/sprites/Sprite.js
- src/core/sprites/webgl/SpriteRenderer.js
- test/core/Bounds.js
A variation of @ivanpopelyshev PR
This PR favours non trimmed Textures (As most will not be trimmed)
- It basically checked for trim, if its not then business as usual
- Renamed a few functions to make it easier to understand that we are calculating trimmed bounds
- Slight refactor that hopefully should make it easier to follow
- vertexTrimmedData only created when required
> sprite bounds tweaks

- package.json
As is the case in the current Pixi 
https://github.com/pixijs/pixi.js/blob/master/package.json#L35
browserify-versionify is picked up when it's a dependency, not a dev dependency.  Tried against the latest version of browserify.
> Fix browserify-versionify dependency

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
The Pixi.js community needs a declared code of conduct. While there have been no issues that I’ve seen so far, it seems entirely appropriate to add this or something similar. Inspired by the [pixi-haxe](https://github.com/pixijs/pixi-haxe/) project.
> Adds Code of Conduct

- src/core/textures/BaseRenderTexture.js
Making sure that the resolution used for realWidth & realHeight will work if nothing has been passed in as a constructor parameter
> Tweak to realWidth / realHeight in base render texture

- src/core/display/DisplayObject.js
- src/interaction/InteractionManager.js
Turns out processInteractive didnt need a fix if we Destroyed the DisplayObject correctly.
by setting interactive and interactiveChildren to false there,  it will no longer throw exceptions when an object gets destroyed in an onMouseEvent for example.
> Fix process interactive

- scripts/jsdoc.conf.json
* Resolves issue #2851
* The link was breaking the window config object in the JSdoc theme. 
* Updated the copyright year for documentation
> Removes link (breaks docs), updates year

- .travis.yml
- package.json
Supports building documentation to the S3 bucket. This can be useful for a couple of reasons:
- Always have a distributed up-to-date version of the documentation represented on a particular branch or release tag.
- Documentation is build and stored (archived) with each tag, so older versions of the docs are readily accessible. This makes the docs more future-forward, without having to so thoroughly capture old, deprecated APIs.
Here's the documentation for this branch that was build by Travis:
http://s3-eu-west-1.amazonaws.com/pixi.js/cdn-docs/docs/index.html
> Support for built, deployable documentation

- src/extras/cacheAsBitmap.js
> Fix invalid hit-testing within containers cached as bitmaps. [#2895]

- src/accessibility/AccessibilityManager.js
- src/core/text/Text.js
Do not create touch hooks for accessibility - this stops cocoon from working - Fixes: https://github.com/pixijs/pixi.js/issues/2648
Do not use gradient text, just use the first colour listed in the array - cocoon displays text with gradients as black otherwise. I think this behaviour will be more like what developers would want as a fallback
> Fixes for PIXI + Cocoon

- src/core/display/DisplayObject.js
- src/core/graphics/Graphics.js
- src/core/renderers/webgl/WebGLRenderer.js
- src/core/sprites/Sprite.js
- src/core/text/Text.js
- src/filters/colormatrix/ColorMatrixFilter.js
- src/mesh/Mesh.js
As a side note, the property ._frame on Texture, and the property _activeRenderTarget on WebGLRenderer both have the leading underscore as if they are to be private, but are publicly accessed all over the shop.
> Jsdoc fixes - marking relevant functions as @private

- src/core/text/TextStyle.js
The change has been made here: https://github.com/pixijs/pixi.js/commit/52d86a2bae9631142d4635e8421d2761023cbcbc
> Update documentation for TextStyle.padding

- src/core/index.js
`core.` being used inside `core = {...}` and small jsdoc change.
> fixes autoDetectRenderer in core/index.js

- src/core/const.js
- src/core/textures/BaseTexture.js
- src/core/textures/Texture.js
- src/core/utils/index.js
- test/core/util.js
SVG images are loaded using canvas which allows pre-texture scaling. Added 4th parameter sourceScale to BaseTexture (and Texture) which is used for scaling the SVG before creating the texture.
> Better SVG support

- src/interaction/InteractionEvent.js
- src/interaction/InteractionManager.js
I've extracted `eventData` into a new class called `InteractionEvent`. 
- what previously was  `event.target` is now `event.currentTarget` (object currently calling the callback handler)
- `event.target` now have the reference to the object that **triggered** the event
The idea here is to mimic the [DOM Event](https://developer.mozilla.org/en-US/docs/Web/API/Event/target) spec.
Is [InteractionData.target](https://github.com/pixijs/pixi.js/blob/0446c7829e9727439349d5dbbdd85f57dd54d5ea/src/interaction/InteractionData.js#L18-L23) being used right now? I guess somebody removed the usage of this at some point and it doesn't work anymore.
Cheers!
> InteractionManager: Add target and currentTarget to eventData

- src/core/text/Text.js
Don't rely on width & height clearing the canvas; both Cocoon and Safari require a proper clearRect
Resubmit of: https://github.com/pixijs/pixi.js/pull/2945
Fixes: https://github.com/pixijs/pixi.js/issues/2941
> Always clear Text Canvas via clearRect

- src/core/textures/BaseTexture.js
Fix issue when creating a BaseTexture with a 'null' source value, then using .loadSource() with an already-loaded IMG element. The 'loaded' event is never fired in that case and Texture objects are forever waiting for the 'loaded' event to be emitted.
I've added a check to see if source was valid before the loadSource() call, then emit the loaded event as necessary
> Fixed issue with delay-loaded BaseTexture objects 

- src/core/sprites/Sprite.js
While trying to switch our games to PIXI 4 we came across loads of cases where we did
```js
sprite.anchor = new PIXI.Point(0.5, 0.5);
```
which causes v4 to break in weird ways. 
This PR uses the same approach used in https://github.com/pixijs/pixi.js/blob/dev/src/extras/BitmapText.js#L366 to make assignments save again and to make updating from v3 to v4 a little easier.
> Allow anchors to be asssigned without breaking ObservablePoint

- src/core/graphics/Graphics.js
Sets the generated texture's resolution properly and calls `texture.update()`.
Resolves the underlying issue that caused #2940.
I wonder if BaseTexture.resolution docs also need a comment noting that if you set it manually, you must call BaseTexture.update() for it to be effected?
> Properly set resolution

- src/core/text/Text.js
I was measuring the total texture pixels being used by Text I created, and noticed that measurement went _down_ during gameplay.
Turns out it's because when Text is created, a canvas is created, and a texture created from it. However, the default canvas size is 150x300 (at least on Chrome) which is usually far larger than actually required. And that only gets updated the first time text gets rendered, which for some hidden away screens or menus, could be a fair while.
So I've changed this default size down to a super small 16x16, so no memory is wasted on unrendered text. Estimated texture memory usage of text went from 21mb to 3mb in my game.
> Smaller default texture size for text

- src/core/textures/VideoBaseTexture.js
- https://github.com/pixijs/pixi.js/commit/8d39e810c595b0afc48e542b2d4cad9c204cc7d2 didn't fully solve the video loading issues; the examples page for videos still doesn't work. I've tracked that down to the static 'fromUrl' function, which called video.play(). This was a tad early, resulting in width and height being 0. Removing the .play here doesn't matter, as it is still automatically called within _onCanPlay()
- autoUpdate changed to a getter/setter. It's doc states that it could be used to control when auto updating happened, but this wasn't true, it was actually just an internal variable to check whether it was currently auto updating or not. I've create a couple of private tracking variable for this state, whilst the public getter / setting now truly controls autoUpdate as per …
> VideoBaseTexture fixes and changes

- src/core/display/Container.js
Returns prior capability of `Container.addChildAt(something, 0)` when `Container.children.length === 0`.
> Allow Container.addChildAt when zero children

- .travis.yml
* Renames the S3 bucket to be “pixi.js” instead of “pixi-builds”. This change makes it easier to remember, consistent with the name of the module and bucket names for other modules (like **pixi-gl-core** and **pixi-filters**).
_Note: links will need to be updated in the Wiki: https://s3-eu-west-1.amazonaws.com/pixi.js/dev/pixi.js_
> Renames S3 bucket from "pixi-builds" to "pixi.js"

- src/core/renderers/webgl/WebGLRenderer.js
- src/core/renderers/webgl/utils/checkMaxIfStatmentsInShader.js
Looks like since we call loseContext() on `WebGLRenderer#destroy()` that
if you create another WebGLRenderer with the same canvas the browser will
recycle that lost context and return it.
This means when we try to use the context it is actually in a lost state.
This change tries to restore a lost context before we use it. It also adds
a debug assert at one location that will be invalid if the context is
invalid.
> Restore lost context before using it

- src/extras/TilingSprite.js
I ran into a problem if the base texture resolution is not 1 and the renderer is not WebGL. The resolution auf the base texture is nowhere considered. This is how i solved it. The solution is probably not the best...
> TilingSprite BaseTexture resolution

- src/extras/TilingSprite.js
When a tiling sprite was destroyed the setter was called, which would
set the point value to null. This gave an error while Point.copy does
not like null values.
My fix is to bypass the setters and set the object properties to null.
I’ve added the uvTransform also.
> Fix for tilingsprite destroy

- src/core/utils/index.js
- src/deprecation.js
In v4.1.0, `PIXI.utils._saidHello = true` was removed in favor of `PIXI.utils.skipHello()`. This PR provides the backward compatibility. It also documents skipHello.
> Document skipHello, deprecates _saidHello

- src/extras/MovieClip.js
Employs the same approach for updating the current frame and invoking the `onFrameChange` callback as `gotoAndStop()`
> Update MovieClip frame immediately with gotoAndPlay #3180

- src/core/const.js
- src/core/utils/index.js
- test/core/util.js
Was unable to create textures from SVGs when optimized according to https://codepen.io/tigt/post/optimizing-svgs-in-data-uris due to the regex only excepting one set of quotes.
> Adjust SVG_SIZE regex to support finding either format of quotes

- src/core/textures/BaseTexture.js
- test/core/BaseTexture.js
- test/core/index.js
The adding of SVG support added a requirement of `imageType`, which is determined by the file extension, and was throwing were no extension available. There doesn't seem to be a way to determine an `HTMLImageElement`'s image type, so this PR just allows non-svg images to be extension-less as per prior functionality.
The caveat is that svg image types cannot be loaded without an extension.  A couple of options to enable it would be;
1) Extend `*.fromImage()` to allow a user to specify an `imageType` override (easy)
2) xhr images as byte arrays instead of Image, determine type from data, convert to image (hard)
> Allow extension-less image urls

- src/interaction/InteractionManager.js
* Fixed issue where browsers that supported pointer events would no longer fire mouse events.
* Changed ordering of listeners, so that they are normalized events are sent in the same order as non-normalized events. pointer event first, mouse/touch event 2nd
https://github.com/pixijs/pixi.js/pull/2997
https://github.com/pixijs/pixi.js/issues/3167
https://github.com/pixijs/pixi.js/issues/3158
> Fixed interaction issues with pointer events

- src/core/ticker/index.js
- src/deprecation.js
- src/extras/AnimatedSprite.js
- src/extras/index.js
Renames `PIXI.extras.MovieClip` to `PIXI.extras.AnimatedSprite` for these reasons:
- The name "MovieClip" does not accurately reflect the nature of the class.
- Preventatively, do not want to confuse this class with a new forthcoming MovieClip API
> Renames MovieClip to AnimatedSprite

- src/core/text/Text.js
- src/deprecation.js
- src/prepare/BasePrepare.js
- src/prepare/canvas/CanvasPrepare.js
- src/prepare/index.js
- src/prepare/limiters/CountLimiter.js
- src/prepare/limiters/TimeLimiter.js
- src/prepare/webgl/WebGLPrepare.js
- test/index.js
- test/prepare/BasePrepare.js
- test/prepare/CountLimiter.js
- test/prepare/TimeLimiter.js
- test/prepare/index.js
* Combines the shared code of WebGLPrepare and CanvasPrepare into one BasePrepare class.
* Makes the rate limiting functionality more configurable by changing it to be class based and adding a class for limiting based on time spent preparing.
* Adds hooks for both WebGL and Canvas for preparing PIXI.Text and PIXI.TextStyle objects.
* Adds unit tests for the rate limiting and basic functionality of BasePrepare.
I did some testing of GPU upload times on a mobile device and found that texture upload time was quite variable and generally expensive, so I wanted to be able to limit preparation to a specified amount of time to attempt to preserve the framerate instead of loading as quickly as possible.
I also found that calculating the font properties was generally worse than uploading any …
> More flexible preparation limits

- src/loaders/spritesheetParser.js
* Adds support for using the `meta.scale` property of spritesheet format to determine the resolution rather than relying on the filename (e.g., `@2x.png`), for conditions when renaming the file might not be appropriate. 
_Note: this is also needed to support an optimization feature in PixiAnimate_
> Spritesheet Scale

- src/extract/canvas/CanvasExtract.js
- src/extract/webgl/WebGLExtract.js
The position of the doc block is a bit awkward, but I'm not sure there's really a better place for it.
Declaring it where the plugin is registered [(here)](https://github.com/pixijs/pixi.js/blob/master/src/extract/webgl/WebGLExtract.js#L223) would clarify why the property is being set for the renderer, but obscure what's being set in the first place.
> Add jsdocs for renderer.extract property

- .babelrc
- .eslintrc.json
- .gitignore
- .travis.yml
- package.json
- scripts/release.js
- src/core/const.js
- src/core/renderers/webgl/filters/spriteMask/SpriteMaskFilter.js
- src/core/sprites/webgl/generateMultiTextureShader.js
- src/extras/webgl/TilingSpriteRenderer.js
- src/filters/colormatrix/ColorMatrixFilter.js
- src/filters/displacement/DisplacementFilter.js
- src/filters/fxaa/FXAAFilter.js
- src/filters/noise/NoiseFilter.js
- src/filters/void/VoidFilter.js
- src/mesh/webgl/MeshRenderer.js
- test/index.js
Removes the ES6 src directory from npm and replaces with a lib folder, which is now the main point for the package.json's `main` field. Creates bundled files in the "dist" folder and individual files in the "lib" folder. 
This should help resolve issues with devs using webpack and other build systems that are more friendly with unbundled modules.
> Build System, Babel and ES6 src

- src/core/Shader.js
- src/core/const.js
- src/core/display/DisplayObject.js
- src/core/index.js
- src/core/renderers/SystemRenderer.js
- src/core/renderers/canvas/CanvasRenderer.js
- src/core/renderers/canvas/utils/CanvasRenderTarget.js
- src/core/renderers/webgl/TextureGarbageCollector.js
- src/core/renderers/webgl/utils/RenderTarget.js
- src/core/settings.js
- src/core/sprites/Sprite.js
- src/core/sprites/webgl/SpriteRenderer.js
- src/core/text/Text.js
- src/core/textures/BaseRenderTexture.js
- src/core/textures/BaseTexture.js
- src/core/textures/RenderTexture.js
- src/core/textures/Texture.js
- src/core/textures/VideoBaseTexture.js
- src/core/ticker/Ticker.js
- src/core/utils/index.js
- src/deprecation.js
- src/extras/TilingSprite.js
- test/core/DisplayObject.js
- test/core/TilingSprite.js
There are a handful of settings in **src/core/const.js** that are actually intended to be writable. Because these are exported, they cannot be changed. This PR deprecates the high-level properties and moves them to a `PIXI.settings` namespace object, which can be edited. _This restores functionality that was lost when converting to ES6._
* `PIXI.RESOLUTION` => `PIXI.settings.RESOLUTION`
* `PIXI.FILTER_RESOLUTION` => `PIXI.settings.FILTER_RESOLUTION`
* `PIXI.TARGET_FPMS` => `PIXI.settings.TARGET_FPMS`
* `PIXI.MIPMAP_TEXTURES ` => `PIXI.settings.MIPMAP_TEXTURES `
* `PIXI.SPRITE_BATCH_SIZE ` => `PIXI.settings.SPRITE_BATCH_SIZE `
* `PIXI.SPRITE_MAX_TEXTURES` => `PIXI.settings.SPRITE_MAX_TEXTURES`
Preview the [docs here](http://pixijs.download/dev-settings/docs/PIXI.settings.html).
Fix for …
> Moves constants that are actually settings

- src/core/index.js
- src/core/renderers/canvas/utils/mapCanvasBlendModesToPixi.js
- src/core/renderers/webgl/utils/mapWebGLBlendModesToPixi.js
- src/core/renderers/webgl/utils/mapWebGLDrawModesToPixi.js
- src/core/utils/createIndicesForQuads.js
- src/core/utils/index.js
Currently the doc contain a few references to exports and module.export. See [here](http://pixijs.download/dev/docs/PIXI.utils.html). Makes these explicit for JSdoc, which seems to be having trouble with the exports.
See updated docs [here](http://pixijs.download/fix-jsdocs/docs/PIXI.utils.html)
> Fixes jsdoc issues with exports and module.exports

- package.json
* Adds support for using [**beefy**](https://www.npmjs.com/package/beefy) with `require(‘pixi.js’)`
cc @GoodBoyDigital
> Support for beefy by removing browserify config

- src/core/renderers/webgl/TextureGarbageCollector.js
- src/core/settings.js
- src/prepare/BasePrepare.js
As a follow-up to #3298, @themoonrat suggested adding some additional settings. 
* PIXI.settings.GC_MAX_IDLE
* PIXI.settings.GC_MAX_CHECK_COUNT
* PIXI.settings.UPLOADS_PER_FRAME
> Adds additional Prepare and GC settings

- src/core/index.js
Resolves #3329 by publicly exposing the Bounds class to the PIXI namespace.
> Expose the PIXI.Bounds class again

- bower.json
Resolves #3327, changes the name from "bin" to "dist" in **bower.json**.
> Bower main fix, "bin" renamed "dist"

- README.md
Updates the build instructions to match the latest build process in v4.2.x
Fixes #3322 (thanks @Friksel for pointing this out)
> Fixes the readme for bundle building excludes

- src/core/const.js
- src/core/settings.js
Per @themoonrat's suggestion in #3298, makes the type valuable click-able. Also, adds a bunch of docs that were missing from CONST.
**Preview:**
http://pixijs.download/fix-settings-docs/docs/PIXI.html
http://pixijs.download/fix-settings-docs/docs/PIXI.settings.html
**Current (old):**
http://pixijs.download/dev/docs/PIXI.html
http://pixijs.download/dev/docs/PIXI.settings.html
> Fixes links to docs

- src/core/text/Text.js
* Fixes issue #3349 by putting quotes around fontFamiy when setting the font style.
> Fix for Text's fontFamily

- src/interaction/InteractionManager.js
Suggested by @bqvle. Tested on iphone,
getClientBoundingRect and coords are screwed, that's why its different by "resolution^2"
> cocoonJS interaction position fix

- src/core/renderers/canvas/utils/canUseNewCanvasBlendModes.js
createColoredCanvas() was documented as taking a number, but should have
said it takes a string. issue #3350
> #3350 Fixed createColoredCanvas() documentation

- src/core/text/TextStyle.js
- test/core/TextStyle.js
- test/core/index.js
defaultText had been moved, but there were references to the old location when cloning or resettings.
Unit tests for these added too
> Text style fixes

- src/core/display/TransformStatic.js
```
const pt = parentTransform.worldTransform;
const wt = this.worldTransform;
```
the code above in updateTransform  is not needed always.
And another reason is like  https://github.com/pixijs/pixi.js/pull/3391
> Change the code lines order in updateTransform in TransformStatic.js

- src/core/utils/index.js
- src/loaders/spritesheetParser.js
Addresses #3458
This PR tweaks the logic for when to respect a spritesheet's internal `scale`.
The current implementation reads the filename but defaults to `1` and then overrides with the JSON scale if it's defined and not `1`.
This change prioritizes the filename resolution (e.g. @2x). If that isn't set, it falls back to the `scale` value set in the JSON. Otherwise, resolution of `1`. 
For example, now if a file is named `atlas@1x.png` with a corresponding scale value of `0.5` in the JSON data, the resolution will be `1` instead of `0.5`. 
* Adds an additional argument for `PIXI.utils.getResolutionOfUrl` to define the default value.
> Fixes logic for spritesheet resolution

- src/interaction/InteractionEvent.js
An attempt to clarify issues like #3450 with respect to accesing `target` rather than `currentTarget`.
Property name change would probably greatly benefit here, but would  be breaking.
> InteractionEvent.target clarification

- src/filters/blur/BlurFilter.js
- src/filters/blur/BlurXFilter.js
- src/filters/blur/BlurYFilter.js
Add parameter kernelSize for blur filters.
```
/**
* ......
* @param {number} kernelSize - The kernelSize of the blur filter.Options: 5, 7, 9, 11, 13, 15.
*/
constructor(strength, quality, resolution, kernelSize)
{
kernelSize = kernelSize || 5;
// ......
}
```
related issue : https://github.com/pixijs/pixi.js/issues/3242
> Add parameter kernelSize for blur filters.

- src/core/text/TextStyle.js
I know internally, canvas likes "#FF0000" for setting colours, but I find it easier to have all values as "0xFF0000" in my settings json. "0x" notation already works in places such as tinting, so I like being able to have this consistency into TextStyle
> Allow '0x' notation of colours via strings to work in Text class

- src/core/renderers/webgl/TextureGarbageCollector.js
Do not unload generated textures when manually running the texture garbage collector. This check is already in place for when it is run automatically. The check is there, as otherwsie the texture to not be able to be renderered again.
Fixes: https://github.com/pixijs/pixi.js/issues/3215
> Fix for the texture garbage collector

- src/core/graphics/Graphics.js
- test/core/Graphics.js
Test case for #3414, plus a potential fix.
@GoodBoyDigital, I'm presuming [this line](https://github.com/pixijs/pixi.js/commit/46b063f501410de6420c4f441e48d23cae33c666#diff-ffbed917ef49b1b44e503c3e91f37be1R790) is a mistake?
> Test case & fix for Graphics._calculateBounds calling updateLocalBounds every time

- src/core/graphics/Graphics.js
Clear something that should be cleared.
```js
this.currentPath = null;
this._spriteRect = null;
```
if no this patch , some test cases will be failed.
There are some common codes of test cases :
```js
var renderer = new PIXI.WebGLRenderer(900, 600, {
clearBeforeRender: false,
backgroundColor: 0xFFFFFF
});
document.body.appendChild(renderer.view);
// the root container.
var stage = new PIXI.Container();
// a shared graphics for drawing multi shapes
var graphics = new PIXI.Graphics();
stage.addChild(graphics);
```
If no  ```currentPath = null ``` ,  the second arc can't be rendered, and there is no error on browser's console.
```js
// clear manually
renderer.clear();
graphics.clear();
graphics.beginFill(0xFF0000);
graphics.arc(150, 160, 100, 0, Math.PI * 2, false);
graphics.endFill();
// …
```
> Update `clear` for a more thorough cleaning

- src/core/renderers/webgl/WebGLRenderer.js
```
this._activeRenderTarget = null;
this._activeTextureLocation = 999;
this._activeTexture = null;
````
must before `this._indexContext()` , otherwise  the _activeRenderTarget & _activeTexture init in  _indexContext will back to `null`.
> Protect the initial state  of `this._activeRenderTarget` in _indexContext

- src/core/sprites/Sprite.js
In get/set width/height method , we don't need use  `this.texture` .
We could use `this._texture.*` to instead of `this.texture.*` , and it could offer a bit little performance gains.
> Use `this._texture.*`to instead of`this.texture.*`

- src/core/sprites/webgl/SpriteRenderer.js
It was an when alpha property is greater than 1.0 . limiting the alpha to 1.0 will avoid alpha flickering when object.alpha is grather than 1.0
> limit alpha number to 255. at rendering.

- src/core/sprites/webgl/SpriteRenderer.js
it could offer a bit little performance gains.
> Use `*._texture.*`to instead of`*.texture.*`

- src/core/text/Text.js
It could offer a bit little performance gains.
and in current version  https://github.com/pixijs/pixi.js/blob/master/src/core/text/Text.js#L637  , there is already used `_texture` .
So I think this patch is OK.
> Use `*._texture.*` instead of`*.texture.*`

- package.json
- src/deprecation.js
- src/loaders/bitmapFontParser.js
- src/loaders/loader.js
- src/loaders/spritesheetParser.js
- src/loaders/textureParser.js
- test/index.js
- test/loaders/bitmapFontParser.js
- test/loaders/index.js
- test/loaders/loader.js
- test/loaders/spritesheetParser.js
- test/loaders/textureParser.js
I put in backward compat handling, or deprecation warning, for all v2 changes except for one:
- If a middleware adds more resources, it must pass in the parent resource in options for .add().
I've updated our middleware to follow this rule, but if there are other ones floating around out there they will need to do this for child resources as well. Otherwise, they will get an error.
Also closes: #3116
> Update to Resource loader v2; fixes #2876

- src/core/text/Text.js
- src/core/text/TextStyle.js
- test/core/Text.js
Addresses #3406 
* Allows support for multiple fonts in the TextStyle#fontFamily property. Either expressed as a comma separated string, or an Array of font names.
> Adds support for multiple font families

- src/core/text/Text.js
This feature could help users to  share canvas among two or more  Text  objects （ like Graphics._SPRITE_TEXTURE in Graphics).
In the game ,normally  we need rebuild stage/scene when stage/scene changed ,  If Text supports passing canvas , we could avoid create and destroy HTMLCanvasElement often when game running. 
e.g. create a canvas-pool  cache some canvas for Text.
> The canvas could be passed into Text

- src/core/textures/Texture.js
In Texture , the `orig` is always exist after new Texture object . 
If `orig` is not accessible , there will be a bug in the App.
The developers must fix it , not ignore and return `0`.
> Remove  the needless checking for `orig`

- src/particles/ParticleContainer.js
For better performance ,  a bit little  , but worth.
> Use `child._texture` instead of `child.texture`.

- src/core/renderers/canvas/CanvasRenderer.js
WebGLRenderer has the ```clear``` method , I think CanvasRenderer should has it too.
Sometimes, maybe we want to clear the canvas manually via ``` game.renderer.clear()``` .
If  CanvasRenderer doesn't  has this method ,  there will be an error.
> Add clear method to CanvasRenderer

- src/extras/TextureTransform.js
In `update` method , there is already  `tex` , we shouldn't use `this.texture` any more.
> Use `tex` instead of `this.texture`

- scripts/jsdoc-fix.js
* Provides a workaround for JSDoc issue https://github.com/jsdoc3/jsdoc/issues/1301 causing member properties to be omitted.
**Preview:**
http://pixijs.download/fix-docs/docs/index.html
**Example:**
* [DisplayObject w/o hack](http://pixijs.download/dev/docs/PIXI.DisplayObject.html)
* [DisplayObject w/ hack](http://pixijs.download/fix-docs/docs/PIXI.DisplayObject.html)
> Adds hack for doc members fix

- src/core/display/Container.js
- src/core/graphics/Graphics.js
- src/particles/ParticleContainer.js
Documents the .texture and .baseTexture parameters for the destroy method settings object. They may not be used for the class itself, but could get propagated down to children.
Fixes https://github.com/pixijs/pixi.js/issues/3407
> Improved documentation of the destroy method

- src/index.js
Fixes https://github.com/pixijs/pixi.js/issues/3291
Exporting the polyfills is a way of making sure they are also imported straight away.
> Ensure that polyfills are import first

- src/core/sprites/webgl/texture.vert
Fiddle: https://jsfiddle.net/Icemic/wmdruwLc/show/light/
Device: MEIZU MX5 ( Android 5.1 )
Browser: Chromium
CPU: MTK Helio X10 Turbo (MTK6795)
GPU: PowerVR G6200
Detail: Draw a 800\*600 image to a 800\*600 canvas, there will be a 1px width line at right. After some test, I find that the image is scaled to 799\*600. It must be to do with precision, maybe a GPU bug.
Solution: add `precision highp float;` to `pixi.js/src/core/sprites/webgl/texture.vert` (default is `mediump`)
Note: Need more test for detecting how many CPUs/GPUs effected by this bug.
> use high precision float instead of medium in texture shader

- src/core/text/Text.js
There are 2 bugs :
* should NOT use `this.context.lineWidth`  before `this.context.lineWidth = style.strokeThickness`.
* The default value of `style.strokeThickness` is `0` , but  `this.context.lineWidth` couldn't be 0 ( in HTML5 , context.lineWidth = 0 will be ignore). So we should NOT use `this.context.lineWidth` for computing size.
-------
Update commit https://github.com/pixijs/pixi.js/pull/3519/commits/81322e377e22d5978fe73e3f589e5b1cce139faf : 
In fact , we shouldn't ` + style.strokeThickness` again . because the `width` has added `style.strokeThickness`.
https://github.com/pixijs/pixi.js/blob/dev/src/core/text/Text.js#L153-L162
```js
// ****** has add style.strokeThickness to width 
let width = maxLineWidth + style.strokeThickness;
if (style.dropShadow)
{
width += …
```
> Fix a bug about compute Text canvas size.

- src/core/display/Container.js
In some complex/advanced  use case ， users would call `updateTransform` manually.
And , if  `renderWebGL` is public , `updateTransform` should be public too.
> Remove `@private` of `updateTransform`.

- README.md
Utilizes Application API in #3551 to create a simpler, more streamlined example in the readme.
Here's the version without comments:
```js
var app = new PIXI.Application();
PIXI.loader.add('bunny', 'bunny.png').load(function(loader, resources) {
var bunny = new PIXI.Sprite(resources.bunny.texture);
bunny.x = app.renderer.width / 2;
bunny.y = app.renderer.height / 2;
bunny.anchor.x = 0.5;
bunny.anchor.y = 0.5;
app.stage.addChild(bunny);
app.ticker.add(function() {
bunny.rotation += 0.01;
});
});
> Update the readme with Application example

- src/extras/AnimatedSprite.js
Add a argument to control whether use core.ticker.shared to update animation.
Related Issue :  https://github.com/pixijs/pixi.js/issues/3428
Default value is true.
```
new AnimatedSprite(textures)  ---> use core.ticker.shared to update, as same as current version.
new AnimatedSprite(textures, false)   ---> don't use core.ticker.shared to update.
```
> Control whether use core.ticker.shared to update

- test/interaction/InteractionManager.js
I've added the following tests to help document the expectations of the InteractionManager specific to when the scene includes children that overlap.  The tests set up a scene similar to [this pen](https://codepen.io/staff0rd/pen/MJWJdy?editors=0010) and then fire clicks at various points on it.
I have left one test failing because it _feels_ off, considering the expectation is valid and passes when the parent is non-interactive.  I need some feedback regarding a decision on whether;
1. ~The expectation is wrong, and the test should be changed or;~
2. The expectation is correct, and the API needs to change ✔️ 
Upon which the following issues at least are then possibly fixed or are a step closer to resolution; #3419, #2921, #2364, #1901.
* when both children are interactive …
> Added overlapping children tests

- src/accessibility/AccessibilityManager.js
- src/accessibility/accessibleTarget.js
- src/accessibility/index.js
- src/core/math/GroupD8.js
- src/core/sprites/canvas/CanvasTinter.js
* Updates accessibility namespace, which was missing.
* CanvasTinter and GroupD8 should be doc’d as classes with static methods, not namespaces.
Preview: http://pixijs.download/docs/docs/index.html
PIXI: [new](http://pixijs.download/docs/docs/PIXI.html) [old](http://pixijs.download/release/docs/PIXI.html)
PIXI.accessibility: [new](http://pixijs.download/docs/docs/PIXI.accessibility.html)
GroupD8: [new](http://pixijs.download/docs/docs/PIXI.GroupD8.html) [old](http://pixijs.download/release/docs/PIXI.GroupD8.html)
CanvasTinter: [new](http://pixijs.download/docs/docs/PIXI.CanvasTinter.html) [old](http://pixijs.download/release/docs/PIXI.CanvasTinter.html)
> Namespace Doc Updates

- scripts/renders/client.js
* Changes the path for Pixi when running `npm run renders`, causing the Electron app to fail.
> Fixes path for renderers client

- src/core/renderers/canvas/utils/CanvasRenderTarget.js
- src/core/renderers/webgl/filters/Filter.js
- src/core/textures/BaseRenderTexture.js
- src/filters/blur/BlurFilter.js
- src/filters/blur/BlurXFilter.js
- src/filters/blur/BlurYFilter.js
Set `this.resolution` to `settings.RESOLUTION` instead of `1`, otherwise texture will be blurred in retina screens (where `settings.RESOLUTION` may be setting to `2` or above).
> Fix resolution setting of PIXI.Filter, and another two wrong codes on resolution importing

- src/core/text/Text.js
- src/core/text/TextStyle.js
Currently, doing
fill: ["#FF0000", "#00FF00", "#0000FF"]
evenly spaces those gradient points out, but sometimes you might want more control over each stop point. With this PR you can optionally adjust these points; for example
fillGradientStops: [0.1, 0.3, 0.9]
> Ability to set stop points on Text with a gradient

- src/core/text/Text.js
Does this by resetting this.context.shadowBlur both if it not required whilst drawing the shadow, and also after drawing the shadow
Fixes: https://github.com/pixijs/pixi.js/issues/3621
> Stops shadow blur appearing on the text as well as shadow

- src/core/renderers/webgl/managers/FilterManager.js
- src/filters/displacement/DisplacementFilter.js
There is a issue : If the filter used `filterClamp` or `filterArea` ,  the canvas will flash when the filter be added.
(see #3609 )
This PR fix this issue.
> Fix #3609 , about `filterClamp` & `filterArea` 

- src/core/text/Text.js
- test/core/Text.js
We got a weird glitch upgrading from pixi 3 to 4, setting the text in a PIXI.Text to 0 results in the label actually saying ' '. This seems like unexpected behaviour considering all the other numbers work :)
> fix unexpected 0 text behaviour

- src/core/sprites/webgl/SpriteRenderer.js
If max textures is one it can omit the attribute. This check that it exists..
> Added a fix for the Chrome on android

- src/core/textures/Texture.js
Every now and then we stumble across this error in our logs:
```Texture Error: frame does not fit inside the base Texture dimensions [object Object]```
It's most likely a problem with some of our sprite packing, but it's always a hard one to debug. It doesn't help that the ```[object Object]``` bit is very unhelpful ;)
I know this error is not very common, but if one does come across it it's going to be a massive help to have a bit more information that helps pinpoint the culprit.
> Improve error message for out-of-bounds Textures

- src/core/renderers/webgl/managers/FilterManager.js
The shaderCache is initially created as an object. When the Filter Manager gets destroyed, it should be reset to an empty object, not an array.
> FilterManager shaderCache reset as object

- test/core/Graphics.js
Seems [this is the case](https://github.com/pixijs/pixi.js/blob/e1b98404a982467811ee655de8372bd5d1d77177/src/core/graphics/Graphics.js#L863-L866), so I've added the expectation to tests.
> Added Graphics.containsPoint with no fill expectation

- src/core/renderers/webgl/utils/RenderTarget.js
- src/core/textures/BaseRenderTexture.js
- src/core/textures/BaseTexture.js
- src/core/textures/RenderTexture.js
Resolves #3660 
RenderTexture was not respecting the `PIXI.settings.SCALE_MODE` as the proper default.
Also, this fixes the logic in several class using the SCALE_MODE as the default. Because LINEAR is `0`, setting this manually would always default to the default.
* **Broken** [example](https://jsfiddle.net/k9ror7dL/1/) (latest release)
* **Fixed** [example](https://jsfiddle.net/8sz55dxt/3/)
> Better use of scale mode default

- test/core/WebGLRenderer.js
Small tweak follow-up to #3630
This way WebGL-only tests show-up as skipped in the Mocha output.
> Fixes tests check for isWebGL

- src/core/Application.js
- src/core/renderers/SystemRenderer.js
- src/core/renderers/canvas/CanvasRenderer.js
- src/core/renderers/webgl/WebGLRenderer.js
According to #3641, we really have a problem. Not even core developers know what does "width" or "height" mean.
Proposition:
1. screen.width and screen.height are used for the stage
2. view.width and view.height are size of canvas, thus they are measured in real pixels
If this one will be approved, I will move forward to
1. ultimate resize logic: resizeView, resizeScreen, resizeCss with autoUpdate tying them to each other. resizeBack for overriding by canvas&webgl. onResize event/signal/whatever
2. possible accessability fixes, I just saw a number of uses of "renderer.width" there which aren't that clear
3. jsdocs for all "width"s and "height"s, explaining which are actually screen coords and which are physical pixels. Most of them will be screen'ed, of course.
4. possible deprecation of …
> initial commit for ultimate renderer dimensions solution

- src/accessibility/AccessibilityManager.js
- src/core/utils/index.js
- src/core/utils/mixin.js
- src/deprecation.js
- src/index.js
- src/interaction/InteractionManager.js
- src/interaction/InteractionTrackingData.js
- src/interaction/interactiveTarget.js
- test/interaction/InteractionManager.js
- test/interaction/MockPointer.js
Changed how cursors are handled:
* `InteractionManager` has a `cursorStyles` dictionary, which is a number of CSS cursor styles, callbacks upon cursor change, or dictionaries of CSS properties.
* `InteractionManager` tracks the cursor mode, and then handles it according to its `cursorStyles` dictionary.
* `interactiveTarget.cursor` is the cursor mode to be used when moused over. It is not limited to just 'default' and 'pointer'.
* `interactiveTarget.buttonMode` now just sets cursor to 'pointer'.
Also, added some mixin utilities so that the Accessibility and Interaction mixins can use accessors and can be affected by deprecations.
This does not directly fix #3301, but allows users to specify callbacks for cursor changes _instead_ of changing CSS, so that their callbacks can change CSS …
> Reworked cursor handling to expand cursor options.

- src/core/renderers/webgl/WebGLRenderer.js
In current PIXI, clear a RenderTexture is complex : 
```
renderer.bindRenderTexture(myRenderTexture);
renderer.clear();
// restore the previous renderTexture
renderer.bindRenderTexture();
```
And bind renderTexture is a high-cost operation . We shouldn't call it for cleaning render texture.
So I  add this method.
relatived : https://github.com/pixijs/pixi.js/issues/3595
> Add an easy way to clear RenderTexture

- src/core/math/Matrix.js
Fixes #3698 
Matrix can now be constructed with optional parameters for its a, b, c, d, tx and ty properties. If no parameters are given, a matrix with the default values is created.
> Fixed #3698 (Matrix constructor now takes parameters)

- test/core/Spritesheet.js
* Windows is not cool with synchronous Image setting `src` in Electron. Not a problem on MacOS.  This allows tests to pass locally on Windows. Fixes #3701
> Fixes #3701

- src/interaction/InteractionManager.js
- test/interaction/InteractionManager.js
I've added the `removeEvent` tests to the `addEvent` tests.  Splitting them out would result in a lot of dupe code and they're heavily related anyway.
> InteractionManager Tests - Remove events

- src/core/graphics/Graphics.js
- src/core/utils/index.js
- test/core/Graphics.js
- test/core/util.js
It seems that fastrected graphics doesn't have blendMode. Tested it on pixi-examples, there is a problem.
> Fast rect blendMode problem

- src/core/renderers/webgl/managers/FilterManager.js
If some texture already exists in slot #0, and syncUniforms is trying to use it - mask wont be rendered at all.
Fiddle: https://jsfiddle.net/jdngw3xy/
> fix slot #0 texture

- src/core/graphics/webgl/utils/buildRoundedRectangle.js
- src/core/renderers/webgl/TextureManager.js
Eslint was complaining about missing doc comments / parameter types in buildRoundedRectangle.js.
Also changed doc type {Number} -> {number} in TextureManager for consistency.
> fixed lint warnings

- src/core/display/Container.js
- test/core/Container.js
I thought that's critical, but i think it waits for 4.4, we can discuss it.
"child.transform._parentID" can be anything at the time of adding the child, thus, collisions may happen.
Also I removed some of double-tests, that checked both addChild and addChildAt the same way.
> addChild/removeChild transform IDs were wrong

- src/interaction/InteractionManager.js
- test/interaction/InteractionManager.js
* Fixes #3689  - cursors not respecting the most specific thing that was moused over.
* Also fixes cursor changes being handled multiple times when mousing over any display object with a `cursor` property of `null` (the default).
* Changes the `pointerout` event that we were listening to to `pointerleave`, which should not give us any extra events that we don't need.
* Fixes #3668
> Fix cursors not working as expected in nested interactive objects

- src/core/Application.js
* Adds an addition Application constructor argument to allow the ticker to be `PIXI.ticker.shared` instead of creating `new PIXI.ticker.Ticker()`
This option provides a performance benefit by having fewer `requestAnimationFrame` calls going on simultaneously.
In response to #3687
> Allow option to make Application ticker the shared ticker

- src/core/textures/Texture.js
Add `HTMLImageElement`.
Breaking line because the line is too long (eslint reports error)
> Fix doc: add missing type of parameter

- src/core/sprites/canvas/CanvasTinter.js
In my project I use resolution as an easy way to use smaller assets on mobile devices. This means that occasionally the `crop.width` or `crop.height` is a decimal. When you set a canvas to a decimal number it seems to always round down (at least it does for me). This sometimes results in the tinted image being very slightly cut off.
Rounding the canvas size up has fixed this issue for me.
> CanvasTinter canvas size rounds up

- src/interaction/InteractionManager.js
- test/interaction/InteractionManager.js
Resolves #3419 and #3628.
I just saw #3628 after I started working on this and I opened another PR (wrong) about the same bug #3628 looks good to me but adds an extra property, which I personally tend to dislike. This might have some side effects for cases that are untested, but I thought it's worth opening as an alternative to #3628.
> Uncomment & fix failing test from #3535.

- src/core/renderers/webgl/WebGLRenderer.js
`bindShader` always  set the projection matrix  automatically . in most cases ,  that's OK.
But When I create some new renderers of PIXI ,  sometimes it would make some problems.
e.g. When : 
* shader no projectionMatrix
* shader need use a custom projectionMatrix (not  _activeRenderTarget's)
* shader use a cached array (don't want to call `toArray` every time)
So I add a new argument to `bindShader` , and the default value is true, so  it would NOT break any current code of PIXI
.
> User can decide whether  auto-set the projection

- src/core/Shader.js
PIXI.settings.PRECISION = 'highp';
Wasn't getting picked up in my game.
It turns out, the style of using the PRECISION setting meant it was a static value. This has been changed so that it's looking to the reference of the settings object to pick up the live changed value
> Fix precision setting change not being picked up

- src/core/Shader.js
- src/core/settings.js
- src/deprecation.js
Follow #3742 #3749
Best practice: use highp on vertex shaders, mediump on fragment. 
Use https://dl.dropboxusercontent.com/u/46636530/pixijs/wobble/pixi.js if you want to test it with bunnymark. Sorry, I prefer not to create branches that I forget to delete later ;)
> [v4.4] different settings for vertex and fragment shader

- src/core/ticker/Ticker.js
Fixes: https://github.com/pixijs/pixi.js/issues/3732
> Allows elapsedMS to show up in the docs

- src/core/graphics/Graphics.js
- src/core/sprites/webgl/SpriteRenderer.js
- src/core/textures/Texture.js
- src/core/utils/index.js
- test/core/Graphics.js
- test/core/WebGLRenderer.js
- test/isWebGLSupported.js
- test/withGL.js
Fixes problem in SpriteRenderer, TICK was set to 0 every time webglrenderer was created. That was a cause that our tests were failing.
Yes, I know that TICK++ will overflow bunnymark after few years of work, I can add "if tick>2^52, tick=0" there. Same with our transforms, so lets not address that issue there ;)
This is cumulative patch, it also adds some APIs that can be used in tests and in runtime:
- added Texture.WHITE, 10x10 texture is used by Graphics for spriteRect
- cleaned spriteRect code
- added clearTextureCache() and destroyTextureCache()
- added withGL transformer to simplify webgl tests
> [v4.4] fix SpriteRenderer for multiple webgl renderers, fix tests, add "withGL"

- src/core/renderers/webgl/filters/extractUniformsFromSrc.js
- src/core/renderers/webgl/managers/FilterManager.js
- test/core/filters.js
- test/core/index.js
I found the real reason behind that bug. 
"filterClamp" and "filterArea" are special cases, they can't appear in extractUniformsFromSrc
That fixes outlineFilter and glowFilter.
> [v4.4] Revert "Fix #3609 , about `filterClamp` & `filterArea`  (#3626)"

- src/core/sprites/webgl/SpriteRenderer.js
The `vertSize` is 5 , but the content is not `positionX, positionY, colorR, colorG, colorB`.
> Fix documents.

- test/core/Container.js
Take 2 removing the 4 pending tests from the Container tests. 
testAddChild and testRemoveChild must return a function for Mocha.
Follow-up to #3722
> Removes pending tests from Container

- src/core/textures/Texture.js
default value for settings.SCALE_MODE was not respected in loader because "undefined !== null"
> default value for settings.SCALE_MODE was not respected in loader

- src/core/Application.js
- src/core/autoDetectRenderer.js
- src/core/renderers/SystemRenderer.js
- src/core/renderers/canvas/CanvasRenderer.js
- src/core/renderers/webgl/WebGLRenderer.js
- src/core/settings.js
This provides an alternative, standardized argument style for `PIXI.autoDetectRenderer` and constructors for `PIXI.Application`, `PIXI.CanvasRenderer`, and `PIXI.WebGLRenderer` to support a single options object instead of optional width/height _and then_ optional options. It maintains backward-compatible support and is therefore **a non-breaking change**. 
To set some renderer options, but you _need_ to provide a width and height:
```js
// Application construction
const app = new PIXI.Application(800, 600, {
view: document.getElementById('pixi'),
backgroundColor: 0xffffff
});
// Renderer construction
const renderer = PIXI.autoDetectRenderer(800, 600, {
view: document.getElementById('pixi'),
backgroundColor: 0xffffff
});
```
Since `width` and `height` are now part of the options object, …
> Application & Renderer Constructor Options Improvements

- src/core/display/DisplayObject.js
- src/core/textures/BaseTexture.js
- src/prepare/BasePrepare.js
- test/prepare/BasePrepare.js
* Added `isDestroyed` to DisplayObject, BaseTexture, which is automatically set in `destroy()`.
* The prepare plugins will automatically skip destroyed items, by checking the `isDestroyed` property.
> Fix preparation of destroyed items

- src/core/textures/BaseTexture.js
- src/core/textures/Spritesheet.js
- src/core/textures/Texture.js
- test/core/BaseTexture.js
- test/core/Spritesheet.js
- test/core/Texture.js
From the dicussion of #3730:
* added `textureCacheId` to Texture, for giving a useful name to Texture objects that hopefully matches what they are in the TextureCache as.
* Textures and BaseTextures do a thorough search of their respective caches in `destroy()` to remove themselves, so that subsequent Texture.fromX calls don't attempt to reuse a destroyed object.
* Removed some event listener cleanup in Texture.destroy() that wasn't actually cleaning up anything that ever got added.
> Small Texture Cache enhancements

- src/extras/webgl/TilingSpriteRenderer.js
Take that demo: http://pixijs.github.io/examples/#/basics/tiling-sprite.js
Now add this into app.ticker:
```js
if (texture.valid && texture.rotate == 0) {
texture.rotate = 8;
}
```
OK, texture is rotated by 180 degrees, but sprite moving in wrong direction! But what if its not calculated in renderer, but in shader itself? Lets cut the texture, calculation moves to shader:
```js
if (texture.valid && texture.rotate == 0) {
var w = texture.frame.width, h = texture.frame.height;
texture.frame = new PIXI.Rectangle(1, 1, w-2, h-2);
texture.orig = new PIXI.Rectangle(1, 1, w-2, h-2);
texture.rotate = 8;
}
```
It works!
So, whats the fix? Just swap texture translate and texture transform order. That way is consistent with shader and behaviour that user expects.
> TilingSprite matrix calculation fix

- src/core/text/Text.js
See http://embed.plnkr.co/hgf5Tb/
Display to Text instances and those rectangles.
`t1`, `t2`, `t3` is OK, but `t4` is not OK.
I fixed it.
(Trimmed texture has been reduced padding, don't reduce padding more)
Sorry for my poor english.
> Problem by padding and trim in Text

- src/extras/cacheAsBitmap.js
In the current pixi.js , when we want to cache a sprite as Bitmap, we have to put the sprite into a container , like this : 
```js
var texture = PIXI.Texture.from(img);
var sprite = new PIXI.Sprite(texture);
sprite.cacheAsBitmap = true;
var renderTexture = PIXI.RenderTexture.create(sprite.width, sprite.height);
var container = new PIXI.Container();
container.addChild(sprite);
renderer.render(container, renderTexture);
```
With this PR , user could cache the sprite directly : 
```js
var texture = PIXI.Texture.from(img);
var sprite = new PIXI.Sprite(texture);
sprite.cacheAsBitmap = true;
var renderTexture = PIXI.RenderTexture.create(sprite.width, sprite.height);
renderer.render(sprite, renderTexture);
```
> Support that cache Sprite as Bitmap directly.

- src/interaction/InteractionManager.js
- test/interaction/InteractionManager.js
- test/interaction/MockPointer.js
* Fixes #3844 - memory leak on touch end.
* Fixes another component of #3790, #3851 - tracking that an interactive child was hit was forgotten more than one level up.
* Adds unit tests for both of these fixes.
> Fix some interaction issues

- src/interaction/InteractionManager.js
- test/interaction/InteractionManager.js
Adds a stable, public method to manually hit test against the display tree, and unit tests to support it.
> Added public hit test method to InteractionManager

- src/core/ticker/Ticker.js
- test/core/Ticker.js
* Resolves issue when destroying Ticker on listener callback which generates this error:
* Adds an additional unit-test to handle this case.
> Hot-fix for Ticker's destroy

- scripts/jsdoc.conf.json
- src/accessibility/AccessibilityManager.js
- src/accessibility/index.js
- src/core/renderers/canvas/CanvasRenderer.js
- src/core/renderers/webgl/WebGLRenderer.js
- src/core/settings.js
- src/core/ticker/index.js
- src/core/utils/index.js
- src/extract/canvas/CanvasExtract.js
- src/extract/index.js
- src/extract/webgl/WebGLExtract.js
- src/extras/index.js
- src/filters/index.js
- src/interaction/index.js
- src/loaders/index.js
- src/prepare/index.js
* Adds documentation for missing namespaces like `PIXI.extract`, `PIXI.extras`, etc.
* Adds documentation for `plugins` on the CanvasRenderer and WebGLRenderer.
* Added CanvasExtract and WebGLExtract classes to `PIXI.extract` namespace instead of on the global `PIXI` object (mirrors how `prepare` is documented).
* Disables `hardwrap` JSdoc setting because ESLint enforces a line-length limit.
This addresses #3876
https://pixijs.download/docs/docs/index.html
> Documentation Updates: namespaces & plugins

- src/core/Application.js
- src/deprecation.js
- src/index.js
- src/loaders/index.js
- src/loaders/loader.js
Adds convenience support for loader to the Application class. 
```js
const app = new PIXI.Application();
// Pause rendering
app.stop(); 
// Load some resources
app.loader
.add('logo', 'images/logo.png');
.load(() => {
app.start(); // resume rendering
});
```
* Adds `loader` property the Application class, e.g., `app.loader.load()`
* Adds constructor argument `options.sharedLoader` to Application to opt-in to using the shared Loader.
* Adds `PIXI.loaders.shared` as an alias for `PIXI.loader` (conforms to Ticker usage `PIXI.ticker.shared`).
* Fixes issue when excluding the loaders module `npm run dist — -e loaders` (deprecations were throwing issues for deprecated Resource, e.g. 'isJson`, etc).
> Application loader support

- src/core/display/DisplayObject.js
- src/core/renderers/canvas/CanvasRenderer.js
- src/core/renderers/webgl/WebGLRenderer.js
- src/core/textures/BaseTexture.js
- src/core/textures/Texture.js
- src/interaction/InteractionData.js
- src/interaction/InteractionManager.js
- src/interaction/interactiveTarget.js
Addresses #3920 
* Adds additional event documentation including parameters for:
* Texture
* BaseTexture
* DisplayObject
* WebGLRenderer
* CanvasRenderer
https://pixijs.download/event-docs/docs/index.html
> Documents events for DisplayObject, renderers, Texture and BaseTexture

- src/core/graphics/Graphics.js
- src/core/text/Text.js
- src/core/textures/BaseTexture.js
- src/core/textures/Spritesheet.js
- src/core/textures/Texture.js
- src/core/textures/VideoBaseTexture.js
- src/core/utils/index.js
- src/deprecation.js
- src/extras/cacheAsBitmap.js
- test/core/BaseTexture.js
- test/core/Bounds.js
- test/core/Spritesheet.js
- test/core/Texture.js
- test/core/index.js
Built upon the good work from https://github.com/pixijs/pixi.js/pull/3789
+ For Text, the base textures were in the BaseTextureCache, but textures weren't in the TextureCache. This has been fixed
+ Now able to tell the BaseTexture the origin of where the canvas being passed through has come from. ie. was it from the text class? was it from the graphic class? was it from caching as a bitmap? More information now to track where these canvases (canvii??) have been generated from
+ BaseTexture has addBaseTextureToCache and removeBaseTextureFromCache functions, to match regular Texture. Any adding or removing to the BaseTextureCache is now through these functions
+ Protection around adding and remove items to the caches using the functions
! Breaking change. When you call …
> Improvements to how and what is stored in the texture caches.

- src/interaction/InteractionManager.js
Fixes the docs for mouse/touch/pointer events. These events return PIXI.interaction.InteractionEvent not InteractionData.
Follow up to #3922
> Fixes event docs for Interaction

- src/core/textures/BaseTexture.js
- src/core/textures/Texture.js
- test/core/BaseTexture.js
- test/core/Texture.js
Prevents errors from being thrown when one attempts to remove a destroyed `Texture` from the texture cache. This is likely to happen when recursively destroying a display tree where a texture is shared, among other possible scenarios.
> Fix destroyed textures throwing errors when destroyed again.

- src/core/ticker/TickerListener.js
- test/core/Ticker.js
Fixes #3936, bug produced when using `addOnce`.
Also, added additional test coverage to support this case.
Broken: https://jsfiddle.net/oqw8119u/ (v4.5.0)
Fixed: https://jsfiddle.net/x037jxoz/ (fix-ticker)
> Fixes issue with addOnce on ticker

- src/core/ticker/TickerListener.js
- src/interaction/InteractionManager.js
- test/core/Ticker.js
- test/interaction/InteractionManager.js
- test/interaction/MockPointer.js
Fixes #3466, which was also reported in #3790.
The issue was not looking at the event target on our window listeners for `mouseup`/`pointerup`. This change looks at that and emits `mouseupoutside`/`pointerupoutside` as appropriate.
For the MockPointer changes, it turns out that `target` is not a parameter for Events, and is a read only property. It is configurable, however, which is why I am setting the target in a roundabout way.
> Fix not respecting target of mouseup events.

- src/filters/noise/NoiseFilter.js
- src/filters/noise/noise.frag
Proposed to fix #3199, as an alternative to #3941.
Using this test code:
```js
'use strict';
const app = new PIXI.Application({
backgroundColor: 0x006600,
width: 512,
height: 512,
view: document.getElementById('view'),
});
const graphic = new PIXI.Graphics()
.beginFill(0xff0000)
.drawCircle(256, 256, 200);
graphic.filters = [new PIXI.filters.NoiseFilter()];
app.stage.addChild(graphic);
```
Produces this output:
> Fix #3199 by honoring alpha

- src/deprecation.js
- src/index.js
This PR removes `enumerable` for the deprecations and fixes #3917. This was originally added as a workaround for Babel (see #3062). Deprecations should not be enumerable.
Show file diff without whitespace changes: https://github.com/pixijs/pixi.js/pull/3952/files?w=1
```js
for ( const name in PIXI ) {
PIXI[name];
}
```
* [Current release displays deprecation warnings.](https://jsfiddle.net/yednwwo9/)
* [This branch hides the deprecation warnings.](https://jsfiddle.net/60csvpoy/)
https://github.com/bfanger/pixi-inspector/issues/15
> Remove enumeration from deprecations

- src/core/ticker/Ticker.js
- test/core/Ticker.js
* When adding a new ticker handler, should be added to the end of handlers with the same priority instead of the beginning. This is compatible with the old EventEmitter approach which uses `push` not `unshift`.
> Fixes order adding of ticker listeners with same priority

- src/core/ticker/TickerListener.js
Fixes: https://github.com/pixijs/pixi.js/issues/3936
I believe the edge case may be because I have a ticker that does not have autoStart turned on.
Instead I manually call .update() on it.
> Stops TickListener 'this.fn is not a function' error

- src/filters/colormatrix/ColorMatrixFilter.js
- src/filters/colormatrix/colorMatrix.frag
Add an interpolation value that allows you to interpolate between a texel's original color and the result of applying the color matrix.
This should fix #3252 where the user wanted to easily define a scale of sepia to apply.
> Fix #3252, add an interpolation value for the color matrix result

- src/prepare/BasePrepare.js
* Internally, the prepare plugin was still using the old Text API. This PR fixes #3968
**v4.5.1** (with warnings) https://jsfiddle.net/bs05a3t8/
**fix-text-prepare** (without warnings) https://jsfiddle.net/bs05a3t8/1/
> Removes deprecation warnings with TextMetrics usage

- test/core/Texture.js
Was unit testing the old Texture.addTexturetoCache and Texture.removeTextureFromCache functions, causing deprecation warnings when running the tests
> Removed unit test for deprecated Texture cache functions

- src/interaction/InteractionData.js
- src/interaction/InteractionManager.js
- test/interaction/InteractionManager.js
- test/interaction/MockPointer.js
Makes the event behavior of InteractionManager closer to that of standard browser behavior with:
* Expose event properties on `InteractionData` (originally from #3890)
* If TouchEvents are supported, use those instead of PointerEvents for touch based events - Fixes #3886
* Emit mouse events on pointer events from a pen device. - Fixes #3867
* A browser would emit a fallback mouse event on those pointer events, which we were not doing.
Also does a little simplification/cleanup of how we were detecting pointer types and right clicks to determine what events to emit.
> Make Interaction events closer to Browser behavior

- package.json
- test/interaction/InteractionManager.js
Updated to #3984 and #3975, Travis was left out of the lint process and tests were being blocked because of `it.only`
See Travis build process: https://travis-ci.org/pixijs/pixi.js/builds/228835831#L349-L355
> Missing lint from travis test

- src/extras/BitmapText.js
- src/extras/index.js
When the base texture has a resolution scale other than 1, then the result of the rendered bitmap text becomes a mess. This change allows you to use bitmap fonts with different screen resolutions.
> Take into account baseTexture resolution when registering a BitmapText.

- src/core/sprites/Sprite.js
- src/core/text/Text.js
* Add `updateText`.  If a sprite is created by a canvas ,  when the canvas's changed , user could call `updateText` for updating sprite.
* Add some shortcuts for accessing  some properties of sprite._texture.
* Cosmetic Text. Just define some local vars for accessing properties of `this` , for DRY.
> Add `updateTexture` & some shortcuts in Sprite; Cosmetic

- src/extras/AnimatedSprite.js
Trying to change the animation textures in an extras.AnimatedSprite to a 1 frame animation, the textures are not refreshed. Here is an example:
[jsfiddle](https://jsfiddle.net/gazzell/jochsbru/)
I solved it forcing to go to frame 0 and updating the textures on the textures setter:
[jsfiddle-solution](https://jsfiddle.net/gazzell/wgn8eLep/2/)
> fix changing textures to a 1 frame animation bug

- src/core/renderers/webgl/WebGLRenderer.js
Context restore didnt work properly.
Please add this to any of [examples](https://pixijs.github.io/examples/#/basics/basic.js)
```js
setTimeout(function() {
const ext = app.renderer.gl.getExtension('WEBGL_lose_context');
ext.loseContext();
setTimeout(function () {
ext.restoreContext();
}, 1000);
}, 3000);
```
And then try it with [the fix](https://pixijs.github.io/examples/?v=fix-context-restore#/basics/basic.js)
> Fix context restore.

- src/core/textures/BaseTexture.js
- test/core/BaseTexture.js
- added fix suggested by @englercj 
- added test coverage
```
test results before fix (with new test added):
341 passing (1s)
1 failing
1) PIXI BaseTexture should set source.crossOrigin to anonymous if explicitly set:
AssertionError: expected null to equal 'anonymous'
at Context.<anonymous> (/Users/eddie.reesman/Development/eddie-github/pixi.js/test/core/BaseTexture.js:119:51)
at runCallback (timers.js:651:20)
test results after fix:
342 passing (1s)
```
> fix for issue #4043: CORS not working with PIXI.Sprite.fromImage

- src/core/renderers/webgl/utils/RenderTarget.js
changed ```RenderTarget#setFrame```
from
```
setFrame(destinationFrame, sourceFrame)
{
this.destinationFrame = destinationFrame || this.destinationFrame || this.defaultFrame;
this.sourceFrame = sourceFrame || this.sourceFrame || destinationFrame;
}
```
to
```
setFrame(destinationFrame, sourceFrame)
{
this.destinationFrame = destinationFrame || this.destinationFrame || this.defaultFrame;
this.sourceFrame = sourceFrame || this.sourceFrame || this.destinationFrame;
}
```
> gl.SCISSOR_TEST fix (related to #4004)

- src/core/const.js
- src/core/renderers/canvas/utils/mapCanvasBlendModesToPixi.js
- src/core/renderers/webgl/WebGLState.js
- src/core/renderers/webgl/utils/mapWebGLBlendModesToPixi.js
- src/core/sprites/webgl/SpriteRenderer.js
- src/core/sprites/webgl/texture.vert
- src/core/utils/index.js
- src/core/utils/mapPremultipliedBlendModes.js
- src/core/utils/premultiplyBlendMode.js
- src/extras/webgl/TilingSpriteRenderer.js
- src/mesh/webgl/MeshRenderer.js
- src/mesh/webgl/mesh.frag
- src/particles/ParticleContainer.js
- src/particles/webgl/ParticleRenderer.js
- src/particles/webgl/ParticleShader.js
We have "premultipliedAlpha" field in BaseTexture from the beginning of times. But we do not respect it. It was ok, but some time ago both me and @bigtimebuddy started to use compressed textures.
There are no compressed formats with premultiplied alpha in WebGL, DXT1,3,5 are supported, while DXT2,4 aren't.
Example: 
Current version of pixi: https://pixijs.github.io/examples/#/textures/not-premultiplied-alpha.js
This branch: https://pixijs.github.io/examples/?v=dev-blendmodes-premultiply#/textures/not-premultiplied-alpha.js
Please read 
https://www.cgdirector.com/straight-alpha-vs-premultiplied-alpha/ 
http://www.adriancourreges.com/blog/2017/05/09/beware-of-transparent-pixels/
to understand the problem.
Later, I hope we'll be able to add compressed textures as childs of BaseTexture.
> premultiply blendModes, critical for compressed textures.

- src/core/text/Text.js
Fixes: https://github.com/pixijs/pixi.js/issues/3960
Don't see why it was set to ignore the shadow colour before when blur was enabled... that behaviour goes back to v3 days. But it feels like incorrect behaviour to me which this PR fixes
> Text drop shadow is now the right colour, even with blur enabled

- src/extras/BitmapText.js
Record how many spaces have already been removed when resetting the index for a new line of text after hitting the maxWidth limit
Fixes https://github.com/pixijs/pixi.js/issues/4063
> Fix for repeated letters on wordWrapped bitmap text

- src/core/text/TextStyle.js
Makes the default value of TextStyle's `dropShadowColor` be consistent with `fill` and `stroke` colors. Uses `black` instead of `#000000`.
Would like to fix this to provide more consistent defaults in https://github.com/pixijs/pixi-text-style
> Changes the default dropShadowColor in TextStyle

- src/core/Application.js
- src/core/autoDetectRenderer.js
- src/core/renderers/SystemRenderer.js
- src/core/renderers/canvas/CanvasRenderer.js
- src/core/renderers/webgl/WebGLRenderer.js
There were a bunch of properties that were missing from some of the constructor options for the renderers/Application/autoDetectRenderer jsdocs. This PR adds the missing options. The added arguments are noted here with a `+`
* http://pixijs.download/docs-renderer/docs/PIXI.Application.html
* http://pixijs.download/docs-renderer/docs/PIXI.html#.autoDetectRenderer
* http://pixijs.download/docs-renderer/docs/PIXI.SystemRenderer.html
* http://pixijs.download/docs-renderer/docs/PIXI.CanvasRenderer.html
* http://pixijs.download/docs-renderer/docs/PIXI.WebGLRenderer.html
width
height
view
transparent
autoResize
antialias
resolution
clearBeforeRender
backgroundColor
roundPixels
+ preserveDrawingBuffer
width
height
view
transparent
autoResize
antialias
resolution
clearBeforeRender
backgroundColor …
> Added missing docs for Renderer options

- src/loaders/bitmapFontParser.js
If loader baseUrl exists, added baseUrl twice to the texture path.
font.xml
```xml
<?xml version='1.0'?>
<font>
<pages>
<page id='0' file='font.png'/>
</pages>
```
application code
```js
PIXI.loader.baseUrl = '/assets/';
PIXI.loader
.add(['font.xml'])
.load();
```
↓
GET /assets//assets/font.png 404 NotFound
Fix the issue https://github.com/pixijs/pixi.js/issues/3510
> Remove duplicated base url from loader path in the bitmapFontParser

- src/core/renderers/webgl/TextureManager.js
Hot fix to #4173
Local WebGL unit-test were failing because of recent PR.
Also, tweaks the code to be a little more readable and optimized to compress.
> Fixes destroyTexture method on TextureManager

- src/core/graphics/Graphics.js
Hey -
Just a tiny fix. Visual Studio Code pointed this out in some code I was writing, the drawPolygon method accepts a PIXI.Polygon, but the doc string doesn't include it.
Cheers
-Courtland
> Graphics drawPolygon Documentation Fix

- src/core/textures/Texture.js
- test/core/Texture.js
Ran into an issue where a texture was replaced in the cache by a new texture with the same name, and was removed unintentionally, causing an error: `The frameID 'line1' does not exist in texture cache.` @andrewstart suggested this fix, making sure the texture to be removed is the same texture as the one passed into `removeFromCache()`
> Don't remove textures if they've been replaced in the cache

- src/core/Application.js
- test/core/Application.js
`autoStart` option allows users to configure the ticker before starting the rendering. That helps to synchronize timing of ticks for recording using `this.ticker.update`.
> Add autoStart option to PIXI.Application

- src/core/ticker/Ticker.js
`update` method could have 0 as timestamp, but the frame would be ignored because the initial `lastTime` is 0. Let it have a negative value.
> Set initial lastTime to -1

- src/core/Application.js
- src/core/autoDetectRenderer.js
- src/core/renderers/webgl/WebGLRenderer.js
According to https://github.com/KhronosGroup/WebGL/issues/2343 , we can use it , because we implemented context loss / context restore. I still can't find original doc, where is that thing specified.
> Add option for dual-graphics devices

- LICENSE
- scripts/jsdoc.conf.json
Implement Google Analytics for documentation as a way to understand which APIs are most used, browsed for, looked up. Also, as a way to understand the traffic relationships between Github/Wiki and Docs.
> Add Google Analytics to Documentation

- package.json
It appears that **jsdoc** 3.5.x introduced a bug with how events are documented which is not rendering any of our DisplayObject or InteractiveManager events.
**release branch:** (has events) http://pixijs.download/release/docs/PIXI.DisplayObject.html
**dev branch:** (no events) http://pixijs.download/dev/docs/PIXI.DisplayObject.html
**bug-jsdoc branch:** (has events again) http://pixijs.download/bug-jsdoc/docs/PIXI.DisplayObject.html
https://github.com/jsdoc3/jsdoc/issues/1425
http://www.html5gamedevs.com/topic/32395-docs-missing-events/
> Pins jsdoc to 3.4.3

- src/extras/TilingSprite.js
Tiling sprite should keep track of texture changes and update the fill pattern when using the canvas renderer
Fixes #4085
> Tiling texture works on canvas when replacing textures

- src/core/textures/Spritesheet.js
- test/core/Spritesheet.js
Spritesheets no longer work properly if your using the `sourceScale` feature introduced in #2614.
This fix multiplies the size by the BaseTexture's sourceScale.
Note: My only concern is Math.floor. It works, however, it's easy to see why it could become a problem. Not sure how else to fix this. sourceScale uses [Math.round](https://github.com/pixijs/pixi.js/commit/4bcacc57bb764782cb307f10ee2048f7d4a4fddd#diff-2820734d8d9cebcd6dd6120421612e81R512) to ensure a clean width/height. I can't use Math.round here because multiple frames could end up being wider or higher than it's baseTexture.
Suggestions?
> Improving SVG handling in Spritesheets with sourceScale support

- src/core/renderers/webgl/WebGLRenderer.js
- src/core/renderers/webgl/managers/FilterManager.js
I believe that PIXI v4 is LTS, so I backported solution from my fork.
Its not fixed in v5: https://github.com/pixijs/pixi.js/blob/next/src/core/renderers/webgl/systems/FilterSystem.js
It is fixed in my v5 fork: https://github.com/gameofbombs/gobi/blob/master/src/pixi/renderers/systems/ShaderSystem.ts
To test the feature put this code in any of pixi examples that has filters, and see if it survives after context is lost. With my patch there are no errors/warnings in console at all.
```js
function loseContext() {
var gl = app.renderer.gl;
var ext = gl;
if (!ext.loseContext) {
ext = gl.getExtension('WEBGL_lose_context');
}
ext.loseContext();
setTimeout(function () {
ext.restoreContext();
}, 1000);
}
setTimeout(loseContext, 2000);
```
> filters can survive context loss

- src/core/textures/Texture.js
What's the error: 
The error will tell you both X and Y are wrong if you only one of them has incorrect value:
For example, set the height to `Number.MAX_VALUE`, then:
Why change `frame && frame.width ...` to `frame.width ...`?
If `frame == undefined`, it already breaks during  `if (frame.x + frame.width > this.baseTexture.width || frame.y + frame.height > this.baseTexture.height)` :)
> Fix texture's frame dimension error report

- package.json
- scripts/jsdoc.conf.json
Forked [jaguarjs-jsdoc](https://github.com/pixijs/jaguarjs-jsdoc) to [@pixi/jsdoc-template](https://github.com/pixijs/pixi-jsdoc-template) which adds a bunch of improvements to the existing docs template:
- Fixes bugs in search
- Changes colors to match website/examples/etc
- Better spacing for improved legibility
- Deep-links next to each API
- Responsive layout to display better on large mobile devices
**Existing Docs**: https://pixijs.download/release/docs/PIXI.CanvasRenderer.html
**New Template**: https://pixijs.download/new-jsdoc-template/docs/PIXI.CanvasRenderer.html
> Upgrade jaguarjs-jsdoc Template

- src/mesh/NineSlicePlane.js
Somehow, we didn't use resolution for NineSlicePlane canvas version, and fix is easy. However I dont have fiddle for it, people just reported this problem and solution to me. 
Theoretically, that's how it suppose to work.
> fix NineSlice with resolution

- src/core/textures/BaseRenderTexture.js
- src/core/textures/RenderTexture.js
I have a bit of code that takes a texture rendered by PIXI.Text, then creates a rope from it to create curved text. I then put that to a renderTexture to be used by sprites.
However, on IE 11 only, (WebGL in IE in fact), the texture just looks bizarre. I've created a fiddle that shows normal text (top), rope (left) then the sprite using a generated texture (right). I've forced some crazy resolution values to help replicate the issue.
By using Math.ceil on width and height of created render textures, the issue goes away. I think this is safe, since regular textures you upload with sprites couldn't be a fraction of a pixel wide, so why should created textures?
https://jsfiddle.net/themoonrat/71hadj49/
In case the fiddle doesn't work for you (remember, IE 11 WebGL only), here's how it looks …
> Force base render textures to be whole pixels to fix error in IE

- src/core/renderers/webgl/systems/geometry/GeometrySystem.js
Add an unbind call to the geometry to bind the VAO to null. This is needed when working with other WebGL lib/tools which runs their own raw gl calls ( e.g. WebVR Polyfill : https://github.com/googlevr/webvr-polyfill). Need to unbind the vao before third party lib start binding their own buffers.
> Add unbind call for Geometry

- src/core/text/TextStyle.js
- test/core/TextStyle.js
Fixes an issue where
```js
const style1= new PIXI.TextStyle();
const style2 = new PIXI.TextStyle();
style1.fillGradientStops.push(0);
```
Because the array is copied by reference (as an `Object.assign` is currently used), 
`style2.fillGradientStops === style1.fillGradientStops`
Which is incorrect. The arrays should be separate instances
> Ensures that text style properties are copied by value, not by reference

- packages/core/src/geometry/Geometry.js
- packages/core/src/geometry/utils/getBufferType.js
- packages/core/src/geometry/utils/interleaveTypedArrays.js
- packages/core/src/shader/Program.js
- packages/core/src/shader/getTestContext.js
- packages/utils/src/browser/index.js
- packages/utils/src/data/index.js
_I’m working on a series of incremental changes which remove, reorganize and realign the current utils (aka the “junk drawer” of PixiJS)._
* Removes `getTestContext` from utils, add to **core/src/shader**
* Removes `getBufferType` and `interleaveTypedArrays` from utils and moves to **core/src/geometry/utils**
> Removes getTestContext, getBufferType and interleaveTypedArrays from utils

- src/filters/colormatrix/ColorMatrixFilter.js
#4419 On the example for ColorMatrixFilter, it gives this as an example:
`let colorMatrix = new PIXI.ColorMatrixFilter();`
fixed it so it reads:
`let colorMatrix = new PIXI.filters.ColorMatrixFilter();`
> fixed ColorMatixFilter documentation issue

- src/core/textures/VideoBaseTexture.js
Paste the following code into the video example http://pixijs.io/examples/#/basics/video.js
What changes to the example is that on the first click of the button, the video be created and  play, but on the 2nd click, it will destroy the video. The next click creates and plays again, and so on.
What you'll notice is that when you click to destroy, the video disappears, but you still hear the sound of it playing, because the video tag source hasn't properly been dealt with. 
This PR pauses the video and sets it's source to null, to properly destroy it.
```js
var app = new PIXI.Application(800, 600, { transparent: true });
// Create play button that can be used to trigger the video
var button = new PIXI.Graphics()
.beginFill(0x0, 0.5)
.drawRoundedRect(0, …
```
> Ensures that the source video is unloaded correctly (v4)

- src/core/sprites/webgl/SpriteRenderer.js
A long time I knew the fact that SpriteRenderer wont like same texture bound in two locations.
But every time I thought that none of our plugins use the same textures as SpriteRenderer.
Now, https://github.com/pixijs/pixi-ui https://github.com/gameofbombs/pixi-heaven, https://github.com/pixijs/pixi-projection and possible others (i havent check sdf and neutrino) are forcing textures to be binded in specific locations, and SpriteRenderer wants to use same textures.
Thankfully, v5 Sprite Renderer doesn't have that issue because @GoodBoyDigital dropped the optimization that caused it.
Now, for the sake of plugins, for the sake of users who have WebGL: INVALID_ENUM: activeTexture: texture unit out of range that can be explained only by virtalBoundId=-1 , I want to merge this fix into 4.6.1 . …
> same textures bound in same places

- src/core/text/TextMetrics.js
original code is in a wrong way to add blank character when the style.breakWords is enabled.
see also issue: [#4251](https://github.com/pixijs/pixi.js/issues/4251)
> fix bug for adding useless extra blank ahead of the first text line [#4251]

- src/core/renderers/SystemRenderer.js
Added an optional "region" parameter to Renderer.generateTexture() to only render the specified area.
https://jsfiddle.net/bma73/92os3a0e/17/
> Region parameter for Renderer.generateTexture()

- packages/loaders/src/Loader.js
- packages/spritesheet/test/SpritesheetLoader.js
cc @GoodBoyDigital 
In the loader refactor (#4471) it changed the scope of the middleware function. Fixed and added a unit-test for loading a spritesheet.
> Fixes scoping issue with loader middleware

- src/particles/ParticleContainer.js
Documentation specifies incorrect default value for `autoResize` param to constructor of `ParticleContainer`. #4504
> Fixes #4504

- src/core/Shader.js
Some users like add `one blank line` before & after the source code.
if no trim , `substring(0, 9)` can't work correct.
e.g. : 
```js
var fragSrc = `
precision mediump float;
uniform sampler2D uSampler;
varying vec2 vTextureCoord;
uniform float uAlpha;
uniform float uColorMultiplier;
uniform vec3 uColorOffset;
void main(void){
vec4 color = texture2D(uSampler, vTextureCoord) * uAlpha;
color.rgb *= uColorMultiplier;
color.rgb += uColorOffset * color.a;
gl_FragColor = color;
}
`;
```
> `trim` shader's source when check precision

- package.json
- src/particles/ParticleContainer.js
- src/particles/webgl/ParticleShader.js
detail at https://github.com/pixijs/pixi.js/issues/4467
1) remove `attribute vec2 aScale;` in the shader source. it's needless. because `scale` has been compute in  ParticleRenderer's `uploadVertices()`. We don't need to upload the scale as attribute to shader.
2) update the document about `properties.scale` in ParticleContainer.
in fact , when sprite's `scale/anchor/trim/frame/orig` changed , users have to set  `scale:true` . 
though that option  named `scale` , but it's not only about `sprite.scale`.
3) change the name from `scale` to `vertices` , and  do polyfill in ParticleContainer's `setProperties()` (like `alpha` & `tint`)
> Fix bug #4467 : `scale` of ParticleContainer

- package.json
Updated resource-loader from v2.0.9 to v2.1.1.
Most important changes are to fix englercj/resource-loader#102 and englercj/resource-loader#106.
Full change logs: [v2.1.0](https://github.com/englercj/resource-loader/releases/tag/v2.1.0), [v2.1.1](https://github.com/englercj/resource-loader/releases/tag/v2.1.1).
> Update resource-loader version

- packages/core/src/renderers/systems/textures/GLTexture.js
- packages/core/src/renderers/systems/textures/TextureSystem.js
- packages/core/src/textures/resources/BaseImageResource.js
Yeah, @GoodBoyDigital broke everything :)
1. Fixing mipmaps - there's one more flag in GLTexture: whether or not mipmaps has to be uploaded
2. default renderTexture logic, that is also used in case of async ImageBitmap creation was faulty
3. minor refactor on width/height, also fixed potential resolution bug.
> Fixing mipmaps and renderTexture

- README.md
@GoodBoyDigital and co produced a wonderful new [website](https://www.goodboydigital.com/), however some of the older demo links being hosted on that site are now broken. We are looking for a restore solution, but in the meantime, I updated a few links which were old anyways.
Partially addresses #4571
* Updates the banner image to be image served on S3 bucket
* Changes bunny demo to be the project on GitHub pages
* Changes the filters demo to be the demo on GitHub pages
> README Link Updates

- packages/core/src/renderers/systems/textures/TextureSystem.js
- packages/core/test/ImageResource.js
- packages/spritesheet/test/SpritesheetLoader.js
This is only a partial fix. In windows, `path` resolves `file:///D:\...`
Another test that is failing - https://github.com/pixijs/pixi.js/blob/next/packages/spritesheet/test/SpritesheetLoader.js#L94 , I honestly don't know what to do about that.
Any ideas?
> [next] Windows tests are failing

- bundles/pixi.js/src/deprecated.js
- packages/canvas/canvas-graphics/src/Graphics.js
- packages/canvas/canvas-renderer/src/CanvasRenderer.js
- packages/canvas/canvas-sprite/src/CanvasSpriteRenderer.js
- packages/core/src/renderers/filters/filterTransforms.js
- packages/display/src/DisplayObject.js
- packages/math/src/Matrix.js
- packages/math/src/ObservablePoint.js
- packages/math/src/Point.js
- packages/math/src/shapes/Rectangle.js
- packages/math/test/ObservablePoint.js
- packages/math/test/Point.js
- packages/math/test/Rectangle.js
- packages/mixin-cache-as-bitmap/src/index.js
- packages/particles/src/ParticleRenderer.js
- packages/sprite-tiling/src/TilingSprite.js
- packages/sprite/src/Sprite.js
- packages/text-bitmap/src/BitmapText.js
Standardizes the use of `copy` methods in Points and Matrix. Resolves a discrepancy between Points and Matrix with how `copy` is being used.
* `PIXI.Point#copy` => `PIXI.Point#copyFrom`
* `PIXI.ObservablePoint#copy` => `PIXI.ObservablePoint#copyFrom`
* `PIXI.Matrix#copy` => `PIXI.Matrix#copyTo`
* `PIXI.Rectangle#copy` => `PIXI.Rectangle#copyFrom`
* `PIXI.Point#copyTo`
* `PIXI.ObservablePoint#copyTo`
* `PIXI.Matrix#copyFrom`
* `PIXI.Rectangle#copyTo`
> [next] Math `copy` inconsistencies

- src/loaders/spritesheetParser.js
- test/loaders/resources/atlas_error.json
- test/loaders/spritesheetParser.js
Fixes #4599
Properly handles situation where image is invalid but spritesheet JSON is not.
> Fixes handling of error when Spritesheet is valid but image is not

- src/mesh/NineSlicePlane.js
That's from Mesh:
```js
renderer.context.globalAlpha = mesh.worldAlpha;
renderer.setBlendMode(mesh.blendMode);
```
blendMode line is missing in NineSlicePlane. I can be a problem if something sets not-normal blendmode before NineSlicePlane is rendered.
Previously in Canvas Mesh: #4535
> Support blendModes with NineSlicePlane and CanvasRenderer

- src/interaction/InteractionManager.js
- test/core/Graphics.js
- test/interaction/InteractionManager.js
Fixes https://github.com/pixijs/pixi.js/issues/4564
Unit tests to cover this new case added (some interaction unit tests were within graphics; I've moved these into the interaction manager)
Example on 4.6.2: http://jsfiddle.net/themoonrat/fjo9aeew/1/
Example with fix: http://jsfiddle.net/themoonrat/fjo9aeew/2/
Note on 4.6.2, you see the hand appear if you follow the circles outside of the box on the bottom right corner. A console log is also output when a circle is hovered over. This no longer occurs with the fix
> Children outside of hitArea cannot be hit

- src/interaction/InteractionManager.js
Update the mouse position in onPointerMove when using a pen tablet (like a wacom), the same as with a mouse. (Browsers that support Pointer events)
> Update mouse position in onPointerMove, when using a pen tablet

- src/core/text/Text.js
- test/core/Text.js
Fix for this issue,  details described in there.
https://github.com/pixijs/pixi.js/issues/4618
This pull request also contains unit test to ensure minimum canvas size.
> added min size restriction for Text canvas

- src/filters/colormatrix/ColorMatrixFilter.js
First off, thanks for PixiJS!
I have been experimenting with `ColorMatrixFilter` and was confused by the `negative` effect: my understanding was that it would invert the RGB colors, but that did not seem to be the case (as simple case try to invert a white shape on a black background); either I'm doing something wrong or the inversion matrix is simply wrong?
Using the matrix:
```
-1  0  0  0  1
0 -1  0  0  1
0  0 -1  0  1
0  0  0  1  0
```
produces negatives for me.
On a related note, I noticed that multiplying effects (using the `multiply` parameter) produces strange results (using both built-in matrices and my own), because of the adjustments done by `_colorMatrix()`. If I multiply effects using `_multiply` and set the resulting matrix myself the result looks good to me (both the matrix …
> Fix ColorMatrixFilter negative effect

- packages/app/src/Application.js
- packages/canvas/canvas-renderer/src/autoDetectRenderer.js
- packages/constants/src/index.js
- packages/core/src/Renderer.js
- packages/core/src/context/ContextSystem.js
- packages/core/src/geometry/GeometrySystem.js
- packages/core/src/index.js
- packages/core/src/settings.js
- packages/core/src/shader/utils/getTestContext.js
- packages/core/test/Renderer.js
- packages/settings/src/settings.js
- packages/sprite/src/SpriteRenderer.js
The following test is breaking locally: `setting option legacy should disable VAOs and SPRITE_MAX_TEXTURES` ~, this will disable WebGL2 if `legacy` is enabled.~
* Adds `PIXI.ENV` enum which describes the different type of maximum environmental settings that PixiJS will attempt to deal with using WebGL (v1, v2, and v1 legacy)
* Adds `PIXI.settings.PREFER_ENV` which accepts values from `PIXI.ENV`.
> Replaces PREFER_WEBGL_2 and options.legacy with ENV and PREFER_ENV

- bundles/pixi.js-legacy/package.json
- bundles/pixi.js/package.json
- lerna.json
- package.json
- rollup.config.js
* Packages are not longer minified, because these libraries are not consumable by the browser directly via `<script>` tag (use for Webpack, etc), users should be responsible for the type of minifying they want. Removing uglify from the Rollup plugins makes the build faster.
* Bundles now generate both minified and unminified browser files, these are also deployed to Travis and published to NPM. Consistent with v4.
* [**pixi.js**](https://pixijs.download/next-bundle-minification/pixi.js)
* [**pixi.min.js**](https://pixijs.download/next-bundle-minification/pixi.min.js)
* [**pixi-legacy.js**](https://pixijs.download/next-bundle-minification/pixi-legacy.js)
* [**pixi-legacy.min.js**](https://pixijs.download/next-bundle-minification/pixi-legacy.min.js)
* Bumped Lerna to latest for the …
> [next] Improves Use of Minified Bundles

- packages/core/src/filters/spriteMask/SpriteMaskFilter.js
- packages/core/src/filters/spriteMask/spriteMaskFilter.frag
- packages/core/src/mask/MaskSystem.js
- packages/display/src/DisplayObject.js
First, MaskSystem was broken.
Second, I found the problem in SpriteMaskFilter shader that existed in v4.
This line in SpriteMaskFilter shader is wrong for masks that have alpha component, because R is premultiplied.
```glsl
original *= (masky.a * masky.r * alpha * clip);
```
Lets fix it and allow to use NPM textures too.
Current: http://pixijs.io/examples/?v=next#/demos/alpha-mask.js
Fix: http://pixijs.io/examples/?v=next-mask-alpha#/demos/alpha-mask.js
NPM fix: https://jsfiddle.net/Hackerham/6os1us0o/6/
> [next] mask alpha fix

- packages/core/src/state/StateSystem.js
- packages/core/src/state/utils/mapWebGLBlendModesToPixi.js
Copy of V4 code:
https://github.com/pixijs/pixi.js/blob/dev/src/core/renderers/webgl/WebGLState.js#L158
This allows to use NPM modes.
> [next] blendFuncSeparate fix

- packages/core/src/textures/resources/ImageResource.js
Chrome ignores webgl texture upload params in favor of createImageBitmap params.
Pixi: https://jsfiddle.net/Hackerham/6os1us0o/113/
WebGL: https://fiddle.jshell.net/sosw339h/36/
Coordinates were added as params because Firefox doesnt like the fact I pass only `options`
Reported: https://bugzilla.mozilla.org/show_bug.cgi?id=1442632
> [next] image bitmap bug

- package.json
This is causing next to fail on Travis. Filed related issue here: https://github.com/rollup/rollup-plugin-commonjs/issues/299
* I would like to upgrade to the latest Rollup (which fixes the issue with commonjs) but I found a bug that prevents me from doing that when building the bundles. Rollup is having issues with importing a namespace and using a single class from that namespace. Will try to sort out a bug issue for Rollup. 
* Also, I would like to start checking in shrinkwrap/lock file to **next** to prevent this happening in future. We cannot have external dependencies break us so easily.
> Hotfix for rollup-plugin-commonjs

- src/core/Application.js
- test/core/Application.js
Hello folks! I like autotests and would like to start to contribute to your project
> Add unit tests for Application.ticker setter

- src/interaction/InteractionData.js
- src/interaction/InteractionEvent.js
- src/interaction/InteractionManager.js
event.buttons is not supported on Safari: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/buttons
However, it does have a non-standard event.which property, which we can use as a backup to convey the same information.
Also, whilst around here, changed private functions to public in InteractionData; they were clearly not private as they are used externally in InteractionManager.js
> Polyfill interactionData buttons property via event.which for Safari browser

- src/core/const.js
Noticed this small typo while reading up on http://pixijs.download/dev/docs/PIXI.html#.WRAP_MODES
Changes `wraping` to `wrapping`.
> Fix typo in PIXI.WRAP_MODES docs

- .travis.yml
- package-lock.json
It's time that we upgrade to Node.js v8 for Travis. This include committing **package-lock.json** to our repo. Information about **package-lock.json**: https://docs.npmjs.com/files/package-lock.json
Mainly, we need to lock down dependencies so we don't have dependencies breaking our builds all the time.  Related issue that just happened when rollup-plugin-commonjs broke our build: #4737
> Adds package-lock.json, upgrades Travis to Node.js v8

- .travis.yml
- packages/graphics/src/GraphicsRenderer.js
I need to temporarily disable deploying the latest release with Travis on **next**. Need a better solution to deal with pre-releases and S3 deployment. This change will not put v5-alpha.2 as the latest release.
> [next] Disables release build

- bundles/pixi.js/pixi.js.d.ts
Somehow my tests failed to show this. I remember that I checked for independent "pixi.js" that doesnt have CanvasRenderer inside.
> [next] Typings CanvasRenderer issue

- packages/core/src/mask/MaskSystem.js
- packages/core/src/mask/StencilSystem.js
- packages/interaction/src/InteractionManager.js
Now any object can be a stencil mask, including a container.
This gives users loads of power, along with the ability to render more complex masks in a much simpler way.
> Allow any object to be a stencil mask.

- packages/core/src/textures/Texture.js
If no resolution is passed to when using ```PIXI.Texture.from```
Pixi will try to figure out the resolution based on the url.
This brings the behaviour in line with how textures are loaded using the loader. Happy days!
> Added resolution check

- src/deprecation.js
Added message-stack map to prevent showing multiple warning messages from same place. 
Didn't change anything for case with "IE < 10 and Safari < 6" - should I add separate array to store shown messages for this case?
Fix for issue #4443
> Repeating deprecation warnings #4443

- bundles/pixi.js/src/deprecated.js
- packages/core/src/textures/Texture.js
- packages/sprite/src/Sprite.js
Cleaned up sprite helper functions.
We only really need one! ```PIXI.Sprite.from```
Added ability to pass texture options
Brings function inline with ```PIXI.Texture.from```
Also you can now pass a texture in to the from function. Handy!
> Clean up of sprite helper functions

- src/core/sprites/canvas/CanvasSpriteRenderer.js
You can see it here:
https://jsfiddle.net/1cj8w0mv/24/
> Fixed a difference between canvas and webgl sprite renderer on scaled textures.

- bundles/pixi.js/src/deprecated.js
- packages/app/src/Application.js
- packages/app/test/index.js
- packages/canvas/canvas-renderer/src/CanvasRenderer.js
- packages/canvas/canvas-renderer/src/autoDetectRenderer.js
- packages/core/src/AbstractRenderer.js
- packages/core/src/Renderer.js
This adds an option to Application to support automatically resizing the canvas to the width and height of the Window or specific DOM element. This is a _very_ common usage and has popped up several times: #4796 #4757 #4731
* Adds `resizeTo` option and property to the Application class, this is the Window or HTMLElement to resize the renderer to.
* Renames `autoResize` option and property of PIXI.AbstractRenderer to `autoDensity` since it has more to do with resolution density of the canvas rather than the actual resizing action. The name `autoResize` is misleading because the user still has to manually trigger `resize` on the renderer.
https://jsfiddle.net/bigtimebuddy/m4a8btv6/
> Adds Application property resizeTo, renames autoResize to autoDensity

- packages/app/src/Application.js
- packages/core/src/renderTexture/BaseRenderTexture.js
- packages/core/src/renderTexture/RenderTexture.js
- packages/core/src/textures/Texture.js
- packages/mesh/src/NineSlicePlane.js
- packages/mesh/src/Plane.js
- packages/mesh/src/Rope.js
- packages/particles/src/ParticleContainer.js
- packages/prepare/src/BasePrepare.js
- packages/sprite-animated/src/AnimatedSprite.js
- packages/sprite-tiling/src/TilingSprite.js
- packages/sprite/src/Sprite.js
- packages/spritesheet/test/Spritesheet.js
- packages/text-bitmap/test/BitmapFontLoader.js
Follow up to #4775 
* Removes `fromFrame`, `fromImage`, etc from the documentation and tests
* Fixes an issue with `TilingSprite.fromImage` not correctly using `Texture.from`
> Next from methods

- src/core/renderers/webgl/managers/FilterManager.js
- src/core/renderers/webgl/utils/RenderTarget.js
#3866 and other issues.
@Patrick-Hammond confirmed that we still have the problem, and I want to solve it radical way.
> backport filter pool key

- bundles/pixi.js/package.json
- bundles/pixi.js/scripts/support-pixi.js
This PR adds a link to Patreon in the console on postinstall when installing **pixi.js**. Many projects are doing this now, and it's a great idea!
> Adds Patreon support link

- packages/core/src/filters/FilterSystem.js
Kinda port of #4897.
Somehow, we forgot to add this field. I know that sometimes custom filters want to know target element. At the same time, we have to clear the state because it can leak a bit. 
Improved documentation.
> [next] Filter target

- src/interaction/InteractionManager.js
Fixes #4908 
I hadn't originally made #4872 this way because it was a little less clean, but in order to retain the same event order this arrangement is required.
> Move pointertap after pointerup for clicks.

- packages/app/src/Application.js
- packages/core/src/AbstractRenderer.js
- packages/core/src/Renderer.js
- packages/core/src/renderTexture/BaseRenderTexture.js
- packages/display/src/DisplayObject.js
- packages/mixin-cache-as-bitmap/src/index.js
- packages/mixin-get-child-by-name/src/index.js
- packages/mixin-get-global-position/src/index.js
- packages/sprite-animated/src/AnimatedSprite.js
- packages/sprite/src/Sprite.js
- packages/text-bitmap/src/BitmapText.js
- packages/utils/src/browser/isWebGLSupported.js
- tools/renders/src/Renderer.js
Code examples make it easy for anyone quickly see how a function or property is used. Add a few code examples for (Sprite.anchor) and (DisplayObject.mask). Fix many grammatical, spellings and punctuation mistakes. Also, highlight actual code values in the description.
First PR to PixiJS, hoping to get more in. Next, I'll try to write some useful unit-tests.
> Add a few code examples in the docs and fix grammatical mistakes

- src/core/Application.js
- src/loaders/index.js
- test/core/Application.js
This PR adds the ability to completely destroy an application including it's textures from a single call to `PIXI.Application.destroy` at the top level.
```javascript
const app = new PIXI.Application();
app.destroy(false, true);
```
[More details](https://github.com/pixijs/pixi.js/issues/4135)
> Allow passing DisplayObject destroy options from PIXI.Application

- packages/text-bitmap/src/BitmapFontLoader.js
- packages/text-bitmap/test/BitmapFontLoader.js
- packages/text-bitmap/test/resources/font1.fnt
This is a cleanup of #4641 which was breaking **next**. The root of the problem is the management of TextureCache by BitmapFontLoader. Resource-Loader middleware should not rely on TextureCache for cached textures and instead should rely on the loader's `resources` object. 
A similar change should probably be backported to v4.
> [next] Fixes Multi-Texture BitmapText Fonts

- src/extras/BitmapText.js
- src/loaders/bitmapFontParser.js
- test/extras/BitmapText.js
- test/extras/resources/font-no-page.fnt
- test/loaders/bitmapFontParser.js
- test/loaders/resources/split_font2.fnt
Fixes #4950
This is a clean up of #4641 which had some issues. Namely:
* Did not gracefully support manually side-loading images with the loader
* Introduced potential race-conditions when loading split image fonts
* Fails to work with single page fonts which do not contain a `page` attribute on `<char>` elements
* Without `page` attributes for the `<char>` element, falls back to a default of `0` instead of creating a 0 width and 0 height Texture frame.
* Fixes and adds tests for side-loading images inside fnt file and prefer an explicit object map of page file names to textures as the first parameter for `BitmapText.registerFont`. This will make sure that textures line up, even if the pages are out of order or have non-numerical IDs.
```js
// If registering fonts with split images, use a …
```
> Creates unit-test and improves single and multiple image font loading

- src/core/text/TextMetrics.js
Fix for the issue I mentioned in https://github.com/pixijs/pixi.js/issues/4791.
> TextMetrics.wordWrap - Don't add a newline if it's the last token/word

- src/core/text/TextStyle.js
- test/core/TextStyle.js
The CanvasRenderingContext2D.font property when taking in CSS generic font families doesn't work correctly when those families are quoted. This makes a whitelist to not quote those families.
> Do not quote escape generic font families

- packages/canvas/canvas-renderer/src/CanvasRenderer.js
- packages/core/src/Renderer.js
- packages/core/src/textures/BaseTexture.js
- packages/display/src/DisplayObject.js
- packages/interaction/src/InteractionManager.js
Follow-up to #4232
This is a workaround for https://github.com/jsdoc3/jsdoc/issues/1425 which doesn't document `@event` correctly if the events are at the bottom of the constructor. Since this is a convention that PixiJS uses in a few places, I moved the events just above the last line. Event now show up correctly and works with JSdoc 3.5.5+.
> Fixes JSdoc Events in 3.5.5

- src/core/graphics/Graphics.js
The default alignment value is 0.5, not 1.
> Fix typo in Graphics.lineStyle's jsdoc

- src/core/sprites/Sprite.js
This makes the documentation read correctly when the line breaks are lost when reading on https://pixijs.download/dev/docs/PIXI.Sprite.html
> [docs] Sprite.anchor: add periods

- src/core/graphics/Graphics.js
When defining a path, any call to beginFill results in the path being closed,
but only for the Canvas renderer, not for the WebGL renderer.
This commit removes the check that sets the shape to be closed when a fill is
active. This unifies the rendering behavior between Canvas and WebGL.
> Bugfix: Don't autoclose paths when using canvas (#4154)

- src/core/renderers/canvas/CanvasRenderer.js
- src/core/renderers/webgl/WebGLRenderer.js
Fixes #5053, incorrect docs for `render` on CanvasRenderer and WebGLRenderer. The `transform` param should be a PIXI.Matrix, not PIXI.Transform.
> Renderers' render transform param should be a Matrix, not Transform

- src/core/display/DisplayObject.js
- src/core/display/Transform.js
- src/core/display/TransformStatic.js
This fixes a documentation problem where two sentences run into
each other when displayed in HTML.
See: http://pixijs.download/release/docs/PIXI.Graphics.html#pivot
> [docs] Add missing period to pivot docs.

- src/core/text/TextMetrics.js
- test/core/TextMetrics.js
`TextMetrics.measureText`'s wordWrap override just used an or statement to detect undefined/null, but in cases of passing an override of false when the style's wordWrap was true, this would just do `= false || true` and not override.
> Small TextMetrics fix - Couldn't override wordWrap to false if TextStyle.wordWrap was true

- src/interaction/InteractionManager.js
Leave note in pointerup docs suggesting mousedown / mouseup instead when multiple button events are desired. Clarification added for #4863
> Update pointerup docs

- packages/text-bitmap/src/BitmapText.js
- packages/text/src/Text.js
- packages/text/test/Text.js
As requested by https://github.com/pixijs/pixi.js/issues/4942
It is annoying to have to check against " " for an empty string when you've set that piece of text to "".
Internally, it'll use " " as it's just easier to deal with for measuring the size of text
> Setting text to be "" means it is actually "", and not transformed to " "

- packages/text/package.json
- packages/text/src/Text.js
- packages/text/test/Text.js
https://github.com/pixijs/pixi.js/issues/4915
By default, it auto adjusts to the render resolution, as per current behaviour
But if you use the resolution setter on the text, it becomes manually controlled.
> Able to set resolution of text separately to the renderer

- test/core/VideoBaseTexture.js
> Removes unnecessary `new` usage for `fromUrl`

- package-lock.json
- package.json
Fixes a known security vulnerability in Electron v1.8.3, upgrades to 1.8.8. Electron is a devDependency we use for headless testing of PixiJS, but still worth upgrading.
> Updates dependency for Electron

- src/core/math/ObservablePoint.js
- src/core/math/Point.js
Observable point was missing clone and equals methods. Since the ObservablePoint is highly coupled to Point, and Point already had those methods, I've updated it to extend.
> Fixes ObservablePoint compatibility with Point

- src/core/graphics/Graphics.js
- test/core/Graphics.js
Ignore duplicate calls to lineTo (same x, y inputs) to prevent gaps in WebGL render. Addresses #4046 and #3592. edit: also #4890
Notes: it is not yet understood why duplicate lineTo calls caused gaps to begin with. Also, I'm not sure of a good way to unit test this without comparing render output. If anyone has anything to say about either point, I'm all ears. Thanks!
> prevent gaps in duplicate lineTo calls

- src/extras/cacheAsBitmap.js
In our internal PIXI-wrapped engine we ended up setting an empty array on the filters property of some cached elements and I found this.
Not that I consider this is a "bug", but adding this won't harm.
Edit: I couldn't find any associated unit tests. Am I missing something?
> Fix cache as bitmap filters check

- src/core/textures/Texture.js
- src/core/textures/VideoBaseTexture.js
There are already 2 PRs to try and solve a problem devs are having; not wanting video to autoplay when created.
https://github.com/pixijs/pixi.js/pull/5109
https://github.com/pixijs/pixi.js/pull/5112
We've put a lockdown on new APIs for v4, which means these 2 PRs are both compromised on how they work, imo.
Since this is a very real issue that multiple developers are having, I think we should allow this extra parameter in the constructor to solve this properly.
> Extra constructor property to control video autoPlay

- src/core/renderers/webgl/managers/FilterManager.js
The code below ([jsfiddle](http://jsfiddle.net/ypex3ktg/4/)) will fail with `Uncaught TypeError: Cannot read property 'value' of undefined`
```javascript
const app = new PIXI.Application({
width: 400,
height: 400,
})
const sprite = new PIXI.Sprite()
sprite.width = 400
sprite.height = 400
const filter = new PIXI.Filter(undefined, `
uniform float xxx;
void main(){
gl_FragColor=vec4(1,0,0,1);
}
`, {
xxx: {
type: 'float',
value: 1.2,
},
})
sprite.filters = [filter]
app.stage.addChild(sprite)
document.body.appendChild(app.view)
```
https://github.com/pixijs/pixi.js/blob/32219397a2a4dbc2d0ad0ead601ffb8636c6d224/src/core/renderers/webgl/managers/FilterManager.js#L422
Because `filter.uniformData` contains `xxx` but `filter.uniforms` does not.
So I am adding a checker here.
> Fix the exception if an unused uniform is defined.

- packages/display/src/DisplayObject.js
- packages/display/test/DisplayObject.js
The proposed solution from https://github.com/pixijs/pixi.js/pull/4579 which got recently closed.
I've had `angle` as a property like this on my version of PIXI for a while, and it makes it so much easier to configure a display object's rotation via JSON :)
> Added 'angle' property for DisplayObject

- packages/settings/src/settings.js
- packages/settings/src/utils/canUploadSameBuffer.js
- packages/settings/src/utils/maxRecommendedTextures.js
Also defaults precision fragment on ios to 'highp' - to stop issues of wobbling sprites by default like with https://github.com/pixijs/pixi.js/issues/3742
canUploadSameBuffer to not use it's own ios detection code, and use 'ismobilejs'
> [Next] Allows more texture units to be used by modern Android and Apple devices

- packages/core/src/filters/FilterSystem.js
- packages/core/src/renderTexture/RenderTextureSystem.js
fixes the final texture always defaulting to the screen. Good catch Ivan!
Took opertunity to moe the defaultFilterStack to the filterSystem as it makes more sense for it to be there.
> fix for #5151

- src/core/graphics/canvas/CanvasGraphicsRenderer.js
- src/core/renderers/canvas/utils/CanvasMaskManager.js
Look at polygon direction, draw a hole to counter it.
Bad: https://www.pixiplayground.com/#/edit/W2Dm4fZVm9ygrRYqiVDXJ
Fixed: https://www.pixiplayground.com/#/edit/X8tnNzuRIXgPJBBiJTi7x
Bad: https://www.pixiplayground.com/#/edit/GfZudGKNnnrFe~xK8iJ7D
Fixed: https://www.pixiplayground.com/#/edit/sRbmePH_D70ofcyRlXMbA
As you can see, strokes around holes are not consistent in canvas/webgl, I don't know what to do about that yet.
Build: http://pixijs.download/dev-canvas-mask-holes/pixi.js
> Mask graphics holes in CanvasRenderer

- packages/core/src/batch/BatchRenderer.js
- packages/graphics/src/GraphicsData.js
- packages/graphics/src/GraphicsGeometry.js
- packages/mesh-extras/src/SimplePlane.js
- packages/mesh-extras/src/SimpleRope.js
- packages/mesh/src/Mesh.js
- packages/sprite-animated/src/AnimatedSprite.js
PR contains only simple fixes
Mesh refactoring will be separate
> `this.textureIds.length = 0;`
That thing crashed https://pixijs.io/examples/?v=next#/basics/textured-mesh.js
> `elements[i] = null;`
Backport from v4 fix
> [next] Graphics memory leak

- packages/core/src/textures/GLTexture.js
- packages/core/src/textures/TextureSystem.js
Setting incorrect wrapMode of texture in webgl1 should not lead to error.
Example:
https://www.pixiplayground.com/#/edit/X7GwGFqITM40hRjBd2cID
Set "PREFER_ENV=2" in first line , see many bunnies. 
Set the build `https://pixijs.download/next-fix-webgl1-wrap/pixi.js`, see one bunny.
> [next] webgl1 and wrapMode

- packages/canvas/canvas-mesh/src/settings.js
- packages/core/src/settings.js
- packages/settings/src/settings.js
- packages/ticker/src/settings.js
- packages/utils/src/settings.js
Some jsdocs were incorrect (none are const, as they can all be overwritten by the user).
Corrected a namespace
Added @name onto them, so ensure that the jsdoc linking works correctly when @link or @see is used. I think this mainly applies to settings applied by importing `@pixi/settings` and adding to it rather than the settings package itself, but for consistency I've applied it to all settings
> [Next] jsdoc fixes for settings

- src/core/textures/TextureUvs.js
This thing exists through all the life of pixi-v4, since 6 jan 2016, it leads to wrong rendering of sprites with LINEAR scaleMode (it is default!).
The thing is, for numbers like `1/1024` we always lose 1 digit, when we actually dont have to lose anything.
```
1/1024 - Math.round(1 / 1024 * 65535) / 65535 === -1.4901388570992546e-8
1/1024 - Math.floor(1 / 1024 * 65535) / 65535 === 1.5244120508125375e-5
```
For center pixel loss is the same for both algorithms:
```
0.5 - Math.round(0.5 * 65535) / 65535 === -7.629510948348184e-6
0.5 - Math.floor(0.5 * 65535) / 65535 === 7.629510948348184e-6
```
Size of pixel 1/1024 is `1e-3`  , one point of color is `2e-2` , if we multiply it we'll get `2e-5`, too close to our precision loss. Experiments show that 1 binary digit in the case is critical. We …
> UV precision bug

- src/core/renderers/webgl/TextureManager.js
- src/core/renderers/webgl/utils/RenderTarget.js
- src/core/textures/VideoBaseTexture.js
Bug was reported in RpkMaker MV year ago , fix appeared in [corescript](https://github.com/rpgtkoolmv/corescript/pull/194), then I found actual cause in [pixi-tilemap](https://github.com/pixijs/pixi-tilemap/commit/1053aab63a7a30004ca7ab249fafb31b8cc0dfe3)
https://www.pixiplayground.com/#/edit/j38lu2giZW7uyEBkI0Eab
> UpdateTexture should not switch FrameBuffer

- src/extras/TilingSprite.js
Hello,
I've found a bug in TilingSprite implementation for canvas renderer. 
In current implementation it doesn't include the necessary transformation for textures rotated in texture atlases, thus rendering them incorrectly. I've tested this with atlases generated by TexturePacker for pixijs.
I hope the description is enough, if you have any questions feel free to ask.
This is my proposal of a fix for this issue.
PS This is my first contribution to pixi.js and I hope that I did everything according to contribution guide.
> Fix TilingSprite:_renderCanvas to account rotated textures from texture atlas

- src/core/textures/Texture.js
- test/core/Texture.js
Follow up to #5011, where `Texture.clone` does not consider  copying `defaultAnchor`.
> Fixes defaultAnchor cloning with Texture.clone

- src/core/graphics/Graphics.js
Graphics bounds calc was broken after adding `lineAlignment` option for non-default values of `lineAlignment`. For example, this is what we getting when value is `1` (outer lines):
And this is for `0` (inner lines):\
Code in PR resolves this issue.
> Fix Graphics _localBounds calculation

- src/core/math/shapes/Ellipse.js
Constructor with (x, y, width, height) parameters confused, because rectangle-based ellipse supposed, but it's created from two radiuses and middle point.
> Rename parameters for user friendly

- packages/core/src/AbstractRenderer.js
- packages/utils/src/logging/deprecation.js
Follow-up to #5057
* Use of Renderer's `roundPixels` option will use PIXI.settings.ROUND_PIXELS instead
* Also, adds a small API improvement to `PIXI.utils.deprecation` to add custom ignore depth stack
> [next] Properly deprecate roundPixels Renderer option

- packages/filters/filter-blur/src/BlurFilter.js
- packages/filters/filter-blur/src/BlurFilterPass.js
- packages/filters/filter-blur/src/generateBlurFragSource.js
- packages/filters/filter-blur/src/generateBlurVertSource.js
I dont understand what `firstRun` was supposed to do, but in v5 its doing nothing. Please return it back if you figure out a way to determine `kernelSize` in constructor.
Also, because of that code in v4, `kernelSize` parameter was ignored, how did it even work? Had we always choose the slowest Blur method available?
> [next] BlurFilter cleanup

- packages/core/src/Renderer.js
Seems we were adding default properties to options in the abstract class, but using the original in the webgl renderer.
all fixed 👍
> Fixes issue where antialiasing setting is always true regardless of options passed in 

- src/interaction/InteractionManager.js
For some reason I can't understand, but probably due to polyfills, an actual pointer event can come through to the 'normalising' function; and you cannot overwrite existing properties on this object, causing the error seen at https://github.com/pixijs/pixi.js/issues/5283
> v4 - interaction assignment fix

- src/core/renderers/webgl/utils/RenderTarget.js
That's the problem. #5321 
build is here: https://pixijs.download/dev-renderbuffer-destroy/pixi.js
leaking fiddle: https://jsfiddle.net/1pdscnzv/
fixed: https://jsfiddle.net/1pdscnzv/1/
> Stencil RenderBuffer leak

- packages/core/src/Renderer.js
- packages/core/src/geometry/GeometrySystem.js
- packages/core/src/shader/Program.js
- packages/core/src/shader/utils/setPrecision.js
- packages/core/src/textures/TextureSystem.js
- packages/sprite/src/Sprite.js
- bugfix, removed geometry buffer cache. This could fall out of sync as setting VAOs could change the buffer outside of the specific function for doing so.
- bugfix, automatically setting precision was a bit borked as it was ending up below the name of the shader (causing it to fail to compile).
- optimisation - added a texture location cache - so we only call ``activeTexture`` if we need to.
- optimisation - TINY tweak to sprite, moved texture prop to the top in ``calculateVertices``.
enjoy!
> A batch of small fixes and tweaks for v5

- packages/ticker/test/Ticker.js
- test/index.js
- test/packages.js
There are two problematic Ticker tests that are failing intermittently and I'm not sure why but I can reproduce locally. I believe this might be after upgrading to Electron v4 + Floss. I need to dig deeper on the issue, but I have disabled them so it stop blocking Travis and other PRs.
Also, I improved how the tests are required which was ignoring Mocha's `skip` and `only` calls.
> Temporarily skip problematic tests

- .travis.yml
- packages/core/test/Renderer.js
- packages/graphics/test/index.js
- packages/mesh-extras/test/Plane.js
Umm, so apparently this is a thing now. WebGL tests run using Electron on Travis.
```
545 passing (4s)
```
* Removes environment setting for disabling WebGL tests
* Removes WebGL test gates from unit-tests
> Enables WebGL test on Travis

- src/core/math/shapes/Rectangle.js
- test/core/Rectangle.js
This bug affected FilterManager for 3 years.
Sometimes filterArea is enlarged, sometimes its entirely gone.
@GoodBoyDigital introduced that function in https://github.com/pixijs/pixi.js/commit/35af42ef1b147f3750323a9ebb1469c2dfe72dc5#diff-02fe1864d0a7cfbb4d01dbc448e82f9dR123
@madclem made a fix: https://github.com/pixijs/pixi.js/commit/ef6df3d5f63d8b6d85efdc2067a336407f804344#diff-02fe1864d0a7cfbb4d01dbc448e82f9dR120
@out-of-band and @bigtimebuddy made tests for it, unfortunately, there was a bug too: https://github.com/pixijs/pixi.js/commit/5f76782f2b1e898a5b32f584bc4b6faab88c4bdb#diff-ecddd9adab4c39b456488ad40a0fc0dbR155
Please make a parallel PR for v5.
> V4 rectangle fit

- packages/display/src/DisplayObject.js
I made a mistake in #5345, I added that field to DisplayObject with default value `true` instead of `false`. It affects masks.
> DisplayObject is not sprite by default

- packages/accessibility/src/AccessibilityManager.js
- packages/accessibility/test/AccessibilityManager.js
When running on phone or tablet accessibility manager creates hook div that doesn't removes when manager dies before the hook has been focused.
> Remove accessibility manager hook div from dom on destruction

- packages/core/src/textures/resources/VideoResource.js
- packages/core/src/textures/resources/autoDetectResource.js
- packages/core/test/VideoResource.js
Can really help the performance; no need to be updating the texture when no change to the video has occured
https://github.com/pixijs/pixi.js/issues/4789
> Allows developer to limit the texture update rate of videos

- packages/core/src/framebuffer/FramebufferSystem.js
- packages/math/src/shapes/Rectangle.js
Demo: https://www.pixiplayground.com/#/edit/iC8~ZgJkLzuEvAFkSTM9a
produces console error 
```
FramebufferSystem.js:226 WebGL: INVALID_OPERATION: renderbufferStorage: no bound renderbuffer
```
> Framebuffer resize doesn't work with masks

- src/extract/canvas/CanvasExtract.js
Fixes #5361
**Broken:** https://pixiplayground.com/#/edit/D7Ej6bF7gjJ34LbtCSTHj
**Fixed:** https://pixiplayground.com/#/edit/5H8_X0gjLAU8iePgEw4_N
> Fixes CanvasExtract plugin canvas method without target

- packages/interaction/src/InteractionManager.js
- packages/interaction/test/MockPointer.js
- packages/prepare/src/BasePrepare.js
- packages/prepare/test/BasePrepare.js
- packages/ticker/src/Ticker.js
- packages/ticker/src/TickerPlugin.js
- packages/ticker/test/Ticker.js
The shared ticker is tricky atm because you may want to pause the visuals on screen, but you don't want to effect the interactions or core system behaviour.
So having this system ticker separate means that you can now safely pause the shared ticker without worrying about it effecting that system behaviour
> A system ticker to sit alongside the shared ticker.

- README.md
First, hello I am new to this project!
I wanted to give this a whirl and noticed that the README had a bootstrap example, but I was getting an ugly deprecated warning within my IDE.
So I simply updated the README to use the newer non deprecated 
`PIXI.Loader.shared.add`
> Updated README example to use new PIXI.Loader.shared method

- packages/text/src/Text.js
- packages/utils/src/color/hex.js
Uses the canvas api for applying the drop shadow functionality, rather than adding it via extra draw calls.
This should be quicker to draw, as well as giving more accurate results; fixing issues such as https://github.com/pixijs/pixi.js/issues/4772
> v5 - Fixes Text drop shadows

- packages/prepare/src/BasePrepare.js
- packages/prepare/src/index.js
- packages/prepare/src/settings.js
- packages/ticker/src/index.js
- packages/utils/src/index.js
Also moved import of settings higher in other index files. Might have been ok where it was, but logically makes sense to import them as early as possible
> BasePrepare was imbedding settings rather than having a settings.js file like other classes

- packages/constants/src/index.js
- packages/core/src/state/State.js
- packages/core/src/state/utils/mapWebGLBlendModesToPixi.js
As seen [here](https://github.com/pixijs/pixi.js/blob/dev/packages/constants/src/index.js#L63-L83), there is no `BLEND_MODES.NONE`
> there is no BLEND_MODES.NONE

- packages/core/src/geometry/Buffer.js
- packages/core/src/geometry/GLBuffer.js
- packages/core/src/geometry/Geometry.js
- packages/core/src/geometry/GeometrySystem.js
- packages/graphics/src/Graphics.js
- packages/mesh/src/Mesh.js
We have to discuss API, I've added `shared` field to Buffer and Geometry, and dev can mark them with `markShared()` method.
Demo:
https://www.pixiplayground.com/#/edit/YqUB4vUo8_Qcyqh6Z~PPT
You can see in the console that each second either strip either all geometries are disposed and it works. Extra VAO that is destroyed in apocalyptic event belongs to BatchRenderer.
Next step after this PR is fix of texture and shader disposal, and `contextLost` test.
> Proper disposal for mesh and graphics geometries

- packages/core/src/state/StateSystem.js
This is an update to #5377
I pulled this out of @ivanpopelyshev's PR #5391 because it's a bug and shouldn't be folded into that new feature PR.
> Fix for BLEND_MODES.NONE in StateSystem

- src/mesh/NineSlicePlane.js
My version of #5371 by @TheWyo , that fixes #3862.
`drawSegment` removed, and `_renderCanvas` has its own temporary uv's. That calls for more optimizations of this function in the future, like custom logic for roundPixels.
I've made an example that uses both resolution and frame cut, based on another old NineSlicePlane example: [https://www.pixiplayground.com/#/edit/HrETbRGJmES~XExxtdFy~](https://www.pixiplayground.com/#/edit/HrETbRGJmES~XExxtdFy~)
There are two renderers (WebGL and canvas2d, left and right), and I cut nineSlice texture exactly on the middle of the border.
> V4.x nineslice tint

- packages/loaders/README.md
This was updated in a previous PR, just fixing the README.
> Renamed LoaderPlugin to AppLoaderPlugin

- packages/app/src/Application.js
- packages/canvas/canvas-renderer/src/CanvasRenderer.js
- packages/canvas/canvas-renderer/src/autoDetectRenderer.js
- packages/core/src/AbstractRenderer.js
This flag seems to have an effect in Firefox as well as Chrome, so this
caveat in the docs is no longer relevant.
For example, on Firefox 60.5.0 on my Debian system:
Without `antialias`:
With `antialias`:
> Update docs for Application.antialias

- src/extras/AnimatedSprite.js
Each texture in animation can have different defaultAnchor.
This change allows AnimatedSprite's anchor to be updated on each frame.
> Added option to update anchor with defaultAnchor when frame changes.

- src/extras/cacheAsBitmap.js
Fix #5416.
Example by @takopus.
Crash Bug, 4.x: https://www.pixiplayground.com/#/edit/UFD711FVtXRvwA~8mIQie 
Press button 4 times, and it'll crash.
Shift Bug, 4.8.1: https://www.pixiplayground.com/#/edit/rIVogz0N~JfQQKR3ItYUc
Press button, sprite shifts.
Fixed: https://www.pixiplayground.com/#/edit/8~rAjGg3Bgicd9o050tKs
Old tests from #5298: 
https://www.pixiplayground.com/#/edit/jg7WEsoNFL1Cy55HB9f69 - shift in 4.8.1
https://www.pixiplayground.com/#/edit/T6MYvWjSO9EXakjVaTHSF - was cut in 4.8.1
https://www.pixiplayground.com/#/edit/~vUkTrNV9CYlxgR_lS_Ue - wrong bounds in 4.8.1
Everything passes on my comp, both Canvas and WebGL.
Also need to cherry-pick it to v5, file looks the same.
I marked it as High, because cacheAsBitmap crashes on CanvasRenderer. 
Lines 84 and 110 are real changes, …
> [v4] cacheAsBitmap fix calculateBounds problem

- packages/core/src/framebuffer/FramebufferSystem.js
- packages/core/src/renderTexture/RenderTextureSystem.js
We should perform all renderTexture checks even if its the same as we bound before. Our `renderer.resize` worked only because `renderer.render` passed `undefined` in this parameter, while `resize` was using `null`.
Try render null's: https://www.pixiplayground.com/#/edit/UomPY6pRxm6qncEEWxl2m
Rendertexture resize after render bug: https://www.pixiplayground.com/#/edit/dCYHcHa~UaegyTf9jDlr2
Those cases are rare, but its better if we cleanup the code.
`current` check is moved to framebuffer.
If we bind the renderTexture second time in a row, there's only one downside of this PR: pixi will check global uniforms projectionMatrix and reupload it. It wont rebind the framebuffer, and it wont call `gl.viewport`.
> RenderTextureSystem invalidation problem

- src/core/renderers/webgl/filters/spriteMask/SpriteMaskFilter.js
#5435 but for v4. Fix is the same, but example is more difficult due to differences in FilterManager. This one has a hackfix!
https://www.pixiplayground.com/#/edit/ZmKDR08Ibz2~HBfdNm167
> v4.x - SpriteMaskFilter clear param

- src/core/graphics/Graphics.js
#5442 for v4. Not critical, because adaptive curves are off by default.
> [v4.x] Adaptive curves fix

- packages/graphics/src/const.js
- packages/graphics/src/utils/QuadraticUtils.js
- packages/graphics/test/index.js
Because of bug in formula, curves that had big coords (>100) were divided by 2048 small segments.
Because of another bug in `pixi-const` v5 had adaptive curves enabled by default. Gladly, adaptive mode wasn't enabled by default in pixi-v4.
When we reviewed #4658 everyone, including the math guy (me), somehow didnt see obviously wrong equation. Obviously wrong because of `(cpX - 2.0)` , a constant subtracted from coordinate.
This PR fixes parenthesis order, that @icosaeder put there to fit it in our lint "no-mixed-operators" rule.
Demo has more than 32 arcs, that's more than 65536 vertices => 16-bit index buffer fails. We can see how its failing exactly on 32-th arc.
Demo 5.0.0-rc: https://www.pixiplayground.com/#/edit/9KVY7oZCiJ7lUG4Zx3bID
Demo this branch: …
> Adaptive curve formulas fix

- packages/core/src/batch/BatchRenderer.js
Fixes some hard coded vertsize 6's to be this.vertSize.
Had some issues with a custom sprite renderer due to not noticing these.
> Update hard coded vertSize's in BatchRenderer.js

- packages/core/src/framebuffer/FramebufferSystem.js
- packages/core/src/renderTexture/RenderTextureSystem.js
- packages/core/src/shader/ShaderSystem.js
- packages/core/src/state/StateSystem.js
- packages/core/src/textures/TextureSystem.js
It started in #5427, then I found out that we dont have enough `reset` methods.
IT WORKS! https://www.pixiplayground.com/#/edit/h9BQpJ3scsslkT~RO2JkM
And now, the old pixiJS-threeJS demo, but for V5 and ThreeJS 101. https://www.pixiplayground.com/#/edit/sPigqH5G1ogJ_5pocOs42
> Make `reset` work like in v4.

- packages/constants/src/index.js
- packages/core/src/textures/BaseTexture.js
- packages/core/src/textures/TextureSystem.js
- packages/settings/src/settings.js
Fixes #5407
This is compatibility PR, that way webgl1 and webgl2 produce the same result. If someone want non-pow2 texture to have mipmaps, they'll have to specify it.
```js
baseTexture.mipmap = PIXI.MIPMAP_MODES.ON;
```
The values are compatible with booleans in v4. `false` is `OFF=0`, `true` is `POW2=1`.
Demo: https://www.pixiplayground.com/#/edit/jk06IGwLU1Q9yT41pv7_j
V4: https://www.pixiplayground.com/#/edit/BuGK_ogiBOqaXCsSHyCe7
First and third colums are the same in V4 and V5, second is `mipmap=ON` for non-pow2 texture. As you see, webgl2 mipmaps are almost the same as webgl1 for enlarged textures.
I propose we use `POW2` mode by default for compatibility, right column for pow2 textures and left for everything else, like in v4.
> Mipmap pow2 compatibility

- packages/core/src/framebuffer/Framebuffer.js
- packages/core/src/framebuffer/FramebufferSystem.js
- packages/core/src/textures/resources/DepthResource.js
This is the start of  enabling depthTexture support.
This fixes the depthTexture from not being written to at all, and adds a depthResource that is used to fix the internalType needed for webgl2.0
This is a first pass at it, to get it working fully in webgl2.0. Then Ill move to 1.0 + extensions.
The depth resource is also something I'd like to instead be a option we can pass into either Resource itself as a property (internalFormat) or as a property for baseTexture. For now tho it'll have to do.
> Fixes depthTexture to work properly

- packages/sprite/package.json
> Unused dependency. Canvas-renderer goes into all es builds

- src/core/math/Matrix.js
- test/core/Matrix.js
Maybe long time ago there was something about scale. Now this branch is triggered only in one case and returns wrong answer.
Can be cherry-picked.
https://www.pixiplayground.com/#/edit/tbHFSNFRW4KCULGpdbygB
> [v4.x] Fix Matrix decomposition for a rare case.

- packages/app/src/Application.js
It seems this option is only available in pixi.js-legacy, and you can't use forceCanvas with pixi.js anymore. The docs should state that.
* https://github.com/pixijs/pixi.js/issues/5417
* https://github.com/pixijs/pixi.js/issues/5389
> Update docs for the forceCanvas option

- src/core/sprites/webgl/generateMultiTextureShader.js
Avoid equal compare between float number.
In extreme conditions, precision conversion can cause some strange problems.
```cpp
// vTextureId = 2.0
float textureId = floor(vTextureId + 0.5);
bool isEqual = textureId == 2.0; // isEqual = false
```
```js
if (i < maxTextures - 1) {
src += `if (vTextureId < ${i}.5)`;
}
```
> Avoid equal compare between float number

- .github/lock.yml
- .github/stale.yml
This pull request adds configurations for [stale](https://github.com/apps/stale) and [lock](https://github.com/apps/lock) GitHub apps.
The PixiJS team is very small and has limited resources to address the backlog of issues. The goal of using these bot apps is to focus the team on the most relevant issues.
Essentially this does a few things:
* Issues older than 3 months with no activity for 2 weeks are automatically closed
* Issues or pull requests that are not touched in over a year are automatically locked
> Implements stale and lock GitHub apps

- packages/core/package.json
- packages/core/test/ArrayResource.js
- packages/display/package.json
- packages/interaction/package.json
- packages/loaders/package.json
- packages/utils/package.json
- types/events.d.ts
Fixes #4594
* Bumps the major version of EventEmitter3 to be the latest.
* Update event typings
* Fixes test which now requires non-undefined listener to `addListener`
> Updates to EventEmitter3 latest release

- packages/prepare/package.json
Remove unused "@pixi/canvas-renderer" dependency from the package "@pixi/prepare".
> Remove canvas-renderer from @pixi/prepare dependency

- packages/core/src/textures/Texture.js
Tiny tweak that saves us having to needlessly call `getResolutionOfUrl` each time `Texture.from` is called.
> Moved resolution check to when a texture is created

- packages/core/src/framebuffer/Framebuffer.js
Howdy! Currently in v5 if you resize a renterTexture with a resolution different from 1 then the frame buffer breaks.. 
This is because the resolution  of the textures was not being taken into account when resizing the frame buffers (which are always resolution 1)
This fixes it 👍 
Here is an example of it busted:
https://www.pixiplayground.com/#/edit/gvG2JWZw7xSdCQIn8LaBB
running with this branch fixes it :)
> Fix a bug when resizing render texture with resolution other than one

- packages/core/src/settings.js
If anyone has better idea how to detect chromium on mobiles, feel free to alter this PR.
https://bugs.chromium.org/p/chromium/issues/detail?id=934823
> Don't use webgl2 on mobiles by default

- packages/graphics/src/GraphicsGeometry.js
Fixes #5503 . 
Algorithm works only if path does not cross edge of the texture.
Demo: https://www.pixiplayground.com/#/edit/M1BjLnu5mYIhqlNOdhMkJ
Thanks to @M00nR4bb1t
> beginTextureFill partial support of texture regions

- packages/interaction/src/InteractionManager.js
- packages/text-bitmap/src/BitmapText.js
Doesn't effect functionality, but will remove browser warning messages
Just implemented the suggested fix in the issue: https://github.com/pixijs/pixi.js/issues/5421
(ps. misc doc fix snuck in, no point in a full PR for it!)
> Only call preventDefault on normalised events if the browser allows it.

- bundles/pixi.js-legacy/src/index.js
- packages/app/package.json
- packages/app/src/Application.js
- packages/canvas/canvas-renderer/src/Renderer.js
- packages/canvas/canvas-renderer/src/index.js
- packages/core/src/AbstractRenderer.js
- packages/core/src/Renderer.js
- packages/core/src/autoDetectRenderer.js
- packages/core/src/index.js
- packages/core/src/renderTexture/BaseRenderTexture.js
- packages/core/src/renderTexture/RenderTexture.js
- packages/ticker/src/Ticker.js
Dropping `PIXI.autoDetectRenderer` from the default `pixi.js` bundle has created some confusion with regards to using `pixi.js-legacy` for the fallback canvas support. This PR changes the implementation of `autoDetectRenderer` and `@pixi/canvas-renderer` to support a more sane more user-friendly version.
* If a user tries to run `PIXI.autoDetectRenderer` with the default `pixi.js` bundle or `@pixi/core` and doesn't have WebGL, PIXI will throw a useful error that says: `WebGL unsupported in this browser, use "pixi.js-legacy" for fallback canvas2d support.`
* Added some documentation for `forceCanvas` options in Application and `autoDetectRenderer` that highlight that this is only used when using `pixi.js-legacy` or `@pixi/canvas-renderer` packages.
* Dropped support for old argument …
> Re-implements autoDetectRender to reduce confusion

- bundles/pixi.js-legacy/package.json
- bundles/pixi.js-legacy/src/index.js
- bundles/pixi.js/package.json
- bundles/pixi.js/src/index.js
Many of the polyfills are required for IE 11 even though WebGL is supported like `Object.assign`, `Math.sign`, `Number.isInteger`, `Promise`. This moves the polyfills package to the default  bundle, not just the `pixi.js-legacy` bundle. In the future, we might want to revert this change. But for now we should try to broadly support all major browsers with WebGL.
> Better support for IE 11, by moving polyfills to default bundle

- packages/canvas/canvas-renderer/src/BaseTexture.js
- packages/canvas/canvas-sprite/src/CanvasSpriteRenderer.js
* Attaches `ICanvasImageSource` to the PIXI namespace for typings and to remove items from http://pixijs.download/dev/docs/global.html
> Cleans up ICanvasImageSource typings/docs

- packages/utils/src/color/premultiply.js
premultiply functions are incorrectly listed in the docs as:
```
exports.premultiplyRgba
exports.premultiplyTint
exports.premultiplyTintToRgba
```
Before: http://pixijs.download/dev/docs/PIXI.utils.html
After: http://pixijs.download/dev-fix-utils-docs/docs/PIXI.utils.html
> Fixes premultiply docs

- bundles/pixi.js/src/useDeprecated.js
Removes the need for [migration guide](https://github.com/pixijs/pixi.js/wiki/v5-Migration-Guide#basetexture-changes) step for BaseTexture's `loadSource` by providing a suitable workaround via deprecation.
Edit:
Also, deprecates `imageUrl` and `hasLoaded`.
cc @Adam13531
> Properly deprecate BaseTexture v4 members and methods

- packages/core/src/state/utils/mapWebGLBlendModesToPixi.js
NPM blendmodes are obtained by swapping `gl.ONE` to `gl.SRC_ALPHA` of original blending modes. When I changed blendmodes in v5 I forgot to change corresponding NPM.
> Fix non-premultiply blendmodes

- src/core/renderers/webgl/utils/mapWebGLBlendModesToPixi.js
According to @Puuca this backport actually fixes artifacts on iPads.
> V4.x blendmode add

- packages/core/src/batch/BatchRenderer.js
- packages/core/src/textures/BaseTexture.js
- packages/graphics/src/GraphicsGeometry.js
Fixes #5520 
I added methods to BaseTexture because that's where `_batchEnabled` field is stored.
I also suggest that we expose those methods for plugin-makers but `_` means that it can be changed in any version without deprecation.
Broken: https://www.pixiplayground.com/#/edit/1WCb9fBbUQieUK2IdMKzR
Works: https://www.pixiplayground.com/#/edit/69HLoVsdpfl0NBwEyJws0
> Assure that TICK is different for multi-textured renderers

- package.json
Fixes an issue where `canvas-*` and `filter-*` dist files are not being copied and deployed on pixijs.download.
**Broken:**
http://pixijs.download/dev/packages/filter-alpha.js
**Fixed:**
http://pixijs.download/fix-copyfiles/packages/filter-alpha.js
> Fixes canvas and filters being copied

- packages/canvas/canvas-display/package.json
- packages/canvas/canvas-particles/package.json
- packages/canvas/canvas-sprite-tiling/package.json
- packages/mixin-cache-as-bitmap/package.json
- packages/mixin-get-child-by-name/package.json
- packages/mixin-get-global-position/package.json
- rollup.config.js
Because of the custom Rollup that's happening, the browser bundles were broken for the following packages. These packages don't actually export anything and a `name` property was ignored. I made this explicit by declaring `bundleNoExports` option in the package.json for these packages.
* canvas-display
* canvas-particles (also the bundle name was copy-pasta error)
* canvas-sprite-tiling
* mixin-cache-as-bitmap
* mixin-get-child-by-name
* mixin-get-global-position
Here's an example that includes every bundle file (basically reproduces **pixi.js-legacy**):
https://jsfiddle.net/bigtimebuddy/h0ytpn48/
> Fixes the mixin bundles

- packages/core/src/geometry/Attribute.js
[Fixes #5586 ](https://github.com/pixijs/pixi.js/issues/5586)
> Fixed parameter ordering

- packages/canvas/canvas-extract/src/CanvasExtract.js
- packages/extract/src/Extract.js
Fixes #4846
Adds `format` and `quality` parameters to extract plugins. This is a pass-through for `toDataURL`, see: https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL
> Adds format and quality options to extract plugins

- packages/canvas/canvas-mesh/src/CanvasMeshRenderer.js
- packages/canvas/canvas-mesh/src/SimpleMesh.js
- packages/core/src/geometry/Buffer.js
- packages/core/src/geometry/Geometry.js
- packages/mesh-extras/src/NineSlicePlane.js
- packages/mesh-extras/src/SimpleMesh.js
- packages/mesh-extras/src/geometry/RopeGeometry.js
- packages/mesh/src/Mesh.js
Noticed that `Geometry::getAttribute` was actually returning a `PIXI.Buffer`. Renamed the function to `getBuffer` and fixed the types (docs). 
Also added an implementation of `getAttribute`.
Added types (docs) to `Buffer::update()`
> Geometry - Rename `getAttribute` to `getBuffer`. Added `getAttribute` method

- packages/text/src/TextStyle.js
- packages/text/test/TextStyle.js
#4969 apparently didn't get put into v5, so here it is.  
Added a new unit test for it, and fixed 2 others who were expecting their result to have quoted generic families.
(not including ones already failing from a clean checkout of dev branch)
> Fix generic font families on v5

- packages/text/src/TextMetrics.js
Ensures giving characters enough height to show: https://github.com/pixijs/pixi.js/issues/5594
I couldn't get it going wrong in the example provided; I had to use the font "Courier New" to see the little circle get cut off.
As you see, it does make new lines of an occasional font slightly taller than before, so would be wary of making this change back to v4. But it does provide more accurate text, so this slight visual change might be fine for v5?
> Adds a potentially taller character to the metrics string

- packages/core/src/Renderer.js
Setting a custom transform slipped out of the render function at some point!
Adding it back in fixes cacheAsBitmap.
> fix for cacheAsBitmap

- packages/core/src/textures/BaseTexture.js
- packages/mesh/src/Mesh.js
Found two problems while trying to debug pixi-spine for v5.
1. I failed typings in #5546 
2. uvBuffer() returns data instead of Buffer.
Now it works with pixi-spine, I'm uploading update to examples.
I dont want to return `mesh.uvs` prop because that way people wont learn how to use buffer and call `update()` function for it.
> Fixes for pixi-spine

- packages/interaction/src/InteractionManager.js
We still require `hitTestChildren` to be true for events outside of a mask to make sure mouseouts are fired.
https://github.com/pixijs/pixi.js/issues/5135
> Ensure that a mouseout is fired with masked containers

- packages/text/src/Text.js
https://github.com/pixijs/pixi.js/issues/5571
Changed fix to use Array.from as linting didn't like the use of for each over a string
> Fixes emoji characters not displaying when letterSpacing style is used

- packages/core/src/textures/Texture.js
Fixes #5632
Internal PixiJS code should NOT be using deprecated properties. This will fail for users that try to import `@pixi/core` and destroy a RenderTexture. Only will work with **pixi.js** or **pixi.js-legacy**
**Broken**: https://pixiplayground.com/#/edit/PP6wCar~eanphFaVq41pZ
**Fixed**: https://pixiplayground.com/#/edit/gG5G1F0fQfK7yhq3EbaJM
> Texture destroy throws a deprecation warning

- package.json
Fixes #5634 
Without a `name` field in the **package.json**, Lerna does the npm default behavior and uses the name of the folder (e.g. `npm init --yes`). Unfortunately, this conflicts with the name of a child package (e.g. **bundles/pixi.js**) which causes the root-level lifecycle methods to be skipped. I'm not sure if this is an error with Lerna, but the workaround seems to be: add a unique `name` in the root **package.json**.
I did a test run locally by running `npm run release` and then killing my internet connection just before publishing. The `postversion` lifecycle method was invoked correctly.
> Adds name to root package.json so Lerna lifecycle hooks are used

- packages/core/src/textures/resources/ImageResource.js
- packages/core/src/textures/resources/autoDetectResource.js
- packages/core/test/ImageResource.js
- packages/settings/src/settings.js
Partially fixes #5626 
There are some issues with using `createImageBitmap` for now, we'll disable and use v4 functionality.
> Temporary disable createImageBitmap in resources

- packages/loaders/src/Loader.js
- packages/sprite/src/Sprite.js
- packages/text/src/TextMetrics.js
Just a few minor fixes for TS definitions I've spotted while upgrading from v4 and @types/pixi.js to v5.
- Added object type for on(Start/Progress/Error/Load/Complete) signals on Loader.
- If there's a better type/method for this let me know, couldn't find a type name that'd actually use the doc from MiniSignal.
- Sprite.getLocalBounds - Rect argument isn't required.
- TextMetrics - Constructor's jsdoc comment doesn't add member properties to the type, so added those to the assignments within the constructor.
> Minor doc fixes for TypeScript definitions

- packages/core/src/textures/resources/BaseImageResource.js
Fixes https://github.com/pixijs/pixi.js/issues/5659
After the PR @ https://github.com/pixijs/pixi.js/pull/5643,
`this.resize(this.source.width, this.source.height);` 
in BaseImageResource is sending source.width and source.height, both of which are 0 in a video. We should be using videoWidth and videoHeight instead. I've copied over what was done in v4 to ensure the right properties are picked up (https://github.com/pixijs/pixi.js/blob/v4.8.7/src/core/textures/BaseTexture.js#L266)
Previously in 5.0.0, it got away with it as `onBaseTextureUpdated` function would get the correct dimensions as set by the video resource, but the base texture was never flagged as 'updated' after that.
> Fixes video not working in 5.0.1

- packages/core/src/renderTexture/RenderTextureSystem.js
@fanjules strikes again.
Fixes #5674
res=0.5: https://www.pixiplayground.com/#/edit/WG2cvHNUbaPQQ_dt041Xp
res=5, bunny scale=50, bunny exceeds 4096 while the canvas is not: https://www.pixiplayground.com/#/edit/EMIDJrfi6kHQykA7LlksD
Both are fixed:
res=0.5, https://www.pixiplayground.com/#/edit/6Z9XI6VBtIzkmr_CfEDXD
res=5. https://www.pixiplayground.com/#/edit/Vplnql8HgViuQR~42iSPm
@GoodBoyDigital we certainly need more tests for ProjectionSystem. I dont understand the logic you made there for resolutions but at least i can fix it temporarily.
> copy sourceFrame only after resolution was adjusted

- packages/particles/src/ParticleContainer.js
- packages/particles/src/ParticleRenderer.js
This change fixes the behaviour of `autoResize` (fixes #4649)
> fixes ParticleRenderer autoResize behaviour (fixes #4649)

- packages/core/src/state/StateSystem.js
Polygon offset never actually got set, just was activated.
This PR means that the following now works:
```
const state = new PIXI.State();
state.polygonOffset = 10
```
this basically adds an offset to the pixel as it depth is calculated.
> finally actually added the polygon offset check :)

- packages/canvas/canvas-graphics/src/CanvasGraphicsRenderer.js
Fix #5727
Its partial fix that works only for polygon that has polygon holes. `drawRect` and other things wont work with it.
Bug: https://www.pixiplayground.com/#/edit/4GVTR9VA2uBmxe74PB2~z
Fixed: https://www.pixiplayground.com/#/edit/VJga6DVoy9jekGt1e~NzF
> Fixes Graphics holes with CanvasRenderer

- src/core/graphics/canvas/CanvasGraphicsRenderer.js
Backport of #5734
Broken: https://www.pixiplayground.com/#/edit/p3zicIS9ncEwipfIYIHAk
Works, but holes are closed: https://www.pixiplayground.com/#/edit/_QS6xG1mRJ23rKZDRpvds
However, v5 result is correct:
v4 has some problems with closing shapes that weren't actually closed. I dont want to backport huge PR's that I made in v5 graphics, so we'll leave that bug for now.
> [v4.x] Fix canvas polygon holes

- packages/canvas/canvas-sprite-tiling/src/TilingSprite.js
- packages/canvas/canvas-sprite/src/CanvasSpriteRenderer.js
- packages/canvas/canvas-sprite/src/Sprite.js
- packages/sprite-animated/src/AnimatedSprite.js
- packages/sprite-tiling/src/TilingSprite.js
- packages/sprite/src/Sprite.js
Fix #5731 
Broken: https://www.pixiplayground.com/#/edit/Cb6stLyzhuLCOEiaYcsZa
Fixed: https://www.pixiplayground.com/#/edit/K19jO7gbgvvsPrdvQiPJu
Broken: https://www.pixiplayground.com/#/edit/07nXx54J53DrMMKg6PO5Q
Fixed: https://www.pixiplayground.com/#/edit/mOaEKjbqZ3kgY09fpbSDz
+1 example, checks TilingSprite:
https://www.pixiplayground.com/#/edit/Tn4p3ZaUggOs0hsO7P4kV
> Fixes regression on CanvasRenderer using tint with Sprite, AnimatedSprite and TilingSprite, BitmapText

- packages/core/src/state/utils/mapWebGLBlendModesToPixi.js
Broken: https://www.pixiplayground.com/#/edit/wh4NJRXJqWCcI87N8lB03
Fixed: https://www.pixiplayground.com/#/edit/2LB0thwrX8EQM5iE7SXN~
Output in Flash runtime: 
This is not the breaking change: in most of cases ADD was applied on opaque backdrop, and when people use it on transparent background they see the difference:
#5677 
#5673 
#5446
This is the final answer on BlendMode ADD problem.
Sometimes when I look many hours on the same line, when I know there's a bug but I dont see it. I knew about that effect and thanks to several people I deduced that something is wrong with my memory and sight.
Call it brain blind zone. Call it memory hash collision. Such things happen.
After blackboxing and making more tests with Adobe Flash, I finally found that brain glitch.
I do not know how the heck …
> BlendMode alpha fix.

- packages/core/src/state/State.js
Fix `State.blendMode` type definition
> change blend mode type from `boolean` to `number`

- packages/sprite/src/Sprite.js
Currently the documentation for Sprite.pluginName does not match the code. This is a small update that sorts out the issue. Related to #5761
> Update Sprite.pluginName documentation

- packages/core/src/batch/BatchPluginFactory.js
- packages/core/src/index.js
Resolves docs/types issue with new BatchPluginFactory. Somehow this was missed.
Also, adds `@hideconstructor` on BatchPluginFactory for future use once the `@pixi/jsdoc-template` supports this.
**Broken:** http://pixijs.download/dev/docs/PIXI.exports.BatchPluginFactory.html
**Fixed:** http://pixijs.download/fix-batch-factory-docs/docs/PIXI.BatchPluginFactory.html
**Future Work:**
Documentation doesn't work for non-default exports unless you explicitly name the class, or else the class shows up as `exports.MyClass`. JSDoc needs an upgrade and we need a better workaround for ES6 non-default exports. JSDoc is not getting updated much these days, so not sure our best solution here.
> Fixes issue with docs/types with BatchPluginFactory

- packages/core/src/textures/resources/CanvasResource.js
Fixes #5780
This should run in Firefox:
https://pixiplayground.com/#/edit/h6zPHuEC1phTPXqEzVLBy
Old example still works:
https://www.pixiplayground.com/#/edit/KgxLhkmOBUL~i8yjgAYid
> Hotfix for OffscreenCanvas + Firefox

- packages/graphics/src/Graphics.js
Subj.
```js
/**
* Clears the graphics that were drawn to this Graphics object, and resets fill and line style settings.
*
* @return {PIXI.Graphics} This Graphics object. Good for chaining method calls
*/
clear()
```
> and resets fill and line style settings
ok.
Here's what is wrong: https://www.pixiplayground.com/#/edit/mFP~j1ZtEiVQXu95WT4Hb
> Graphics clear fill and line style settings

- packages/core/src/textures/resources/CanvasResource.js
Older typescript version doesn't have offscreenCanvas in it. Lets do the same as in `BufferResource` and `SharedArrayBuffer`, declare an empty interface!
I've tested it on old and new ts.
> OffscreenCanvas types fix

- packages/utils/src/browser/isWebGLSupported.js
- packages/utils/src/settings.js
https://github.com/pixijs/pixi.js/issues/5774
https://github.com/pixijs/pixi.js/issues/5778
> Adds a setting that allows disabling the 'failIfMajorPerformanceCaveat' flag used in the 'isWebGLSupported' function

- packages/graphics/src/GraphicsGeometry.js
- packages/graphics/test/index.js
This PR is for fixing the #5817.  If a `PIXI.Graphics` instance has no graphics data (i.e., `graphics.geometry.graphicsData.length` is zero), `BatchRenderer` may treat it as if it is not batchable. This is because `PIXI.GraphicsGeometry#updateBatches()` leaves the property `#batchable` as it is when `#graphicsData.length` is zero. This PR fixes the method `#updateBatches()` to update the property `#batchable` when `#graphicsData.length` is zero.
> Fix for the empty graphics batchability issue (#5817)

- packages/display/src/DisplayObject.js
In Pixi.js v5.0.4, the `DisplayObject#mask` is declared as `PIXI.Graphics | PIXI.Sprite`. However, to remove a mask from a display object, need to set a mask to null (as far as I know). This PR makes the `DisplayObject#mask` nullable.
https://github.com/pixijs/pixi.js/blob/c4968736f2c6e928097ef7e903e14e86e6f1de01/packages/display/src/DisplayObject.js#L682-L688
I tried the following variations of the type declaration. 
None of them works for me. The `tsd-jsdoc` may not support the question mark?
- ?(PIXI.Graphics | PIXI.Sprite),
- ?PIXI.Graphics | ?PIXI.Sprite, and
- (?PIXI.Graphics) | (?PIXI.Sprite).
> Make DisplayObject#mask nullable

- packages/core/src/textures/TextureUvs.js
The `PIXI.TextureUvs` properties such as `x0` are missing in the type declaration file. I thought this might be intentional. If so, I'm sorry for bothering you :(. However, they were in the PixiJS v4 type declaration file. So I thought this might be not. This PR adds JSDoc comments on the `TextureUvs` properties.
I omit the property `TextureUvs#uvsFloat32` on purpose. 
It looks too internal to me.
> Add JSDoc comments on the TextureUvs properties

- bundles/pixi.js/src/useDeprecated.js
- packages/core/src/textures/BaseTexture.js
- packages/core/src/textures/TextureGCSystem.js
- packages/core/src/textures/TextureSystem.js
- packages/prepare/src/Prepare.js
There were 2 errors here; the first is in Prepare.js, the property on the renderer was renamed in v5 from textureManager to texture. (added a deprecation for this)
Second, the TextureSystem had an assumption in updateTexture that there would be a glTexture, which could end up throwing an error
> Fixes the prepare system in v5

- packages/mixin-cache-as-bitmap/src/index.js
This PR is to fix #5784. There are two problems in `DisplayObject#_initCachedDisplayObject`.
1) The first one is `renderer._activeRenderTarget` does not hold a current rendering target.
https://github.com/pixijs/pixi.js/blob/4d71fa06ea787d81651fc3e624610ccfc3c3f457/packages/mixin-cache-as-bitmap/src/index.js#L185-L189
I replaced it with `const cachedRenderTarget = renderer.renderTexture.current;`.
2) The second one is `renderer.projection.transform` is not restored after the line 213.
I changed the method so that the projection transform is restored.
https://github.com/pixijs/pixi.js/blob/4d71fa06ea787d81651fc3e624610ccfc3c3f457/packages/mixin-cache-as-bitmap/src/index.js#L210-L216
Working example is [https://www.pixiplayground.com/#/edit/hk1gjmUM84Nl72GncOii~](https://www.pixiplayground.c …
> Fix the DisplayObject#cacheAsBitmap issue #5784

- packages/core/src/textures/resources/SVGResource.js
- packages/core/test/SVGResource.js
This PR is for fixing the issue #5816. As described at the issue, a canvas created by `document.createElement('canvas')` may have non-zero width and height. Thus, the method `SVGResource#valid` may return true even when loading is in process. This PR changes the `SVGResource` to set the width / height of a created canvas to zero.
> Fix for the SVGResource#valid issue (#5816)

- packages/mixin-cache-as-bitmap/src/index.js
Follow-up for #5841
I figured out what's wrong with filters inside CacheAsBitmap.
Here's the demo: https://www.pixiplayground.com/#/edit/62HZx5glfSl7R1TJe_5aH
Look in the end, and comment the line, you'll see that first frame with filters is wrong.
*** Theory
To change renderTexture temporarily we need to save current renderTexture, its sourceFrame and projection transform. 
We dont usually need to save transform, only when we already are in cacheAsBitmap or generateTexture.
sourceFrame is needed for filters.
That means that most of my plugins that manipulate will fail because they dont save projection transform. Maybe we need special API for saving/restoring current renderTexture context.
> fix cacheAsBitmap filter

- packages/core/src/Renderer.js
- packages/core/src/System.js
- packages/core/src/batch/BatchPluginFactory.js
I've fixed #5825 and a the side effect on `BatchPlugin`. This was discussed in a failed PR https://github.com/pixijs/pixi.js/pull/5826, which was corrupted due to another change being recorded in the same branch.
> Prevented System from attaching itself to the Renderer's contextChange signal

- packages/text/src/TextMetrics.js
OffscreenCanvas setFont + measureText is 15-40% faster than the Canvas element version, when available. This detects if OffscreenCanvas 2D exists, and if so, uses it instead of canvas. There should be no visible behavior change.
> Use OffscreenCanvas for measureText if available

- packages/core/src/batch/BatchPluginFactory.js
- packages/core/src/batch/BatchRenderer.js
- packages/graphics/src/Graphics.js
(PLEASE JUST READ THE NEW `BatchRenderer` CLASS, since the changes reordered a lot
of things and you might not be able to locate the additions/deletions pairs.
I have edited the BatchRenderer class. The following major changes were
made:
1. Changed old `vertexCount` to `_flushId`. This is because the name
itself was misleading. It signified the number of flushes in the
current frame.
2. Renamed `vaos` and `vaosMax` to `_packedGeometries` and
`_packedGeometryPoolSize`. They _were not_ VAOs in the sense
that they binded all the buffers automatically to the WebGL
context. Instead, they were just reusable `BatchGeometry` objects.
3. Renamed `groups` to `_drawCalls`. That is what they are, and it
makes more sense, especially after documenting it.
4. Renamed all private variables by adding a _ …
> Polished BatchRenderer

- packages/core/src/AbstractRenderer.js
The generateTexture method should return `RenderTexture `, but it is actually return `Texture`.
> Fix RenderTexture type

- packages/core/src/batch/BatchRenderer.js
- packages/math/src/GroupD8.js
Fixed typo in BatchRenderer JSDoc which breaks the TypeScript definitions (capital L in FLoat).
> Fix BatchRenderer and GroupD8 types

- packages/ticker/src/Ticker.js
This lets the game run as fast as it can.
Also tweaked maxFPS, so that when it is set, there is a padding to it that is relative to the target fps set. So a target of 20fps allows for more padding than a target of 60fps. Added for accuracy reasons on higher refresh rate monitors.
Should fix https://github.com/pixijs/pixi.js/issues/5741
> Max FPS can be disabled by setting to 0.

- packages/core/src/textures/resources/CanvasResource.js
- packages/core/src/textures/resources/ImageBitmapResource.js
- packages/core/src/textures/resources/index.js
- packages/core/test/ImageBitmapResource.js
- packages/core/test/autoDetectResource.js
- packages/core/test/index.js
This is a follow-up to #5783 
Basically adds a new resource type for ImageBitmap. Instead of overcomplicating ImageResource, a simple new resource types adds the ability for developers to create their own ImageBitmaps.
> Adds new ImageBitmapResource

- packages/core/src/batch/BatchPluginFactory.js
- packages/core/src/batch/BatchRenderer.js
Can't build [pixi-projection](https://github.com/pixijs/pixi-projection/) without it.
Those fields have to be overriden in constructor, cant do that in case of read-only. 
Protected `_shader` is needed for extra renderer hacks.
Factory doesn't return BatchRenderer, it returns class of BatchRenderer.
> Batch renderer types

- packages/prepare/src/Prepare.js
`updateTexture` was changed in v5 which caused the prepare to do nothing. Callng `bind` here will actually create the texture.
> Fixes base texture prepare (#5856)

- packages/core/src/batch/BatchRenderer.js
> BatchBuffer.vertices => ViewableBuffer.rawBinaryData

- bundles/pixi.js-legacy/package.json
- bundles/pixi.js-legacy/src/index.js
- packages/canvas/canvas-text/LICENSE
- packages/canvas/canvas-text/README.md
- packages/canvas/canvas-text/package.json
- packages/canvas/canvas-text/src/Text.js
- packages/canvas/canvas-text/src/index.js
- packages/text/src/Text.js
- packages/text/test/Text.js
- tools/integration-tests/package.json
- tools/integration-tests/test/display/getLocalBounds.js
It's only required for legacy builds, not normal WebGL only builds
Also renamed render to _render, as internally in other areas of the code, when overriding a render method it is always the underscored version
> Moved _renderCanvas call from text package into new canvas-text package

- packages/core/src/geometry/ViewableBuffer.js
Subj. I just dont know cases that dont use one or both of them.
Pushing colors or something else in uint8 or int8 can happen but its rare.
Also Uint32 had wrong jsdoc type.
> ViewableBuffer: Uint32View and Float32View dont need getters

- packages/core/src/framebuffer/FramebufferSystem.js
- packages/core/src/renderTexture/BaseRenderTexture.js
`count` didnt actually affect much , we just had some old links inside Framebuffer in case of context loss. 
`renderer` is not field of RenderTexture for a long time.
> minor mistakes related to framebuffer

- packages/core/src/Renderer.js
Fixes #5892
Still works as expected:
https://pixiplayground.com/#/edit/_mWHW7~9s4k6QZDuOOlQ5
> Uses super instead of prototype.call

- bundles/pixi.js/scripts/support-pixi.js
We have decided to move to the [OpenCollective](https://opencollective.com/pixijs) platform for sponsorship. We have already added the **Sponsor** button to the project.
Primarily, @GoodBoyDigital and I feel like this is a better vehicle for driving community engagement. This change will also make it easier for us to compensate the community for things such as bug/feature bounties, allows for more transparency with regard to expenses, and we hope push PixiJS toward our long-term goal of financial independence.
In addition, OpenCollective is home to tools like Babel and Webpack which are heavily used by the PixiJS developer community. We feel like we'd be in good company with this move.
This PR simply replaces the **pixi.js** postinstall message with an OpenCollective link.
> Moving to OpenCollective

- packages/core/src/batch/AbstractBatchRenderer.js
- packages/core/src/renderTexture/RenderTexturePool.js
subj.
Also, `vertexSize` should be protected like `geometryClass`, need that for the only ts plugin that uses new API.
> Pre-5.1.0 types fixes

- packages/text/src/TextMetrics.js
Re submission of fix to bug where an iOS webview OffscreenCanvas would return a context of null.
> fix bug where OffscreenCanvas.getContext is null

- packages/display/src/Container.js
Empty filter array in Container breaks batched render.
Bug replay:
https://www.pixiplayground.com/#/edit/pRUcpdTxAEml0qiV83HUI
Remove line 37 and bunny will nbe rendered.
- [ x] Tests and/or benchmarks are included
> Fixing batch breaking by empty filter array.

- types/events.d.ts
The `DisplayObject` is declared as follows:
https://github.com/pixijs/pixi.js/blob/fc70bdd66c19b2d52e42f3653fe43e313cb19566/types/events.d.ts#L102-L109
This declaration overrides the methods inherited from the `EventEmitter`. Because overridden methods do not accept the `string | symbol` as a `event`, `displayObject.on( "foo", ... )` leads to a compilation error as shown in the following typescript playground. This PR is to fix this.
https://www.typescriptlang.org/play/index.html#code/MYGwhgzhAECiBuBTAdgF1gWwJatYgTtAN4BQ050A9sgBTSJJoBc0Eq+WyA5tAD6sBPDACNKIaAEoW8SlgAmxAL4llJUJBgARLBAAO4AQHlhAK0TBU9AB55kcmAhTpsuAkpIlOefADMwwRGhtPQNjMwtiMgoAemjoADlYWE1oABUACVgE2AANVOgAGQBJRLTDaAAlWABlQwKANSyMrIBhQwBZAAUigoBBVKLDeLgKisMKqPJYqlp6RlQWNg5uPkERMUlpWTkAbmhJmboGJxYAIl1ZNAI5SgB3ZFPN6Bl5HZUPYGo2aDkdfT …
> Fix the DisplayObject type declaration

- packages/core/src/shader/utils/getTestContext.js
Fixes #5664
The private function `getTestContext` is only called from these files. And in both cases, they handle if `gl` is `null`. It's not necessary to throw an exception.
* packages/core/src/shader/Program.js
* packages/core/src/shader/utils/getMaxFragmentPrecision.js
> Better handling of webgl-less environments

- types/events.d.ts
Two `"mouseover"` were declared in the `InteractionMouseEvents` type, so I removed one.
> Removed duplicate type declaration

- packages/text/src/Text.js
Alternative to https://github.com/pixijs/pixi.js/pull/5943
Goes back to v4 style of separate draw calls to make sure all of the drop shadow is underneath all of the text; but this time rather than using the first drawn text as the actual drop shadows, it draws this text off screen, whilst positioning the drop shadow to appear on screen. So we get the drawing order that v4 has with the good native canvas drop shadow looks of v5.
It doesn't solve 'double drop shadow with low alpha overlapping', but I think that'd require using a second canvas, which is out of scope for this PR
> Fixes text shadows for v5, take 2

- types/assemble.js
Adds generic types to Container.addChild, Container.removeChild and Container.addChildAt, allowing for the proper subclass of PIXI.DisplayObject to be returned.
fixes #5927.
> Adds generic types to container child methods

- packages/core/src/filters/FilterSystem.js
- packages/core/src/renderTexture/RenderTexturePool.js
Since internally it has already scaled the requested render texture size within getOptimalTexture
https://github.com/pixijs/pixi.js/issues/5954
> The RenderTexturePool should create renderTextures at resolution of 1

- packages/runner/src/Runner.js
- packages/runner/test/index.js
Same as #5972 , but it handles many other cases, I'll prepare more tests.
This is not "I can code better" statement.
The approach was taken from mozilla shumway https://github.com/mozilla/shumway/blob/master/src/flash/events/EventDispatcher.ts#L66
I modified it a bit, we don't even spawn new array in case we had only one listener.
> Support mid-emit removal of Runner items

- packages/core/src/mask/StencilSystem.js
- types/assemble.js
Fixes #5974
Broken: https://www.pixiplayground.com/#/edit/PmNR2aqebJB2i56E5IiBz
Fixed: https://www.pixiplayground.com/#/edit/t09LhS3_ttR6R7przuBOi
> Restore stencil params after mask stack swap

- packages/core/src/textures/BaseTexture.js
As otherwise you lose precision going from one to the other.
Just trying to create some demo's that show up the issue in pixi playground
> Removed the ceil'ing of width and height in base texture

- packages/graphics/src/Graphics.js
- packages/graphics/src/GraphicsGeometry.js
- packages/graphics/src/utils/buildLine.js
Thanks to @eXponenta , one more obvious fix in Graphics.
Unfortunately, we are introducing new constant in GraphicsGeometry API , and without default settings (we can do it in next version).
Source: https://commons.m.wikimedia.org/wiki/File:Ghostscript_Tiger.svg
Broken: https://www.pixiplayground.com/#/edit/hA0cEqMaLra2qlieotC0F , look at the right - curve is not actually closed, and its real case from some SVG.
Fixed: https://www.pixiplayground.com/#/edit/GTnupAh_2mr6pMhvIUUfn
Why are those points different? Because `arc` in SVG cant be converted to our arc clearly, and while calculating coefficients for our arc rounding error can happen.
Alternative solution: provide a round resolution to graphicsGeometry tesselator. Make everything close to 0.001 or so.
@GoodBoyDigital are we ready to …
> Graphics close points epsilon

- packages/graphics/src/GraphicsGeometry.js
- packages/graphics/test/index.js
Fixed failed result of containsPoint when GraphicsData#matrix is setted.
GraphicsData support setting specific matrix for points transformation, but containsPoint wasn't consider it.
Before:
https://www.pixiplayground.com/#/edit/iMS~MESj6tf1KHMhiRO~Q
After:
https://www.pixiplayground.com/#/edit/DGKjCWH7ayLAU7FW6NnJl
> fixed `containsPoint` failing

- packages/app/src/Application.js
- packages/app/test/index.js
Fixed `stageOptions` not being propagated to `stage.destroy()`
> Fixed issue where Application.destroy ignored stageOptions

- packages/core/src/textures/resources/ImageResource.js
This is to fix #5968. 
FireFox 68, and possibly other versions, seems like setting the `HTMLImageElement#width` and `#height`  to non-zero values before its loading completes (namely, `HTMLImageElement#complete === false`) if images are in a cache. Because of this, need to set the `_width` and the `_height` to zero to avoid uploading incomplete images.
Please refer to the following working example:
[https://www.pixiplayground.com/#/edit/XX8a7e2XBMBpDMc0gLzz_](https://www.pixiplayground.com/#/edit/XX8a7e2XBMBpDMc0gLzz_)
> Fix the FireFox cached image issue (#5968)

- packages/core/src/textures/resources/VideoResource.js
Ref: #5996
just set `preload` with some value (`'auto'`) when it be created.
I don't know the reason, but it just works.
And those also work::
```
preload='' // equal to `preload='auto'`
// or
preload='none'
```
> workaround for the issue that videos not working issue on Chrome v76

- packages/core/src/textures/BaseTexture.js
- packages/core/src/textures/resources/ImageResource.js
- packages/core/src/textures/resources/Resource.js
- packages/core/src/textures/resources/SVGResource.js
- packages/core/src/textures/resources/VideoResource.js
- packages/core/test/BaseTexture.js
Fixes #5900
This change handle error events for Video, SVG and Image resources that can load their own contents via HTML element tags.
> Fixes the error event for BaseTexture resources

- packages/sprite-animated/src/AnimatedSprite.js
copy is deprecated, but was still used in AnimatedSprite
> Use copyFrom instead of deprecated copy

- packages/interaction/src/InteractionEvent.js
- packages/interaction/src/InteractionManager.js
- packages/interaction/test/InteractionManager.js
This fixes ``event.stopPropagation()`` - which didn't ever really just stop propagation, but rather
stopped events dead in their tracks.
Basically when you called ``stopPropagation`` there would be no further events emitted for the same action. So if you did it in, say, a ``mouseup`` event, you wouldn't even get a ``click`` event. Bummer.
This becomes really apparent with the recent [mouseover/pointerover](https://github.com/pixijs/pixi.js/pull/5989) changes, because if you now call ``stopPropagation`` in a ``mousemove`` event, you wouldn't ever see any ``mouseover`` event (which *would* be dispatched after).
Previously there were no tests for event propagation, so I added three of those.
> InteractionManager: fix event.stopPropagation()

- packages/display/src/Container.js
This is a small change recommended by @finscn. Probably a good idea because `render` will use the property directly instead of hitting the getter function.
> Replace filters getter with filters member

- packages/sprite/src/Sprite.js
Bug:
https://www.pixiplayground.com/#/edit/nygKQ4JiT675hWX35JN8k
Resume:
When `baseTexure` or `frame` was be reassigned, uvs not changes on sprites with this base texture.
Case 1:
It corrupts sprite when basetextures is valid  but dimensions isn't equals.
Case 2:
Renderer throws 'undefined' exception about uvs when you chage from Texture.EMPTY (`valid = false`) to `valid = true` texture;
Fixed:
https://www.pixiplayground.com/#/edit/gcxJ1nKj2GUp5H~AptY37
> Fix sprite's uvs updating

- packages/display/src/Container.js
This reverts commit 646990a3846a581f9d8eeeba17df807c72638562.
This change was wrong, (my bad) we no longer use getter/setters for filters.
See https://github.com/pixijs/pixi-filters/issues/220
> Revert "Replace filters getter with filters member (#6058)"

- packages/core/src/textures/resources/BaseImageResource.js
- packages/core/src/textures/resources/VideoResource.js
Addresses #4089 
This defaults `texImage2D` uploading instead of `texSubImage2D` for VideoResource objects.
See for more information and performance measurements: http://codeflow.org/issues/slow_video_to_texture/
**Build:**
http://pixijs.download/fix-video-performance/pixi.min.js
**Example:**
https://pixiplayground.com/#/edit/jpeAPzXpQFY336WzsTKqn (PR)
https://pixiplayground.com/#/edit/9vDVREwmsMLTMNoCgW2VI (5.1.3)
**Measurements (Chrome 76)**
I did a small benchmark in Chrome to see the performance. At least in Chrome, `texImage2D` is  faster (although on my laptop I didn't _perceive_ much of a different, would probably show up more on mobile/slower devices).
| Branch | Duration | Render Time (lower is better) |
|---|---|---|
| 5.1.3 | 5000ms | 387ms `texSubImage2D` |
| …
> Force texImage2D upload for videos

- src/core/text/Text.js
Addresses issue of incorrect kerning for PIXI.Text when `letterSpacing` is a value other than `0`, as described in issue [#4635](https://github.com/pixijs/pixi.js/issues/4635).
```new PIXI.Text('YouTube', {align: 'center', fontSize: 72, fontFamily: 'Times', letterSpacing:1});```
> Fix kerning rendering with letterSpacing (v4.x)

- packages/text/src/Text.js
Same as https://github.com/pixijs/pixi.js/pull/6090 but targeted at v5.x - I have not separately tested the v5 change, so it would be good to confirm correct visual behavior in renderer.
Addresses issue of incorrect kerning for PIXI.Text when `letterSpacing` is a value other than `0`, as described in issue [#4635](https://github.com/pixijs/pixi.js/issues/4635).
```new PIXI.Text('YouTube', {align: 'center', fontSize: 72, fontFamily: 'Times', letterSpacing:1});```
> Fix kerning rendering with letterSpacing (v5.x)

- packages/core/src/framebuffer/FramebufferSystem.js
- packages/core/src/mask/StencilSystem.js
- packages/core/src/renderTexture/BaseRenderTexture.js
That's for 5.1.4
First part of renderTexture stencil optimization: reduce the memory of renderTexture in case there are no masks. Comparing to v4 that was a downgrade.
Next PR's will add temporary pow2 renderbuffers for filters, and add a setting to allow run pixi in stencil-less webgl.
Open chrome or canary, single page, press SHIFT+ESC, look in GPU process memory
1000 renderTextures of size 256x256. 
In windows stencil+depth is 32bit, and STENCIL8 cant help, it always creates both. +33% tax on potential mipmaps for colorbuffer.
That's 350kb colorbuffer per one renderTexture +256kb stencil/depth. 
That means 350MB vs 600MB if we use stencil for every texture.
My measurements:
Empty playground, 140M total.
Stencil, 800M GPU total in chrome canary: …
> Optional renderTexture stencil

- packages/interaction/src/InteractionManager.js
- packages/interaction/src/TreeSearch.js
I've got many ideas how to make our interaction code more clear and moddable.
This is first PR in a sequence: I removed 180 lines of code from huge 1900 lines file and got rid of 2 params in a function call.
Here's the biggest case when we need to inject different search behaviour:  https://github.com/pixijs/pixi-layers/blob/master/src/InteractionManagerMixin.ts
Several changes in interaction were the reason why users stuck with particular versions of pixijs.
I need help with testing that thing, but it should be easy - I didnt add any new features, just copied the code&docs and passed params.
Why is it separate class, and not a mixin? I think that after several PR's we'll be able to give ability to use treeSearch for hittesting independently of interaction, and with many optional params, …
> InteractionManager refactoring: extract TreeSearch

- packages/core/src/framebuffer/FramebufferSystem.js
As in last critical, THANK YOU @Metatron92
#6099 , my bad
Problem appears only in webgl1.
DEPTH_STENCIL/STENCIL_ATTACHMENT, Bad: https://www.pixiplayground.com/#/edit/smrqNrd3Vgv7v5GeRdf12
DEPTH_STENCIL/DEPTH_STENCIL_ATTACHMENT , Good: https://www.pixiplayground.com/#/edit/RQ6S5kkMpjtUzPzoZ7rXK
STENCIL_INDEX8/STENCIL_ATTACHMENT, Also good, but eats the same memory in windows anyway: https://www.pixiplayground.com/#/edit/RQ6S5kkMpjtUzPzoZ7rXK
Also that rebind is useless.
How to check that branch works: comment this line in a good example, its bound to our branch so it'll work.
```js
PIXI.systems.FramebufferSystem.prototype.forceStencil = forceStencil;
```
> Critical fix stencil webgl1

- packages/core/src/shader/utils/getTestContext.js
I found a problem with #6116  , however I have no test for it. One of our possible returns is `null`, means there's no webgl on computer. In that case, asking second time for a test context will lead to nullpointer.
> Fix test context

- packages/sprite/src/Sprite.js
- packages/sprite/test/Sprite.js
Unsubscribe from old texture in Sprite once the new one set.
> Fix: unsubscribe from old Sprite texture

- packages/graphics/src/GraphicsGeometry.js
- packages/math/src/groupD8.ts
With the #6141 pr the jsdoc type for `GD8Symmetry` was being removed. Placing the doc comment below the initialisation fixes this issue.
Also found that `GraphicsGeometry` had a typo in one of its types.
> Fixes types for groupD8 and GraphicsGeometry

- .eslintrc.json
- packages/math/src/IPoint.ts
- packages/math/src/Matrix.ts
- packages/math/src/ObservablePoint.ts
- packages/math/src/Point.ts
- packages/math/src/groupD8.ts
- packages/math/src/index.ts
Follow-up for #6141 
After mentioned PR, `IPoint` disappeared from `pixi.js.d.ts` , completely. Type `npm run types` and see the result in `bundles/pixi.js/pixi.js.d.ts`.
I don't understand what is going on, but at least I can start moving this thing from union to normal interface, in case some classes in `pixi-projection` (Point3d) will to implement it.
`IPoint` is still missing in output, but now we have one more problem!
```js
interface ObservablePoint extends IPoint {
}
class ObservablePoint implements IPoint {
}
```
I know that it should work, but how exactly this thing is generating?
Our current typings are filled with copies of methods and classes that we dont need, we didnt have all those problems in manual v4. Please help me fix at least that one.
I also specified …
> make IPoint an interface and not union

- packages/interaction/src/TreeSearch.js
- types/jsdoc-legacy.conf.json
- types/jsdoc.conf.json
Fixes #6161
The intention always was explicitly to ignore the typings for deprecated APIs. But our pattern was old.
* **Broken:** http://pixijs.download/dev/types/pixi.js.d.ts
* **Fixed:** http://pixijs.download/fix-deprecated-typings/types/pixi.js.d.ts
> Ignore useDeprecated file from typings

- packages/core/src/context/ContextSystem.js
- packages/core/src/textures/TextureGCSystem.js
I think we have to call `gl.flush()` for certain mobile devices after our frame, but we dont have to do it for each renderTexture call.
Also GC ticker rate was increased if user draws renderTextures.
> Remove extra gl-flush and GC checks

- packages/core/src/textures/TextureSystem.js
- packages/core/test/TextureSystem.js
- packages/core/test/index.js
subj.
We have special logic for mipmaps, so they work the same in webgl1 and webgl2 by default, but if user wants he can enable mips for non-pow texture in webgl.
For REPEAT wrapMode its different : we have workarounds in tilingSprite and i'll add one for Graphics,
> Allow wrap for webgl2 without mipmap

- packages/canvas/canvas-mesh/src/NineSlicePlane.js
Fixes #6204 
**Broken (v5.1.5):** https://jsfiddle.net/bigtimebuddy/2zbtowq7/1/
**Fixed (this branch):** https://jsfiddle.net/bigtimebuddy/bg85rLs3/1/
(open console to see the deprecation warning on v5.1.5)
> Fix deprecation on BaseTexture in NineSlicePlane

- packages/canvas/canvas-mesh/package.json
- packages/canvas/canvas-mesh/src/NineSlicePlane.js
- packages/canvas/canvas-mesh/test/.eslintrc.json
- packages/canvas/canvas-mesh/test/NineSlicePlane.js
- packages/canvas/canvas-mesh/test/index.js
Follow-up for #6205 
This is not a bugfix, this is just extra test for last PR. 
We have special method `getDrawableSource` in case we want to get canvas drawable from baseTexture, lets use it. It worked in @bigtimebuddy because CanvasRenderer creates actual resource for RenderTexture, and I honestly didnt remember about that.
I think that in future, we'll change `getDrawableSource` code, so its better if we cover it with extra test.
> Add NineSlicePlane canvas test

- packages/math/src/ObservablePoint.ts
- packages/ticker/src/Ticker.ts
- packages/ticker/src/TickerListener.ts
I've updated Ticker, TickerListener and ObservablePoint 's callback properties to have a stricter `this`
parameter. This provides additional IntelliSense and error catching capabilities in some situations such as:
```ts
ticker.add(function(dt) {
//Type of this is {index: number}
this
}, {index: 5});
```
> Add typings to `this` parameter of callback functions

- package.json
Fixes #6208 #5998 
These issues are caused because of the default fuzzy dependency versions used throughout the project. By pinning the dependencies with Lerna whenever we bump, it will reduce our complexity in the wild.
There could be side-effect issues with users having multiple version of the same package, but that's a little more manageable then the current situation which requires users resolve all sub-packages of pixi explicitly.
Context about `--exact` https://github.com/lerna/lerna/tree/master/commands/version#--exact
> Publishes exact versions when version bumping

- packages/display/src/DisplayObject.js
- packages/display/test/DisplayObject.js
> Fix `DisplayObject.destroy` should call listener `removed`

- packages/graphics/src/GraphicsGeometry.js
- packages/graphics/src/utils/BatchPart.js
- packages/graphics/src/utils/index.js
- packages/graphics/test/index.js
Another bug again, found by @eXponenta 
Bugged: https://www.pixiplayground.com/#/edit/QF2RXuO21iDTwvxGntVBr
Fixed: https://www.pixiplayground.com/#/edit/yhKcbj73S9RHy1ajD0tdX
I've added test on it. With our previous tests everything should be fine, but I'll make a pass on pixijs examples anyway.
Also it fixes our typings.
> Fix graphics fillStyle instead of lineStyle

- bundles/pixi.js/src/useDeprecated.js
Added a deprecation to PIXI.SimpleRope (which was PIXI.mesh.Rope) that I came across upgrading games from v4 to v5.
> Added SimpleRope deprecation

- packages/text-bitmap/src/BitmapFontLoader.js
- packages/text-bitmap/test/BitmapFontLoader.js
Fixed the two tests that failed on windows in BitmapFontLoader. I think the code itself is self-explanatory so I don't really have much more to say. I am confident the change in `dirname` method should be safe because backslashes are not allowed in a URL, so shouldn't ever break any existing code, and even though they're allowed in unix's filenames afaik no one ever does it.
Referenced issue: #6247
> Fixed BitmapFontLoader tests failing on Windows

- packages/mesh-extras/src/NineSlicePlane.js
- packages/mesh-extras/test/NineSlicePlane.js
- packages/mesh-extras/test/index.js
If nine slice object on scene is smaller than frame it shouldn't be distorted
https://jsfiddle.net/Heorhiy/ex35ty0m/
> Corners supposed to be proportionally scaled

- packages/core/src/shader/utils/compileProgram.js
- packages/sprite-animated/src/AnimatedSprite.js
- packages/sprite-animated/test/AnimatedSprite.js
if it's stoped naturally, then reset frame to the last frame and don't trigger one more onFrameChange
> Fix double onFrameChange events with AnimatedSprite

- packages/text/test/TextMetrics.js
Refactored some of `TextMetric` tests so that they pass on Windows.
* I've allowed myself to leave a comment at the top of `TextMetric` class about the fact that the text may render (and measure) differently on different platforms.
* One failing test required changing the expected width, because `exercitationem` renders to about 217px making it impossible to fit in the requested 200px. This shouldn't invalidate the test on different platforms, because `breakWords` was set to `false` either way, so on other platforms it just rendered to a smaller dimension already. Also the test's goal is to check if the width is not exceeded by stacking >1 word in the line, not by a word too long.
* Two other tests I refactored to be 2 tests each, one part being stuff that works the same across all …
> Refactored some of TextMetrics tests so that they pass on Windows

- packages/text/src/TextMetrics.js
- packages/text/test/TextMetrics.js
As requested in #6201, made it so that the method used to split a token into characters in `TextMetrics.wordWrap()` can be customized.
> TextMetrics.wordWrap() customization of splitting method

- package-lock.json
- packages/core/src/batch/AbstractBatchRenderer.js
- packages/core/test/BatchRenderer.js
- packages/particles/src/ParticleRenderer.js
- packages/sprite-tiling/src/TilingSpriteRenderer.js
The way we handled blendModes in BatchRenderer is wrong, it doesn't call`gl.disable(gl.BLEND)`
Broken: https://www.pixiplayground.com/#/edit/862Ww3O7ZhoAxzQW15ZjV
Fixed: https://www.pixiplayground.com/#/edit/OSKK2hg7EugpvQ2VTR40h
> BlendMode NONE fixes

- packages/canvas/canvas-renderer/package.json
- packages/canvas/canvas-renderer/src/utils/CanvasMaskManager.js
- packages/canvas/canvas-renderer/test/CanvasMaskManager.js
- packages/canvas/canvas-renderer/test/index.js
- packages/display/src/DisplayObject.js
Currently assigning container as a mask causes an Exception in CanvasRenderer.
Lets fix that, add a feature, and cover with pair of tests.
Demo: https://www.pixiplayground.com/#/edit/IO~sST9K~QxzhBh9b4b3u
Two rects in two graphics instead of one.
To be fixed in next PR: Even-odd fail. https://www.pixiplayground.com/#/edit/DsFS6hI4dG0tFGrdBSbxW
> Canvas mask supports container with graphics

- packages/mesh/src/Mesh.js
- packages/sprite/src/Sprite.js
Fixes issue descripted in https://github.com/pixijs/pixi.js/issues/6232 with roundPixels implementation difference between v4 and v5 for resolutions less than 1.
> Fixes roundPixels calculation differences between v4 and v5

- global.d.ts
- package.json
- tsconfig.docs.json
- tsconfig.json
As discussed here #6261 and in the slack channels there have been issues with getting types and modules being recognised properly.
Before we ran into issues of either a module not being recognised or cannot use namespace as type, depending on the different solutions that have been thrown around.
With this change we no longer need to declare modules inside the `global.d.ts` file (except for settings as this one is weird). We should also get types for packages that are still in javascript.
I've tested this out on my display branch and it fixed all my build issues. 
@EvidentlyCube @ivanpopelyshev  this should help with the core/spritesheet packages as well. 
- [x ] Lint process passed (`npm run lint`)
- [x ] Tests passed (`npm run test`)
> Fixes modules/types not being found by typescript from js packages

- packages/sprite-tiling/src/TilingSprite.js
- packages/sprite/src/Sprite.js
Brings documentation for `Sprite` and `TilingSprite` in line with changes made in #6034 when number was removed as an option in the `.from` function
> Fixes .from docs for sprite and tiling sprite

- packages/utils/src/network/decomposeDataUri.ts
This pr fixes the automatically generated types where `DecomposedDataUri` is not exported. This has been an issue before in #6150 where interfaces are stripped out along with there comments.
To document it in a way that it doesn't get removed means defining it below its declaration
> Fixes docs for DecomposedDataUri

- packages/interaction/src/InteractionManager.js
- packages/interaction/test/InteractionManager.js
- packages/ticker/src/Ticker.ts
- packages/ticker/test/Ticker.js
By default ``InteractionManager`` adds ``InteractionManager.update`` to ``Ticker.system``.
Except for now adding ``tickerUpdater`` *instead* this behavior is unchanged.
``tickerUpdate`` now contains the rate limiting check based on ``deltaTime``, then calls ``update`` if it passed.
A configuration option ``InteractionManager.useSystemTicker`` has been added. If it is
set to ``true``, InteractionManager won't automatically use the system ticker.
This partially fixes the problems outlined in https://github.com/pixijs/pixi.js/issues/6307
Basically you can now use your own updating logic like this:
```js
// ...
const renderer = new pixi.Renderer();
renderer.plugins.interaction.useSystemTicker = false;
function renderOneFrame() {
// update scene
gameLogic();
// update transforms once, needs a …
```
> add option to disable the built-in InteractionManager updater

- packages/display/src/Bounds.js
- packages/display/src/DisplayObject.js
Since ``DisplayObject`` uses ``DisplayObject.calculateBounds``, it should at least provide an empty implementation to be overwritten in child classes like ``Container``.
Also there was two places in which ``bounds.updateID++`` was used, which is a property that doesn't actually exist on bounds (anymore?). This just causes that property to be created and set to ``NaN`` and it thus was a silent error.
> Add empty calculateBounds to DisplayObject, remove Bounds.updateID references

- packages/text/src/TextMetrics.js
@Metatron92 reported strange error in his game's "report error" feature: 
```
TypeError: i.measureText is not a function\\n    at Function.ho.measureFont 
```
Its probably another OffscreenCanvas surprise. OffscreenCanvas is used since #5804.
Unfortunately, we don't know which browsers have this issue, I hope @Metatron92 improves his error reporting method.
We really should move this method to another file and make it accessible for users, also make it lazy so user can disable it with `PIXI.settings`. Currently we have to override `_canvas` and `_context` varibles for fast fix.
> Extra checks for OffscreenCanvas text measure

- packages/text/src/Text.js
For example, see: https://pixijs.io/examples/#/text/text.js
In the example above, when modifying the dropShadowDistance, try 100, one will observe the gradient distorting across the 3 lines of text.
Animating it will result in a clearer demonstration. For example, add the following:
```
app.ticker.add((delta) => {
richText.style.dropShadowDistance += 1;
});
```
This is due to the drop shadow's offset increasing the dimensions of the canvas used to render the text and which the gradient's calculations rely on.
The fix corrects the dimensions by removing this offset thus maintaining the desired gradient.
> A fix to maintain the text gradient when modifying the drop shadow distance.

- packages/display/src/Bounds.js
- packages/display/src/Container.js
- packages/display/src/DisplayObject.js
- packages/mixin-cache-as-bitmap/src/index.js
It is my fault that #6261 had conflicts, because I made a mistake in review. The problem appeared when we tried to merge #6304  and found that field is still used.
So, lets clear how exactly `_boundsID` is handled:
DisplayObject invalidates its `_boundsID`. The dependent inner object, `_bounds`, tracks its version, and it is being updated in `calculateBounds`. The tracker is stored in `_bounds.updateID`.
No more `lastBoundsID`.
In future, I hope to separate global bounds from local ones and content bounds, thus I store updateID in object that contains the result - we will have multiple objects like that.
Alternatives:
0. Merge this, then merge it with TS convertion
1. I integrate that PR in typescript convertion
2. We disbandle this thing and leave _lastBounds
> Clarify boundsID

- packages/display/src/Container.ts
- packages/display/src/DisplayObject.ts
I congratulate @Zyie with merge of his big PR, there are not many people that had modified that many lines in PixiJS in one commit, its certainly an achievement!
Now to fixes:
1. `_lastBoundsID` is not needed anymore.
2. my typescript still complaints about certain expression in `Container` I do not understand why, I've tried several versions of TS. Lets make it simple.
> Typescript display bounds fix

- packages/graphics/src/utils/buildCircle.js
Fix #6327 
Sometimes (with specific radius) `totalSegs` is integer and this case generate extra point same as start point.
Ex:
```
r = 5.3;
Math.floor(30 * Math.sqrt(r)) / 2.3 => 30.00000004
```
Reproduced by:
https://www.pixiplayground.com/#/edit/Iv9DmRYIMeoPAb-TQyBpq
Look in to console. 
Start and 2 end  points are similar.
Line builder fails when more that 2 points one after another is same and generate line segments on [0,0] for them.
Fixed:
https://www.pixiplayground.com/#/edit/OzhTsdVMM0xE-7O1Tcima
> Fix gaps in circle geometry again

- package.json
This is a more permanent fix to #6344 by making sure next time I publish a v4.x version of PixiJS, it'll be under the `legacy` dist-tag on npm instead of `latest`.
> Fix the dist-tag for v4 to be "legacy"

- packages/display/src/Container.ts
Fix for #6348
In #6261, when I asked @Zyie to add type for `containerUpdateTransform` i didnt check the result properly
Fixed: https://pixijs.io/examples/?v=fix-container-update#/text/bitmap-text.js
> Fix display conversion container mistake

- packages/display/src/Container.ts
- packages/display/src/DisplayObject.ts
Continuation of #6348 #6349. This time `pixi-tilemap` dropped into infinite recursion.
> More fixes after @pixi/display conversion

- packages/app/src/ResizePlugin.ts
Because, of course, we made field duplicate in #6376
> Fix app jsdoc types

- bundles/pixi.js/src/useDeprecated.js
- packages/loaders/package.json
- packages/loaders/src/Loader.ts
- types/loader.d.ts
Follow up to #6385
This removes EventEmitter mixins to Loader officially. They have been removed from docs since v5.0.0 and now are removed from typings and runtime as well. Added a deprecation notice to be a little user-friendly for EE methods.
> Remove EventEmitter mixin from Loader, deprecate methods

- packages/core/src/batch/BatchSystem.ts
- packages/core/src/framebuffer/FramebufferSystem.ts
- packages/loaders/src/Loader.ts
- packages/sprite-animated/src/AnimatedSprite.ts
- packages/ticker/src/Ticker.ts
- types/loader.d.ts
I am once again asking to approve a jsdoc fix.
@Zyie , @eXponenta made a few mistakes in conversion PRs.
I, @ivanpopelyshev , made two ANY's caused two messages that were bothering us from december.
> Fix jsdoc typings

- packages/canvas/canvas-mesh/src/NineSlicePlane.js
- packages/canvas/canvas-particles/src/ParticleContainer.js
- packages/canvas/canvas-renderer/src/BaseTexture.js
- packages/canvas/canvas-sprite/src/CanvasSpriteRenderer.js
Fix #6401 .
Proof: https://www.pixiplayground.com/#/edit/bDATVV0BjViqlg1suv75b
> Dont show `baseTexture.source` deprecation if texture is not valid

- packages/canvas/canvas-graphics/src/CanvasGraphicsRenderer.js
Follow-up for #6367 
I made an obvious mistake there.
This is not final refactor. To stop rendering of empty textures we need more changes, for future PR's. Right now not valid textures will be shown as `#808080`.
Test: https://pixijs.io/examples/?v=fix-graphics-linestyle-texture#/graphics/advanced.js
> fix&refactor linestyle texture

- packages/text/src/Text.ts
In Chrome, I'd noticed some of my text in a project didn't always have the same gradient on each line. Turns out the seams between tiled gradients could sometimes have floating point imprecision, effectively swapping the start/end gradient colours around and messing a line or two up. This PR caps the gradient to the last value (as color stops are generated in order anyway) to prevent this happening.
[Playground demo (Open in chrome, change bool at start to toggle fix)](https://pixiplayground.com/#/edit/8I-EO0eRlShU4YHvuD6bc)
Happy to backport this for v4 as well if wanted.
- Demo provided.
- Do we have a way of testing visual stuff?
- Can't verify, tests currently failing already.
> Fix: Floating point imprecision could break vertical text gradient generation

- packages/graphics/src/const.ts
IE doesn't support the Number.NaN location, so reverting to global NaN
https://github.com/pixijs/pixi.js/issues/6421
> Fixes usage of NaN

- packages/text/src/Text.ts
We often give advice to use this to force updating of the texture outside of a render cycle; for example, to generate a texture containing a piece of text which is then shared across multiple sprites.
For example
https://github.com/pixijs/pixi.js/issues/5138#issuecomment-425715507
https://github.com/pixijs/pixi.js/issues/5043#issuecomment-408377422
https://www.html5gamedevs.com/topic/42319-pixitext-caching-with-resolution/?do=findComment&comment=239720
> Making "updateText" to be public

- packages/extract/src/Extract.ts
Related to #6424 
Why? Because extract drawn canvas to itself, it is wrong when there is a alpha.
In fix extract creates new CanvasRenderTarget and draw flipped to it.
Before:
https://www.pixiplayground.com/#/edit/pAo7HerhsY5JZTf16ajNq
After:
https://www.pixiplayground.com/#/edit/0vBcRtK80ctpV8pI2bVVn
> Hot extract fix

- packages/core/src/context/ContextSystem.ts
Follow up #6417 , #6433 
Includes test to exist `WebGL2RenderingContext` in `window`  before calling `instanceof`, suppresses failing (and downgrade to canvas) on iOS and any devices without WebGL2
Oops:)
> Fix failing on iOS when webgl2 does not exist on global scope

- packages/canvas/canvas-graphics/src/CanvasGraphicsRenderer.js
- packages/canvas/canvas-mesh/src/CanvasMeshRenderer.js
- packages/canvas/canvas-mesh/src/NineSlicePlane.js
- packages/canvas/canvas-particles/src/ParticleContainer.js
- packages/canvas/canvas-renderer/src/CanvasRenderer.js
- packages/canvas/canvas-renderer/src/utils/CanvasMaskManager.js
- packages/canvas/canvas-renderer/test/CanvasRenderer.js
- packages/canvas/canvas-sprite-tiling/src/TilingSprite.js
- packages/canvas/canvas-sprite/src/CanvasSpriteRenderer.js
- packages/mixin-cache-as-bitmap/src/index.js
Our Canvas2d and webgl code regarding render transform differs.
It makes difficult to debug some cases, and it prevents us from refactor all that "temporary parent" code to "pixi/@display" package.
This PR does not add new functionality nor does it change behaviour.  No moving `floor`s around, no doing extra multiplications/divisions, it should be the same code.
I'll add some resolution-related examples a bit later.
+81-158 , yeah, that's a good balance!
> Canvas2d transform improvement

- packages/app/src/Application.ts
- packages/app/src/ResizePlugin.ts
- packages/app/test/index.js
- packages/core/src/AbstractRenderer.ts
- packages/core/test/Renderer.js
I've been meaning to tackle this one for awhile, since no one seemed keen on adding the PR for it.
Fixes #6081
* Introduces `resize` event to the Renderer. Called immediate after view is resized can be used for responsive layouts, or other resizing events.
* Adds throttle resizing on the Application when using `resizeTo`, this will prevent unnecessary extra event calls triggered by the window 'resize'.
https://jsfiddle.net/bigtimebuddy/u05c1s28/
> Application and Renderer resize improvements

- packages/core/src/shader/Program.ts
- packages/core/src/shader/utils/generateUniformsSync.ts
- packages/core/src/shader/utils/uniformParsers.ts
- packages/core/test/Shader.js
- packages/core/test/index.js
With this change we can set structs in shader uniforms the same way we can set it using WebGL directly.
```
shader.uniforms["material.color"] = [1, 1, 1];
shader.uniforms["lights[1].position"] = [0, 1, 0];
```
- [ x] Tests and/or benchmarks are included
- [x ] Lint process passed (`npm run lint`)
- [x ] Tests passed (`npm run test`)
> Added support for structs in shader uniforms

- packages/app/src/Application.ts
- packages/core/src/Renderer.ts
- packages/core/src/autoDetectRenderer.ts
- packages/settings/src/settings.ts
Partially fixes #6444 
We have long discarded the use of `forceFXAA` functionality (last implemented in v3), this removes from docs and typings.
> Remove forceFXAA Application and Renderer option

- packages/text/src/Text.ts
Texts with gradients don't take the style's padding property into account, and assumed the gradient should be applied to the whole canvas size. On multiline vertical gradients, this caused each successive line to be more offset on the gradient.
For example, the following style with extreme padding to highlight the issue (screenshots from the TextStyle generator):
```json
{
"fill": [
"#fff0a1",
"#face08",
"#db8c00"
],
"fontWeight": "bold",
"padding": 20
}
```
Current behaviour (can see the gradient seams for the multiple lines):
Fixed behaviour:
Playground demo: https://pixiplayground.com/#/edit/Ko5N0jUy1hAgUalGWisJn
- Of those not already failing
> Fix: Text gradients don't account for texture padding

- packages/core/src/Renderer.ts
- packages/prepare/test/BasePrepare.js
- packages/prepare/test/CountLimiter.js
- packages/prepare/test/Prepare.js
- packages/text/src/TextStyle.ts
- packages/ticker/src/const.ts
Docs updates after prepare plugin namespace change - https://github.com/pixijs/pixi.js/commit/c8cda62ed5899de901fb766b8aa7e12e176d620a
Also fixed a missing typescript return type
> Fixes incorrect mentions of deprecated namespaces

- src/core/display/Bounds.js
- src/core/display/Container.js
- src/core/display/DisplayObject.js
- src/core/graphics/Graphics.js
- src/extras/cacheAsBitmap.js
- test/core/Container.js
Our v5 bounds update has a few good tests that allow us to backport our epic bounds fixes to v4!
Cumulative changes from PR's: #6365 #6334 #6304 
All this code was CTRL+C - ed.
`_localBounds` from v5 is renamed to `_$localBounds` , because name collision with field in v4 Graphics.
@tywang2006 confirmed that there are people who want to use the fix in production.
> V4 backport localbounds

- packages/core/src/textures/resources/VideoResource.ts
- packages/sprite-animated/src/AnimatedSprite.ts
- packages/sprite-animated/test/AnimatedSprite.js
New autoUpdate setter getter for AnimatedSprite, that matches behaviour as in the VideoResource autoUpdate setter getter
> Public animated sprite update

- packages/core/src/textures/Texture.ts
- packages/core/test/Texture.js
Texture should not receive onBaseTextureUpdated once destroyed. But it left 'loaded' event subscription active.
> Unsubscribe from baseTexture loaded event on Texture::destroy

- packages/canvas/canvas-mesh/src/SimpleRope.js
Was trying to set a property that only had a getter
Change the code to match the WebGL renderer code style, using _width instead
https://github.com/pixijs/pixi.js/issues/6531
> Fixes SimpleRope on Canvas renderer

- packages/graphics/src/utils/buildRoundedRectangle.ts
The issue with rendering rounded rectangle was there were some very strange results when the radius was larger than half the smallest size or negative. This should resolve these cases. The rendering mirrors how CSS behaves with `border-radius`.
**Bug (v5.2.1)**
https://jsfiddle.net/bigtimebuddy/hgje6tpy/
**Fixed**
https://jsfiddle.net/bigtimebuddy/at18sdop/
> Handle extreme radius inputs for rounded rect

- packages/prepare/src/Prepare.ts
_resolveDirectShader is needed in a renderer parameter, otherwise it will fail [there](https://github.com/pixijs/pixi.js/blob/dev/packages/graphics/src/Graphics.ts#L1157)
Just passing down renderer to the _resolveDirectShader.
> Fix issue with preparing Graphics without shader

- packages/settings/package.json
- packages/settings/src/utils/isMobile.ts
This was bumping up in a few places namely: #6550 #6546 #6511
Since the release of ismobilejs@1.1.0, there's no longer a default user-agent/navigator argument.  This was breaking for our users trying to build against `ismobilejs@^1.0.3`
> Fix ismobilejs breakage

- packages/graphics/src/utils/buildLine.ts
> Fixed inner miter point adjustment when on opposite side of corner

- packages/core/src/renderTexture/RenderTexture.ts
I ran into this when looking at the documentation.
Skimming the readme I failed to see guidlines for comment/doc only changes.
I hope this is enough.
> Fixed example code for RenderTexture.create()

- packages/core/src/framebuffer/Framebuffer.ts
- packages/core/src/framebuffer/FramebufferSystem.ts
- packages/core/src/renderTexture/BaseRenderTexture.ts
- packages/core/test/RenderTexture.js
- packages/core/test/index.js
- packages/prepare/src/Prepare.ts
> RenderTexture#destroy destroys the depth texture as well.

- packages/core/src/filters/FilterSystem.ts
Fixes #6303
* Filter `padding` is now additive if you have multiple filters. 
* Adds `useMaxPadding` on FilterSystem for the old behavior, e.g., `renderer.filter.useMaxPadding = true;` (default is `false`)
**Current (v5.2.1)**
https://jsfiddle.net/bigtimebuddy/tz3w5cju/
**This PR (fixed)**
https://jsfiddle.net/bigtimebuddy/9whkty5L/
> Fix filters to sum padding instead of max padding

- packages/graphics/src/GraphicsData.ts
- packages/graphics/src/utils/buildCircle.ts
- packages/graphics/test/index.js
#6562 made a regression in the stroke. The "points" array is used to do a stroke, and adding the center there add a line from the center to circumference. This reverts that and transforms the center in `triangulate` instead.
> Removed center from points

- packages/spritesheet/src/Spritesheet.ts
- packages/spritesheet/src/SpritesheetLoader.ts
Thanks to #6508 pixi-tilemap `basic.html` example broke. Other people could use `atlasResource.texture` it too, so this is now a breaking change. Now imagine what could happen if they will get **destroyed texture**!
You guys can push changes to this branch, I honestly don't care what you decide about it. At the least please leave `texture = null` here. Please cherry-pick it for `5.2.2`.
> Hotfix for Spritesheet memory leak PR #6508

- packages/core/src/settings.ts
A very minor tweak to the documentation of the `STRICT_TEXTURE_CACHE` setting. I literally just moved a single word to a new location; I feel this tweaked wording better communicates what this setting does.
> Clarify STRICT_TEXTURE_CACHE documentation

- .github/workflows/nodejs.yml
Follow-up to #6600 comment about not building branches that are `feature/*` or basically contain any `/`. We want to build on all branches pushes, regardless of name.
> Build for all push branches including ones with slashes

- packages/core/test/MaskSystem.js
This is a temporary fix for slow test processing time for this one test. There may be others, but this one seems the most consistently hovering around the 2000 ms timeout.
> Fixes #6604 slow runs on CI timing out mocha

- packages/settings/src/utils/maxRecommendedTextures.ts
Switched logic, so only when we KNOW it's an old OS version do we limit the textures. In all other scenarios, allowMax
https://github.com/pixijs/pixi.js/issues/6368
> If the user agent string didn't include the OS version one day, it'd default to allowMax

- packages/display/src/DisplayObject.ts
Fixes #6606 
Clear-up typings for `mask` property.
> Add `null` as valid type for DisplayObject's mask

- packages/graphics-extras/README.md
- packages/graphics-extras/global.d.ts
- packages/graphics-extras/package.json
- packages/graphics-extras/src/drawChamferRect.ts
- packages/graphics-extras/src/drawFilletRect.ts
- packages/graphics-extras/src/drawRegularPolygon.ts
- packages/graphics-extras/src/drawTorus.ts
- packages/graphics-extras/src/index.ts
- packages/graphics/global.d.ts
- packages/graphics/src/Graphics.ts
This introduces a new package: **@pixi/graphics-extras** to provide some convenience drawing functions for various shapes. Ideally this would've been the place where `drawStar` was included too.
This PR was inspired by some draw experiments I did over the past year with Graphics. I thought these would be useful as a package. I added this package as opt-in (i.e., not included in the default bundles **pixi.js** or **pixi.js-legacy**).
**Regular Polygon:**
https://jsfiddle.net/bigtimebuddy/rqpbnj6d/
**Torus:**
https://jsfiddle.net/bigtimebuddy/mzq0yLv8/
**Fillet and Chamfer Rectangles:**
https://jsfiddle.net/bigtimebuddy/jzsgep42/
[Documentation](http://pixijs.download/dev-graphics-extras/docs/PIXI.Graphics.html)
https://pixijs.download/dev-graphics-extras/packages/graphics-extras.js
> Introduces optional Graphics Extras Package

- packages/graphics/src/utils/Star.ts
- packages/graphics/src/utils/index.ts
Fixes #6648 - Star polygon class is part of `graphicsUtils` namespace not root.
Also, members of this class documented incorrectly. Fixed the names.
```
exports.BATCH_POOL
exports.DRAW_CALL_POOL
exports.FILL_COMMANDS
```
Current dev (broken)
http://pixijs.download/dev/docs/PIXI.graphicsUtils.html
This PR (fixed)
http://pixijs.download/dev-graphics-docs/docs/PIXI.graphicsUtils.html
> Fix docs for graphicsUtils namespace and members

- global.d.ts
- packages/polyfill/src/requestAnimationFrame.ts
After updating the polyfill package to TypeScript the pixi examples page no longer works.
As discussed here [pixijs/examples#66](https://github.com/pixijs/examples/issues/66) this was due to the `commonjs` rollup plugin not being compatible with TypeScript.
To fix this i replaced `global` with `window` as @bigtimebuddy suggested.
This should also fix #6668
> Replace global for window in polyfill

- bundles/pixi.js-legacy/src/index.ts
- bundles/pixi.js/src/index.ts
- bundles/pixi.js/src/useDeprecated.ts
- bundles/pixi.js/test/index.js
- packages/accessibility/src/AccessibilityManager.ts
- packages/accessibility/src/accessibleTarget.ts
- packages/accessibility/src/index.ts
- packages/canvas/canvas-renderer/src/CanvasRenderer.ts
- packages/core/src/Renderer.ts
- packages/interaction/src/InteractionData.ts
- packages/interaction/src/InteractionEvent.ts
- packages/interaction/src/InteractionManager.ts
- packages/interaction/src/InteractionTrackingData.ts
- packages/interaction/src/TreeSearch.ts
- packages/interaction/src/index.ts
- packages/interaction/src/interactiveTarget.ts
- packages/ticker/src/Ticker.ts
- packages/ticker/src/const.ts
Recently in v5, we removed `extract` and `prepare` internal namespaces. I would also like to remove `interaction` and `accessibility` namespaces as well. These are not useful for organizing the code since they only contain a small number of classes and it simplifies the code and documentation. Internal namespacing is only really useful for `utils` (which would pollute the root `PIXI` object with lots of generic functions) and `filters` (which we can hang a lot more filters on with pixi-filters). It should also make it easier for users importing types in the future.
**Documentation**
https://pixijs.download/dev-namespace-deprecation/docs/index.html
> Remove interaction and accessibility namespaces

- packages/core/src/AbstractRenderer.ts
- packages/core/src/filters/Filter.ts
- packages/core/src/state/State.ts
- packages/core/src/textures/Texture.ts
- packages/core/src/textures/TextureMatrix.ts
- packages/core/src/textures/resources/VideoResource.ts
- packages/display/src/Container.ts
- packages/display/src/DisplayObject.ts
- packages/filters/filter-alpha/src/AlphaFilter.ts
- packages/filters/filter-blur/src/BlurFilter.ts
- packages/filters/filter-blur/src/BlurFilterPass.ts
- packages/filters/filter-color-matrix/src/ColorMatrixFilter.ts
- packages/filters/filter-displacement/src/DisplacementFilter.ts
- packages/filters/filter-noise/src/NoiseFilter.ts
- packages/interaction/src/InteractionTrackingData.ts
- packages/math/src/ObservablePoint.ts
- packages/math/src/Transform.ts
- packages/mesh-extras/src/NineSlicePlane.ts
- packages/particles/src/ParticleContainer.ts
- packages/sprite-animated/src/AnimatedSprite.ts
- packages/sprite-tiling/src/TilingSprite.ts
- packages/sprite/src/Sprite.ts
- packages/text-bitmap/src/BitmapText.ts
- packages/text/src/Text.ts
- packages/text/src/TextStyle.ts
- packages/ticker/src/Ticker.ts
- packages/utils/src/media/CanvasRenderTarget.ts
These inline rule exceptions are not longer necessary and is an artifact of earlier version of eslint.
> Remove old unnecessary eslint rule

- packages/core/src/textures/Texture.ts
- packages/math/src/IPoint.ts
- packages/spritesheet/src/Spritesheet.ts
We should strictly define the Spritesheet format we're expecting. Remove the `any` references in Spritesheet.
> Formalize the Spritesheet format in TypeScript

- packages/canvas/canvas-graphics/src/Graphics.ts
- packages/canvas/canvas-renderer/src/canvasUtils.ts
There were two uses of `@ts-ignore` in canvas-renderer and canvas-graphics that were pretty easy to fix and remove all the weird linting exceptions.
> Remove uses of ts-ignore in canvasUtils and canvas-graphics

- .eslintrc.json
- packages/canvas/canvas-display/src/Container.ts
- packages/canvas/canvas-display/src/DisplayObject.ts
- packages/core/src/batch/ObjectRenderer.ts
- packages/core/src/filters/Filter.ts
- packages/core/src/projection/ProjectionSystem.ts
- packages/core/src/textures/resources/Resource.ts
- packages/core/src/textures/resources/VideoResource.ts
- packages/display/src/Container.ts
- packages/display/src/DisplayObject.ts
- packages/graphics/src/utils/ArcUtils.ts
- packages/text/src/TextMetrics.ts
Adds a better linting rule for unused-vars to avoid false-positives. This enforce a TypeScript convention with ESLint.
> Improves unused-vars usage, removes inline exceptions

- packages/core/src/filters/Filter.ts
- packages/core/src/geometry/Geometry.ts
- packages/core/src/geometry/GeometrySystem.ts
- packages/core/src/geometry/utils/interleaveTypedArrays.ts
- packages/core/src/geometry/utils/setVertexAttribArrays.ts
- packages/core/src/shader/GLProgram.ts
- packages/core/src/shader/Shader.ts
- packages/core/src/shader/ShaderSystem.ts
- packages/core/src/shader/UniformGroup.ts
- packages/core/src/shader/utils/compileProgram.ts
- packages/core/src/shader/utils/generateUniformsSync.ts
- packages/core/src/shader/utils/mapSize.ts
- packages/core/src/shader/utils/mapType.ts
- packages/core/src/textures/resources/VideoResource.ts
- packages/display/src/DisplayObject.ts
- packages/utils/src/logging/deprecation.ts
We have a utility for representing simple generic string-key objects called `Dict`, it was used in some places and not others, this harmonizes it across the code base.
```typescript
{[name: string]: number}
```
Becomes
```typescript
Dict<number>
```
> Converts generic string-map types to Dict typing in utils

- packages/core/src/batch/AbstractBatchRenderer.ts
I've been working on updating our dependencies to the latest linting toolchain. This exposed a bunch of issues where we were ts-ignoring and using `any` to mask issues.  I'm working on a series of PRs to improve typings and remove more instances using `any` before upgrading eslint.
This PR adds a stricter type to define the interface for batch-able elements.
> Add IBatchableElement to AbstractBatchRenderer

- packages/text-bitmap/src/formats/TextFormat.ts
- packages/text-bitmap/src/formats/XMLFormat.ts
We should not be using `@ts-ignore` as it masks potential issues. This removes the heavy usage of this from the new TextFormat.
> Remove use of ts-ignore in TextFormat

- packages/core/src/textures/resources/BufferResource.ts
- packages/core/src/textures/resources/CanvasResource.ts
- packages/core/src/textures/resources/CubeResource.ts
- packages/core/src/textures/resources/ImageBitmapResource.ts
- packages/core/src/textures/resources/ImageResource.ts
- packages/core/src/textures/resources/Resource.ts
- packages/core/src/textures/resources/SVGResource.ts
- packages/core/src/textures/resources/VideoResource.ts
- packages/core/src/textures/resources/autoDetectResource.ts
- packages/core/test/autoDetectResource.js
* Removes more usage of `any` and replaces with `unknown` in resource `test` functions.
* Changes the behavior slightly of `autoDetectResource` to throw an error when a resource type cannot be auto-detected. This is better than just shoving it into an ImageResource.
> Replace any with unknown in resource test functions

- packages/core/src/textures/Texture.ts
- packages/core/test/Texture.js
This creates a convenience method for loading remote URLs. Fixes #6514. There are currently ways to error handle loads, and they suck and are confusing/verbose to use.  This adds an alternative path for loading Texture by returning a Promise.
```js
const texture = PIXI.Texture.from('http://path/to/wherever.png', {
resourceOptions: { autoLoad: false }}
);
await texture.baseTexture.resource.load();
```
```js
const texture = PIXI.Texture.from('http://path/to/wherever.png', {
resourceOptions: { autoLoad: false }}
);
texture.baseTexture.resource.onError.add(() => {
// handle error here
});
```
```js
const texture = await PIXI.Texture.fromURL('http://path/to/wherever.png');
```
> Provide a convenience Texture API to handle invalid URLs more effectively

- packages/core/src/shader/ShaderSystem.ts
- packages/core/src/shader/UniformGroup.ts
- packages/core/src/shader/utils/generateUniformsSync.ts
- packages/core/src/textures/resources/SVGResource.ts
In the newer linting tools `Function` is a discouraged type. Replaced this in the code with more specific types.
> Remove the use of Function as a type

- packages/interaction/src/InteractionManager.ts
There are issues with InteractionManager's linting using the latest version of ESLint and TypeScript plugins. This preemptively addresses those issues:
* Discourage the use of `object` as a type
* No longer provides platform-specific CSS properties like `msTouchAction`
> Fix linting issues with InteractionManager

- packages/mesh/src/Mesh.ts
- packages/mesh/src/MeshBatchUvs.ts
- packages/mesh/src/MeshGeometry.ts
- packages/mesh/src/MeshMaterial.ts
- packages/prepare/src/BasePrepare.ts
- packages/sprite/src/Sprite.ts
- packages/utils/src/index.ts
This removes the last of the unnecessary `@ts-ignore` instances. In general, `@ts-ignore` should be avoid at all costs.
> Remove all remaining instances of @ts-ignore

- packages/core/src/textures/Texture.ts
- packages/display/src/Bounds.ts
- packages/display/src/DisplayObject.ts
- packages/graphics/src/Graphics.ts
- packages/graphics/src/GraphicsGeometry.ts
- packages/interaction/src/InteractionData.ts
- packages/interaction/src/InteractionManager.ts
- packages/math/src/IPoint.ts
- packages/math/src/IPointData.ts
- packages/math/src/Matrix.ts
- packages/math/src/ObservablePoint.ts
- packages/math/src/Point.ts
- packages/math/src/index.ts
- packages/mesh/src/Mesh.ts
- packages/mixin-cache-as-bitmap/src/index.ts
- packages/sprite-tiling/src/TilingSprite.ts
- packages/sprite/src/Sprite.ts
This was @andrewstart's (excellent) suggestion to use `IPointData` instead of `IPoint`, `Point` or `ObservablePoint`. This means we can use _more_ generic objects instead of having to construct one of the Point classes. For instance:
```typescript
const shapes = new PIXI.Graphics();
shapes.containsPoint({ x: 10, y: 10 });
```
> Formalizes the Use of IPointData

- packages/canvas/canvas-renderer/src/CanvasRenderer.ts
Implement render-target clearing in `CanvasRenderer#render`. This was reported in #6674.
Additional fixes:
* Fix the default value of the `clear` argument in the documentation.
> Implement render-target clear in CanvasRenderer

- packages/utils/src/color/hex.ts
After testing an update from v5.2.4 to 5.3.0, I noticed an error relating to `string2hex`. After the update, it seems the generated .d.ts signature changed to accidentally not accept any arguments. This doesn't affect tests or the generated JavaScript at runtime since the actual code itself and TypeScript annotation does still correctly accept a string parameter. But when using Pixi as an external dependency in a TypeScript project, something like `PIXI.utils.string2hex('#FFFFFF')` will throw a TypeScript error.
Inspired by a similar recent PR https://github.com/pixijs/pixi.js/pull/6703 that seems to fix up some issues created from the refactor in https://github.com/pixijs/pixi.js/pull/6634, this simply adds a parameter name to the JSDoc so the generated `pixi.js.d.ts` function signature …
> Fix parameter name so string2hex has correct generated .d.ts signature

- packages/canvas/canvas-graphics/src/Graphics.ts
fix: #6083 
bug: https://jsfiddle.net/JetLu/Lnzyx135/
fixed: https://jsfiddle.net/JetLu/3ok4n7La/
> fix: generateCanvasTexture generates textures twice the size

- packages/mixin-cache-as-bitmap/src/index.ts
fix: #6733 
It's consistent with `CanvasRenderer`
fixed: https://jsfiddle.net/JetLu/gk2o7vmb/
> fix: CacheAsBitmap problem under WebGLRenderer

- packages/display/src/DisplayObject.ts
- packages/text/src/Text.ts
- packages/text/test/Text.js
fix: #6744 
fixed: https://jsfiddle.net/JetLu/w501jpxk/
```js
label.text += '100'
app.render()
```
Only in step `2` will `Text.updateText` be triggered, but it's too late.
`Text.updateText` -> `Text.updateTexture` -> `Sprite._onTextureUpdate` -> `Transform.onChange`
`Text` update `transform` property lags behind `render`.
**This PR may be only a temporary solution.**
> fix: Text updateTransform cannot be triggered before Render

- packages/sprite-animated/src/AnimatedSprite.ts
Fixes #6536 
Adds some additional context for using `onComplete`, `onFrameChange` and `onLoop`.
https://pixijs.download/fix-6536/docs/PIXI.AnimatedSprite.html#onComplete
As a side-note, I think we should convert these handlers to events. Using handlers like this doesn't really fit with other API patterns internally that really on dispatching with EventEmitter. So this implementation is a bit of an outlier, IMO. We could certainly have both and deprecate one. That would be another PR though.
> Update documentation for AnimatedSprite handlers

- bundles/pixi.js/src/useDeprecated.ts
> Fixes namespace on deprecation entries for interaction manager

- packages/canvas/canvas-mesh/src/CanvasMeshRenderer.ts
fix: #6759 
fixed: https://jsfiddle.net/JetLu/y3x5s9g7/
It's assigned to @GoodBoyDigital , but I want to try to fix it.
The content of the code is actually copied from [NineSlicePlane._renderCanvas](https://github.com/pixijs/pixi.js/blob/dev/packages/canvas/canvas-mesh/src/NineSlicePlane.ts#L38).
> Fix Mesh tint for CanvasRenderer

- types/assemble.js
During the recent conversion of the display package to TypeScript (#6261) the function signature of `addChild` and `removeChild` got changed. Previously their parameter was called `child` but now it is `children`.
As a result the massaging of the type output via string replacement (#5941) stopped working for these methods. Since 5.3.0 the declaration files state that the return type of `addChild` and `removeChild` is `DisplayObject`.
This pull request re-adds the generic types to these container methods by adjusting the regular expression.
> Fix generic types of container child methods

- packages/text-bitmap/src/BitmapFont.ts
User on Slack (@Bouh) reported a problem where pollution on `Array.prototype` was creating issue with BitmapFont because of the type of loops being use `for...in` instead of incrementing `for` loops.
**Broken** (v5.3.2): https://jsfiddle.net/bigtimebuddy/xp9k76nj/
**Fixed** (this PR): https://jsfiddle.net/bigtimebuddy/04ysxjef/
While, in general, adding Array.prototype assignments is not best practice, it's sometimes necessary for older browser and getting ES6 features. This change actually fixes the BitmapFont data arrays to be looped consistent with the rest of Pixi (`for...in` are really only used for plain objects).
> Fix for loops in BitmapFont.from to guard against Array.prototype pollution

- packages/text-bitmap/src/BitmapFont.ts
Partial addresses #6789 
http://pixijs.download/fix-bitmap-font-from-docs/docs/PIXI.BitmapFont.html#.from
> Fix documentation for BitmapFont.from to indicate used style properties

- packages/canvas/canvas-graphics/package.json
- packages/canvas/canvas-mesh/package.json
- packages/canvas/canvas-sprite/package.json
- packages/canvas/canvas-text/package.json
Just added missed `canvas-display` dependency to `canvas-graphics`, `canvas-mesh`, `canvas-sprite` packages and added `canvas-sprite` to `canvas-text` dependecy.
As you can see Graphics extends Container
https://github.com/pixijs/pixi.js/blob/8998367f026d2a729bc3ae8583c4b6954de42260/packages/graphics/src/Graphics.ts#L78
and CanvasRenderer execute next line
https://github.com/pixijs/pixi.js/blob/cdf9494b1a4f8ad758033683dcf101033cf8c95b/packages/canvas/canvas-renderer/src/CanvasRenderer.ts#L299
which call next method ```Container.prototype.renderCanvas``` it exist in `canvas-display` (**without this module it will throw an error that `renderCanvas` method doesn't exist in Graphics class**) package and then
```Container.prototype.renderCanvas``` call method `_renderCanvas` …
> Added missed dependency for canvas-graphics, canvas-mesh, canvas-sprite and canvas-text

- packages/utils/package.json
Upgrade to Earcut v2.2.2
**NOTE:** I ran `npm run test`, and the functional tests seem to pass, but ran into the same issue as #5931 where running `mkdirp dist/types && jsdoc -c types/jsdoc-legacy.conf.json && node types/assemble pixi.js-legacy` throws the same error.   I tried upgrading/downgrading node from 8 <-> 13.  Uninstalled my global copy of `jsdoc`.  Pulled in the latest from https://github.com/pixijs/pixi.js/pull/6700 but didn't seem to resolve my particular issue.  I would love to be able to run tests, but I must be missing something obvious... If anyone knows, give me a hint! Thnx :)
> Upgrade to Earcut v2.2.2

- packages/text/src/TextMetrics.ts
Fix wrong result when a key is reserved name of `Object.prototype` fields, like `constructor`
https://github.com/pixijs/pixi.js/issues/6836
> Fix TextureMetrics wrong cache

- packages/text-bitmap/src/formats/TextFormat.ts
- packages/text-bitmap/test/resources/bmtxt-test.txt
Fixes #6839
The text-based font format supports a `kernings` attribute, but it was missing from the parsing code. Also, updates the unit-test to make sure we are parsing kernings.
> Fix crash with "kernings" field in BitmapFont txt-based format

- packages/math/src/Matrix.ts
- packages/math/test/Matrix.js
#6810
This patch has been battle-tested in the [@pixi-essentials/transformer](https://github.com/SukantPal/pixi-essentials/blob/ffe467dc8da91f3ac36723fbd59395428fbd8ffd/packages/transformer/src/utils/decomposeTransform.ts#L44) package.
Basically, the `Matrix#decompose` method sets the position assuming the pivot is (0, 0). Obviously, this is not always
the case.
There are either two fixes to this: set pivot to (0, 0) always OR calculate the position so that the pivot does not have to
change. I chose the latter b/c the user does not expect the pivot to change when decomposing a matrix, because it is
not a part of the actual transform.
The reason why this will work is b/c of the way tx, ty are calculated:
https://github.com/pixijs/pixi.js/blob/8f7ed7662949ea1217b6f3b6af470e855cfe0b13/package …
> Account for transform pivot when decomposing matrix

- bundles/pixi.js-legacy/package.json
- bundles/pixi.js/package.json
- rollup.config.js
This adds support in the build system for exporting a native browser-based module. Currently, only esm files exported are intended for users of Webpack/Rollup/Parcel. This module export will run directly in modern browsers that support `<script type="module">` and provides a modern solution for importing directly in the browser.
Fixes #6734
* https://pixijs.download/dev-browser-modules/pixi.mjs
* https://pixijs.download/dev-browser-modules/pixi-legacy.mjs
Code: https://github.com/bigtimebuddy/pixi.js-browser-module-example
Preview: https://mattkarl.com/pixi.js-browser-module-example/
> Create Native Browser Module Bundles

- packages/canvas/canvas-sprite-tiling/package.json
- packages/canvas/canvas-sprite-tiling/src/TilingSprite.ts
Fixes #6862
~~A regression has been introduced in this PR as the tiles appear smaller than they should. Maybe @ivanpopelyshev can help me here.~~
> Fix canvas rendering transform of TilingSprite

- packages/core/src/geometry/GeometrySystem.ts
gl.createVertexArray may not be null in WebGL1 context on some platforms.
Use context.webGLVersion instead.
> Fix VAO & instance array check in WebGL2.

- packages/graphics/src/Graphics.ts
The sampler array should not be a hardcode value of 16 since it will be larger than what maxRecommendedTextures returns.
maxRecommendedTextures will return 4 if the android version is smaller than 7.
The crash stack is:
```
09-14 14:41:35.409 14755-14934/? A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 14934 (GLThread 1122)
09-14 14:41:35.519 622-622/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-14 14:41:35.519 622-622/? A/DEBUG: Build fingerprint: 'vivo/1606/1606:6.0.1/MMB29M/compiler01052117:user/release-keys'
09-14 14:41:35.519 622-622/? A/DEBUG: Revision: '0'
09-14 14:41:35.519 622-622/? A/DEBUG: ABI: 'arm'
09-14 14:41:35.519 622-622/? A/DEBUG: pid: 14755, tid: 14934, name: GLThread 1122  >>> com.yy.demo <<<
09-14 14:41:35.519 622-622/? A/DEBUG: …
```
> Fix crash on Adreno 3xx GPU devices (e.g. vivo 1606, vivo 1610, Xiaomi Redmi Note 4G).

- packages/core/src/mask/ScissorSystem.ts
Fixes #6866
-----
:pen: https://codepen.io/sukantpal/pen/mdPLvJG?editors=0010
> Account for scaling b/w sourceFrame → destinationFrame in ScissorSystem

- packages/core/src/Renderer.ts
Fix #6878
Add missing properties:
-PIXI.ParticleRenderer
-PIXI.BatchRenderer
-PIXI.TilingSpriteRenderer
First PR here 🥳
> Add property to Renderer Plugins

- packages/text-bitmap/src/BitmapFont.ts
Attempt at partially fixing #6884
Basically, when using `BitmapFont.from` we were not making any effort to get kerning information. This would make `BitmapText` look very different from the standard `Text` object.
This PR does not solve xadvance, but gets us a little closer.
In this example `Y` + `e` and `Y` + `o` in Arial is a dramatically example.
**Before**
https://jsfiddle.net/bigtimebuddy/k8jdeczu/
**After**
https://jsfiddle.net/bigtimebuddy/ufrneabt/
> BitmapFont.from generate the kerning information

- packages/text-bitmap/src/BitmapText.ts
Fix #6900
https://jsfiddle.net/18dkq4t3/
> Zero out garbage space of vertices buffer of BitmapText

- packages/graphics/src/Graphics.ts
Fixed typo in Graphics._render method `hasuit32 -> hasuint32`
> Fix typo in Graphics._render

- packages/sprite-animated/src/AnimatedSprite.ts
```this.animation.onComplete = undefined;```
that line gives me an error in typescript
```Type 'undefined' is not assignable to type '(...params: any[]) => any'.ts(2322)```
Even `AnimatedSprite.destroy()` function sets these to `null`, so why can't I ?
```
public destroy(options: IDestroyOptions|boolean): void
{
this.stop();
super.destroy(options);
this.onComplete = null;
this.onFrameChange = null;
this.onLoop = null;
}
```
> Make AnimatedSprite event functions optional

- packages/core/src/textures/resources/CompressedTextureResource.ts
`premultiplyAlpha` is deprecated.
`resources` namespace is removed.
> Fix compressed texture docs

- packages/mixin-cache-as-bitmap/src/index.ts
Functions and methods are fundamentally different things, at least for webdoc. A function can be called without a `this` context and is not a member of a class/object. They are documented as separate pages. A method does have a `this` context and only is called using "`context.`"`method()`
The methods added by the cache mixin should be tagged `@method` and not `@function`.
> @function -> @method

- packages/core/src/textures/TextureSystem.ts
Noticed that we always assume texture is 2d, rather than using the textures target type.
easy fix 👍
> fixes unbind issue when using different targets

- packages/core/src/renderTexture/RenderTexture.ts
Fixes #6519 
Made clear that the creation of a new renderer is not needed to render a RenderTexture in the documentation.
> Update doc of RenderTexture

- packages/text-bitmap/src/utils/drawGlyph.ts
Fixes #6939 
I [downloaded Opera 29](https://get.geo.opera.com/pub/opera/desktop/29.0.1795.60/mac/) and verified this is an issue and the fix that @relefant suggested worked.
```html
<html>
<body>
<script src="https://pixijs.download/dev/pixi.min.js"></script>
<script>
var app = new PIXI.Application({
backgroundColor: 0x1099bb,
width: 500,
height: 200
});
var size = 150;
var style = new PIXI.TextStyle({
fontFamily: 'Arial',
fontSize: size
});
var font = PIXI.BitmapFont.from("fontName", style);
var bitmapFontText = new PIXI.BitmapText('Bitmap', {
fontName: 'fontName',
});
bitmapFontText.x = 10;
bitmapFontText.y = 10;
app.stage.addChild(bitmapFontText);
</script>
</body>
</html>
```
> Fix defaults args for setTransform

- packages/graphics/src/Graphics.ts
Fixes #6942 
Remove duplicate `super.destroy`
> Remove duplicate destroy function in Graphics

- bundles/pixi.js/src/useDeprecated.ts
- package-lock.json
- package.json
- packages/canvas/canvas-extract/src/CanvasExtract.ts
- packages/compressed-textures/package.json
- packages/core/src/AbstractRenderer.ts
- packages/core/src/filters/FilterSystem.ts
- packages/graphics/src/Graphics.ts
- packages/sprite-tiling/src/TilingSprite.ts
- packages/text-bitmap/src/BitmapText.ts
- rollup.config.js
This PR depends on #6961
* Fix production browser bundles to use _production_ packages
* Production bundles exclude deprecations messages (more performant, removes ~10KB from bundle size)
I'd like to create a simple guide for bundle users (Rollup & Webpack) that shows them how to bundle a production version of the library. For instance, here's the Rollup version. Might create a Rollup plugin for this.
```js
// rollup.config.js
import alias from '@rollup/plugin-alias';
const rollupConfig = {
plugins: [
alias({
entries: [{
find: /^(@pixi\/([^\/]+))$/,
replacement: '$1/dist/esm/$2.min.js',
}]
}),
]
}
```
```js
// webpack.config.js
import AliasRegexOverridePlugin from 'alias-regex-webpack-plugin';
const webpackConfig = {
plugins: [
new AliasRegexhOverridePlugin(
/^(@pixi\/([^\/]+))$/, …
```
> Exclude deprecation messages from Production builds

- src/core/renderers/webgl/utils/mapWebGLBlendModesToPixi.js
Fix BLEND_MODES.ADD based on the commit: https://github.com/pixijs/pixi.js/pull/5740/commits/2d50b0526d7aee8075ec3e60eac254172ea0ca26
> [4.4.x] Fix BLEND_MODES.ADD based on the commit from the 4.x branch 

- packages/text-bitmap/src/BitmapText.ts
- packages/text/src/TextStyle.ts
Add 'justify' feature to bitmap texts. This aligns the text both right and left using varying spaces between words
roundPixels = true, is recommended for small font sizes. 
[TestJustify.zip](https://github.com/pixijs/pixi.js/files/5453257/TestJustify.zip)
> Support text alignment 'justify' in BitmapText

- packages/core/src/mask/MaskSystem.ts
> Enable scissor mask support by default

- bundles/pixi.js/src/index.ts
After moving to JSCC, I forgot to replace `__VERSION__` with `$_VERSION` in the pixi.js bundle. @andrewstart reported this issue with pixi-particles trying to upgrade to 5.4.0-rc.2.
```js
/**
* String of the current PIXI version.
*
* @static
* @constant
* @memberof PIXI
* @name VERSION
* @type {string}
*/
var VERSION$1 = '__VERSION__';
```
https://pixijs.download/v5.4.0-rc.2/pixi.js
```js
/**
* String of the current PIXI version.
*
* @static
* @constant
* @memberof PIXI
* @name VERSION
* @type {string}
*/
var VERSION$1 = '5.4.0-rc.2';
```
https://pixijs.download/fix-version/pixi.js
> Missed Version Substitution

- packages/interaction/src/InteractionManager.ts
- packages/prepare/src/BasePrepare.ts
Fixes #7009 and part of #7013 (the rest of that is fixed by #7006).
For the OffscreenCanvas change, I realized that bailing early would prevent the non-style cursor functionality from working, so changed it to be a more targeted check.
> Some fixes for 5.4.0
