src/extras/MovieClip.js
src/extras/Rope.js
src/extras/Strip.js
src/text/BitmapText.js
src/text/Text.js

I took the liberty to remove setText while making since change since Sprite dropped setTexture

Update extras to use texture setter, update Text to use getter/setter for style/text

---

src/pixi/textures/RenderTexture.js

This PR fixes #1322
I also did a bit of cleanup in the `resize` method as I noticed it was logically doing things differently from the constructor, which could lead to a lot of confusion if anyone ends up using it.

RenderTexture fixes

---

src/core/math/Matrix.js

Have apply be consistent with applyInverse change by https://github.com/GoodBoyDigital/pixi.js/pull/1439

Matrix.apply bug

---

src/filters/tiltshift/TiltShiftAxisFilter.js
src/filters/tiltshift/TiltShiftXFilter.js
src/filters/tiltshift/TiltShiftYFilter.js

This resolves a TODO that was in there.

Remove code duplication from TiltShiftX and Y filters. 

---

README.md

The current url for demo Fight for Everyone is broken, i fix it with the link on goodboydigital.com. That i believe is the correct.

Fixing link for Fight for Everyone game.

---

src/loaders/index.js

gulp build wasn't working because of this

fixed typo in loaders/index.js

---

src/core/display/Container.js
src/core/graphics/Graphics.js
src/core/renderers/webgl/WebGLRenderer.js
src/core/renderers/webgl/filters/AbstractFilter.js
src/core/renderers/webgl/managers/StencilManager.js
src/core/renderers/webgl/utils/ObjectRenderer.js
src/core/renderers/webgl/utils/Quad.js
src/core/renderers/webgl/utils/RenderTarget.js
src/core/sprites/Sprite.js
src/interaction/interactiveTarget.js
src/spine/Spine.js
src/text/BitmapText.js
src/text/Text.js

The containsPoint method exists so that if people want to build their own interaction manager they don't need to touch some pixi stuff such as worldTransform.applyInverse, etc...

Bit of docs, but more importantly some api fixes

---

inch.json
src/core/index.js
src/core/particles/ParticleContainer.js
src/core/particles/webgl/ParticleRenderer.js
src/core/renderers/webgl/utils/StencilMaskStack.js
src/core/sprites/Sprite.js
src/core/textures/BaseTexture.js
src/extras/TilingSprite.js
src/interaction/interactiveTarget.js
src/loaders/spineAtlasParser.js
src/spine/index.js

Also added a configuration file for Inch Ci

Added fromImage and fromFrame helpers to tiling sprites

---

src/deprecation.js
src/extras/mesh/Mesh.js
src/extras/mesh/webgl/MeshRenderer.js
src/spine/Spine.js

Even though I prefer it the other way, it matches the V3 changes on the other consts like BLEND_MODES, etc...

Renamed The DrawModes consts

---

src/core/renderers/webgl/filters/FXAA.frag
src/core/renderers/webgl/filters/FXAA.vert
src/core/renderers/webgl/filters/FXAAFilter.js

The fragment and vertex shader for the FXAA filter were the wrong way around, it worked, but their naming was rubbing me the wrong way :)

FXAA vert and frag filters were the wrong way around

---

src/core/renderers/webgl/WebGLRenderer.js
src/core/renderers/webgl/filters/SpriteMaskFilter.js
src/core/utils/index.js
src/deprecation.js
src/extras/TilingSprite.js
src/filters/color/ColorMatrixFilter.js

This fixes most of the complaints jshint gave. It also fixes some weird issue in SpriteMaskFilter where the fs module could only be required inside the constructor for browserify to work.

jshint housekeeping

---

src/index.js

I'm just opening this as a separate PR so we have a place to talk about it and get people's feedback.
Obviously the code can be shortened, I did it on purpose so people can look at the file and instantly see what it does.

Namespacing discussion 

---

src/core/textures/Texture.js

VideoBaseTexture.baseTextureFromVideo not avaliable, so changed it to VideoBaseTexture.fromVideo

VideoBaseTexture bug fix

---

src/core/display/Container.js
src/core/display/DisplayObject.js
src/core/renderers/webgl/shaders/Shader.js
src/core/renderers/webgl/utils/ObjectRenderer.js
src/core/sprites/webgl/SpriteRenderer.js
src/deprecation.js
src/filters/color/ColorMatrixFilter.js
src/filters/dropshadow/BlurYTintFilter.js
src/index.js
src/mesh/webgl/MeshRenderer.js
src/polyfill/requestAnimationFrame.js

- Removed some unused vars
- Note trailing line format for things meant to stay

Fix all the remaining jshint stuff

---

src/core/renderers/webgl/filters/FXAAFilter.js
src/core/renderers/webgl/filters/SpriteMaskFilter.js
src/filters/ascii/AsciiFilter.js
src/filters/blur/BlurXFilter.js
src/filters/blur/BlurYFilter.js
src/filters/blur/SmartBlurFilter.js
src/filters/color/ColorMatrixFilter.js
src/filters/color/ColorStepFilter.js
src/filters/convolution/ConvolutionFilter.js
src/filters/crosshatch/CrossHatchFilter.js
src/filters/displacement/DisplacementFilter.js
src/filters/dot/DotScreenFilter.js
src/filters/dropshadow/BlurYTintFilter.js
src/filters/gray/GrayFilter.js
src/filters/invert/InvertFilter.js
src/filters/noise/NoiseFilter.js
src/filters/normal/NormalMapFilter.js
src/filters/pixelate/PixelateFilter.js
src/filters/rgb/RGBSplitFilter.js
src/filters/sepia/SepiaFilter.js
src/filters/shockwave/ShockwaveFilter.js
src/filters/tiltshift/TiltShiftAxisFilter.js
src/filters/twist/TwistFilter.js

Reference issue for all fs requires (fixes typo as well)

---

src/core/textures/Texture.js

ee3 doesn't have those methods

missed on, and use once

---

src/pixi/InteractionData.js
src/pixi/InteractionManager.js

* Add the global position on all changedTouches object
* Best way to gesture the double tap event on touchstart and getting each position.
* add optimisation and speed up the code
* add compatibility support for CocoonJS
* add more optimization

More flexibility with multitouch gesture events (Advances, Optimization, ConconJS)

---

gulp/util/karma.conf.js

gulp build pixi to bin/pixi.js

change karma path to pixi build

---

src/core/utils/index.js

Add some padding and some ✰ stars ✰

add some space in the “sayHello” console.log

---

src/core/textures/RenderTexture.js

fixed retrieve Canvas from RenderTexture bug

---

src/pixi/extras/PIXISpine.js

One more fix for spine region attachments, continuation of 5e96a5fad5f8a90eddf5a7a5715d91d9a5b577be

Spine plugin: ScaleX and ScaleY of attachments

---

src/pixi/extras/Spine.js

Again, my animation crashed against small error. Even webstorm shown that thing in warnings :) Who wants to check other modules with WebStorm?

Spine FlipX/FlipY timeline fix

---

src/core/graphics/Graphics.js

That probably wasn't meant to be there.

remove consol.log

---

src/pixi/renderers/webgl/utils/WebGLGraphics.js

Fixed WebGL line rendering problem (issue #975 )

---

src/core/textures/RenderTexture.js

implemented feature discussed in #1552

added pixel data retrieval functions to RenderTexture

---

src/pixi/loaders/ImageLoader.js

this was posted by error in v3 branch :)

Fix for loadFramedSpriteSheet crash when the texture is not loaded yet

---

src/deprecation.js

It was useful for me when I was migrating to PIXI v3.

Added more depracation API

---

src/extras/MovieClip.js

https://github.com/GoodBoyDigital/pixi.js/issues/1694

MovieClip.currentFrame renamed  because of confusing name

---

src/extras/MovieClip.js

typo fix - _textures instead of _texture

---

src/pixi/loaders/ImageLoader.js

fixed warnings

---

src/mesh/Mesh.js
src/mesh/Rope.js

Rope can use texture from spriteheets, not only standalone image

Rope supports textures from spritheet

---

src/mesh/webgl/MeshRenderer.js

Mesh Rendering was not working at all (at least when created via pixi-spine)
With That fix Spine animation Mesh & skinned mesh will work (I need to create a pull request to the pixi-spine as well there were couple broken thing there too)

Fix Mesh Rendering to enable pixi-spine Mesh to render properly

---

src/core/index.js
src/core/ticker/Ticker.js
src/core/ticker/index.js
src/extras/MovieClip.js
src/index.js
src/interaction/interactiveTarget.js

Take it or leave it ;)
This was just getting annoying to me since it's a shared module across extras and interaction modules.

Moved ticker to core

---

src/core/graphics/Graphics.js

respect polygon's closed value when not filled

drawshape update

---

src/mesh/Mesh.js

Mesh Interaction and optimizing spaces (I'm sorry)

Mesh interaction

---

src/core/particles/ParticleContainer.js

ParticleContainer Destroy Fix

---

src/core/textures/VideoBaseTexture.js

reopened PR for correct branch. Couldn't find anywhere to change the old one.

make sure fromUrl uses the the iterator to find the right src

---

src/filters/noise/noise.frag

Fix the issue #1970 
Change ```precision mediump float;``` to ```precision highp float;```

Fix a display bug on iOS with NoiseFilter

---

src/interaction/InteractionManager.js

fix https://github.com/GoodBoyDigital/pixi.js/issues/1817

Fix an error when an event occurs on deleted obj

---

gulp/tasks/clean.js
package.json

clean task fix (for del versions >= 2)

---

src/core/graphics/Graphics.js

fixes a number of issues with open and closed paths

graphics update

---

src/core/renderers/canvas/utils/CanvasTinter.js

From the tests that i could do, both on desktop, emulators and devices, this seems to fix the issue without side effects ...

Fix #2006 by applying texture resolution to crop size

---

CONTRIBUTING.md
README.md
package.json
src/core/index.js
src/core/text/Text.js
src/core/ticker/Ticker.js
src/core/ticker/index.js
src/extras/index.js
src/filters/index.js
src/interaction/index.js
src/loaders/index.js
src/mesh/index.js

Just fixing something that was getting annoying every time I saw it in the docs.

jsdoc cleanup

---

src/interaction/InteractionManager.js

Revert "dispatch mousemove/touchmove event only inside hit area"

---

src/core/display/DisplayObject.js

@GoodBoyDigital For the PIXI.flash work

Added setTransform convenience method

---

src/core/graphics/webgl/GraphicsRenderer.js

I tested it on my https://github.com/ivanpopelyshev/railways and didnt notice differences, it still sucks. Regardless of my tests, this expression is just wrong.

Fix for #1950

---

src/core/textures/RenderTexture.js

Issue 2197: renderTexture canvas fallback bug

renderTexture canvas fallback

---

src/core/display/DisplayObject.js
src/interaction/InteractionData.js
test/unit/interaction/InteractionData.test.js

fix(InteractionData): populate second param of getLocalPosition

---

package.json
src/core/index.js
src/loaders/bitmapFontParser.js
src/loaders/spritesheetParser.js

newer version of resource-loader
pass the metadata to images
export WebGLManager

Changes for pixi-compressed-textures

---

src/core/text/Text.js

Related: https://github.com/pixijs/pixi.js/issues/1906
Adds `breakWords` option to `PIXI.Text` that allows for breaks to be added in the middle of words if they are wider than `wordWrapWidth`. Defaults to false and maintains current behavior.
With `breakWords` option:
With current behavior (notice some characters are cut off):

Add breakWords option to PIXI.Text

---

README.md

This resolves the first part of Issue #2361 and all of Issue #2306

Fix example code so that it runs when copy-pasted

---

src/core/textures/Texture.js

small fix in case of trim. I dont know why did I forget about that.

---

src/core/renderers/webgl/TextureGarbageCollector.js
src/core/renderers/webgl/TextureManager.js

O(N+M) complexity, where N is number of managed textures and M is number of deleted textures

cleaning. isnt tested.

---

src/mesh/Mesh.js

Canvas renderer mesh issue with resolution fix. Tested!

Dev canvas mesh fix

---

src/core/sprites/canvas/CanvasSpriteRenderer.js
src/core/textures/Texture.js
src/interaction/InteractionManager.js

pair of jshint

---

src/core/graphics/Graphics.js
src/core/sprites/Sprite.js
src/core/sprites/canvas/CanvasSpriteRenderer.js
src/core/text/Text.js
src/core/textures/RenderTexture.js
src/core/textures/Texture.js
src/loaders/spritesheetParser.js
src/particles/webgl/ParticleRenderer.js

crop -> orig rename

---

README.md
src/core/graphics/Graphics.js
src/core/graphics/GraphicsData.js

Dev v4 pre1

---

src/loaders/spritesheetParser.js

Handling data url's in Spritsheets

---

src/accessibility/AccessibilityManager.js

Adjusting the bracket style in AccessibilityManager

Adjusting bracket style in AccessibiltyManager

---

src/core/display/DisplayObject.js
src/core/display/Transform.js
src/core/display/TransformStatic.js
src/core/index.js

this will be better in v4.1, please dont base your stuff on this objects yet :)

expose Transform and TransformStatic, REQUIRED FOR PIXI-SPINE

---

src/particles/webgl/ParticleRenderer.js

Particles didnt take worldTransform into account

ParticleContainer fix

---

src/core/renderers/canvas/CanvasRenderer.js

Behaviour of renderTexture is a bit different

trying to fix clear()

---

src/core/utils/index.js

As discussed here: https://github.com/pixijs/pixi.js/issues/2233
No-one actually submitted a PR for that so here it is!

Forcing the loss of the WebGL context after detecting WebGL capabilities

---

src/core/text/Text.js
src/core/text/TextStyle.js

Nothing exciting to add, sorry.

A few JSDoc corrections relating to Text and TextStyle

---

src/core/text/Text.js
src/core/text/TextStyle.js

Reverts pixijs/pixi.js#2490 - text seems to have gone a bit funny on some of my tests

Revert "A few JSDoc corrections relating to Text and TextStyle"

---

src/core/text/Text.js
src/core/text/TextStyle.js

Revert "Revert "A few JSDoc corrections relating to Text and TextStyle""

---

src/extras/cacheAsBitmap.js

CacheAsBitmap bounds bug

---

src/core/Shader.js
src/core/const.js
src/core/graphics/webgl/shaders/PrimitiveShader.js
src/core/index.js
src/core/renderers/webgl/filters/Filter.js
src/core/renderers/webgl/filters/spriteMask/spriteMaskFilter.frag
src/core/renderers/webgl/managers/FilterManager.js
src/core/renderers/webgl/utils/checkMaxIfStatmentsInShader.js
src/core/sprites/webgl/generateMultiTextureShader.js
src/core/sprites/webgl/texture.vert
src/extras/webgl/TilingShader.js
src/extras/webgl/tilingSprite.frag
src/extras/webgl/tilingSprite.vert
src/filters/FXAA/FXAA.frag
src/filters/FXAA/FXAA.vert
src/filters/blur/generateBlurFragSource.js
src/filters/colormatrix/colorMatrix.frag
src/filters/colormatrix/colorMatrix.vert
src/filters/displacement/displacement.frag
src/filters/godray/godray.frag
src/filters/gray/gray.frag
src/filters/gray/gray.vert
src/filters/twist/twist.frag
src/mesh/webgl/MeshShader.js
src/particles/webgl/ParticleShader.js

Precision constant

---

src/core/text/Text.js

Revert "Documentation update in Text.js for style.fill"

---

src/core/text/Text.js
src/core/text/TextStyle.js

To get this previous PR working https://github.com/pixijs/pixi.js/pull/2488 
As @AMorporkian himself worked out, there were a couple of style settings that weren't being set in TextStyle that were trying to be used in Text, thus causing the display issues.

Fixes to TextStyle

---

src/core/text/TextStyle.js

@englercj I'm guessing the squash wasn't working because of the way I did the upstream merge, but I'm not 100% sure. Here it is again in a single commit.

Updated the style.fill documentation to reflect gradient options

---

src/core/renderers/webgl/managers/FilterManager.js
src/filters/displacement/displacement.frag

Dev filter clamp

---

src/filters/FXAA/FXAAFilter.js
src/filters/gray/GrayFilter.js
src/filters/index.js
src/filters/void/VoidFilter.js
src/filters/void/void.frag
src/filters/void/void.vert

Filters jsDocs, VoidFilter

---

src/core/textures/BaseTexture.js

wrap -> wrapMode. WebGLRenderer already has wrapMode reference inside.

---

src/deprecation.js

Added return to deprecated calls, resolves #2573

---

src/accessibility/AccessibilityManager.js
src/accessibility/accessibleTarget.js

Added a touch 'hook' div to activate the accessibility layer if a screen reader is being used on mobile.

Mobile accessability fix

---

src/core/textures/Texture.js

small fix for spritesheet loader

---

src/core/renderers/webgl/filters/filterTransforms.js
src/core/renderers/webgl/managers/FilterManager.js

strange filter stuff for #2572

Typo and fix for filter

---

src/deprecation.js

deprecation bug

---

src/core/display/Container.js

Resolves ambiguous usage from #2597

Better docs for addChild when using multiple children

---

src/index.js
src/prepare/canvas/CanvasPrepare.js
src/prepare/index.js
src/prepare/webgl/WebGLPrepare.js

On low performing devices, uploading Textures or Graphics to the GPU can create some unwanted chug in performance. This PR provides a convenience plugin for WebGLRenderer to preload Textures and Graphics to the GPU. The load is spread across multiple update ticks to throttle the load. It improves the initial playback speed of WebGL content.
The first argument can be any PIXI.DisplayObject or a PIXI.Container. If a Container, upload will recursively find all Graphics and Texture children and upload.
```js
renderer.plugins.prepare.upload(container, function(){});
```
Alternatively you can manually add items for upload:
```js
renderer.plugins.prepare.add(graphic)
.add(container)
.add(baseTexture)
.add(graphic)
.upload(function(){
console.log("Upload completed");
});
```
```html
<!DOCTYPE …
```

Renderer plugin to upload Textures & Graphics to the GPU

---

src/core/graphics/Graphics.js

Fix for fastRect alpha

---

src/core/ticker/Ticker.js

This is my preferred approached to fixing the issue for this PR https://github.com/pixijs/pixi.js/pull/2626. 
It was originally addressed here https://github.com/pixijs/pixi.js/commit/52e4a749d4a6c7150422cabe1288a9cf884808ef#commitcomment-17744980, with information on the issue in the comment thread.
The comment in the diff describes things.

Comment about ticker timing issue. Do not trigger update for zero delta.

---

README.md

remove double dummy declaration

clear up basic usage example

---

src/core/const.js
src/core/index.js
src/core/renderers/SystemRenderer.js
src/core/renderers/canvas/CanvasRenderer.js
src/core/renderers/canvas/utils/CanvasRenderTarget.js
src/core/renderers/webgl/WebGLRenderer.js
src/core/renderers/webgl/utils/RenderTarget.js
src/core/text/Text.js
src/core/textures/BaseRenderTexture.js
src/core/textures/BaseTexture.js
src/core/textures/RenderTexture.js
src/core/utils/index.js
src/interaction/InteractionManager.js

Should consist of only text / documentation changes.

pixijs#2541 resolution means pixel ratio too

---

src/core/renderers/webgl/WebGLRenderer.js
src/core/renderers/webgl/utils/validateContext.js

address #1182 Thoughts welcome!

Added context validator

---

src/core/renderers/webgl/filters/extractUniformsFromSrc.js
src/core/renderers/webgl/utils/validateContext.js

Cleanup jshint errors

---

src/core/display/DisplayObject.js
src/core/sprites/Sprite.js
src/deprecation.js
src/extras/BitmapText.js

Like rotation, skew, scale etc.

Some display object properties weren't showing up in jsdoc

---

src/core/text/TextStyle.js

No-one likes a missed semi-colon :/

---

src/core/display/DisplayObject.js
test/unit/core/display/Container.test.js
test/unit/core/text/Text.test.js

http://www.html5gamedevs.com/topic/23380-position-in-latest-dev-build/

Assignment by value for position/scale/skew/pivot

---

src/core/display/DisplayObject.js
src/core/display/Transform.js
src/core/display/TransformBase.js
src/core/display/TransformStatic.js
src/core/index.js
src/core/math/Matrix.js
src/deprecation.js

simple transform refactoring

---

src/mesh/NineSlicePlane.js
src/mesh/index.js

without the bin folder this time.

Add NineSlicePlane.js to enable 9Slice scaling, 

---

src/core/display/BoundsBuilder.js
src/core/display/Container.js
src/core/display/DisplayObject.js
src/core/graphics/Graphics.js
src/core/sprites/Sprite.js
src/core/text/Text.js
src/mesh/Mesh.js

tidied up bounds - less variable
fixed caching of bounds if called multiple times in with skipUpdate

Dev bounds tweak

---

src/core/graphics/Graphics.js
src/core/graphics/webgl/GraphicsRenderer.js
src/mesh/Mesh.js

same graphics object can no be rendered in multiple contexts

Same graphics object can no be rendered in multiple contexts

---

src/mesh/Plane.js

params, and vars renamed to reflect their true content/function

Dev 2679 rename params in plane

---

src/core/display/DisplayObject.js

A possible response to [this](https://github.com/pixijs/pixi.js/commit/2565f7a555b895b79c8dc77c723d946fa83879ca#commitcomment-18600748).

fix call to getBounds

---

src/core/display/Container.js
src/core/display/DisplayObject.js
src/core/renderers/webgl/filters/Filter.js

added enabled to filters

---

src/extras/BitmapText.js

Fixes align with bitmap fonts when using on maxWidth to make break lines

Fix for issue #2759

---

src/core/display/Container.js
src/core/display/DisplayObject.js

Child removes itself upon being destroyed. 
Responds to issue #2800

Destroying a DisplayObject will remove itself

---

src/core/display/Transform.js
src/core/display/TransformStatic.js

dots and commas

---

src/core/renderers/webgl/utils/RenderTarget.js

jsdocs rendertarget

---

src/interaction/InteractionManager.js

InteractionManager event documentation

---

src/core/renderers/webgl/WebGLState.js

I think we dont use push/pop, but its not good that they had that bug. Also, blendMode can be 2, so resetToDefault had a problems too

cleaning up WebGLState

---

src/core/sprites/webgl/SpriteRenderer.js

some stuff in renderer

---

src/interaction/interactiveTarget.js

added clarification to interactiontarget.hitArea

---

src/core/text/Text.js

Update Text.js fix for lineHeight

---

README.md

Adds a section on the README for how to install.
cc @GoodBoyDigital

Adds installation section on readme

---

src/core/text/Text.js
test/core/Text.js

Default destroy options for text are now all true.

Fixes #2840

---

src/core/text/Text.js

Updated docs example with fontFamily and fontSize

---

README.md

Fixes a typo and the link for CDN

---

src/deprecation.js
src/index.js

This fix maintains the deprecations in release (minified) build, but strips out the console warnings.
Resolves issue #2869

Maintains deprecations in release, strips warnings

---

src/accessibility/AccessibilityManager.js
src/core/text/Text.js
src/extras/index.js
src/interaction/InteractionManager.js

- Removed some require references that were preventing mixins like
interaction from working.
- Fixed Text

Small updates to fix some es6 conversion issues

---

src/core/graphics/Graphics.js

Multiple renerers for Graphics fastRect, solution that will work for sure

---

README.md

Oops, my first merge and I did it wrong

Derp merge master-dev

---

src/core/renderers/webgl/managers/FilterManager.js

fixed filter issue

---

package.json

This will mean things will work with web pack - we can address properly in a future release

webpack temp fix

---

src/core/textures/VideoBaseTexture.js

Can play automatically too if video has no audio track

Allow videos to play inline on iOS10

---

.editorconfig
CONTRIBUTING.md

Added more details, links to GitHub docs about forking, and the new
branching flow. As a bonus, also changed some minor things in the
editorconfig.
Best viewed in Side-by-Side view.

Update Contributing Guide with new branch flow.

---

src/interaction/InteractionManager.js

Fixes https://github.com/pixijs/pixi.js/issues/2914
Easier to do this new PR than rebase https://github.com/pixijs/pixi.js/pull/2917#issuecomment-248977216

Fixes mouseover behaviour

---

src/interaction/InteractionManager.js
src/interaction/interactiveTarget.js

And for devices that don't support pointer events, it normalises mouse / touch events to give the same data that a pointer event would
Re-submit of https://github.com/pixijs/pixi.js/pull/2476

Adding support for pointer events

---

src/core/display/Bounds.js
src/core/display/Container.js
src/core/display/DisplayObject.js
src/core/graphics/Graphics.js
test/core/Bounds.js

#2955, #2893, #2850 and other issues. 
Also, http://www.html5gamedevs.com/topic/25184-animating-mask-thats-a-graphics-shape/
Basically, "renderable" and "visible" properties now affect ONLY recursive calls from parent. You can get bounds of object or manually call updateTransform() even if not invisible.

bounds refactoring: not visible and renderable objects, masks

---

scripts/release.js
src/core/display/Container.js
test/core/Bounds.js

Fix linting issues

---

src/core/graphics/GraphicsData.js
src/core/renderers/SystemRenderer.js
src/core/renderers/webgl/TextureGarbageCollector.js
src/core/renderers/webgl/TextureManager.js
src/core/renderers/webgl/WebGLState.js
src/core/renderers/webgl/filters/spriteMask/SpriteMaskFilter.js
src/core/renderers/webgl/managers/BlendModeManager.js
src/core/renderers/webgl/utils/ObjectRenderer.js
src/core/renderers/webgl/utils/Quad.js
src/core/renderers/webgl/utils/validateContext.js
src/core/textures/RenderTexture.js
src/core/textures/Texture.js
src/core/textures/TextureUvs.js
src/core/textures/VideoBaseTexture.js
src/interaction/InteractionManager.js

Cleans some `export default`s to be on the item they export rather than declared later.

cleanup some export defaults

---

src/core/renderers/webgl/managers/FilterManager.js

filter clamp was wrong

---

src/core/display/Container.js

addChildAt index

---

src/core/sprites/Sprite.js

onAnchorUpdate function is private with underscore

onAnchorUpdate function is private with underscore

---

src/core/display/TransformBase.js
src/core/renderers/webgl/managers/FilterManager.js

+ parentID did not belong to hidden class
+ filter import problem

_parentID was not in the class. Hidden class problem

---

package.json

I find it extremely useful to have an easy to access npm command to do the automatic eslint fixes

Adding npm command 'lintfix'

---

src/index.js

Corrected some minor typos in index.js because I'm anally retentive

---

src/extras/TilingSprite.js

Resolves #3051.
Not sure if it's addressed in #3048 - @ivanpopelyshev?

Added TilingSprite.getLocalBounds

---

src/core/display/Container.js

Its ok to add child in the end of array.
Actually, it will work even without this "if", <0 will have same result as 0, and >length will be the same as length, its how splice works :)

Improvement of PR #3053

---

src/core/const.js
src/core/textures/BaseTexture.js
src/core/utils/index.js
test/core/util.js

Replace url extension regex

---

test/core/Container.js

Some other functions also remove a child from parent, so I included those also.

Complete addChildAt test coverage

---

test/.eslintrc.json
test/core/Matrix.js
test/core/ObservablePoint.js
test/core/Point.js
test/core/index.js

* Adds unit-tests for Point, ObservablePoint and some Matrix
See issue: #3047

Adds unit tests for Point, ObservablePoint, Matrix

---

src/core/textures/Texture.js

#3090: Putting this out here. After encountering #3085 this is what I found. Please feel free to revise as needed, as I admit my knowledge on the matter is limited. I hope it helps someone else.

Update docs: issue #3085

---

src/extras/getGlobalPosition.js
test/core/getGlobalPosition.js
test/core/index.js

Fixes for #2791 , with tests

---

src/core/sprites/Sprite.js
src/extras/TilingSprite.js
test/core/Sprite.js
test/core/TilingSprite.js
test/core/index.js

TilingSprite bounds fixes

---

src/core/textures/Texture.js

https://github.com/pixijs/pixi.js/issues/3100

Fixes Texture.from variable error

---

src/core/textures/Texture.js

Revert "Fixes Texture.from variable error"

---

src/core/textures/Texture.js

Revert "Revert "Fixes Texture.from variable error""

---

.eslintrc.json
src/core/display/Container.js

No new arrays being created here! Also tweaked the eslintsrc to   allow
us to not have to use rest.

faster add child #3152

---

src/core/math/shapes/Polygon.js

This might also fix issue #3151

fixes issue #3155 - Polygon.contains not working

---

src/core/math/shapes/RoundedRectangle.js
test/core/RoundedRectangle.js
test/core/index.js

Fixing #1889, also added test.
It isn't 100% accurate, but better than current.

Fixed RoundedRectangle.contains()

---

src/core/math/shapes/Rectangle.js

Update Rectangle.js small typo in api doc

---

src/loaders/spritesheetParser.js

This looks like it is the fix. Couldn't find any tests for loaders..

Fixes issue #2932 trimmed spritesheet

---

src/core/display/Container.js

I wish the parameter names here could be a little more self-documenting - especially for typescript, but alas.

Container add/remove docs

---

src/core/graphics/Graphics.js
test/core/Graphics.js

Custom version of #3196 without trigonometric functions

Fix polygon bounds

---

src/core/renderers/canvas/CanvasRenderer.js
src/extras/TilingSprite.js
src/mesh/canvas/CanvasMeshRenderer.js

BlendMode canvas, http://www.html5gamedevs.com/topic/25832-blend-modes-inside-a-canvas-wich-is-inside-a-java-webview/

Canvas stuff

---

src/mesh/Plane.js
test/core/Plane.js
test/core/index.js

@englercj This adds tests around mesh.Plane, as well as fixes for non loaded textures, per #3145

Fixes for mesh.Plane texture loading

---

src/core/renderers/webgl/WebGLRenderer.js
src/core/sprites/webgl/SpriteRenderer.js
src/extras/webgl/TilingSpriteRenderer.js
src/mesh/webgl/MeshRenderer.js
src/particles/webgl/ParticleRenderer.js

Fixed a little issue where the same texture could end up being bound in
different locations.
Added a smartBindTexture function that finds a the best texture slot
(its pretty basic at this stage!)

Dev texture states

---

src/core/graphics/Graphics.js

This changed from v3 to v4, we reverted back and it fixed arcs in our application.

Fix anticlockwise sweep calculation

---

test/core/Polygon.js
test/core/index.js

Added some polygon tests.
What should be done about [this](https://github.com/staff0rd/pixi.js/blob/480cbbaa1f80ce36db05b768aab660bb21406612/test/core/Polygon.js#L109)?

Polygon tests

---

src/core/utils/index.js
test/core/util.js

expose isMobile (PIXI.utils); added tests to core/util

---

.eslintrc.json
src/core/graphics/webgl/utils/buildRectangle.js
src/mesh/Mesh.js
src/mesh/Rope.js
src/mesh/webgl/MeshRenderer.js

- Recreate Types arrays in rope if the size changes
- Fixed a little rope dirty issue too where it was being set to false
rather than incremented.
- Pass the data to buffer when calling upload as this will resize the
buffers automatically

Fixes issue where rope breaks if it changes size

---

src/core/const.js
src/core/display/Container.js
src/core/graphics/webgl/GraphicsRenderer.js
src/core/renderers/webgl/WebGLRenderer.js
src/core/renderers/webgl/managers/FilterManager.js
src/core/renderers/webgl/utils/Quad.js
src/core/sprites/webgl/SpriteRenderer.js
src/core/utils/canUploadSameBuffer.js
src/extras/webgl/TilingSpriteRenderer.js
src/mesh/webgl/MeshRenderer.js

Even more caching! even less webGL calls :D
This PR builds on #3201 and reduces GL calls even further by added a bindVAO function to the renderer.

Dev vao state cache

---

src/core/sprites/webgl/SpriteRenderer.js
test/core/SpriteRenderer.js
test/core/index.js

SpriteRenderer.destroy() was failing - looks related to #3201

SpriteRenderer.destroy fix

---

package.json
src/core/graphics/Graphics.js

Just a small update merge to ensure `dev` has the latest `master` changes.

Merge master -> dev

---

src/particles/webgl/ParticleBuffer.js
src/particles/webgl/ParticleRenderer.js

Open this one: http://pixijs.github.io/examples/?v=dev#/demos/batch.js
Then copy&paste this:
```js
var renderer = PIXI.autoDetectRenderer(800, 600);
document.body.appendChild(renderer.view);
// create the root of the scene graph
var stage = new PIXI.Container();
var sprites = new PIXI.particles.ParticleContainer(10000, {
scale: true,
position: true,
rotation: true,
uvs: true,
alpha: true
});
// create a texture from an image path
var texture = PIXI.Texture.fromImage('required/assets/basics/bunny.png');
for (var i=0;i<5;i++) {
bunny = new PIXI.Sprite(texture, 40, 40);
bunny.position.set(i*50, i*50);
stage.addChild(bunny)
}
stage.addChild(sprites);
for (var i=5;i<10;i++) {
bunny = new PIXI.Sprite(texture, 40, 40);
bunny.position.set(i*50, i*50);
stage.addChild(bunny)
}
// create a new …
```

ParticleRenderer vao fix

---

src/mesh/webgl/MeshRenderer.js

Mesh created extra vao

---

src/core/renderers/webgl/managers/FilterManager.js

fixes issue where texture id my be incorrect

little filter-fix

---

src/core/sprites/webgl/SpriteRenderer.js

That's our iOS bug. I suggest to re-publish 4.2.1 ASAP

vertexCount is number of last used buffer

---

src/core/const.js
src/core/settings.js
src/core/sprites/webgl/SpriteRenderer.js

I really dont know what to do with TODOs

move CAN_UPLOAD_SAME_BUFFER to settings

---

src/core/renderers/SystemRenderer.js
src/core/renderers/webgl/TextureGarbageCollector.js
src/core/renderers/webgl/utils/RenderTarget.js
src/core/sprites/webgl/SpriteRenderer.js
src/core/text/Text.js
src/core/textures/BaseTexture.js
src/core/ticker/Ticker.js

Discovered that using this kind of code:
```const { MY_SETTING } from settings;```
means that changing settings properties has no effect as the objects
are being set before the user changes them.

fixed settings not being respected

---

README.md

* Removes the broken image from the README file.

Removes broken image from README

---

src/core/display/Transform.js
src/core/display/TransformStatic.js
src/core/math/Matrix.js
test/core/TransformStatic.js
test/core/index.js

Fix for order of skew and scale in transform, plus a test

---

src/core/graphics/Graphics.js
test/core/Graphics.js

Fixed the issue #3343 
Added a test case, it catches the bug, but it is not very obvious as test should be. So if you have any suggestions i will modify/remove it.
All tests pass, new build works (use for my project now), and lint is satisfied. 😄

fix/graphics: get points for newly created shape (#3433)

---

test/core/getLocalBounds.js

f23b286 is the real change - the test passes without it so I assume its not needed.

Reduce Graphics.getlocalBounds test

---

src/core/graphics/Graphics.js
test/core/getLocalBounds.js

Graphics - getLocalBounds after generateCanvasTexture

---

src/loaders/loader.js

Extend loader docs to show loading more than just images

---

test/core/Ellipse.js
test/core/index.js

Hey there, ready for a review. Added the Ellipse math object methods tests following convention from other shapes.
Let me know if this needs changed in any way - happy to do so. My second ever OSS PR! Woohoo!
Thanks,
Geordi

Add Ellipse method unit tests

---

src/core/sprites/Sprite.js
src/extras/TilingSprite.js
src/mesh/Mesh.js

Customize rendering process with "pluginName" field.

---

src/core/display/Transform.js

_ removed for non observable points

fix for regular transform

---

src/core/display/Transform.js

Change the lines order in updateTransform for unified style
see 
https://github.com/pixijs/pixi.js/pull/3404
https://github.com/pixijs/pixi.js/pull/3391

Change the lines order in updateTransform.

---

src/mesh/Mesh.js

Format some codes.
Haven't changed any logic.

Code Formatting

---

src/core/sprites/webgl/SpriteRenderer.js

Update annotation: `SpriteBatch to SpriteRenderer`

---

src/extras/TextureTransform.js

docs fix for TextureTransform

---

src/core/text/Text.js

Remove the needless assignment operation.

Less codes , Less assignment operations.

---

test/interaction/InteractionManager.js
test/interaction/MockPointer.js

* Added MockPointer
* This class will eventually be expanded to include all mouse/touch/pointer event simulations
* Added onTap tests

Added MockPointer

---

src/core/renderers/webgl/managers/FilterManager.js

Fixes a couple of issues experienced when stacking filters.
1 - fixes bound textures going out of sync
2 - fixes occasional no clearing of renderTargets

fixed some filter issues with textures not clearing correctly

---

src/extras/BitmapText.js

Fixes https://github.com/pixijs/pixi.js/issues/3461

Ensures textWidth and textHeight values are accurate for BitmapText

---

src/core/renderers/webgl/TextureManager.js
src/core/renderers/webgl/WebGLRenderer.js

does what it says on the tin!
Please give this a test!

fix for invalid texture

---

src/mesh/webgl/MeshRenderer.js

Fix  https://github.com/pixijs/pixi.js/issues/3453 .

Rebind vao before glData upload.

---

src/extras/TilingSprite.js
src/extras/webgl/TilingSpriteRenderer.js

Fix for #3536
ping @ivanpopelyshev

Fixes #3536

---

src/core/Application.js
src/core/autoDetectRenderer.js
src/core/index.js

Setting up a new PIXI scene often requires a few steps: setting up a `requestAnimationFrame` or `Ticker`, creating a `PIXI.Container` and creating the renderer. I would like to improve this experience by creating a very simple API for setting up PIXI, as well as create something that is extendable and object-oriented.
```js
// creates the renderer, root and ticker
const app = new PIXI.Application();
// Add the view to the DOM
// ex, add display objects
const graphic = new PIXI.Graphics();
graphic.beginFill(0xff0000).drawRect(0, 0, 100, 100);
app.stage.addChild(graphic);
```
http://pixijs.download/application/docs/PIXI.Application.html
https://jsfiddle.net/9s002r34/

Creates new PIXI.Application class

---

src/mesh/Rope.js

More detail see : https://github.com/pixijs/pixi.js/pull/3457

Remove needless `Number()` call (on dev branch)

---

src/core/renderers/webgl/managers/MaskManager.js

added check for root

---

src/core/sprites/Sprite.js

I already ask a question about this  https://github.com/pixijs/pixi.js/issues/3408  , but no one reply .
I think opening PR is better than asking question.

Do check as same as `calculateVertices`

---

src/core/graphics/canvas/CanvasGraphicsRenderer.js

Updated link #3368

---

src/core/math/shapes/Rectangle.js
test/core/Rectangle.js

Converted to arrow functions
Added new tests and new cases to existing tests
Removed unreachable ternary in Rectangle.pad()
Fixed invalid comparison in Rectangle.enlarge()
Changed param name in Rectangle.enlarge(rectangle) to match other methods
Can anyone help me with the expected functionality of the Rectangle.fit(rectangle) method?  I'm not sure I understand its purpose sufficiently to write a test.

Rectangle test updates

---

test/core/BaseTexture.js
test/core/Container.js
test/core/DisplayObject.js
test/core/Graphics.js
test/core/Polygon.js
test/core/SpriteRenderer.js
test/core/TransformStatic.js
test/core/util.js

Per https://github.com/pixijs/pixi.js/wiki/Unit-Tests

Preserve mocha scope

---

src/core/Application.js
test/core/Application.js
test/core/index.js

* Adds a `destroy` method to the new Application API to cleanup the container, renderer and ticker instances.

Adds destroy method to Application

---

src/core/graphics/Graphics.js
src/core/renderers/canvas/CanvasRenderer.js

does exactly what it says on the tin! #3446

Fix for generateCanvasTexture() #3446

---

src/core/text/Text.js
src/core/text/TextStyle.js
src/core/utils/trimCanvas.js

Allows `PIXI.Text` to be trimmed of transparency for better layouts.
Opt in only;
~~~javascript
new PIXI.Text('my text', null, null, true);
~~~
https://codepen.io/staff0rd/pen/KaVdXZ?editors=0010

Trimmed text

---

src/core/text/Text.js
test/core/getLocalBounds.js

Fixed local bounds issue with text

---

src/core/graphics/webgl/utils/buildCircle.js

Fixed issue where radius of circle may be 0

---

src/extras/TilingSprite.js

#3645
It turns out, people are using that mode, so we need implementation for Canvas2d.
I tested it in pixi-examples window, its safe to merge.

uvRespectAnchor for CanvasRenderer

---

src/extras/cacheAsBitmap.js

Doc update

---

src/core/sprites/Sprite.js
src/core/text/TextStyle.js

Minor doc fixes

---

src/core/display/Container.js

When add or remove child , the flags should be changed.

Add missing 'flag updating'

---

src/prepare/BasePrepare.js
src/prepare/canvas/CanvasPrepare.js
src/prepare/webgl/WebGLPrepare.js

Putting into right namespace, and updating the list of things you can upload for clarity

Prepare docs fix

---

src/interaction/InteractionManager.js

Marks the interaction events as being of the type PIXI.interaction.InteractionData

---

test/core/Container.js

Supports #3640, which should be merged for these tests to pass.

Added container recalc transform tests

---

src/core/graphics/Graphics.js
src/core/graphics/GraphicsData.js
src/core/graphics/webgl/GraphicsRenderer.js
src/core/graphics/webgl/utils/buildLine.js

Hi everyone!
Some time ago I was trying to make a galactic game map with pixi and I had a problem. The width of the lines increase with the scale of the container. The only way to maintain the correct width in screen was to recreate the line every time. After some research I created a patch for pixiv3 that used gl.LINE to draw the 1px lines https://github.com/DavidBM/pixi-nativeGLline
Now, with the version 4 is impossible to apply this kind of patches. Then I thought, "hey! why a path? Better a pull request!"
And this is the pull request :D
This patch adds a new method to the graphics object (drawNative) that accepts only one parameter (native). If this parameter is true, the next lines will be draw using GL_LINE instead of GL_TRIANGLE_STRIP. 
This have an advantage, is faster than …

add nativeLine method in graphics

---

src/core/Application.js
src/core/renderers/webgl/filters/Filter.js

see http://pixijs.download/release/docs/PIXI.Filter.html
members aren't present there
I've checked other classes, they seem to be OK

Incorrect export causing docs generator to miss members

---

src/core/const.js

when i translate the documentation into chinese,i find this strange word,so :)

a wrong word

---

test/interaction/InteractionManager.js

Testing events added to the correct place in DOM.  
Will add mouse/touch soon.

InteractionManager.addEvent tests

---

src/core/graphics/webgl/utils/buildRoundedRectangle.js

Just a really small thing really, to prevent creating unnecessary functions instance. I have to admit I'm trying to get in the slack channel...

Minor optimisation of quadratic bezier curve calculation.

---

src/extras/TextureTransform.js
src/extras/webgl/TilingSpriteRenderer.js
src/mesh/webgl/MeshRenderer.js
src/prepare/limiters/CountLimiter.js
src/prepare/limiters/TimeLimiter.js
test/interaction/MockPointer.js

Linting issues are blocking release.

Fixes linting issues on master

---

src/core/renderers/webgl/WebGLState.js

Fixed crash in WebGLState::push().

---

src/core/textures/BaseTexture.js
src/core/textures/Texture.js

* Add BaseTexture.from().
* Support create BaseTexture from HTMLImageElement.
* Support BaseTexture cache.

Add BaseTexture.from() & fix a bug of `Texture.from`

---

src/core/sprites/Sprite.js

Reason:
* Do similar things in similar way :  compute left / top , then add width/height .
* A very very very very (...* 1000000) bit little performance improvement :  one `-` & one `*` become one `+`.
* fix some words in document.

Improve the logic about calculate vertices

---

src/loaders/loader.js

To match `resource-loader` actual version.

Updated PIXI.loaders.Loader docs

---

src/core/settings.js

Sometimes ，this PR could fix https://github.com/pixijs/pixi.js/issues/3755 .
Maybe this PR is better than https://github.com/pixijs/pixi.js/pull/3756.

Improve the accuracy of RETINA_PREFIX

---

test/core/Circle.js
test/core/Ellipse.js
test/core/Matrix.js
test/core/TilingSprite.js

Added matrix tests for prepend() and identity() functions.
Added contains if-branch tests on Ellipse and Circle shapes for 100% coverage. 
Added TilingSprite test for containsPoint true and false paths.
Added TilingSprite test for height and width getters and setters.

Added core tests for Matrix, Ellipse, Circle and TilingSprite

---

src/interaction/InteractionTrackingData.js
src/interaction/interactiveTarget.js

Done!
By the way, eslint has this rule: http://eslint.org/docs/rules/valid-jsdoc for (simple) jsdoc validation. If you want, I can do a PR with it :)

Fixed issue #3774

---

test/core/index.js

Reference polygon tests

---

src/interaction/interactiveTarget.js

Expose interactive member docs

---

src/loaders/spritesheetParser.js

Support for root-relative path in Spritesheet's image loading (#3715)

---

src/interaction/InteractionManager.js
test/interaction/InteractionManager.js

Fix #3790, which was caused by an improper bit flag check. Added a unit test to catch it in the future.

Fix #3790 and add unit test

---

src/interaction/InteractionManager.js
test/interaction/InteractionManager.js

Fixed a different issue that was helping cause mouseups to trigger clicks without mousedowns.

Fix another issue that was causing #3790

---

src/mesh/Mesh.js
src/mesh/NineSlicePlane.js
src/mesh/Plane.js

The bugs is talked in https://github.com/pixijs/pixi.js/pull/3842

Fix some bugs  about new mesh moudel.

---

src/core/textures/Texture.js

WHITE and EMPTY weren't truly clean textures

---

src/interaction/InteractionManager.js
test/interaction/InteractionManager.js

Fixed further problem as reported in #3851. Also undid the constants added in #3857 because there was actually a simpler way to handle that.

Further fix interaction issues related to nesting and display tree positioning

---

src/core/renderers/webgl/filters/Filter.js
src/core/renderers/webgl/managers/FilterManager.js

previously known as "dontFit" and "fitToDestination"

autoFit temporary fix

---

src/core/Application.js
src/core/const.js
src/core/textures/VideoBaseTexture.js
src/core/ticker/Ticker.js
src/core/ticker/TickerListener.js
src/core/ticker/index.js
src/extras/AnimatedSprite.js
src/interaction/InteractionManager.js
src/prepare/BasePrepare.js
test/core/Ticker.js
test/core/index.js

Inspired by @drkibitz’s comment https://github.com/pixijs/pixi.js/issues/3835#issuecomment-287284349. This adds an optional priority argument to `Ticker.prototype.add(fn, context, priority)` and `Ticker.prototype.addOnce(fn, context, priority)`. This also adds unit-tests for the Ticker class.
This should address #3835.

Adds Ticker priority argument

---

src/core/settings.js
src/core/ticker/index.js
src/core/utils/index.js
src/extract/index.js
src/filters/index.js
src/loaders/index.js
src/prepare/index.js

Follow-up to #3876
* Adds code samples for namespaces.
https://pixijs.download/docs-examples/docs/index.html

Adds namespace code examples

---

src/core/renderers/webgl/filters/filterTransforms.js
src/core/renderers/webgl/utils/Quad.js
src/interaction/InteractionEvent.js
src/mesh/Mesh.js
src/mesh/Rope.js

* Restores some missing properties for Quad, Rope and InteractionEvent not showing up because of improper JSDoc block formatting.
**Current Dev (broken)**
* [Quad](http://pixijs.download/release/docs/PIXI.Quad.html)
* [InteractionEvent](http://pixijs.download/release/docs/PIXI.interaction.InteractionEvent.html)
* [Rope](http://pixijs.download/release/docs/PIXI.mesh.Rope.html)
**This PR (fixed)**
* [Quad](http://pixijs.download/fix-missing-docs/docs/PIXI.Quad.html)
* [InteractionEvent](http://pixijs.download/fix-missing-docs/docs/PIXI.interaction.InteractionEvent.html)
* [Rope](http://pixijs.download/fix-missing-docs/docs/PIXI.mesh.Rope.html)

Fixes missing docs

---

src/core/text/Text.js

Fixes: https://github.com/pixijs/pixi.js/issues/3946

Fixes text gradient when there is a stop point is set to 0

---

src/index.js

* Supports excluding deprecations from the building: `npm run dist — -e deprecation`
Addresses #3954

Fixes #3954 support excluding deprecations

---

README.md

Fixes #3979
Also, bumped the CDN version to the latest.

Removes Bower mention from README

---

src/extras/index.js

I think i lost it in one of PR's

return of TextureTransform

---

src/mesh/NineSlicePlane.js

NineSlicePlane didnt work properly with 4.5 mesh

---

src/mesh/Plane.js

Fix the bug that talk about  at  https://github.com/pixijs/pixi.js/pull/3842#issuecomment-299017773

Change the order of `refreshDimensions()`

---

src/extras/AnimatedSprite.js
src/extras/TilingSprite.js

omg, even textures weren't destroyed! Fixes #3994

TilingSprite destroy fix

---

src/core/sprites/canvas/CanvasSpriteRenderer.js
src/core/sprites/canvas/CanvasTinter.js

Fix for #3972. Modifies the cached tinted frame of a texture in canvas.

fix for #3972

---

src/particles/ParticleContainer.js
src/particles/webgl/ParticleRenderer.js
src/particles/webgl/ParticleShader.js

Applies tint to whole particle container.

Apply Tint to Particle Container (#3899)

---

src/core/graphics/Graphics.js

Addresses #4019
**Broken** : https://jsfiddle.net/ed6zpLtj/
**Fixed**: https://jsfiddle.net/frzjy4vx/

Fixes the padding for Graphics

---

src/loaders/index.js
test/core/Application.js

Addresses #4017 
Adds additional unit-test for removing view.

Fixes Application overriding destroy not removing view

---

test/core/Graphics.js

Adds unit-test for #3976 
2045fe4 (should fail)
205a96c (should pass)

Adds unit-test for Graphics hole

---

src/mesh/webgl/MeshRenderer.js
src/particles/webgl/ParticleRenderer.js

Yes, I made some mistakes with _tintRGB and tintRGB. Both ParticleContainer and Mesh were screwed.

DERP! tintRgb now without _, its a legal property

---

src/core/utils/index.js
src/extras/webgl/TilingSpriteRenderer.js

Yeah, once again BlendModes and tint makes me suffer.

TilingSprite derp

---

src/core/renderers/canvas/CanvasRenderer.js
test/core/CanvasRenderer.js
test/core/WebGLRenderer.js
test/core/index.js

Fixes https://github.com/pixijs/pixi.js/issues/4045

Fixes clear error on CanvasRenderer with no child container

---

src/deprecation.js

Fixes: https://github.com/pixijs/pixi.js/issues/3710

deprecation.js now works with modules excluded at build time

---

src/extras/BitmapText.js

Fixes: https://github.com/pixijs/pixi.js/issues/3853

Changed BitmapText max width to be a setter

---

test/core/Rectangle.js

subject. Was sleep-coding, found something strange.

Tests: fix negative width/height of rectangle

---

src/extras/AnimatedSprite.js

As requested by https://github.com/pixijs/pixi.js/issues/4072

Adds an onLoop callback for AnimatedSprites

---

src/core/renderers/webgl/WebGLRenderer.js

doc fix for renderer.bindTexture

---

src/core/sprites/Sprite.js
src/extras/TilingSprite.js
test/core/Sprite.js
test/core/TilingSprite.js

Fixes #3205. Thanks to @opty2001.

Fix Sprite.containsPoint edge handling

---

src/core/renderers/SystemRenderer.js
src/extras/TilingSprite.js
src/extras/webgl/TilingSpriteRenderer.js
src/mesh/webgl/MeshRenderer.js
src/particles/webgl/ParticleRenderer.js

I'll make a few commits, then we'll review it in a batch.

Cleaning the code

---

src/core/math/shapes/Rectangle.js
src/core/textures/Texture.js
test/core/Rectangle.js

Minor improvement for #4150.
Regards.

Includes the sum in the error thrown when trying to create a texture

---

src/extras/webgl/tilingSprite.frag
src/extras/webgl/tilingSprite_simple.frag

I don't know how did I miss it :) Thanks @bigtimebuddy for https://jsfiddle.net/2bLnu0b5/ 
This one is tested.

fix tilingSprite alpha tint

---

src/extras/AnimatedSprite.js
src/particles/ParticleContainer.js

Just two small mistakes I noticed reading the documentation.

Two small grammar fixes

---

src/core/renderers/webgl/managers/StencilManager.js

https://github.com/pixijs/pixi.js/issues/2559
https://github.com/pixijs/pixi.js/issues/2877

Fixed issues with overlapping shapes in masks for WebGL

---

src/core/renderers/webgl/filters/Filter.js
src/filters/blur/BlurFilter.js

make blendMode a property with documentation, pass it to inner filter

fix blendMode on blurFilter

---

src/core/sprites/Sprite.js

I dont know if its a crit.
#4175

Sprite getLocalBounds derp

---

README.md
package.json

* Doc badge was broken
* Updates “our website” to pixijs.com
* Updates new filter example
* Fixes link to User Plugins
* Updates description and tagline to match website

Improvements and fixes to README

---

src/core/renderers/canvas/CanvasRenderer.js
src/core/renderers/canvas/utils/CanvasMaskManager.js
src/core/sprites/canvas/CanvasTinter.js
src/mesh/canvas/CanvasMeshRenderer.js
src/particles/ParticleContainer.js

Fixed an issue in CanvasRenderer where globalCompositeOperation is being changed without _activeBlendMode being updated.

Wrong blendMode in CanvasRenderer

---

README.md

Also I made this branch by mistake, will remove it soon :)

There's no resources page in wiki.

---

src/core/text/TextMetrics.js
src/core/text/TextStyle.js

add leading support to add extra space between lines before renderer measuring. it's different from lineHeight but based on lineHeight.

leading support

---

src/core/text/TextStyle.js

https://github.com/pixijs/pixi.js/issues/4197
Example should show up at http://pixijs.download/text-style-docs/docs/PIXI.TextStyle.html once travis has finished it's thang

Adds docs for TextStyle getters and setters

---

src/core/renderers/webgl/managers/StencilManager.js

Test case: https://jsfiddle.net/x1zq0xbd/

Fixed nested stenicl masks not rendering correctly

---

src/core/renderers/webgl/filters/filterTransforms.js

Don't use ratio and there wont be such problem. Now, where is my beer?
I tested it. Also, improved version for projections is here: https://github.com/pixijs/pixi-projection/blob/master/src/proj2d/z_masks/SpriteMaskFilter.ts#L70

refactor, remove unnecessary operations

---

src/core/renderers/webgl/managers/FilterManager.js

Lowercase on FilterManager type checks

---

src/core/renderers/webgl/filters/Filter.js
src/core/renderers/webgl/managers/FilterManager.js

move toLowerCase into Filter constructor

---

src/particles/ParticleContainer.js
src/particles/webgl/ParticleBuffer.js
src/particles/webgl/ParticleRenderer.js
src/particles/webgl/ParticleShader.js

tint in ParticleContainer

---

src/mesh/NineSlicePlane.js
src/mesh/Plane.js

Fixes #4296
We forgot that some instances aren't booleans.

fixing dirty problem in plane/nineslice

---

src/particles/ParticleContainer.js
src/particles/webgl/ParticleRenderer.js

We will need to improve ParticleContainer later, but that will do for now.
Added autoResize, changed docs.
#4294

particle container docs and resize mode

---

src/core/sprites/Sprite.js
src/extras/AnimatedSprite.js
src/extras/TilingSprite.js

fix canvas sprite texture change

---

src/core/renderers/canvas/CanvasRenderer.js

Consistent Canvas State after render() - 2

---

src/core/renderers/webgl/WebGLRenderer.js

That's for pixi integration with threejs.
Another old thread for threejs is here: https://github.com/pixijs/pixi.js/issues/3230
Basically, if we dont have proper "reset", we can switch between renderers.
WORK IN PROGRESS.
Build will be here: https://pixijs.download/dev-fix-reset/pixi.js

Add textures in reset method

---

src/mesh/Plane.js

dirty as in Rope

---

src/mesh/Mesh.js

More talking about this PR : https://github.com/pixijs/pixi.js/pull/4352

Add default value of  `mesh.texture`

---

src/filters/alpha/AlphaFilter.js

Really don't know how we missed this... 🤔 
http://pixijs.download/alpha-filter/docs/PIXI.filters.AlphaFilter.html

Adds alpha param to constructor of AlphaFilter

---

src/core/renderers/webgl/managers/FilterManager.js

Just looked inside, saw a bug. Lets test it!
#4418 #4420

fix filterManager destroy

---

src/particles/webgl/ParticleBuffer.js
src/particles/webgl/ParticleShader.js

* Clear some properties in `ParticleBuffer.destroy()`.
* improve the shader.

Clear some properties in `ParticleBuffer.destroy()`.

---

src/particles/ParticleContainer.js

Update the docs of ParticleContainer to contain information about possibility to tint individual sprites.
#4463

Update docs of ParticleContainer

---

src/interaction/InteractionManager.js

removed @private from setTargetElement

---

README.md

Updated some code on the readme with ES6 syntax.

Updated readme to include ES6 syntax

---

package.json
src/core/renderers/webgl/WebGLRenderer.js

renderer resets vao correctly.

---

src/mesh/canvas/CanvasMeshRenderer.js

Canvas mesh alpha. Fix for #4534

---

src/core/graphics/GraphicsData.js
src/core/renderers/webgl/filters/filterTransforms.js
src/core/text/TextStyle.js
src/core/utils/index.js
src/extras/AnimatedSprite.js

issue #4539
cleaned up documentation Globals, corrected formatting

cleaned up documentation Globals issue #4539

---

test/loaders/spritesheetParser.js

Fixes a bug where unit-tests fail on Windows. Follow-up to #4573

Fixes unit-tests Windows bug

---

packages/core/src/renderers/Renderer.js
packages/core/src/renderers/systems/textures/TextureGCSystem.js
packages/core/src/renderers/systems/textures/TextureSystem.js
packages/sprite/src/SpriteRenderer.js

Fixes all GC-related problems.
Also, I made a mistake, WebGLRenderingContext has `deleteTexture`, not `destroyTexture`. That part in #4589 was wrong.

[next] Fix Garbage Collector

---

packages/canvas/canvas-mesh/package.json
packages/canvas/canvas-mesh/src/CanvasMeshRenderer.js
packages/canvas/canvas-mesh/src/Mesh.js
packages/canvas/canvas-mesh/src/index.js
packages/canvas/canvas-mesh/src/settings.js
packages/mesh/src/Mesh.js
packages/settings/src/settings.js

v5 Port of #4549
Also:
* Adds some more documentation for Mesh that was removed
* Fixes documentation with settings

[next] Fixes Mesh canvasPadding default  setting (#4549)

---

src/core/display/DisplayObject.js

Exists within Graphics class, but saw it was never actually set anywhere.

Correct set "isMask" property

---

src/core/display/Container.js
test/core/Container.js

Add supplied index to setChildIndex error message. Test updated.

Improve setChildIndex error message

---

packages/mesh/src/Mesh.js

Fixed issue where uTransform was not being set causing uvs to be calculated incorrectly

---

src/core/math/Matrix.js

fix #4654  comment mistake in Matrix.js

fix comment mistake for matrix.js

---

package.json
src/core/utils/index.js
test/core/util.js

Expose earcut dependency in PIXI.utils

---

packages/core/src/textures/BaseRenderTexture.js

does what it says on the tin. Easy fix!

Fixed up resolution issue with RenderTexture

---

packages/core/src/renderers/systems/filter/FilterSystem.js

Fix issue with nested filters

---

packages/settings/src/settings.js

Lets enable webGL 2, petty stable!

WebGL 2 Lets do it :)

---

packages/core/src/renderTexture/RenderTextureSystem.js

Lovely filters with lovely resolutions!

Fixes resolution issue with filters

---

README.md
bundles/pixi.js-legacy/README.md
bundles/pixi.js/README.md

Update the banner in the read me to be v5. Example:

[next] Use "v5" in banner

---

src/core/renderers/webgl/managers/FilterManager.js

@themoonrat found a problem in https://github.com/pixijs/pixi.js/pull/4682

Double resolution multiplication bug

---

src/core/renderers/webgl/filters/Filter.js

Fixes the default filter resolution to use the proper PIXI.setting

---

src/particles/ParticleContainer.js
src/particles/webgl/ParticleBuffer.js
src/particles/webgl/ParticleRenderer.js

particle container multiple renderers possible fix

---

bundles/pixi.js-legacy/package.json
bundles/pixi.js/package.json

[next] Fixes missing dist files from bundles

---

src/polyfill/Number.isInteger.js
src/polyfill/index.js

Fixes IE11, which doesn't have this functionality (as reported in https://github.com/pixijs/pixi.js/pull/4724)
Before: https://jsfiddle.net/themoonrat/zmmndr00/
After: https://jsfiddle.net/24cjpr2w/2/ (will work when build has finished for this branch)

Adds Number.isInteger polyfill

---

src/core/sprites/canvas/CanvasSpriteRenderer.js

Need to revert #4800 and publish a hotfix. It broke existing functionality. @themoonrat can follow-up with details.

🔥 Reverts #4800

---

packages/core/src/Renderer.js
packages/core/src/System.js
packages/core/src/batch/BatchSystem.js
packages/core/src/context/ContextSystem.js
packages/core/src/filters/Filter.js
packages/core/src/filters/FilterSystem.js
packages/core/src/filters/spriteMask/SpriteMaskFilter.js
packages/core/src/framebuffer/FramebufferSystem.js
packages/core/src/geometry/Geometry.js
packages/core/src/geometry/GeometrySystem.js
packages/core/src/mask/MaskSystem.js
packages/core/src/mask/StencilSystem.js
packages/core/src/projection/ProjectionSystem.js
packages/core/src/renderTexture/RenderTextureSystem.js
packages/core/src/state/StateSystem.js
packages/core/src/textures/TextureGCSystem.js
packages/core/src/textures/TextureSystem.js

Stubbed out a ton of documentation for the systems, runners in PIXI.Renderer. Made a few code stylistic changes for consistency.
Could use some help to fill in the gaps, particularly for private vs readonly properties and public vs private methods. Also, @GoodBoyDigital each system could definitely use a sentence description but I'll need your help with that.
http://pixijs.download/next-system-docs/docs/PIXI.systems.html

[next] Documentation For New Systems in v5

---

packages/core/src/textures/TextureSystem.js
packages/core/src/textures/resources/CompressedResource.js
packages/core/src/textures/resources/autoDetectResource.js
packages/loaders/src/CompressedLoader.js
packages/loaders/src/Loader.js
packages/loaders/src/TextureLoader.js
packages/loaders/src/index.js

* Made a CompressedLoader instead of having both functionality in the TextureLoader
* Cleaned up the documentation to add more links and description
* Support for CompressedResource being created by autoDetectResource

[next] Fixes for Compressed Texture

---

src/core/graphics/Graphics.js
src/core/graphics/GraphicsData.js
src/core/graphics/webgl/utils/buildCircle.js
src/core/graphics/webgl/utils/buildLine.js

No allows you to specify if a line is inner or outer aligned. 0 =
inner, 1 = outer, 0.5 = middle (default)
Fun for all :D

Added Line alignment property to lineStyle

---

src/core/graphics/Graphics.js
src/mesh/Mesh.js

I havent tested it yet.
`if` for `data.destroy` exists for renderer plugins for mesh.
#4891

vao leak in Mesh and Graphics

---

bundles/pixi.js/pixi.js.d.ts

Dont merge yet, there will be more entries.

Cumulative typings update

---

src/core/sprites/webgl/SpriteRenderer.js

Fixes #4090, same as #4899 
Credit goes to @YahorPadlucki

SpriteRenderer pseudo-leak

---

README.md

properly capitalized Twitter

---

src/core/renderers/webgl/managers/FilterManager.js

Fixes #3973
Same as #4783 on a diet
At first commit i wrote just one line `currentState.target = null` , then I improved the documentation.
Credit goes to @YahorPadlucki

FilterState target leak

---

src/mesh/Mesh.js
src/mesh/webgl/MeshRenderer.js

This should fix #4037, should not introduce any breaking changes and can be used as an optimization for static meshes.

Add vertexDirty boolean to Mesh, with backwards compatibility flag.

---

bundles/pixi.js/pixi.js.d.ts

Just a little fix to be ok with API documentation

Fix fromBuffer arguments types

---

src/core/sprites/Sprite.js
test/core/Sprite.js

Fixes #4930
Adds a unit-test that fails on **dev**

Fixes Sprite's texture listener not getting removed

---

src/core/text/Text.js
src/core/text/TextStyle.js

I've added a link to it in the docs for both Text and TextStyle as those are the two docs I used.
I'll fully appreciate if you don't accept this on the grounds of link-rot.
Solves issue #4978
Share and Enjoy
Tom

Added links to TextStyle Editor

---

src/core/sprites/Sprite.js

Coerce null to Texture.EMPTY in Sprite.texture

---

src/loaders/bitmapFontParser.js

BitmapFont loader fix

---

bundles/pixi.js/pixi.js.d.ts
packages/core/src/filters/FilterSystem.js
packages/core/src/renderTexture/RenderTextureSystem.js

FilterArea is padded every frame! Lets fix it.

FilterSystem bugfix

---

src/extract/canvas/CanvasExtract.js
src/extract/webgl/WebGLExtract.js

The height and the width of the canvas were 2 times multiplied by the resolution.
http://jsfiddle.net/54zu1y7n/60/

[BUG] Canvas Extract resolution

---

src/mesh/Plane.js

https://github.com/pixijs/pixi.js/issues/4551

Docs to show correct default settings on plane constructor

---

bundles/pixi.js/pixi.js.d.ts
packages/graphics/src/GraphicsData.js

Little fix to make GraphicsData types work like in js source file.

Add missing GraphicsData default param.

---

src/core/textures/VideoBaseTexture.js
test/core/VideoBaseTexture.js
test/core/index.js

Addresses issue #4882 by throwing away the query string (everything after and including the '?')

fix Video type wrongly set

---

.gitignore
packages/core/src/geometry/GeometrySystem.js
packages/core/src/textures/TextureSystem.js

Added a couple of caching layers for binding textures and binding buffers.

Next speedup

---

packages/core/src/filters/FilterSystem.js
packages/core/src/renderTexture/RenderTextureSystem.js
packages/core/src/shader/Program.js

allows you to name your shaders, handy for debugging!

Shaders can now have names

---

package-lock.json
packages/graphics/src/Graphics.js
packages/graphics/src/styles/FillStyle.js
packages/graphics/src/styles/LineStyle.js

I don't like to spawn many objects without prototype.
What if we reduce the number a bit?

[next] Graphics LineStyle refactor

---

src/core/settings.js
src/core/sprites/webgl/generateMultiTextureShader.js

Revert "LOD Bias support for BaseTexture (fixes #2277)"

---

packages/graphics/src/Graphics.js

Bug fix - tint / alpha was broken for non batched graphics objects

---

src/core/display/TransformStatic.js

Thank @Eriksom
Need parallel PR for v5

Transform rotation cache

---

src/core/renderers/webgl/TextureManager.js

Follow-up for #5225
https://www.pixiplayground.com/#/edit/RnH1N_j5H3GaMxiyFxykr

Problem with destroying active framebuffer

---

packages/graphics/src/GraphicsGeometry.js

re enabled graphics batching for next

---

src/core/textures/BaseRenderTexture.js
src/core/textures/RenderTexture.js

Fixes old examples for BaseRenderTexture & RenderTexture

---

package-lock.json
package.json

Bumps earcut to 2.1.4

---

packages/canvas/canvas-mesh/src/CanvasMeshRenderer.js
packages/canvas/canvas-mesh/src/Mesh.js
packages/canvas/canvas-mesh/src/MeshMaterial.js
packages/canvas/canvas-mesh/src/SimpleRope.js
packages/canvas/canvas-mesh/src/index.js
packages/core/src/textures/TextureMatrix.js
packages/display/src/Bounds.js
packages/display/src/DisplayObject.js
packages/mesh/src/Mesh.js
packages/mesh/src/MeshBatchUvs.js
packages/mesh/src/MeshMaterial.js
packages/mesh/src/index.js

Test it here: https://www.pixiplayground.com/#/edit/b0RAyPYeQobRMwa2aMQ~T
Build: https://pixijs.download/next-mesh-fix/pixi-legacy.js
Unlike default rope example, this thing also changes the texture matrix every frame.
Things to check:
1. `forceCanvas`
2. `batchable`
3. `app.stage.alpha`
4. `tick += 0.1`
5. `tick2 += 0.1;`
6. `PIXI.settings.MESH_CANVAS_PADDING`

[next] Fix mesh TextureMatrix and CanvasMeshRenderer

---

packages/filters/filter-blur/src/BlurFilter.js

https://www.pixiplayground.com/#/edit/OHdg4QdmL3FAEnMmnqP0z
suddenly, v4 bug, i dont know how to fix it yet, maybe clamping: https://www.pixiplayground.com/#/edit/yOsbHL0kmqpjC918jgT2c

blurFilter does not clear the result in case of several filters

---

src/core/graphics/GraphicsData.js

Adds missing to clone prop for alignment

---

packages/core/src/filters/Filter.js
packages/core/src/filters/defaultFilter.frag
packages/core/src/filters/defaultFilter.vert
packages/filters/filter-blur/src/generateBlurVertSource.js

Also, remove unused uniform from BlurFilter

Make default filter work like in v4

---

packages/core/src/textures/TextureMatrix.js
packages/mesh-extras/src/NineSlicePlane.js
packages/mesh-extras/src/SimpleMesh.js
packages/mesh-extras/src/SimplePlane.js

First PR in 2019 :)
Fixes https://github.com/pixijs/pixi.js/issues/5312 and other possible NineSlicePlace bugs.
https://www.pixiplayground.com/#/edit/w1XiifwuHEmeG95ZwFr6r
Build: https://pixijs.download/dev-mesh-texture/pixi.js

TextureMatrix and SimplePlane texture change fix

---

packages/canvas/canvas-extract/src/CanvasExtract.js
packages/extract/src/Extract.js

Fixes typos

---

packages/core/src/textures/Texture.js
packages/text/src/Text.js

Small fix in Text

---

packages/sprite-animated/src/AnimatedSprite.js

Callback functions were not being nulled

Animated Sprite does not full destroy properly

---

packages/graphics/src/GraphicsGeometry.js

Fixes #5400
We have a bug in batch group pool.
Fixed fiddle: https://jsfiddle.net/Hackerham/6xvg4L18/

Fix non-batched graphics.

---

packages/core/src/textures/resources/ImageResource.js

Fixes #5402. 
We cant remove bitmap before other renderer gets it, or the cycle will be started: first renderer uploads bitmap to GPU and removes bitmap, second starts creation of another bitmap that leads to update of `dirtyId`.
Demo: https://www.pixiplayground.com/#/edit/D18Qp4tpdFKfdN6~gcyql
Try comment the line with function override and see how 5.0.0-rc doesnt work with two renderers.

MultiRenderer async problem

---

packages/core/src/Renderer.js

Renderer docs

---

packages/core/src/filters/FilterSystem.js
packages/core/src/renderTexture/RenderTextureSystem.js

subj.
Proof that filters work: https://www.pixiplayground.com/#/edit/ZLTblGp99em2n1fqT~NGF

Rename `renderTexture` field to `current`, like in FramebufferSystem

---

packages/core/src/filters/spriteMask/SpriteMaskFilter.js

Fourth param affects the case with multiple filters: https://www.pixiplayground.com/#/edit/4zAeNxu0PYGhHMFYt~FQm

SpriteMaskFilter clear param

---

packages/core/src/mask/MaskSystem.js

Thanks to @bigtimebuddy for the demo! It works on both v4 and v5.
https://pixiplayground.com/#/edit/0FMtqLQIUyNB91SKORFeL

SpriteMask filterArea 1-frame lag

---

src/core/renderers/webgl/managers/MaskManager.js

#5444 copy for v4.
https://pixiplayground.com/#/edit/0FMtqLQIUyNB91SKORFeL

[v4.x] mask filterArea 1-frame lag

---

src/core/renderers/webgl/WebGLRenderer.js

V4.x reset textures

---

package-lock.json
packages/core/src/textures/resources/VideoResource.js
packages/text/src/TextMetrics.js
packages/ticker/src/Ticker.js
packages/ticker/src/TickerListener.js

Yes, I know that VideoResource Promise passes VideoResource and not void, we can deal with that later, that's a problem with overrides.
Yes, we can move `IFontMetrics` it to namespace TextMetrics if you guys want it.
`update(deltaTime)` has default param value because of override issue.

Fix typings

---

types/loader.d.ts

Spritesheet definition

---

packages/graphics/src/utils/buildLine.js

Fixes #5447 
It does not contain optimizations, it does not remove slice() method, its just a fix.
Buggy: https://www.pixiplayground.com/#/edit/K45xTRXqfExRiZ6VUmx61
Fixed : https://www.pixiplayground.com/#/edit/T9qMUdet4~M1B5vAluucY

Detect close stroke shapes

---

packages/filters/filter-displacement/src/DisplacementFilter.js

Added more documentation about how the displacement filter works.

Added more docs for displacement filter.

---

packages/utils/src/color/hex.js

Provides examples and more explicit information about the color utility functions. Specifically noting that [R,G,B] are floats not uints. 
http://pixijs.download/fix/color-utils-docs/docs/PIXI.utils.html

Provides better documentation for color utilities

---

packages/core/src/shader/Program.js

Mistake in typings

---

packages/graphics/src/GraphicsGeometry.js

Fix for #5495 and maybe #5498
Demo: https://www.pixiplayground.com/#/edit/ry07lOifbUxG1bt85ay2k
Uncomment a line to see that increment works.

Graphics clear

---

packages/graphics/src/Graphics.js

Based on @bigtimebuddy comment from #5462
Original demo : https://www.pixiplayground.com/#/edit/BDm_4pTY_4DUR3X1XvzSV

Graphics closePath()

---

packages/mesh/src/MeshMaterial.js

Fixed #5414
demo: [https://jsfiddle.net/JetLu/n2vtdmrg/](https://jsfiddle.net/JetLu/n2vtdmrg/)

Fixed SimpleMesh tint bug

---

packages/mesh-extras/src/geometry/RopeGeometry.js

Update documentation for RopeGeometry

---

bundles/pixi.js/src/useDeprecated.js
packages/canvas/canvas-graphics/src/Graphics.js

Provide an assist for users implementing v4 canvas features in v5

---

packages/graphics/src/Graphics.js

Port of #5010 for v5.
Original thread: http://www.html5gamedevs.com/topic/42433-graphicsarc-has-weird-artefacts-when-chained/
Original PR author: @fmhdp
It was found thanks to @terrygonguet

Fix arc duplicating points

---

packages/graphics/src/GraphicsData.js
packages/graphics/src/GraphicsGeometry.js

Graphics holes docs fix

---

packages/mesh-extras/src/geometry/RopeGeometry.js
packages/utils/src/data/removeItems.js

Fixes #5541
We need to validate the autogenerated ts files to makes sure it compiles without error.

Resolves TypeScript Errors

---

packages/core/src/geometry/GeometrySystem.js

Fixes #5548
No functional improvements, it just removes stupid warnings.

Cant bind active destroyed vao

---

packages/core/src/geometry/GeometrySystem.js
packages/graphics/src/utils/buildCircle.js
packages/graphics/src/utils/buildRoundedRectangle.js

https://www.dropbox.com/s/zl8yf5te4vo50p3/Screenshot%202019-04-08%2020.01.42.png?dl=0

Fix for rounded rect #5540

---

packages/utils/src/browser/isWebGLSupported.js

Avoid creating a new context each time it's called
https://github.com/pixijs/pixi.js/issues/3076

isWebGLSupported util function is now cached

---

packages/accessibility/src/AccessibilityManager.js
packages/core/src/renderTexture/BaseRenderTexture.js
packages/core/src/renderTexture/RenderTexture.js
packages/core/src/textures/BaseTexture.js
packages/core/src/textures/TextureSystem.js
packages/display/src/Container.js
packages/mixin-get-global-position/src/index.js
packages/particles/src/ParticleContainer.js
packages/sprite-tiling/src/TilingSpriteRenderer.js
packages/text/src/Text.js

Updated the documentation to better reflect the implementation of the function "getGlobalPosition"

Update documentation to show that the parameters of getGlobalPosition are optional and thereby fix the type declaration

---

packages/sprite/src/Sprite.js

Adds missing optional Sprite constructor arg

---

types/loader.d.ts

Fixes typo with Loader types

---

packages/core/src/textures/resources/SVGResource.js

close #5682
Demo: [https://www.pixiplayground.com/#/edit/Og4Qr9Q6w5yyRTepEaNJs](https://www.pixiplayground.com/#/edit/Og4Qr9Q6w5yyRTepEaNJs)
Fixed: [https://www.pixiplayground.com/#/edit/nvtwQS6GOGYzqkmzLPO9T](https://www.pixiplayground.com/#/edit/nvtwQS6GOGYzqkmzLPO9T)

Fixes SVGResource can not trigger resize

---

packages/core/src/filters/FilterSystem.js
packages/core/src/renderTexture/RenderTexture.js

Demo: https://www.pixiplayground.com/#/edit/xwiTwNFC3Q8A5iWPHKkOw
Fixed: https://www.pixiplayground.com/#/edit/S7Om1JRG4jqxbLz0oZ9Lu

Change resolution of temp renderTexture for filter

---

packages/core/src/textures/Texture.js

BaseTexture `loaded` event happens before BaseTexture `update`, and due to #5643 texture size is updated on `update` event.
Demo: https://www.pixiplayground.com/#/edit/hT~zMRT2gdccHTZ_EXeej
Fixed: https://www.pixiplayground.com/#/edit/IdFV1nkRYYokJ~TiyWuep

Fix baseTexture loaded event

---

packages/core/src/renderTexture/RenderTexture.js

Subj dedicated to @JohnKarel and @jdelrue .

RenderTexture hint

---

src/core/renderers/webgl/utils/mapWebGLBlendModesToPixi.js

Related to #5739 and #5563
Im trying to contact @Puuca to see if BlendMode breaks his case on iPads

[V4.x] Blendmode ADD again

---

packages/core/src/context/ContextSystem.js
packages/core/src/geometry/GeometrySystem.js

add support for uint32 element index

---

packages/core/src/renderTexture/RenderTextureSystem.js

typings renderTexture bind

---

packages/core/test/Texture.js
packages/particles/src/ParticleContainer.js
packages/prepare/src/BasePrepare.js
packages/sprite/src/Sprite.js

Remove the new keyword before the static method

---

package.json

Addresses https://github.com/englercj/playground/issues/7
Adds support for deploying Typescript typings to pixijs.download
* https://pixijs.download/dev-deploy-types/types/pixi.js.d.ts
* https://pixijs.download/dev-deploy-types/types/pixi.js-legacy.d.ts

Adds support for deploying Typescript typings to pixijs.download

---

packages/core/src/geometry/Geometry.js

Fix JSDoc type of refCount

---

packages/core/src/geometry/GeometrySystem.js
packages/core/src/textures/BaseTexture.js
packages/core/src/textures/GLTexture.js
packages/display/src/DisplayObject.js

Holes in typings found when I was porting https://github.com/pixijs/pixi-tilemap/

More typings

---

packages/utils/src/data/createIndicesForQuads.js

Subj. Follow-up for #5738 . Lets discuss the API.

Make createIndicesForQuads public, add uint32

---

packages/text/src/Text.js

If there is only 1 fill style in the array, then just use that fill, no need to go through creating a gradient for that

Small optimisation with text and gradients

---

packages/core/src/context/ContextSystem.js

one extensions name was wrong, the other extension is actually part of core in webgl2.

webgl2 extension fix

---

packages/canvas/canvas-renderer/src/CanvasRenderer.js

Fix #5815
demo: https://www.pixiplayground.com/#/edit/8n9Jy3acWWJyv9XZRlKm1
fixed: https://www.pixiplayground.com/#/edit/7WcFe0Jrt3HTleIncZLNr

Fix RenderTexture not working on Canvas with pixi-legacy

---

packages/core/src/textures/TextureUvs.js
packages/math/src/GroupD8.js
packages/mixin-cache-as-bitmap/src/index.js
packages/sprite/src/Sprite.js

I've built proper documentation of `GroupD8`. Please check it out!
(Thanks @ivanpopelyshev for telling me about resetting my `gd8-dev` branch to `origin/dev` and then pushing.)

GroupD8 documentation

---

packages/loaders/package.json
packages/loaders/src/Loader.js

Update to the latest version of resource-loader

---

packages/core/src/context/ContextSystem.js
packages/core/src/shader/ShaderSystem.js

Fix #5700 
Wait a few seconds after opening the link.
demo: https://www.pixiplayground.com/#/edit/l8h6NrzSYO6y5g8s84PSk
fixed: https://www.pixiplayground.com/#/edit/5Uk~cUocqKhiktZ451glL

Fix WebGL context cannot be restored

---

packages/graphics/src/Graphics.js

A simple fix to bring documentation into line with the implementation.
- [x ] Documentation is changed or added

Fix inconsistent lineStyle alignment parameter documentation

---

packages/interaction/src/InteractionManager.js

update InteractionManager.setTargetElement typings to HTMLElement

---

packages/canvas/canvas-graphics/src/CanvasGraphicsRenderer.js
packages/canvas/canvas-mesh/src/NineSlicePlane.js
packages/canvas/canvas-renderer/src/CanvasTinter.js

Fix #5889
demo: https://www.pixiplayground.com/#/edit/WF0gD7FRlpVCtvUB8iuWJ
fixed: https://www.pixiplayground.com/#/edit/tCSzOdIh7zj8_om9WEvKs

Fix tint does not work on CanvasRenderer

---

packages/accessibility/src/AccessibilityManager.js

added a 'pointertap' event dispatch to AccessibilityManager

Added 'pointertap' event for accessibility

---

packages/core/src/geometry/ViewableBuffer.js

Minor typings fix for ViewableBuffer

---

packages/core/src/textures/Texture.js
packages/settings/src/settings.js

Fixed a few jsdoc mistakes
References:
https://github.com/pixijs/pixi.js/pull/5537#issuecomment-513457260
https://github.com/pixijs/pixi.js/blob/3630c98f255b2d39ced1909b5cb5d1f70feaaa99/packages/core/src/textures/Texture.js#L596

[FIX] Fix jsdoc

---

packages/core/src/geometry/Geometry.js
packages/display/src/DisplayObject.js

Geometry#_size was redundant, removed!

---

packages/app/src/Application.js

https://github.com/pixijs/pixi.js/issues/5628

Updated docs on app ticker

---

packages/display/src/DisplayObject.js

DisplayObject#getBounds automatically syncs _lastBoundsID, _boundsID

---

packages/canvas/canvas-graphics/src/CanvasGraphicsRenderer.js
packages/graphics/src/GraphicsGeometry.js

Follows https://github.com/pixijs/pixi-spine/issues/307 and http://www.html5gamedevs.com/topic/9374-change-the-style-of-line-that-is-already-drawn/
Broken: https://www.pixiplayground.com/#/edit/LP7TfzH7XSAQ3G02WZ_Mb
Fixed: https://www.pixiplayground.com/#/edit/GYy0QCPK1I62IyCxr2WH1

Support manual changes in GraphicsData

---

packages/core/src/shader/utils/getTestContext.js

Broke dev with #5966
This fixes it.
Verify: https://pixijs.io/examples/?v=fix-test-context-2#/demos-basic/container.js

Fix dev with getTestContext tweak

---

packages/core/src/filters/FilterSystem.js
packages/core/src/renderTexture/RenderTexture.js
packages/core/src/renderTexture/RenderTexturePool.js
packages/core/src/textures/Texture.js

WIP, here'll be demos soon, explaining everything.

RenderTexturePool and FilterSystem changes

---

packages/core/src/textures/BaseTexture.js
packages/core/test/BaseTexture.js

Follow-up for #5959 
Broken: https://www.pixiplayground.com/#/edit/d~jTog12dqKjAY9K1wBmg
Fixed: https://www.pixiplayground.com/#/edit/A_eMpc5bJ5C2M9KuR~wM4
consoleLog should report 15,15 , not 16,16

add eps in ceiling

---

packages/core/src/textures/Texture.js
packages/graphics/src/GraphicsGeometry.js

Texture resolution type missing

---

types/loader.d.ts

More accurate typing is provided for load() method of Loader.

Improve typing for load() function

---

README.md

Adds an open collective donate button to the readme, while removing the reference to the Patreon

Open collective donate button

---

packages/mesh-extras/src/SimpleRope.js

The documentation of SimpleRope was referring to the older Rope.

Fixed documentation of SimpleRope

---

packages/graphics/src/Graphics.js

The documentation for arcTo() is wrong. Also [refer this thread](http://www.html5gamedevs.com/topic/17312-not-working-arcto-method/?tab=comments#comment-97487)

Update arcTo() documentation

---

packages/utils/src/data/pow2.js

The documentation did not much the code.

Fixed the name of the util function

---

src/core/renderers/webgl/managers/StencilManager.js

@ivanpopelyshev I don't know what happened with that cherry-pick #5983 , but it's not working in v4. Can you take another look at it?

Revert "v4.x nested masks + filter "

---

packages/settings/src/settings.js

update silly typo on jsdoc

---

packages/core/src/Renderer.js
packages/core/src/textures/resources/Resource.js
packages/sprite/src/Sprite.js

Found something while porting pixi-compressed-textures.

Types adjustments

---

packages/graphics/src/Graphics.js

Problem:
https://www.pixiplayground.com/#/edit/wDkRfBh_mws1~L3IZkKC6
Or heavy example :
https://www.pixiplayground.com/#/edit/6Q2sohQJ3Pomw_5reM_VG
Scroll down and uncomment `drawRoundedRect`.
Fixed:
https://www.pixiplayground.com/#/edit/SF_M5l0B3QB0pk7hR3Ms8

Fix broken rendering of graphics by custom graphics plugin when is can't batched.

---

packages/display/src/DisplayObject.js

Just add hitArea to destroy display object and avoid some issue in some context.
update: +add filters to destroy display object.

add [hitArea,filters] to destroy

---

packages/core/src/geometry/Geometry.js

Geometry Typing Fixes

---

packages/core/src/shader/utils/getTestContext.js

Add WebGLContext Missing Detection：
bug: https://pixiplayground.com/#/edit/m2uYajft~ZRxeTrFQbix6
fixed: https://pixiplayground.com/#/edit/nY0h0MXAStRQCnHTd1wYY

Fixes WebGL Context Regression

---

packages/canvas/canvas-renderer/src/utils/mapCanvasBlendModesToPixi.js
packages/constants/src/index.js
packages/core/src/state/utils/mapWebGLBlendModesToPixi.js

Fixes #6131
Demo for all composition modes: https://www.pixiplayground.com/#/edit/bWeh8BX~4XaD5jslgtb_3
XOR is first row. Left is canvas2d, right is webgl.

XOR blendMode

---

packages/canvas/canvas-renderer/package.json
packages/canvas/canvas-renderer/src/CanvasRenderer.js
packages/canvas/canvas-renderer/test/CanvasRenderer.js

As I said in #5891, that's dangerous area.
Broken: https://www.pixiplayground.com/#/edit/xkHG6hYV_bu~NVmasKWZL
Fixed: https://www.pixiplayground.com/#/edit/yht49knRJxXSSZ_zBQ2iq
+ 1 not trivial test
Problem was discovered by @a-rasinski and @themoonrat

Fix CanvasRenderer "translate" parameter behaviour

---

packages/core/src/geometry/Attribute.js
packages/core/src/shader/Program.js

simple jsdoc update.
fixes #6137 and also fixes `Attribute.from`

small jsdoc fixes for program and attribute

---

packages/display/src/Bounds.js
packages/math/src/shapes/Rectangle.js

Optional paddingY in math/src/Rectangle.js and display/src/Bounds.js

Optional paddingY

---

packages/graphics/src/Graphics.js
packages/graphics/test/index.js

beginTextureFill had a problem.

beginTextureFill old style params fix

---

packages/prepare/src/Prepare.js
packages/prepare/test/Prepare.js
packages/prepare/test/index.js

Fix Prepare graphics + test

---

src/core/graphics/Graphics.js

Cherry-pick #6159, thanks to @xuyangbill for noticing it and providing a fix.

[v4.x] HitTest hole fix

---

packages/filters/filter-blur/src/BlurFilterPass.js

Fix #6257 
Comment out the bottom line and see the problem.
https://www.pixiplayground.com/#/edit/kuhrhc4jG5QnRRtIfwGwk

BlurFilter: clear temporary texture

---

packages/settings/package.json
packages/settings/src/index.js
packages/settings/src/settings.js
packages/settings/src/utils/canUploadSameBuffer.js
packages/settings/src/utils/isMobile.js
packages/settings/src/utils/maxRecommendedTextures.js

Replaces #6254.
Upgrades the **ismobilejs** dependency in settings.

Upgrade to ismobilejs v1

---

packages/constants/src/index.ts
packages/math/src/const.ts

As discussed in #6179 the `PRECISION` docs caused the generated types to become a const enum, while not being declared so in code.
This fixes the docs for that and also removes the unnecessary const enum for `SHAPES`

Fixes issues related to #6179

---

packages/canvas/canvas-particles/README.md
packages/canvas/canvas-particles/src/ParticleContainer.js

Fix canvas-particles readme and outdated internal deprecation

---

packages/prepare/src/BasePrepare.js

fix typings error for 5.2.1

---

packages/core/src/filters/spriteMask/SpriteMaskFilter.js

fix typings in 5.3

---

packages/core/src/textures/resources/ArrayResource.ts
packages/core/src/textures/resources/CubeResource.ts
packages/core/src/textures/resources/VideoResource.ts
packages/core/src/textures/resources/autoDetectResource.ts
packages/core/src/textures/resources/index.ts

Follow up to #6340 to fix the typings for resource options

Add stricter types for resource options and resource plugins

---

packages/filters/filter-displacement/src/DisplacementFilter.ts

fix import `@pixi/math/src` to `@pixi/math`

fix import `@pixi/math/src` to `@pixi/math`

---

packages/core/src/textures/Texture.ts
packages/core/test/Texture.js

Texture.clone should clone orig, frame, trim Rectangles

---

packages/canvas/canvas-graphics/src/Graphics.js
packages/core/src/AbstractRenderer.ts
packages/core/src/framebuffer/Framebuffer.ts
packages/core/src/textures/TextureSystem.ts

https://github.com/pixijs/pixi.js/issues/5831

Any reference to scaleModes is done via using the enums setup

---

packages/sprite-animated/src/AnimatedSprite.ts
packages/sprite-animated/test/AnimatedSprite.js

Fix issues with previousFrame and resetting textures

---

packages/graphics/src/styles/LineStyle.ts

LineStyle alignment
Change default Value in document: 0 > 0.5

Document update

---

packages/spritesheet/src/SpritesheetLoader.ts
packages/spritesheet/test/SpritesheetLoader.js

Fix Texture leak with SpritesheetLoader

---

packages/text-bitmap/src/BitmapFont.ts

Support BitmapText resolution on high-density displays (fixes #5171)

---

packages/core/src/framebuffer/FramebufferSystem.ts
packages/core/src/projection/ProjectionSystem.ts

Simplify two small scopes within the core package.

Simplify logic

---

packages/graphics/README.md

Pointed out by @SukantPal on Slack.

Update graphics README.md

---

packages/graphics/src/Graphics.ts

Fix typo in Graphic.clone documentation

---

README.md

https://github.com/pixijs/pixi.js/issues/6413 was proposed and @bigtimebuddy agreed!

Slack Invite!

---

packages/core/src/geometry/Attribute.ts
packages/core/src/projection/ProjectionSystem.ts
packages/core/src/textures/resources/BaseImageResource.ts
packages/core/src/textures/resources/ImageResource.ts
packages/graphics/src/Graphics.ts
packages/graphics/src/utils/ArcUtils.ts
packages/graphics/src/utils/buildLine.ts

This fixes cases where the no. of documented parameters is greater than those actually taken.

Fix documented parameters

---

packages/text-bitmap/src/BitmapFont.ts
types/events.d.ts

Our jsdoc-generated types were broken because of recent changes. This fixes those issues.

Fixes broken generated typings

---

.github/workflows/nodejs.yml

So now it seems to be working properly.
I've tested with `git push --tags`.
Here is the result https://github.com/cursedcoder/pixi.js/actions/runs/149723902
See #6715

Trigger on tag push

---

packages/canvas/canvas-graphics/src/CanvasGraphicsRenderer.ts

fix: #6394 
I just added a matrix multiplication.
before: https://jsfiddle.net/y5scnf3j/
fixed: https://www.pixiplayground.com/#/edit/QTZihAP-tdEGtHnhzewVU

Fix Graphics.setMatrix for CanvasRenderer (#6394)

---

packages/canvas/canvas-mesh/src/Mesh.ts

fix: #6491 
before: https://jsfiddle.net/JetLu/tz2bnmu7/
fixed: https://jsfiddle.net/JetLu/L6dzc74o/

fix: Mesh crash in canvasRenderer

---

.eslintrc.json
packages/core/src/textures/resources/VideoResource.ts

Fix missing event parameter from VideoResource

---

packages/core/src/textures/TextureMatrix.ts

Fix #6711 
buggy: https://www.pixiplayground.com/#/edit/RcAmTMe1Fc3gfj1rR390u
fixed: https://www.pixiplayground.com/#/edit/FvEQwae-5UsSIUtoMz-06

separate uvMatrix and texture updateID's

---

packages/core/src/projection/ProjectionSystem.ts

Fix incorrect typings in v5.3.1

---

packages/app/src/Application.ts

Supersedes gh-6815
---
For more, see https://github.com/pixijs/pixi.js/pull/6815#issuecomment-674545234

Remove unused option from Application

---

packages/text/src/Text.ts

Fixes drop shadow bug as described: https://github.com/pixijs/pixi.js/issues/6819
Before: https://www.pixiplayground.com/#/edit/FXkQRBFr0W4ESDpBadysG
After: https://www.pixiplayground.com/#/edit/rnOyg5U1BvSeHEpucEM0E

Fixed duplicate text when using drop shadow and large padding

---

packages/spritesheet/src/SpritesheetLoader.ts

Fixes #6851
http://pixijs.download/fix-6851/docs/PIXI.SpritesheetLoader.html

Improve documentation for SpritesheetLoader

---

packages/core/src/context/ContextSystem.ts

Fixed #6847 
demo: https://www.pixiplayground.com/#/edit/5HPwteo_LzF8BVrFGRa5i

Fixed webGLVersion of context

---

packages/core/src/Renderer.ts
packages/core/src/filters/Filter.ts
packages/core/src/filters/FilterSystem.ts
packages/core/src/framebuffer/Framebuffer.ts
packages/core/src/mask/AbstractMaskSystem.ts
packages/core/src/mask/MaskSystem.ts
packages/core/src/mask/ScissorSystem.ts
packages/core/src/projection/ProjectionSystem.ts
packages/core/src/renderTexture/BaseRenderTexture.ts
packages/core/src/renderTexture/RenderTexture.ts
packages/core/src/textures/TextureSystem.ts

Documentation for all 'em systems

---

packages/core/src/renderTexture/RenderTextureSystem.ts

Documentation describing frames used by RenderTextureSystem

---

packages/core/src/renderTexture/RenderTextureSystem.ts

#6871 
Unfixed:
* https://codepen.io/sukantpal/pen/VwaxgdV?editors=0010
Fixed:
* https://codepen.io/sukantpal/pen/eYZrxXe?editors=0010

Handle y-flipping when rendering to screen in RenderTextureSystem

---

packages/display/src/Bounds.ts
packages/display/src/Container.ts
packages/display/src/DisplayObject.ts

@pixi/display documentation

---

packages/loaders/src/LoaderResource.ts

Updated links on LoaderResource docs
fixes #6918

Fixed LoaderResource docs reference links

---

packages/canvas/canvas-mesh/global.d.ts
packages/canvas/canvas-mesh/src/CanvasMeshRenderer.ts
packages/canvas/canvas-mesh/src/Mesh.ts
packages/mesh/src/Mesh.ts

Fix #6921 
demo: https://codepen.io/jerald/pen/vYKBPQQ
It's hard to imagine this being the third revision.

Fix  rendering tinted Spines

---

.github/CONTRIBUTING.md

Documentation of a speedy testing workflow, coming out of discussion in #6925.

Describe speedy testing workflow in CONTRIBUTING.md

---

packages/sprite-tiling/src/tilingSprite.frag

Fixes #6933
Thanks @JohnEastWork for the suggestion and finding the bug.
https://pixijs.io/examples/?v=fix-6933#/sprite/tiling-sprite.js

Fix TilingSprite shader on some mobile devices

---

packages/core/src/textures/Texture.ts
packages/core/src/textures/resources/AbstractMultiResource.ts
packages/display/src/DisplayObject.ts

Fixed some problems webdoc was complaining about.

Fix documentation problems

---

packages/canvas/canvas-graphics/src/CanvasGraphicsRenderer.ts
packages/canvas/canvas-graphics/test/.eslintrc.json
packages/canvas/canvas-graphics/test/CanvasGraphicsRenderer.js
packages/canvas/canvas-graphics/test/index.js

Fix #7027 
Includes unit test.
Aaaand the "Grand Fail of the Year" award goes to Ivan Igorevich!

Fix serious performance problem in canvas renderer

---

packages/core/src/filters/FilterSystem.ts

Fixes #7063. See #7073 for explanation of why this will work.
Clear whole filter texture in filter system.

Fix: Clear full texture in filter system

---

packages/accessibility/package.json
packages/accessibility/src/AccessibilityManager.ts

Fix typo in package.json: "_impared_" => "_impaired_"
Fix typo in AccessibilityManager: "_accessability_" => "_accessibility_"

Accessibility package errata

---

packages/filters/filter-blur/src/BlurFilter.ts
packages/filters/filter-blur/src/BlurFilterPass.ts

Minor typo in filter package, occurred twice - probably copied and pasted.
- _quaility_ => _quality_

Filter package jsdoc

---

packages/canvas/canvas-sprite-tiling/package.json
packages/canvas/canvas-sprite-tiling/src/TilingSprite.ts

Fixes #7077 by reverting #6869 from v5.3.x.
https://jsfiddle.net/bigtimebuddy/035tmsra/

Revert #6869

---

packages/canvas/canvas-renderer/src/CanvasRenderer.ts
packages/compressed-textures/src/loaders/KTXLoader.ts
packages/interaction/test/MockPointer.js
packages/math/src/ObservablePoint.ts
packages/math/src/shapes/Polygon.ts
packages/mesh-extras/src/SimpleRope.ts
packages/mesh/src/Mesh.ts
packages/runner/src/Runner.ts

Some minor typos I previously missed, affecting JS Doc.

Documentation

---

README.md

Updates the readme, that's it.

webdoc instead of JSDoc

---

packages/mesh/src/Mesh.ts

Fix types for Mesh constructor #7229

Fix types for Mesh

---

packages/app/src/ResizePlugin.ts

Fix missing removeEventListener in ResizePlugin

---

packages/runner/src/Runner.ts

- [x ] Documentation is changed or added

Fix more documentation typos

---

packages/mesh/src/Mesh.ts

Fix Mesh render crash due new behaviour of ShaderSystem

---

packages/mesh-extras/src/SimplePlane.ts

Fix #7302 
DEMO1: https://codepen.io/jerald/full/MWbMJjO
DEMO2: https://codepen.io/jerald/full/eYBwoEa
Thanks to @ivanpopelyshev

Fix video texture not working in SimplePlane

---

package-lock.json
package.json

Upgrade @pixi-build-tools/api-extractor-lerna-monorepo to 1.0.3

---

packages/ticker/src/TickerPlugin.ts

Remove app dependency from ticker

---

packages/display/src/DisplayObject.ts

Types support nullable filters

---

README.md

* README.md: Update URL(Filters Demo)
* `http://pixijs.io/pixi-filters/tools/demo/` -> `https://filters.pixijs.download/v3.2.0/demo/index.html`

Update URL_Filters Demo

---

packages/graphics-extras/src/drawRoundedPolygon.ts
packages/graphics-extras/src/index.ts

Added new drawing method to creating regular polygons but with rounded corners.
https://jsfiddle.net/bigtimebuddy/czr97ox3/112/

Add drawRoundedPolygon to graphics-extras

---

packages/math/src/Point.ts

First pass at contributing to the documentation update effort. Please let me know if there is anything I should change or could do better.
* `fix` - update documentation according to: #7159

Documentation Update: Point.ts

---

packages/graphics/src/Graphics.ts

Fix #7435 
Fixed: https://codepen.io/jerald/full/poRqKpv

Fix holes in mask not working

---

packages/mixin-get-child-by-name/global.d.ts

Make getChildByName non-optional

---

package-lock.json
packages/text-bitmap/src/utils/drawGlyph.ts

Remove duplicate lines from BitmapText's drawGlyph

---

packages/events/src/FederatedEventTarget.ts

Fixes #7486
Documentation: http://pixijs.download/fix-7486/docs/PIXI.DisplayObject.html#addEventListener

Fix docs removeEventListener & addEventListener

---

packages/display/src/DisplayObject.ts

Fix DisplayObject's parent type as Container

---

packages/events/src/EventSystem.ts

Fix typo in EventSystem.ts

---

packages/core/src/textures/BaseTexture.ts

Fixes #7550 
Also: move documentation comments to properties
---
I'm back 👋

Wrap mipmap, scaleMode, wrapMode in getter/setter

---

packages/display/src/DisplayObject.ts

Add getter for DisplayObject destroyed

---

packages/basis/src/BasisLoader.ts
packages/basis/src/TranscoderWorker.ts
packages/basis/src/TranscoderWorkerWrapper.ts
packages/canvas/canvas-extract/src/CanvasExtract.ts
packages/canvas/canvas-graphics/src/CanvasGraphicsRenderer.ts
packages/canvas/canvas-mesh/src/CanvasMeshRenderer.ts
packages/canvas/canvas-prepare/src/CanvasPrepare.ts
packages/canvas/canvas-renderer/src/CanvasRenderer.ts
packages/canvas/canvas-renderer/src/utils/CanvasMaskManager.ts
packages/canvas/canvas-sprite/src/CanvasSpriteRenderer.ts
packages/compressed-textures/src/loaders/CompressedTextureLoader.ts
packages/compressed-textures/src/loaders/DDSLoader.ts
packages/compressed-textures/src/loaders/KTXLoader.ts
packages/compressed-textures/src/resources/CompressedTextureResource.ts

#7159 This ticket to reformat the documentation has been around for a while so I thought I would start to chipping away at it.

Reformat canvas and compressed textures documentation

---

packages/core/src/geometry/GeometrySystem.ts
packages/core/src/index.ts
packages/core/src/shader/ShaderSystem.ts
packages/core/src/shader/utils/generateProgram.ts
packages/core/test/UniformBuffer.tests.ts

also exported `generateProgram` to its own function.

fix up tests for UBO

---

packages/graphics/src/Graphics.ts
packages/graphics/src/GraphicsData.ts
packages/graphics/src/GraphicsGeometry.ts
packages/graphics/src/styles/FillStyle.ts
packages/graphics/src/styles/LineStyle.ts

Hi. This is an update to docs for files in Graphics package. I tried to update all 10 files but could not figure out what to change for files in util directory. If there is anything else I can update in those 5 files or something I can do better with 5 files I have updated, tell me and I'll improve them.
I'm not quite sure how webdocs or Pixi in general works in depth but I'll try to contribute in updating rest of the docs if you guys can tolerate some silly mistakes by me. Thanks in advance.

Update graphics package docs

---

packages/loaders/src/Loader.ts

Subj.
Btw we really have to check if simple 404 goes to onError with correct arguments

Fix #7663 loader signal typings

---

packages/core/src/framebuffer/FramebufferSystem.ts

Add type to res var in FramebufferSystem > detectSamples

---

packages/core/src/framebuffer/FramebufferSystem.ts

- I added the missing disposal of `blitFramebuffer`.
- If the current framebuffer doesn't have a color texture attachment, there's no reason to blit, because there's no target. Currently a color texture would be created and added to `blitFramebuffer`. That would lead to problems if the color texture was attached later for some reason. And nobody disposes of that created texture as well, since framebuffers don't dispose of their attachments.
- I added code that checks whether the color texture changed.
- Resizing `blitFramebuffer` was working before this change even though `resizeFramebuffer` was not called on it. It seems like it isn't necessary, but I changed it anyway for correctness. I didn't use the `resize` method, because `blitFramebuffer` doesn't own the color texture and therefore …

Fix blit framebuffer

---

packages/core/src/Renderer.ts

Reformat Renderer.ts documentation

---

packages/filters/filter-alpha/src/AlphaFilter.ts
packages/filters/filter-blur/src/BlurFilter.ts

#7159 
Looks like webdoc isn't inferring data-types for getter/setters!

Reformat documentation for AlphaFilter.ts, BlurFilter.ts

---

packages/runner/src/Runner.ts

Reformat Runner.ts documentation

---

package-lock.json
package.json

Upgrade to webdoc 1.5.5

---

packages/particle-container/src/ParticleContainer.ts

Fix ParticleContainer type issues

---

packages/sprite/src/Sprite.ts

Reformat Sprite.ts documentation

---

packages/text/src/TextStyle.ts

Reformat documentation for TextStyle.ts

---

packages/text/src/Text.ts
packages/text/src/TextMetrics.ts

Reformat documentation for Text.ts, TextMetrics.ts

---

packages/sprite-animated/src/AnimatedSprite.ts

Reformat documentation for AnimatedSprite.ts

---

packages/filters/filter-color-matrix/src/ColorMatrixFilter.ts
packages/filters/filter-displacement/src/DisplacementFilter.ts
packages/filters/filter-fxaa/src/FXAAFilter.ts
packages/filters/filter-noise/src/NoiseFilter.ts

Reformat documentation for ColorMatrixFilter.ts, DisplacementFilter.ts, FXXAFilter.ts, NoiseFilter.ts

---

packages/mesh/src/Mesh.ts

Reformat documentation for Mesh.ts

---

packages/math/src/shapes/Polygon.ts

Reformat documentation for Polygon.ts

---

packages/core/src/geometry/Attribute.ts
packages/core/src/geometry/Buffer.ts
packages/core/src/geometry/Geometry.ts
packages/core/src/geometry/GeometrySystem.ts

Reformat documentation for Attribute.ts, Buffer.ts, Geometry.ts, GeometrySystem.ts

---

packages/core/src/filters/Filter.ts
packages/core/src/filters/FilterState.ts
packages/core/src/filters/FilterSystem.ts
packages/core/src/filters/spriteMask/SpriteMaskFilter.ts

Reformat documentation for Filter.ts, FilterState.ts, FilterSystem.ts, SpriteMaskFilter.ts

---

packages/text-bitmap/src/BitmapFontData.ts
packages/text-bitmap/src/BitmapFontLoader.ts
packages/text-bitmap/src/BitmapText.ts
packages/text-bitmap/src/formats/TextFormat.ts
packages/text-bitmap/src/formats/XMLFormat.ts
packages/text-bitmap/src/formats/XMLStringFormat.ts

Reformat documentation for BitmapFontData.ts, BitmapFontLoader.ts, BitmapText.ts, TextFormat.ts, XMLFormat.ts, XMLStringFormat.ts

---

packages/prepare/src/TimeLimiter.ts

Reformat documentation for TimeLimiter.ts

---

packages/core/src/textures/resources/AbstractMultiResource.ts
packages/core/src/textures/resources/ArrayResource.ts
packages/core/src/textures/resources/BaseImageResource.ts
packages/core/src/textures/resources/BufferResource.ts
packages/core/src/textures/resources/CanvasResource.ts
packages/core/src/textures/resources/CubeResource.ts
packages/core/src/textures/resources/DepthResource.ts
packages/core/src/textures/resources/ImageBitmapResource.ts
packages/core/src/textures/resources/ImageResource.ts
packages/core/src/textures/resources/Resource.ts
packages/core/src/textures/resources/SVGResource.ts
packages/core/src/textures/resources/VideoResource.ts

Reformat documentation for all Resource classes

---

packages/math/src/shapes/RoundedRectangle.ts
packages/math/test/RoundedRectangle.tests.ts

Fix RoundedRectangle.contains

---

packages/text/src/Text.ts

Move the letterSpacing check

---

bundles/pixi.js/README.md

Fixes code example shown on npmjs readme.

Fix readme example

---

packages/text-bitmap/src/utils/drawGlyph.ts
packages/text/src/Text.ts

Fixed issue with visuals of drop shadows on different renderer / text resolutions
https://github.com/pixijs/pixijs/issues/8004
Text Before Fix: https://jsfiddle.net/vsu1ermb/1/
Text After Fix: https://jsfiddle.net/3v1Lb54e/2/
Bitmap Font Before Fix: https://jsfiddle.net/o2ryepz0/
Bitmap Font After Fix: https://jsfiddle.net/47gLmkc1/1/

Fixes drop shadow positioning with resolutions other than 1

---

README.md

* Replaces insecure links with HTTPS requests
* Remove old contributor Twitter links and replaced with PixiJS official Twitter
* Other minor link fixes.

README link improvements

---

packages/core/src/framebuffer/Framebuffer.ts
packages/core/src/framebuffer/FramebufferSystem.ts
packages/core/src/framebuffer/GLFramebuffer.ts

Reformat documentation for Framebuffer.ts, FramebufferSystem.ts, GLFramebuffer.ts

---

packages/core/src/geometry/ViewableBuffer.ts
packages/core/src/renderTexture/BaseRenderTexture.ts
packages/core/src/shader/GLProgram.ts
packages/core/src/shader/UniformGroup.ts

Reformat documentation for ViewableBuffer.ts, BaseRenderTexture.ts, GLProgram.ts, UniformGroup.ts

---

packages/mesh-extras/src/geometry/RopeGeometry.ts
packages/mesh/src/MeshBatchUvs.ts
packages/mesh/src/MeshGeometry.ts
packages/mesh/src/MeshMaterial.ts

Reformat documentation for RopeGeometry.ts, MeshMaterial.ts, MeshBatchUvs.ts, MeshGeometry.ts

---

packages/core/src/utils/Quad.ts
packages/core/src/utils/QuadUv.ts
packages/display/src/Bounds.ts
packages/display/src/Container.ts
packages/display/src/DisplayObject.ts

Reformat documentation for Quad.ts, QuadUv.ts, Bounds.ts, Container.ts, DisplayObject.ts

---

packages/graphics-extras/src/drawStar.ts
packages/graphics/src/utils/ArcUtils.ts
packages/graphics/src/utils/BatchPart.ts
packages/graphics/src/utils/BezierUtils.ts
packages/graphics/src/utils/QuadraticUtils.ts

Reformat documentation for ArcUtils.ts, BatchPart.ts, BezierUtils.ts, QuadraticUtils.ts, drawStar.ts

---

packages/canvas/canvas-extract/src/CanvasExtract.ts
packages/canvas/canvas-mesh/src/CanvasMeshRenderer.ts
packages/core/src/AbstractRenderer.ts
packages/core/src/geometry/BufferSystem.ts
packages/extract/src/Extract.ts
packages/text/src/Text.ts

Documentation contains repeated words:
- "the the"
- "a a"

Documentation duplicated words

---

packages/text-bitmap/src/utils/drawGlyph.ts
packages/text/src/Text.ts

Cherry picked https://github.com/pixijs/pixijs/pull/8080#issuecomment-1065351791 to v5.3.x branch

Fix drop shadow positioning with resolutions other than 1 (#8080)

---

package-lock.json
package.json
packages/display/src/DisplayObject.ts
packages/sprite-tiling/src/TilingSprite.ts

Chore: Upgrade to TypeScript 4.3.0 and make setters for ObservablePoints accept IPointData

---

README.md

Changed the URL with a never-expire one
Bug found by a user in a comment of #8298

The discord url was an expired one

---

packages/graphics/src/utils/buildLine.ts

Fixes #8288.
Before: https://www.pixiplayground.com/#/edit/tbwiR5jHfNTXTF-E_d2AF
After: https://www.pixiplayground.com/#/edit/vT8SdivEYyzo-MH3zE1PX

Fix round line join

---

packages/mesh/src/MeshMaterial.ts

The color uniform has to be updated if the texture is changed and with it the alpha mode of the texture.

Update color uniform of MeshMaterial if alpha mode changes

---

packages/events/src/EventBoundary.ts
packages/interaction/src/TreeSearch.ts

Added `MaskData` checks where they were missing.

Add missing MaskData checks

---

packages/canvas-graphics/src/CanvasGraphicsRenderer.ts
packages/canvas-renderer/src/CanvasObjectRendererSystem.ts
packages/canvas-renderer/src/Renderer.ts
packages/compressed-textures/src/resources/BlobResource.ts
packages/core/src/filters/FilterSystem.ts
packages/core/src/render/ObjectRendererSystem.ts
packages/core/src/renderTexture/BaseRenderTexture.ts
packages/core/src/shader/utils/getTestContext.ts
packages/core/src/textures/BaseTexture.ts
packages/core/src/textures/Texture.ts
packages/core/src/textures/TextureSystem.ts
packages/core/src/textures/resources/ImageResource.ts
packages/display/src/Container.ts
packages/graphics/src/Graphics.ts
packages/interaction/src/InteractionManager.ts
packages/loaders/src/LoaderResource.ts
packages/loaders/src/middleware/parsing.ts
packages/mixin-cache-as-bitmap/src/index.ts
packages/prepare/src/BasePrepare.ts
packages/sprite/src/Sprite.ts
packages/spritesheet/src/Spritesheet.ts
packages/text/src/TextMetrics.ts
packages/utils/src/network/getResolutionOfUrl.ts

In an attempt to modernize v7 source, did a clean-up some low-hanging fruit using [nullish coalescing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) and [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) and even [logical nullish assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_nullish_assignment).

Chore: nullish coalescing and optional chaining pass

---

packages/assets/src/loader/parsers/loadWebFont.ts

The webfont loader should return either a single font face or an array as we load multiple different weights

Fix webfont loader

---

README.md
bundles/pixi.js-legacy/README.md
bundles/pixi.js/README.md

Updates the bundle readme files to use open collective instead of Patreon
Also removes the broken analytics link

Chore: Update readme

---

packages/core/src/textures/resources/ImageBitmapResource.ts

Fixes https://github.com/pixijs/pixijs/issues/8498

Fixes (#8498) ReferenceError: Can't find variable: ImageBitmap

---

packages/assets/package.json

Added exports to Assets Package 
fixes #8503

Added exports to package.json in Assets Package

---

README.md
bundles/pixi.js-node/README.md

Added some instructions to the readme's for when the node packages fail to install
This should help with issues like this #8537

add installation error help to readme

---

packages/assets/src/loader/parsers/loadBitmapFont.ts

Support in Assets text-based loading of fnt BitmapFonts

---

README.md

Add link to @miltoncandelero tutorial https://www.pixijselementals.com/ to "Learn" section in main page of PixiJS README.md
Because is very good tutorial :)
Currently is using pixi.js version 6.3.0 - so quite recent

Add link to pixijselementals.com to "Learn" section in main page of PixiJS readme

---

packages/interaction/src/InteractionManager.ts

Docs [here](https://pixijs.download/dev/docs/PIXI.InteractionManager.html#autoPreventDefault) remove linebreaks, so we need full-stops.

[docs] grammar/punctuation

---

packages/core/src/shader/utils/generateUniformsSync.ts

Cache sampler uniform values

---

scripts/injectGlobalMixins.ts

The new node bundle was not included in the script
So i've tidied the script up a little to make it easier to add more bundles (webworker) in the future

Fix injectGlobalMixins script

---

packages/events/src/EventBoundary.ts

Fixes a typo in `capture` documentation.

Fix documentation of catpture events

---

packages/sprite-animated/src/AnimatedSprite.ts
packages/sprite-animated/test/AnimatedSprite.tests.ts

Make `sprite-animated` `currentFrame` be mutable
close #6098

Feat(sprited-animated): make currentFrame mutable

---

README.md

Fix GitHub Actions Link

---

packages/core/src/textures/TextureSystem.ts

Fixes the issue described in #8636.
- Before: https://pixiplayground.com/#/edit/qKbwGLPkoY2VNAZc8Gr-a
- After: https://pixiplayground.com/#/edit/xwo4Pux8OLrkb9RNfX2dg

Update texture style if `dirtyStyleId` changes

---

package-lock.json
packages/settings/package.json

Fix settings type error with v7.0.0-beta.2

---

packages/settings/src/ICanvas.ts

Fix ICanvas type issue in v7.0.0-beta.2

---

packages/utils/src/color/hex.ts
packages/utils/src/index.ts

Follow-up to #8637 
Missed a few examples in utils.

Modernize documentation examples in utils

---

bundles/pixi.js-node/src/adapter/NodeCanvasElement.ts
bundles/pixi.js-node/src/adapter/NodeCanvasResource.ts
bundles/pixi.js-node/src/adapter/loadNodeBitmapFont.ts
packages/assets/src/loader/parsers/textures/loadTexture.ts
packages/canvas-renderer/src/canvasUtils.ts

Additional optional chaining and startsWith/includes

---

package-lock.json
package.json
packages/canvas-graphics/src/utils/PolygonUtils.ts
packages/core/src/index.ts
packages/events/src/EventSystem.ts
packages/utils/src/url.ts

Fix some Webdoc issues mentioned in #8720.
- Fix some invalid document comment (7fdaf86b0c9aefbc4af0b28c3031c6624194f2a7)
- Details in https://github.com/pixijs/pixijs/issues/8720#issuecomment-1279373269 and https://github.com/pixijs/pixijs/issues/8720#issuecomment-1279735053
- Bump `@pixi/webdoc-template` from 1.5.3 to 1.5.4 (c7facf707af6ed7987314fdc1636b10376af7278)
- Details in https://github.com/pixijs/pixijs/issues/8720#issuecomment-1279691366 and https://github.com/pixijs/webdoc-template/pull/22
- ~Wait for other fixes in [`@webdoc/cli`](https://github.com/webdoc-labs/webdoc) and bump it~

Fix some Webdoc issues

---

README.md
packages/assets/src/Assets.ts
packages/events/src/EventSystem.ts
packages/text/src/TextMetrics.ts
packages/utils/src/media/trimCanvas.ts

Add document of how to install Assets and EventSystem for v6.x:
- https://pixijs.download/chore/v6-docs/docs/PIXI.Assets.html
- https://pixijs.download/chore/v6-docs/docs/PIXI.EventSystem.html
Also some minor revision in document is included.
Also fix the type issue caused by previous commit 2befc6864846c43928bac68e4feeca9c684bb8ea.
Fixes #8740.

Chore: Update document for v6.x

---

packages/display/global.d.ts
packages/display/src/DisplayObject.ts
packages/events/global.d.ts

Decouple events from display

---

packages/extensions/src/index.ts
packages/extensions/test/extensions.tests.ts

During the https://github.com/pixijs/pixijs/commit/84096a7d4c82522a62ecf354f459d89277f8b903, an important details was lost, namely checking for duplicate plugins https://github.com/pixijs/pixijs/commit/84096a7d4c82522a62ecf354f459d89277f8b903#diff-975c951909dd96296e87b4491bef8dcd42606b9174e880e3ce30e92120b911afL195

Fixed plugins duplicating

---

packages/basis/README.md

Fix typo in basis readme

---

packages/sprite-animated/src/AnimatedSprite.ts
packages/sprite-animated/test/AnimatedSprite.tests.ts

~Add `AnimatedSprite.loopCount`, and `loopCount` parameter for `AnimatedSprite.onLoop`.~
Add tests for `AnimatedSprite.onLoop`.

Add tests for AnimatedSprite.onLoop

---

package-lock.json
package.json

See https://github.com/pixijs/webdoc-template/releases/tag/v1.5.5.

Bump @pixi/webdoc-template 1.5.5

---

packages/extract/README.md
packages/prepare/README.md

Fix typos in packages usage instructions

---

.github/workflows/nodejs.yml

Closes #8952
Attempting workaround to unblock CI.

Unblock GitHub Actions, pin Ubuntu version

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
README.md
bundles/pixi.js-node/README.md
packages/assets/package.json
packages/basis/package.json
packages/canvas-extract/src/CanvasExtract.ts
packages/canvas-prepare/src/CanvasPrepare.ts
packages/compressed-textures/package.json
packages/core/src/filters/Filter.ts
packages/events/package.json
packages/extract/src/Extract.ts
packages/prepare/src/BasePrepare.ts
packages/prepare/src/Prepare.ts
webdoc.conf.json

Fix some legacy issues in the document:
- <https://github.com/pixijs/pixi.js> -> <https://github.com/pixijs/pixijs>
- `renderer.plugins.extract` -> `renderer.extract`
- `renderer.plugins.prepare` -> `renderer.prepare`

Chore: Update document

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Issue forms name don't support `:emoji_name:` syntax, so replace them with raw emojis.
Fixes problem in <https://github.com/pixijs/pixijs/pull/8981#issuecomment-1356913249>.

Fix: Issue forms emojis

---

packages/assets/src/resolver/Resolver.ts
packages/assets/src/resolver/types.ts

Fix ResolverAssetsArray.srcs type

---

packages/graphics/src/Graphics.ts
packages/graphics/src/utils/ArcUtils.ts

Fix inappropriate document for `Graphics.arcTo` and `ArcUtils.curveTo`.
Fixes #9049.

Fix inappropriate document for `arcTo`

---

.github/workflows/nodejs.yml

Follow up #8953, fixing blocked GitHub Actions on v6.x branch.

Pin GitHub Actions Ubuntu version for v6.x

---

packages/core/src/context/ContextSystem.ts
packages/core/src/framebuffer/FramebufferSystem.ts

I am not sure if v6 is still maintained, but felt like the fix from @dev7355608  #8835 could come in handy for the current v6 projects.

Migrate loseContext/restoreContext fix #8835 to v6

---

packages/assets/src/utils/copySearchParams.ts
packages/assets/src/utils/index.ts
packages/spritesheet/src/spritesheetAsset.ts
packages/text-bitmap/src/loadBitmapFont.ts
packages/text-bitmap/test/BitmapFontLoader.tests.ts

Appends defaultSearchParams to the assets they're loading by spritesheet or bitmapfont

Fix defaultSearchParams to append to Spritesheets or BitmapFonts

---

LICENSE

Updated License Year

---

packages/assets/src/resolver/Resolver.ts
packages/assets/src/resolver/types.ts
packages/assets/test/bundle.tests.ts

data now being passed correctly!
test added
fixes #9053

Add missing data pass-through for bundle assets

---

packages/extract/src/Extract.ts
packages/prepare/src/Prepare.ts

Update some outdated document in `Extract` and `Prepare`.

Chore: Update document for Extract and Prepare

---

.github/workflows/nodejs.yml

Follow up #9104. Cleanup GitHub Actions deprecation warnings for v6.x branch.

Chore: Cleanup GitHub Actions deprecation warnings (for v6.x)

---

README.md

Chore: Add financial contributors badge

---

package-lock.json
package.json
packages/app/src/Application.ts
packages/canvas-renderer/src/CanvasRenderer.ts
packages/color/src/Color.ts
packages/core/src/IRenderer.ts
packages/core/src/Renderer.ts
packages/core/src/autoDetectRenderer.ts

- Update document for [`Color`](https://pixijs.download/docs/color-source/docs/PIXI.Color.html) and [`ColorSource`](https://pixijs.download/docs/color-source/docs/PIXI.html#ColorSource) (more examples)
- Update document for [`IRendererOptions.backgroundColor`](https://pixijs.download/docs/color-source/docs/PIXI.IRendererOptions.html) (update type and description)
- Bump `@webdoc/cli` to `2.2.0`, otherwise the document for `ColorSource` cannot be parsed correctly

Docs: Update document for ColorSource

---

packages/graphics/src/Graphics.ts

Fix regression gracefully handling null color in Graphics

---

packages/app/src/Application.ts
packages/canvas-renderer/src/CanvasRenderer.ts
packages/core/src/Renderer.ts
packages/core/src/autoDetectRenderer.ts

Add document for the new `defaultInteraction` option in `Application`, `CanvasRenderer`, `Renderer` and `autoDetectRenderer`. Not quite sure if the default value is `'auto'`, if it is wrong I will change it.

Docs: Add defaultInteraction for renderer params

---

packages/events/src/FederatedMouseEvent.ts
packages/events/test/EventSystem.tests.ts

It was mentioned in the discord that getLocalPosition didn't exists anymore
So i've added it back to help with the transition from v6 -> v7

adds back getLocalPosition from v6

---

packages/text-html/src/HTMLText.ts

Fix major bug: https://github.com/pixijs/html-text/pull/42
https://jsfiddle.net/bigtimebuddy/35rzwkt8/ (canvas)
https://jsfiddle.net/bigtimebuddy/yp8z1t95/ (webgl)
https://jsfiddle.net/bigtimebuddy/hpr42yte/ (canvas)
https://jsfiddle.net/bigtimebuddy/zfvk0hdq/ (webgl)

Fix the flicker between text renders

---

packages/color/src/Color.ts
packages/color/test/Color.tests.ts

Closes #9198 
Verify:
https://jsfiddle.net/bigtimebuddy/n83h1kw5/

Add support for Color input that extends Number

---

packages/events/src/EventBoundary.ts

Fixes `rightclick` and `onrightclick` not triggering

---

package-lock.json

Update package-lock.json (with `npm i`), it is missed in #9222.

Chore: Update package-lock.json

---

packages/events/src/EventBoundary.ts

This PR fixes the performance issues seen with the global move events
before: https://jsfiddle.net/k69qz4c2/3/
after: https://jsfiddle.net/k69qz4c2/2/
When comparing the two there is no longer lag when the `eventMode` is `passive` or `auto`

Fix interaction performance

---

bundles/pixi.js-webworker/src/adapter.ts
scripts/filterTypeScriptErrors.ts

Add strict null checks to @pixi/webworker.

Add strict null checks to @pixi/webworker

---

packages/mixin-get-child-by-name/global.d.ts
packages/mixin-get-child-by-name/src/index.ts
scripts/filterTypeScriptErrors.ts

Add strict null checks to @pixi/mixin-get-child-by-name.

Add strict null checks to @pixi/mixin-get-child-by-name

---

scripts/filterTypeScriptErrors.ts
scripts/prepublish.ts
scripts/utils/bump.ts
test/index.ts

Add strict null checks to scripts in `scripts`, `test` and `tools` folder.

Add strict null checks to misc scripts

---

packages/events/src/EventBoundary.ts

fixes: #9257 
before: https://jsfiddle.net/pvz7un6y/
after: https://jsfiddle.net/1b84L3fd/

Fix: pointer target being incorrect

---

scripts/utils/bump.ts

* Add confirmation to the bump
* Make sure to fail when attempting to bump using the same version
* Better bump order (patch, minor, major) instead of (major, minor, patch)

Chore: Bump workflow improvements

---

packages/core/src/filters/Filter.ts

Fix a broken link for filter example: <http://pixijs.io/examples/#/filters/blur-filter.js> -> <https://pixijs.io/examples/#/filters-basic/blur.js>.

Fix: Broken link for filter example

---

packages/color/src/Color.ts
packages/color/test/Color.tests.ts

* Fix: Ensure input color channels are clamped 0-1

Fix: Ensure input color channels are clamped

---

packages/events/src/EventBoundary.ts
packages/events/test/EventSystem.tests.ts

Fixes #9299 #9274
[before](https://codesandbox.io/s/pixi-interaction-fix-2f8hj1?file=/src/index.js)
[after](https://github.com/pixijs/pixijs/pull/9301#issuecomment-1485321335)
also fixes nested mask interactions
https://codesandbox.io/s/pixi-interaction-masked-fix-gpjv53?file=/src/index.js

Fix nested interaction

---

packages/core/src/filters/Filter.ts
packages/core/src/filters/FilterSystem.ts
packages/core/src/mask/MaskData.ts
packages/core/src/mask/MaskSystem.ts
packages/core/src/settings.ts
packages/filter-blur/src/BlurFilter.ts
packages/filter-blur/src/BlurFilterPass.ts
packages/mixin-cache-as-bitmap/src/index.ts

Automatic filter resolution and multisample

---

.github/workflows/trigger-website-build.yml

Fix the repo after pushing the live site.

Chore: Update trigger-website-build.yml

---

packages/display/src/Container.ts

Update the documentation of addChildAt as per discussion in #9542

Clarify the documentation of addChildAt regarding indices.

---

.eslintrc.json
src/app/Application.ts
src/mesh-extras/NineSlicePlane.ts
src/rendering/mesh/shared/Mesh.ts
src/rendering/renderers/shared/ViewSystem.ts
src/rendering/renderers/shared/system/AbstractRenderer.ts
src/rendering/text/Text.ts
src/rendering/text/TextStyle.ts
src/utils/logging/deprecation.ts

I've exposed a deprecation string to make it easier to maintain a consistent naming convention for the deprecation messages which is `8.0.0`
I have also added `this.screen` to the Renderer and Application to match v7

Update deprecation messages and add screen to Application

---

src/maths/Matrix.ts
src/rendering/renderers/shared/system/AbstractRenderer.ts
src/rendering/scene/LayerSystem.ts

- added transform to RenderOptions
- update matrix log

v8 - added transform to RenderOptions

---

src/rendering/text/bitmap/BitmapTextPipe.ts

fix for bitmap text update bug v8 - fixes #9619 

---

src/rendering/graphics/gl/graphics-batcher-template.vert
src/rendering/graphics/shared/GraphicsContextSystem.ts
src/rendering/sprite/shared/SpriteView.ts
src/rendering/text/Text.ts
src/rendering/text/TextView.ts
src/rendering/text/bitmap/BitmapTextPipe.ts
src/rendering/text/canvas/CanvasTextPipe.ts
src/rendering/text/canvas/CanvasTextSystem.ts
src/rendering/text/html/HTMLTextPipe.ts
src/utils/updateQuadBounds.ts

style.padding now does not affect position of the text (same as v7)

fix padding issue with text

---

src/assets/Assets.ts
src/assets/loader/Loader.ts
src/assets/loader/parsers/textures/utils/createTexture.ts
src/assets/resolver/Resolver.ts
src/assets/utils/convertToList.ts
src/events/EventSystem.ts
src/rendering/renderers/shared/texture/Texture.ts
src/rendering/renderers/shared/texture/sources/TextureSource.ts
src/rendering/text/bitmap/asset/textFormat.ts
src/rendering/text/bitmap/asset/xmlFormat.ts
src/rendering/text/bitmap/asset/xmlStringFormat.ts
src/spritesheet/Spritesheet.ts
src/utils/path.ts

migrating over a couple of recent v7 changes

Migrate v7 changes

---

src/rendering/animation/shared/AnimatedSprite.ts
tests/renderering/animation/AnimatedSprite.test.ts

Add `AnimatedSprite` with tests:
* Mostly ported from v7 as is
* Tests ported from v7

add AnimatedSprite with tests

---

src/rendering/batcher/shared/BatchTextureArray.ts
src/rendering/batcher/shared/Batcher.ts
src/rendering/renderers/shared/system/AbstractRenderer.ts
src/rendering/renderers/shared/texture/Texture.ts
src/rendering/text/bitmap/BitmapTextPipe.ts

- fix a v8 batch bug
- fixed bitmap text anchor bug
- added clear prop to RenderOptions

v8-batch fixes

---

src/rendering/renderers/gl/texture/GlTextureSystem.ts
src/rendering/renderers/gpu/texture/GpuTextureSystem.ts
src/rendering/renderers/shared/texture/sources/TextureSource.ts

fixed a little issue i noteced when text was being GC collected

v8 text texture gc fix

---

src/rendering/renderers/shared/ExtractSystem.ts

surprisingly useful!
```
renderer.extract.log(myContainer)
```

v8 console log a texture

---

src/filters/displacement/displacement.frag
src/rendering/filters/shared/FilterSystem.ts
src/rendering/renderers/gl/GlRenderTargetSystem.ts
src/rendering/renderers/gpu/texture/GpuTextureSystem.ts
src/rendering/renderers/shared/system/AbstractRenderer.ts
src/rendering/renderers/shared/texture/TexturePool.ts

a few tidy ups!
- fix webGPU texture bug | instead of ||
- fix interaction issue
- optimised filter to not use antialiasing unless required

- fix displacement uniform bug

---

src/assets/loader/parsers/textures/loadVideoTextures.ts
src/filters/color-matrix/colorMatrixFilter.wgsl
src/rendering/batcher/gpu/GpuBatchAdaptor.ts
src/rendering/batcher/shared/BatcherPipe.ts
src/rendering/filters/shared/FilterSystem.ts
src/rendering/renderers/gl/GlBackBufferSystem.ts
src/rendering/renderers/gl/GlRenderTargetSystem.ts
src/rendering/renderers/gl/context/GlContextSystem.ts
src/rendering/renderers/gpu/texture/GpuTextureSystem.ts
src/rendering/renderers/shared/texture/sources/TextureSource.ts
src/rendering/scene/LayerSystem.ts
src/rendering/text/canvas/CanvasTextSystem.ts

- WebGPU texutre resize fix
- video texture priority fix
- fix mask issue on webGPU

last v8 WebGPU bugs!

---

src/mesh-extras/NineSlicePlane.ts
src/rendering/graphics/shared/Graphics.ts
src/rendering/mesh/shared/Mesh.ts
src/rendering/scene/Container.ts
src/rendering/scene/container-mixins/childrenHelperMixin.ts
src/rendering/sprite/shared/Sprite.ts
src/rendering/text/Text.ts
src/tiling-sprite/TilingSprite.ts
tests/scene/Children.test.ts

deprecates adding children to anything that isn't a container

Chore deprecate children

---

src/events/EventSystem.ts

This was missed when we updated the event mode previously for v8

Fix default event mode

---

src/scene/text/html/utils/measureHtmlText..ts

fix for cropping on HTML-Text.
This is also present in v7

add some descender padding

---

src/rendering/renderers/shared/texture/TextureLayout.ts
src/scene/mesh-extras/NineSliceSprite.ts
src/spritesheet/Spritesheet.ts
tests/scene/Children.test.ts

adds borders property to texture for use with nine slice textures

add borders to texture

---

src/scene/text/canvas/CanvasTextSystem.ts
src/scene/text/html/HTMLTextSystem.ts
src/scene/text/html/utils/getPo2TextureFromSource.ts
tests/renderering/scene/getPo2TextureFromSource.test.ts

little fix caused by texture layout bing incorrect due to previous code dedupe,
added little test to cover it!

v8 fix text alignment issue for canvas text

---

src/rendering/renderers/shared/system/AbstractRenderer.ts

Fixed v8 missing resolution change runner emit

Fixed resolutionChange runner emit

---

packages/assets/src/Assets.ts
packages/assets/src/resolver/Resolver.ts

Update Assets docs to reflect the 7.3.0 changes better

Update Assets docs

---

src/rendering/batcher/gpu/BatchGeometry.ts
src/rendering/batcher/shared/Batcher.ts
src/scene/graphics/shared/GraphicsContextSystem.ts
tests/renderering/batch/Batcher.test.ts

fixed an issue where buffers were switching and growing exponentially.

Fix crazy WebGPU buffer switching with large graphics

---

src/scene/container/container-mixins/effectsMixin.ts

feat: support mask to null

---

src/scene/text/bitmap/asset/xmlFormat.ts
src/scene/text/bitmap/utils/getBitmapTextLayout.ts
tests/assets/XMLStringFormat.test.ts

- added default char to be " " is char is missing

v8 fix xml parser for text

---

src/filters/FilterPipe.ts
src/filters/FilterSystem.ts
src/rendering/batcher/shared/Batcher.ts
src/rendering/mask/alpha/AlphaMaskPipe.ts
src/rendering/mask/color/ColorMaskPipe.ts
src/rendering/mask/stencil/StencilMaskPipe.ts
src/rendering/renderers/shared/blendModes/BlendModePipe.ts
src/rendering/renderers/shared/instructions/Instruction.ts
src/rendering/renderers/shared/instructions/InstructionSet.ts
src/rendering/renderers/shared/instructions/RenderPipe.ts
src/scene/container/LayerGroup.ts
src/scene/container/utils/executeInstructions.ts
src/scene/graphics/shared/GraphicsPipe.ts
src/scene/mesh/shared/MeshPipe.ts

v8 docs for instructions

---

src/rendering/renderers/gpu/renderTarget/GpuRenderTargetSystem.ts
src/rendering/renderers/shared/background/BackgroundSystem.ts
src/rendering/renderers/shared/texture/sources/CanvasSource.ts
tests/renderering/BackgroundSystem.test.ts

fixes background alpha for renderers
fixes #9816

v8 fix background alpha bug

---

src/maths/misc/squaredDistanceToLineSegment.ts
src/maths/shapes/Circle.ts
src/maths/shapes/Ellipse.ts
src/maths/shapes/Polygon.ts
src/maths/shapes/Rectangle.ts
src/maths/shapes/RoundedRectangle.ts
src/maths/shapes/ShapePrimitive.ts
src/maths/shapes/Triangle.ts
src/scene/container/bounds/Bounds.ts
src/scene/graphics/shared/GraphicsContext.ts
tests/math/Circle.tests.ts
tests/math/Ellipse.tests.ts
tests/math/Polygon.tests.ts
tests/math/Rectangle.tests.ts

Strokes now have a physical presense  in PixiJS v8
also optimise the Graphics contains point test to early out with a bounds check

v8 Measure Graphics Strokes

---

src/scene/text/TextStyle.ts
src/scene/text/bitmap/DynamicBitmapFont.ts
src/scene/text/utils/generateTextStyleKey.ts
tests/renderering/text/textStyleToCSS.test.ts
tests/visual/scenes/text/html-text.scene.ts

word wrap now working
and size triggers and update
also fixed a line height bug in bitmap text

fix couple of Text bugs

---

src/spritesheet/Spritesheet.ts
tests/renderering/sprite/Spritesheet.tests.ts

Add number type support to scale field of SpritesheetData

---

src/assets/Assets.ts

Resolves [ticket](https://github.com/orgs/pixijs/projects/2/views/4?pane=issue&itemId=46876492).
- Add collapsable sections using details tag.
- Tweak and clean up content.
- Styling update is done on the template side, here: https://github.com/pixijs/webdoc-template/pull/30

Update documentation header content for assets

---

src/rendering/renderers/shared/geometry/Geometry.ts
src/rendering/renderers/shared/geometry/utils/getGeometryBounds.ts
tests/renderering/Geometry.test.ts
tests/renderering/utils/getGeometryBounds.test.ts
tests/utils/getGeometry.ts
tests/utils/getGlProgram.ts

adds bounds object to geometry

add geometry bounds

---

src/scene/container/container-mixins/effectsMixin.ts

fix: allow mask to be null or undefined

---

README.md

Re-order README for more impact. New order is:
* What to Use PixiJS for and When to Use It
* Current features (added WebGPU)
* Setup
* Basic Usage Example
* Learn
* Demos
* Community
* How to build
* How to generate the documentation
* Contribute
* License
NOTE: Checked links, all have valid urls but these ❌ links don't load any content properly. Need checking:
- ✅ [Filters Demo](https://pixijs.io/filters/tools/demo/)
- ✅ [Run Pixie Run](http://work.goodboydigital.com/runpixierun/)
- ✅ [Bunny Demo](http://www.goodboydigital.com/pixijs/bunnymark)
- ❌ [Storm Brewing](http://www.goodboydigital.com/pixijs/storm)
- ❌ [Render Texture Demo](http://www.goodboydigital.com/pixijs/examples/11)
- ❌ [Primitives Demo](http://www.goodboydigital.com/pixijs/examples/13)
- ✅ [Masking …

reorder readme sections

---

src/events/FederatedEventTarget.ts
src/events/init.ts

enhance events documentation

---

src/extensions/Extensions.ts

Enhance extensions documentation.

enhance extensions docs

---

src/filters/Filter.ts
src/filters/defaults/blur/BlurFilter.ts

enhance filters documentation

---

src/maths/matrix/Matrix.ts
src/maths/misc/const.ts
src/maths/point/Point.ts
src/maths/shapes/Ellipse.ts
src/maths/shapes/Polygon.ts
src/maths/shapes/Rectangle.ts
src/maths/shapes/RoundedRectangle.ts
src/maths/shapes/Triangle.ts

enhance maths documentation

---

src/rendering/init.ts

Enhance rendering documentation

enhance rendering documentation

---

src/scene/container/Container.ts
src/scene/container/destroyTypes.ts
src/scene/graphics/shared/Graphics.ts
src/scene/mesh-nine-slice/NineSliceSprite.ts
src/scene/mesh-plane/MeshPlane.ts
src/scene/mesh-plane/PlaneGeometry.ts
src/scene/mesh-simple/MeshRope.ts
src/scene/mesh-simple/MeshSimple.ts
src/scene/mesh-simple/RopeGeometry.ts
src/scene/mesh/shared/Mesh.ts
src/scene/mesh/shared/MeshView.ts
src/scene/sprite-animated/AnimatedSprite.ts
src/scene/sprite-tiling/TilingSprite.ts
src/scene/sprite/Sprite.ts
src/scene/text-html/HtmlTextStyle.ts
src/scene/text/Text.ts
src/scene/text/TextStyle.ts

enhance scene documentation

---

src/ticker/Ticker.ts
src/ticker/const.ts

enhance ticker documentation

---

src/scene/container/utils/definedProps.ts
src/utils/browser/isMobile.ts
src/utils/const.ts
src/utils/logging/deprecation.ts
src/utils/misc/Transform.ts
src/utils/path.ts
src/utils/types.ts

enhance utils documentation

---

package-lock.json
package.json
src/accessibility/AccessibilitySystem.ts
src/assets/Assets.ts
src/environment/adapter.ts
src/filters/Filter.ts
src/scene/text/TextStyle.ts
src/scene/text/TextView.ts
src/ticker/Ticker.ts
src/utils/types.ts

Clean up a few details after merging all the doc details and giving them a once over review.
Also update the `@pixi/webdoc-template` to latest `^2.2.2`.

cleanup misc docs details

---

src/filters/Filter.ts
src/scene/graphics/gl/GlGraphicsAdaptor.ts
src/scene/graphics/gpu/GpuGraphicsAdaptor.ts
src/scene/mesh/gl/GlMeshAdaptor.ts
src/scene/text/sdfShader/SdfShader.ts

small PR to remove code we no longer need!

remove redundant `addResource`

---

src/extensions/Extensions.ts
tests/extensions/extensions.tests.ts

chore: strict null checks for extensions

---

src/filters/FilterSystem.ts
src/filters/defaults/displacement/DisplacementFilter.ts
src/filters/defaults/displacement/displacement.wgsl
src/rendering/renderers/shared/shader/utils/createUBOElements.ts

Fixes the displacement y issue. 
This is due to an alignment issue with Mat2x2. Will be addressed in a subsequent PR

Fix: displacement scale y not updating

---

src/rendering/renderers/gpu/buffer/GpuBufferSystem.ts
tests/accessibility/AccessibilitySystem.tests.ts
tests/accessibility/accessibleTarget.tests.ts
tests/events/EventSystem.tests.ts
tests/prepare/PrepareSystem.test.ts
tests/renderering/Buffer.test.ts
tests/renderering/Geometry.test.ts
tests/renderering/GlBackBufferSystem.test.ts
tests/renderering/State.test.ts
tests/renderering/extract/Extract.test.ts
tests/renderering/graphics/Graphics.Destroy.test.ts
tests/renderering/mesh/Mesh.test.ts
tests/renderering/scene/RenderGroupSystem.test.ts
tests/renderering/sprite/Sprite.test.ts
tests/renderering/sprite/TilingSprite.test.ts
tests/renderering/text/BitmapFontLoader.tests.ts
tests/renderering/text/BitmapText.tests.ts
tests/renderering/text/Text.tests.ts
tests/renderering/textures/GLTextureSystem.test.ts
tests/renderering/textures/GenerateTexture.test.ts
tests/renderering/utils/detectVideoAlphaMode.test.ts
tests/utils/getRenderer.ts
tests/utils/localTest.ts

- rename `getRenderer` to `getWebGLRenderer`
- fix listener bug on buffer in webGPU
- added test

Fix: buffer firing multiple events

---

src/rendering/renderers/shared/system/AbstractRenderer.ts

Fix: background color not being set correctly

---

src/rendering/renderers/gl/shader/program/generateUniformsSync.ts
src/rendering/renderers/gl/shader/program/uniformParsers.ts
src/unsafe-eval/generateUniformsSyncPolyfill.ts

fix up uniform parsers

---

src/rendering/renderers/shared/texture/sources/CanvasSource.ts

Fix: Texture.update not updating texture

---

src/assets/Assets.ts
src/assets/resolver/parsers/resolveJsonUrl.ts

Fix: json url resolutions not being parsed

---

packages/core/src/geometry/Geometry.ts

Updated example for PIXI.Geometry to draw a square instead of dovetail

---

src/rendering/renderers/gpu/shader/GpuProgram.ts
src/rendering/renderers/shared/state/State.ts
src/scene/container/Container.ts
src/scene/sprite/Sprite.ts

final docs

---

README.md

Chore: Update readme links

---

src/accessibility/AccessibilitySystem.ts
src/accessibility/accessibilityTarget.ts
src/rendering/renderers/gl/GlBackBufferSystem.ts
src/rendering/renderers/shared/background/BackgroundSystem.ts
src/rendering/renderers/shared/system/AbstractRenderer.ts
src/rendering/renderers/shared/system/System.ts
src/rendering/renderers/shared/texture/TextureGCSystem.ts
src/rendering/renderers/shared/view/ViewSystem.ts
src/scene/text-bitmap/AbstractBitmapFont.ts
src/utils/pool/Pool.ts
src/utils/pool/PoolGroup.ts

Fixes build issues seen in Gif plugin

Fix: type errors

---

src/scene/container/RenderGroupSystem.ts

fixes root container alpha not being respected

Fix: applying alpha on the stage

---

src/rendering/renderers/shared/system/AbstractRenderer.ts
tests/renderering/Renderer.test.ts

adds the missing `resize` event on the renderer from v7

Fix: add missing resize event

---

src/rendering/renderers/gl/GlBackBufferSystem.ts
src/rendering/renderers/gl/WebGLRenderer.ts
src/rendering/renderers/gl/context/GlContextSystem.ts
src/rendering/renderers/gpu/GpuDeviceSystem.ts
src/rendering/renderers/gpu/WebGPURenderer.ts
src/rendering/renderers/shared/background/BackgroundSystem.ts
src/rendering/renderers/shared/startup/HelloSystem.ts
src/rendering/renderers/shared/system/SharedSystems.ts
src/rendering/renderers/shared/texture/TextureGCSystem.ts
src/rendering/renderers/shared/view/ViewSystem.ts

Chore: Fix docs for WebGLOptions and WebGPUOptions

---

packages/settings/src/ICanvasRenderingContext2D.ts

Fix: ICanvasRenderingContext2D extending letterSpacing (v7.x)

---

src/scene/container/utils/mixColors.ts
tests/scene/utils/mixColors.tests.ts

Guess who's back
@Ziye "<< 32" is doing nothing.

Fix: Clean white implementation

---

src/rendering/high-shader/shader-bits/roundPixelsBit.ts

ensure pixels are rounded and not floored. 
fixes #10373
Clue was in the variable name all along :)
Thanks @FunFetched for the suggestion!

Fix: roundPixels offset 

---

src/rendering/renderers/gl/renderTarget/GlRenderTargetAdaptor.ts
src/rendering/renderers/gpu/renderTarget/GpuRenderTargetAdaptor.ts
src/rendering/renderers/shared/renderTarget/RenderTarget.ts
src/rendering/renderers/shared/renderTarget/RenderTargetSystem.ts
tests/renderering/render-target/RenderTarget.test.ts

Fixes an issue where we were not destroying the render texture frambuffers correctly. This PR fixes this.
Test added also!

Fix: destroying the render texture frambuffers correctly

---

src/scene/sprite-tiling/TilingSprite.ts
src/scene/text/AbstractText.ts
tests/renderering/sprite/TilingSprite.test.ts
tests/renderering/text/Text.tests.ts

fix: containsPoint for TilingSprite and Text when anchor is set

---

src/scene/text-bitmap/AbstractBitmapFont.ts
tests/renderering/text/BitmapFontManager.test.ts

fix: uninstalling bitmap font containing space characters

---

README.md

Fix license link in the README, it seems it was intended to be a link, sorry if it was not the case.

chore: Fix license link in the README

---

src/scene/graphics/shared/utils/buildContextBatches.ts

rendering graphics in the proxy object.
This is a follow-up to  #10590
Fixes #10477

fix: rendering graphics in the proxy object

---

.husky/pre-commit
package-lock.json
package.json

After looking at #10669 I realised our pre commit script was only testing `.ts` files in `src`. I've updated the script to use `lint-staged` and our usual `lint:fix` command

chore: update pre commit

---

src/scene/container/Container.ts

Fixes "did local transform change" check,

fix: _didLocalTransformChangeId check

---

src/rendering/batcher/shared/Batcher.ts
src/scene/container/utils/updateRenderGroupTransforms.ts

A little perf boost when benchmarking 10000s of sprites!

fix: update check for visible / blend / alpha updates

---

src/scene/container/RenderGroupSystem.ts
src/scene/container/utils/clearList.ts
src/scene/container/utils/updateRenderGroupTransforms.ts
src/scene/container/utils/validateRenderables.ts
src/utils/pool/Pool.ts
tests/scene/RenderGroup.tests.ts

Add some code to not retain items in the update lists after use. Should be nice and fast too!
fixes #10719

fix: clean our render lists after use!

---

.codesandbox/sandbox/Bunny.js
.codesandbox/sandbox/index.js
.codesandbox/sandbox/package.json
.codesandbox/sandbox/sandbox.config.json

Updating the sandbox to use bunnymark so that we can more easily identify major performance hits from PR's

chore: add bunnymark to sandbox

---

src/scene/sprite-animated/AnimatedSprite.ts
src/spritesheet/Spritesheet.ts
tests/renderering/animation/AnimatedSprite.test.ts

* Support sprite constructor arguments with AnimatedSprite

fix: Support options for AnimatedSprite

---

src/compressed-textures/basis/transcoder/basis_transcoder.js

chore: remove console logs from basis import

---

tests/assets/assets.tests.ts
tests/assets/bundle.tests.ts
tests/events/EventSystem.tests.ts
tests/ticker/Ticker.tests.ts

Very minor cleanup of the use of wait and setTimeout in tests.

chore: Use node's setTimeout for wait

---

src/filters/defaults/blur/gpu/blur-template.wgsl
src/filters/defaults/blur/gpu/generateBlurProgram.ts

Noticed that WebGPU was not bluring correctly! This should resolve that

fix: WebGPU blur jitter

---

src/rendering/renderers/shared/system/AbstractRenderer.ts
tests/events/EventSystem.tests.ts

fix: Cascade resolution changes when using resize

---

src/scene/container/Container.ts
src/scene/container/RenderGroup.ts
src/scene/container/RenderGroupSystem.ts
src/scene/container/container-mixins/childrenHelperMixin.ts
src/scene/container/utils/buildInstructions.ts
src/scene/container/utils/updateRenderGroupTransforms.ts
src/scene/graphics/shared/Graphics.ts
src/scene/graphics/shared/GraphicsPipe.ts
src/scene/mesh/shared/BatchableMesh.ts
src/scene/mesh/shared/Mesh.ts
src/scene/particle-container/shared/ParticleContainer.ts
src/scene/sprite-nine-slice/NineSliceSprite.ts
src/scene/sprite-nine-slice/NineSliceSpritePipe.ts
src/scene/sprite-tiling/TilingSprite.ts
src/scene/sprite-tiling/TilingSpritePipe.ts
src/scene/sprite/BatchableSprite.ts
src/scene/sprite/Sprite.ts
src/scene/sprite/SpritePipe.ts
src/scene/text/AbstractText.ts
src/scene/view/ViewContainer.ts
tests/renderering/scene/RenderGroupSystem.test.ts
tests/renderering/sprite/TilingSprite.test.ts

another update from #10785
this one unifies the calls to `onViewUpdate` to be shared between the views

chore: unify onViewUpdate calls

---

.github/workflows/publish-branch.yaml
.github/workflows/pull-name.yml
.github/workflows/pull-unit.yml
.github/workflows/push.yml
.github/workflows/release.yml

it seems that our ci is not working now that `ubuntu-latest` is using 24.x instead of 22.x

chore: fix ci

---

src/rendering/renderers/shared/texture/Texture.ts

Updated the `Texture.update()` docs to clarify when to call `update()` on the texture's source.
This change was first discussed in https://github.com/pixijs/pixijs/issues/10954.

chore: Clarified when a texture's source should be updated.

---

src/rendering/renderers/shared/view/View.ts
src/scene/container/RenderContainer.ts
src/scene/container/bounds/getGlobalBounds.ts
src/scene/container/bounds/getLocalBounds.ts
src/scene/container/bounds/getRenderableBounds.ts
src/scene/graphics/shared/Graphics.ts
src/scene/mesh/shared/Mesh.ts
src/scene/particle-container/shared/ParticleContainer.ts
src/scene/sprite-nine-slice/NineSliceSprite.ts
src/scene/sprite-tiling/TilingSprite.ts
src/scene/sprite/Sprite.ts
src/scene/text-bitmap/BitmapText.ts
src/scene/text-html/HTMLText.ts
src/scene/text/AbstractText.ts
src/scene/text/Text.ts
src/scene/view/ViewContainer.ts
tests/scene/DummyView.ts

A port of some of the changes made in this PR: #10785
This PR simplifies how bounds are updated and measured

chore: tidy bounds update

---

src/scene/container/container-mixins/childrenHelperMixin.ts

Very minor docs fix  - remove repeated word
(removed items - do not apply)

chore: minor docs fix

---

README.md

A while ago we stopped using the node ci workflow, so I have updated the read me to show the correct one

chore: update README.md CI badge

---

src/scene/container/container-mixins/getGlobalMixin.ts
tests/display/toGlobal.tests.ts
tests/display/toLocal.tests.ts
tests/scene/getGlobalTransform.tests.ts

I made a boo boo - and appended a matrix incorrectly. Fixed and added tests to cover this too!

fix: getGlobalTransform flipped matrix

---

src/scene/graphics/shared/Graphics.ts

fix: Better undefined check in beginFill deprecation

---

src/assets/loader/parsers/textures/loadVideoTextures.ts
src/color/Color.ts
src/compressed-textures/basis/transcoder/basis_transcoder.js
src/events/EventBoundary.ts
src/events/EventSystem.ts
src/filters/FilterSystem.ts
src/filters/defaults/color-matrix/ColorMatrixFilter.ts
src/maths/shapes/Circle.ts
src/maths/shapes/Ellipse.ts
src/maths/shapes/Polygon.ts
src/maths/shapes/Rectangle.ts
src/maths/shapes/RoundedRectangle.ts
src/maths/shapes/Triangle.ts
src/rendering/renderers/gl/buffer/GlBufferSystem.ts
src/rendering/renderers/gl/geometry/GlGeometrySystem.ts
src/rendering/renderers/gl/state/GlStateSystem.ts
src/rendering/renderers/gl/texture/GlTextureSystem.ts
src/rendering/renderers/gpu/pipeline/PipelineSystem.ts
src/rendering/renderers/shared/buffer/Buffer.ts
src/rendering/renderers/shared/geometry/utils/transformVertices.ts
src/rendering/renderers/shared/texture/sources/TextureSource.ts
src/scene/graphics/shared/buildCommands/buildArc.ts
src/scene/graphics/shared/path/GraphicsPath.ts
src/scene/particle-container/shared/utils/createIndicesForQuads.ts
src/scene/text-html/utils/measureHtmlText.ts
src/scene/text/AbstractText.ts

* Quick pattern match to find obvious OR assignment operator or nullish assignment operator potential usage

chore: Cleanup OR/nullish assignment operators

---

src/rendering/renderers/shared/texture/RenderableGCSystem.ts

dumb bug on my end, easy fix at least!

fix: renderable GC bug

---

packages/events/src/FederatedPointerEvent.ts

add missing properties to v7 FederatedPointerEvent

---

src/scene/container/RenderGroup.ts
src/scene/container/RenderGroupSystem.ts
src/scene/container/container-mixins/onRenderMixin.ts

feat: access renderer from onRender

---

src/scene/mesh/shared/BatchableMesh.ts
src/scene/mesh/shared/MeshPipe.ts

when swapping textures with the same source, we were not updating the uvs correctly on the Mesh. This fixes that!
fixes #11251

fix: texture update bug on mesh

---

src/rendering/renderers/gl/GlStencilSystem.ts

Resets the stenil cache when resetState is called
fixes #11248

fix: mask resetState bug

---

src/prepare/PrepareQueue.ts
src/prepare/PrepareUpload.ts
src/prepare/__tests__/PrepareSystem.test.ts

Fixed an issue with uploading / preparing graphics.
added test
Fixes a #11254

fix: graphics prepare bug

---

src/rendering/renderers/shared/shader/Shader.ts
src/scene/sprite-nine-slice/NineSliceGeometry.ts
src/scene/sprite-nine-slice/NineSliceSprite.ts

Closes #11353
I have an idea how we an catch these bad imports sooner. Will work on that in a followup, but wanted to get this out ASAP.

fix: bad aliased imports

---

src/spritesheet/Spritesheet.ts

fix: documentation regarding anchor values in spritesheet

---

package.json

Adds funding link to the package on npm's website, and calls to `npm fund`. Note: not tested.

chore: add funding link to npm package

---

src/events/EventBoundary.ts
src/events/FederatedEventTarget.ts

A little change to the cursor type to allow for autocomplete to work properly

feat: allow for autocomplete on cursor strings

---

src/ticker/Ticker.ts

Add comprehensive JSDoc documentation for Ticker time-related properties to clarify their units and usage.
This PR addresses issue #10021 by documenting the units for:
- `deltaTime`: Dimensionless scalar representing the fraction of a frame at target framerate
- `elapsedMS`: Time elapsed in milliseconds (raw, uncapped timing)
- `lastTime`: Timestamp in milliseconds since epoch
- Callback parameter in `add()` method: Receives deltaTime (dimensionless)
The documentation clarifies the relationship between these properties and explains that `deltaTime` is calculated as `elapsedMS * Ticker.targetFPMS * speed`, making it a dimensionless value typically around 1.0 at 60 FPS.
Fixes #10021

chore: add time units documentation to Ticker class
