pixijs/pixijs

packages/text-bitmap/src/BitmapText.ts

Fix #7003 
DEMO: https://jsfiddle.net/JetLu/w58mbhry/
The [original demo](https://www.pixiplayground.com/#/edit/AGAuOUo9ogkEvDnM3vxqf) memory footprint will increase over time.

Fix memory leak with BitmapText

---

packages/basis/assets/basis_transcoder.js
packages/basis/src/BasisLoader.ts
packages/basis/src/TranscoderWorkerWrapper.ts
packages/compressed-textures/src/loaders/KTXLoader.ts
packages/compressed-textures/src/resources/CompressedTextureResource.ts

declare BASIS as var in `basis_transcoder.js`
fix mipmapping support for compressed textures transcoded from BASIS

BASIS fixes

---

packages/core/src/textures/BaseTexture.ts
packages/core/src/textures/resources/ArrayResource.ts
packages/core/src/textures/resources/CanvasResource.ts
packages/core/src/textures/resources/CubeResource.ts
packages/core/src/textures/resources/ImageBitmapResource.ts
packages/core/src/textures/resources/SVGResource.ts
packages/core/src/textures/resources/VideoResource.ts
packages/graphics/src/utils/Star.ts
packages/loaders/src/Loader.ts

Fixes #7022 
Moves documentation from the class doc block to the constructor.

Move constructor documentation params from class declaration

---

packages/text/src/TextMetrics.ts
packages/text/test/TextMetrics.js

As the discussion with @themoonrat in #6975, suggest allowing the `isBreakingSpace ` to be able to receive the `nextChar ` for solving the CJK issues in adding additions.
For example, the example plugin(https://codepen.io/huang-yuwei/pen/GRqbEmm) shows how we can solve the #6975 and #4447 via an adding addition.
However, I am not 100% sure whether the CJK related issues should be solved directly in PIXI.js itself.
Therefore, suggest applying the additional parameters for other developers can change via other plugins.

Add overridable TextMetrics.isBreakingSpace for better CJK plugin support

---

packages/text-bitmap/src/formats/XMLStringFormat.ts
packages/text-bitmap/test/BitmapFontLoader.js
packages/text-bitmap/test/resources/font-random-args.fnt

Fix #7008 
- For BitmapFont text format that's XML-based check if <font> tag exist than parse as XML and check if needed tags exist
- Added test for case when args into <info> tag placed randomly

Fix bitmap font loader to load fonts with random placed args into <info> tag in 5.4.0-rc.2

---

packages/text-bitmap/src/utils/drawGlyph.ts
packages/text/src/Text.ts

Firefox warn`Expected color but found ‘0’.` to create Text instances.
Because, run `context.shadowColor = '0'` in `updateText()`, but it should be css color, '0' is not valid css color.
I silenced it.

Silence harmless warning

---

packages/app/src/Application.ts
packages/canvas/canvas-renderer/src/CanvasRenderer.ts
packages/core/src/AbstractRenderer.ts
packages/core/src/Renderer.ts
packages/core/src/autoDetectRenderer.ts
packages/settings/src/settings.ts

Fixes #7066
This clears up the ambiguity of the recent transparent changes by creating two distinct options for Application and Renderer. It's easier to backward support `transparent` by not overloading it with new meaning.
* **`contextAlpha`** the readonly property for creating the `canvas.getContext`
* **`backgroundAlpha`** the amount of background alpha from 0 to 1
The option `transparent` is marked as deprecated but still supports backward compatibility by setting `contextAlpha` and `backgroundAlpha`.
**Broken**
https://pixijs.io/examples/#/demos-basic/transparent-background.js
**Fixed**
https://pixijs.io/examples/?v=dev-context-alpha#/demos-basic/transparent-background.js

Deprecates transparent Option

---

.npmrc
package.json

This is a non-critical change to define `engines` in the root package.json. I added similar changes for v5.3.x and v5.2.x branches (those old branches explicitly require Node 10 to build docs/types) and thought it would be good to declare supported Node.js versions and npm versions more explicitly. This aligns with the GitHub Actions for testing. In the past, users trying to build have hit issues #6775, #6571, #5724, etc

Add strict engines support

---

packages/utils/src/settings.ts

After the discussions in https://github.com/pixijs/pixi.js/issues/7054 - I feel it's a better strategy by default to allow WebGL where possible, and let developers decide if they want to fail on this flag. It seems it's not always an accurate indicator on whether a device will have good performance or not.
How docs looks after generation

FAIL_IF_MAJOR_PERFORMANCE_CAVEAT switched to false by default

---

packages/graphics/src/GraphicsGeometry.ts

JSDoc comment doesn't match function signature: `aloow32Indices` changed to: `allow32Indices`
Also updated "_preventings_" to "_preventing_" in the comment.  
Might want to assure you actually mean "_artefacts_" instead of "_artifacts_".

GraphicsGeometry JSDoc function signature

---

packages/text/src/Text.ts

Fix #7069 
DEMO: https://jsfiddle.net/JetLu/8crp01qt/
From @themoonrat: https://jsfiddle.net/ktpyjbqc/
Try the fix, limiting the gradient to `0-1` and fixed floating point precision issues.

Fix fillGradientStops descending ordered

---

packages/core/src/filters/FilterSystem.ts

JSDoc comment doesn't match function signature: `Fload32Array` changed to: `Float32Array`

FilterSystem JSDoc function signature

---

packages/basis/src/BasisLoader.ts
packages/basis/src/TranscoderWorkerWrapper.ts

Perhaps this started out as Basis Universal, then became `basisLibrary`?
This library is the only [basisu keyword at npm](https://www.npmjs.com/search?q=keywords:basisu), defined in [basis package.json](https://github.com/pixijs/pixi.js/blob/dev/packages/basis/package.json)
Set JSDoc param `basisu` to type `BasisBinding` named `basisLibrary`
Minor typo (ignored from JSDoc): _anothor_ => _another_

Basis package jsdoc

---

packages/core/src/batch/BatchShaderGenerator.ts
packages/core/src/filters/Filter.ts
packages/core/src/fragments/index.ts
packages/core/src/framebuffer/Framebuffer.ts
packages/core/src/geometry/GeometrySystem.ts
packages/core/src/shader/ShaderSystem.ts
packages/core/src/textures/TextureGCSystem.ts

Minor typos in core package:
- _fragement_ => _fragment_
- _modifigedTextureCoord_ => _modifiedTextureCoord_
- _explicity_ => _explicitly_
- _acount_ => _account_
- _compability_ => _compatibility_
- _defualt_ => _default_
- _garabage_ => _garbage_

Core package jsdoc

---

packages/display/src/Container.ts
packages/display/src/DisplayObject.ts

Minor typos in display package:
- _mantained_ => _maintained_
- _overriden_ => _overridden_

Display package jsdoc

---

packages/graphics/src/Graphics.ts
packages/graphics/src/styles/FillStyle.ts
packages/graphics/src/utils/buildLine.ts

Minor typos in the graphics package:
- _outter_ -> _outer_
- _tin_ => _tint_
- _Recalcuate_ => _Recalculate_
- _recaculate_ => _recalculate_
- _aplpied_ => _applied_
- _displacment_ => _displacement_

Graphics package jsdoc

---

packages/interaction/src/InteractionManager.ts

Minor typo in interaction package, occurred twice - probably copied and pasted.
- _requency_ => _frequency_

Interaction package jsdoc

---

packages/core/src/filters/FilterSystem.ts

The `tempRect` x, y values can be non-zero since they are used to store the invert-transformed source frame. That's why the x, y values must be set to zero when storing the texture destination frame.

Fix tempRect x,y

---

packages/core/src/geometry/GeometrySystem.ts
packages/core/test/Geometry.js

Added special test for it.
Exists for all v5 branches.
Recommend to backport to 5.3.x
Bug was eating memory in production application on thousands of users. Now we can move to hundred thousands :)

Fix: Geometry with different shaders leaked buffers

---

packages/constants/src/index.ts
packages/core/src/filters/FilterSystem.ts
packages/core/test/FilterSystem.js

As discussed with @SukantPal , I have to clarify this once more.
Most people that write filters dont know about clamping and other tricks that are needed in case we use pow2 temporary renderTextures. Even our `BlurFilter` is affected, @GoodBoyDigital wrote this version for v5 :)
For them, we distinguish two clearing modes - one `CLEAR` that clears everything, and second `BLIT` that just overwrites new content over texture, and leaves right and bottom zone as it was.

Improve CLEAR_MODES docs

---

packages/sprite-tiling/src/TilingSpriteRenderer.ts

Fixes issue found here: https://github.com/pixijs/pixi.js/pull/7105#issuecomment-751520798
Thanks for the tip @ivanpopelyshev :+1: 
https://jsfiddle.net/bigtimebuddy/7xeLys04/
https://jsfiddle.net/bigtimebuddy/wt354zu2/

Fix bug with TilingSpriteRenderer reseting default UVs

---

packages/canvas/canvas-sprite-tiling/src/TilingSprite.ts
packages/sprite-tiling/src/TilingSprite.ts

Fixes #7098 
Apply the "shift matrix" in case of `uvRespectAnchor` being false as described in the (newly added) implementation notes. The local space rect being drawn is now always (-anchor.x * W, -anchor.y * H, W, H) (i.e. equal to the local bounds of the tiling sprite).
Pen: https://codepen.io/sukantpal/pen/yLaPqWd?editors=1010

Fix: TilingSprite uvRespectAnchor = false mode.

---

README.md
bundles/pixi.js-legacy/README.md
bundles/pixi.js/README.md

In anticipation of our new major version, this removes "v5" so we can be more ever-green.

Update the banners without version number

---

tools/integration-tests/test/display/Bounds.js

It appears that `radius` parameter is being passed twice to `drawCircle` in the following tests.
```js
drawCircle(0, 0, 10, 10);
```
That doesn't match the function signature of `drawCircle`:
```ts
public drawCircle(x: number, y: number, radius: number): this
```

Bounds integration test circle radius

---

packages/core/src/filters/Filter.ts

Small typings bug was discovered upgrading pixi-filters to new types.
The `apply` method for Filters should have an optional `clearMode`. This is defaulted in the FilterSystem class.

Clear-mode should be optional for Filters

---

packages/core/src/Renderer.ts
packages/extract/src/Extract.ts

This type issue happens when using `@pixi/core` without installing `@pixi/extract`.
```
node_modules/@pixi/core/index.d.ts:13:43 - error TS7016: Could not find a declaration file for module '@pixi/extract'. '/node_modules/@pixi/extract/lib/extract.js' implicitly has an 'any' type.
Try `npm install @types/pixi__extract` if it exists or add a new declaration (.d.ts) file containing `declare module '@pixi/extract';`
13 import type { Extract as Extract_2 } from '@pixi/extract';
```
CanvasExtract was removed in #6503 as a property of CanvasRenderer. This make this change consistent with Renderer and Extract. The `extract` property is redundant with `plugins.extract` and unnecessary. It also create an undesirable dependency between core with extract.

Remove type coupling between core and extract

---

packages/core/src/AbstractRenderer.ts
packages/core/src/IRenderableObject.ts
packages/core/src/Renderer.ts
packages/core/src/index.ts
packages/interaction/src/InteractionManager.ts

When attempting to install `@pixi/core` without `@pixi/display`, you get this error. There was previous work to decouple runtime the core and display (#6450), but the types were still creating this unnecessary coupling.
```
node_modules/@pixi/core/index.d.ts:10:31 - error TS7016: Could not find a declaration file for module '@pixi/display'. '/node_modules/@pixi/display/lib/display.js' implicitly has an 'any' type.
Try `npm install @types/pixi__display` if it exists or add a new declaration (.d.ts) file containing `declare module '@pixi/display';`
10 import { DisplayObject } from '@pixi/display';
```
Created two interfaces that define the surface area between the Renderer and the DisplayObject/Container. These are called IRenderableObject and IRenderableContainer. Potentially this could be …

Remove type coupling between core and display

---

packages/accessibility/package.json
packages/accessibility/src/AccessibilityManager.ts

A little light, non-critical cleanup to AccessibilityManager. There were some left-over TODOs from the conversion to TypesScript that added a lot of unnecessary casting. Also, tweaked some local variables to minimize verbose variable reuse. None of these changes impact functionality.

Remove Renderer casting in accessibility, clean up local variables

---

packages/mixin-get-global-position/global.d.ts

Parameters of `getGlobalPosition` should be optional.

Optional arguments to getGlobalPosition

---

packages/app/src/Application.ts
packages/canvas/canvas-renderer/src/CanvasRenderer.ts
packages/compressed-textures/src/resources/BlobResource.ts
packages/core/src/AbstractRenderer.ts
packages/core/src/Renderer.ts
packages/core/src/autoDetectRenderer.ts
packages/core/src/deprecations.ts
packages/core/src/renderTexture/RenderTexture.ts
packages/settings/src/settings.ts

These were notes from @themoonrat on Slack.

Cleanup docs and types for upcoming release

---

packages/mixin-cache-as-bitmap/package.json
packages/mixin-cache-as-bitmap/src/index.ts

Reported on Slack when installing cache-as-bitmap, there's a missing CanvasRenderer reference in the types.

Add missing dependency to fix type errors on mixin-cache-as-bitmap

---

packages/sprite-animated/src/AnimatedSprite.ts

I met an incorrect type definition for `PIXI.AnimatedSprite`'s `textures` setter. on 5.3.x.
I realized annotation is different from a real `.ts` code, so I just adjusted.
I don't know which base branch is better to be merged.
but I expect this PR will be merged into 5.3.x and release as 5.3.8 or later.
btw, I read CONTRIBUTING.md but there is no `master` branch anymore. Is it (a little bit) outdated?

Fix AnimatedSprite.textures type annotation

---

packages/app/global.d.ts
packages/app/src/Application.ts
packages/loaders/global.d.ts
packages/ticker/global.d.ts

Partially fixes #7141 by adding types for Application plugins. Will support types for `loader`, `resizeTo` and `ticker`.

Add GlobalMixin types for Application plugins

---

packages/graphics/src/Graphics.ts

Partially fixes #7141 
* Object-based 'lineStyle' was missing from documentation
* Param-based 'lineStyle' was missing from types 
* [Graphics#lineStyle](https://pixijs.download/fix-line-style/docs/PIXI.Graphics.html#lineStyle)

Fix documentation and types for Graphics' lineStyle

---

packages/app/global.d.ts
packages/loaders/global.d.ts
packages/text/src/TextStyle.ts
packages/ticker/global.d.ts

Issues reported by users on Slack in 6.0.0-rc.2
* TextStyle constructor arg is optional
* Application plugin options are optional
cc
@miltoncandelero 
@tomasfreres

Fix types for missing optional options and param

---

packages/core/src/deprecations.ts
packages/core/src/index.ts

Upon further investigation, this deprecation strategy needed a little refining.
Deprecations should work runtime even for production builds (minus the console warnings). My first attempt at this meant that runtime didn't work. In this case, trying to use `PIXI.resources.ImageResource` would fail in production builds but work in development builds.

Improve deprecations strategy for core

---

package-lock.json
package.json
webdoc.conf.json

[webdoc 1.1.6](https://github.com/webdoc-labs/webdoc/releases/tag/1.1.6) has a little breaking change - the config now matches what JSDoc's options provided - include/includePattern/excludePattern/exclude. The includePattern(s) must be regex(s) and not glob paths, which should be input(s).
* Install webdoc 1.1.6
* Change includePattern to include in webdoc.conf.json

Upgrade to @webdoc/cli 1.1.6

---

packages/core/test/MaskSystem.js
packages/core/test/TextureSystem.js
packages/prepare/test/Prepare.js

A few tests use the construction `.to.be.notnull`. I could be missing something but I don't think `notnull` is defined or does anything. (Unfortunately, chai's cute "you don't need to put parentheses at the end!" use of properties means that this wont trigger an error. 🤷‍♂️)
I've replaced them with `.to.exist`.

fix instances of '.to.be.notnull' in tests

---

packages/sprite-animated/src/AnimatedSprite.ts

Fixes issue where animated sprite continues to play even when `_playing = false`

Fix for animated sprite not stopping

---

packages/core/src/textures/TextureGCSystem.ts

https://github.com/pixijs/pixi.js/issues/7201
Copies the same logic for not destroying render textures as the 'run' function has - ie. must have a _texture, but can't have a framebuffer property, as only render textures have that
Use https://pixijs.download/bugfix/render-texture-unload/pixi.js as url in https://www.pixiplayground.com/#/edit/CdtIblFjYmf47uNXMIWap to see the fix works (for some reason, custom url isn't saved on pixi-playground

Fixes render textures being destroyed on unload plugin

---

packages/canvas/canvas-mesh/src/CanvasMeshRenderer.ts
packages/core/src/textures/BaseTexture.ts
packages/core/src/textures/Texture.ts
packages/core/src/textures/resources/autoDetectResource.ts
packages/mesh-extras/src/SimpleMesh.ts

This adds an opt-in stricter type for Texture and BaseTexture using Generics.
Here are some uses cases:
```js
// current
const texture = Texture.from('path/to/image.png');
const url = (texture.baseTexture.resource as ImageResource).url;
// new!
const texture = Texture.from<ImageResource>('path/to/image.png');
const url = texture.baseTexture.resource.url;
```
```js
// current
const url = (sprite.texture.baseTexture.resource as ImageResource).url;
// new!
const texture = sprite.texture as Texture<ImageResource>;
const url = texture.baseTexture.resource.url;
```
```js
// current
const base = BaseTexture.from("path/to/image.svg", {
resourceOptions: { anything: 'goes' } // <-- NO TYPE CHECKING HERE
});
// new!
const base = BaseTexture.from<SVGResource, ISVGResourceOptions>("path/to/image.svg", …
```

Add Generics to Texture, BaseTexture for Resource types

---

packages/core/src/geometry/BufferSystem.ts
packages/core/src/shader/GLProgram.ts
packages/core/src/shader/ShaderSystem.ts
packages/core/src/shader/UniformGroup.ts
packages/core/src/shader/utils/generateUniformBufferSync.ts
packages/core/src/shader/utils/generateUniformsSync.ts
packages/core/src/shader/utils/uniformParsers.ts
packages/core/test/shader/UniformBuffer.js

Final pass on ubo functionality
- added `bindBufferRange`
- optimised uniform reading in generateSync
- fixed up a few binding issues with ubos

updates to ubo

---

packages/display/src/Container.ts

pixi.js@6.0.0-rc.2
TypeScript:
```ts
class A extends PIXI.Container {
constructor() {
super()
// There is no `addChild` method because it is `DisplayObject`
this.parent.addChild
}
}
```

Fixed Parent type for Container

---

packages/utils/package.json
packages/utils/src/index.ts
packages/utils/src/network/determineCrossOrigin.ts
packages/utils/src/url.ts

Moved the `utils` Node types dependency to a dev dependency. Had to redeclare types for Node `url` and `querystring` packages for the `utils.url` export.
Fixes #7283

Remove utils dependency to Node types

---

.eslintrc.json
packages/core/src/batch/BatchSystem.ts
packages/core/src/context/ContextSystem.ts
packages/core/src/filters/FilterSystem.ts
packages/core/src/framebuffer/FramebufferSystem.ts
packages/core/src/geometry/GeometrySystem.ts
packages/core/src/mask/AbstractMaskSystem.ts
packages/core/src/mask/MaskSystem.ts
packages/core/src/projection/ProjectionSystem.ts
packages/core/src/renderTexture/RenderTextureSystem.ts
packages/core/src/shader/ShaderSystem.ts
packages/core/src/state/StateSystem.ts
packages/core/src/textures/TextureGCSystem.ts
packages/core/src/textures/TextureSystem.ts

Fixes #7276 
Unfortunately, parameter properties aren't quite ready for Webdoc [related](https://github.com/webdoc-labs/webdoc/issues/98). This is an easier to fix to unblock the current broken docs.

Workaround webdoc parsing crash

---

packages/loaders/src/Loader.ts
packages/loaders/src/LoaderResource.ts
packages/spritesheet/global.d.ts
packages/spritesheet/src/Spritesheet.ts

Replaces #7295
* Remove the `@pixi/spritesheet` dependency from `@pixi/loaders`
* Fix the `resources` type for Loader to be more strict (e.g., contains `texture`) credit: @AdrienLemaire
* Added some additional documentation for Loader interfaces

Remove spritesheet dependency from loader, fix resources type

---

.github/workflows/nodejs.yml

Made these changes to the workflow so I could iterate more freely on some of the tooling related to unit-tests and I thought it would be valuable for other users too. 
* Allows running GitHub Actions on forks by checking for and excluding steps that require secrets (e.g., codecov, s3 deployment)
* Cleaned up common env variables to be at the top of the workflow
* Externalize AWS_REGION in case someone wants to implement their own deployment on a fork
* Removes Node.js matrix, as we only really need to practically test on a single Node version
* [Fork Actions](https://github.com/bigtimebuddy/pixi.js/runs/2148901897?check_suite_focus=true) (ignores Codecov & S3)
* [Branch Actions](https://github.com/pixijs/pixi.js/runs/2148997163?check_suite_focus=true) (runs Codecov & S3)

Support running GitHub Actions on Forks and other workflow cleanup (take 2)

---

packages/display/src/DisplayObject.ts
packages/display/test/DisplayObject.js

Add `destroyed` event to `DisplayObject.destroy()`.
I need it sometimes.
(`removed` event is almost insufficient.)

feat(DisplayObject): Add `destroyed` event

---

packages/mesh-extras/test/SimplePlane.js
packages/sprite/test/Sprite.js

This tests are using the old deprecated syntax for RenderTexture.create. Updated tests to use the new API.

Remove deprecation warnings in tests

---

packages/utils/src/index.ts
packages/utils/src/network/determineCrossOrigin.ts
packages/utils/src/url.ts

Follow-up to #7286
API Extractor was failing on utils [here](https://github.com/pixijs/pixi.js/runs/2171709081#step:11:128), because of how the typings were being exported. I tweaked this a little to not have type generator complain. Also, removed the export for the Node url types/interfaces, which seem unnecessary.
cc @qtiki

Fix url package types for API extractor

---

packages/text-bitmap/src/BitmapFont.ts
packages/text-bitmap/src/BitmapFontLoader.ts
packages/text-bitmap/test/BitmapFontLoader.js

Fixes #7323
Unchanged behavior: BitmapFont page Textures are automatically destroyed when:
* ... loaded with `BitmapFontLoader`
* ... created with `BitmapFont.from`
New behavior: BitmapFont page Textures are _preserved_ when:
* ... manually created with `BitmapFont.install(fontData, texture)`
This is consistent with how PixiJS respects objects that are passed externally versus generated internally. Another example of this is Graphic and GraphicsGeometry. If passed to the constructor, Graphics will ignore destroying its geometry.

Fix BitmapFont destroying respects external Textures

---

packages/events/src/EventSystem.ts

Small bug I found while I was making [this](https://pixijs.io/examples/#/events/slider.js) example earlier today.

Fix wheel events not getting a nativeEvent

---

packages/core/src/ISystem.ts

Follow up to #7269
This properly deprecates System to support 3rd-party custom Renderer systems. @SukantPal pointed this out, he has a few plugins that do this path.

Fix deprecation for System class

---

packages/basis/src/BasisLoader.ts
packages/compressed-textures/src/loaders/CompressedTextureLoader.ts
packages/compressed-textures/src/loaders/DDSLoader.ts
packages/compressed-textures/src/loaders/KTXLoader.ts
packages/compressed-textures/src/loaders/registerCompressedTextures.ts

Partially fixes #7329
* The Loader's resource was not getting populated with the Texture being created, the only way to fetch this was by using the TextureCache.
* Fixes an issue where the first compressed texture resource was creating two Textures
* Properly handle errors internally and passed them to the loader instead of throwing globally
* Supports passing options to the BaseTexture constructor using LoaderResource's metadata
* Fixes baseUrl or path for loading manifest of compressed textures

Populate the Loader resource with Texture objects for basis and compressed-textures

---

packages/core/src/geometry/Buffer.ts
packages/core/src/shader/UniformGroup.ts

This was failing @pixi/tilemap's build against latest PixiJS. Can we get this merged ASAP so that the CI can pass there?
https://github.com/pixijs/tilemap/pull/117/checks?check_run_id=2265403059

Don't import BUFFER_TYPES from @pixi/constants/src (exclude src)

---

packages/events/src/EventBoundary.ts

This will allow developers to modify `event.global` before hit-testing actually happens. (Useful for projections!)

Fix - Hit-test after the event has been copied

---

package-lock.json
packages/events/src/EventBoundary.ts
packages/events/src/EventSystem.ts
packages/events/src/FederatedPointerEvent.ts
packages/events/test/EventBoundary.js

In this [example](https://pixijs.io/examples/#/events/hit-testing-with-spatial-hash.js) (before this PR is merged!), errors are thrown in the `pointerout` event dispatch because I remove each character on click. This is fixed by finding the most specific ancestor of the original target **that is still mounted**.
---
**Additional change**: Add `getCoalescedEvents` and `getPredictedEvents` to `FederatedPointerEvent` as they're new APIs and are needed to correctly implemented `PointerEvent` (was getting type errors).

Fix EventBoundary crashing when the pointerupoutside, pointerout target is unmounted from the scene graph.

---

packages/canvas/canvas-display/global.d.ts
packages/canvas/canvas-graphics/global.d.ts
packages/canvas/canvas-mesh/global.d.ts
packages/canvas/canvas-sprite/global.d.ts

This seems to be a problem when trying build external packages against latest PixiJS in their CI.

Declare _renderCanvas, _generateCanvasTexture as a methods not function properties

---

packages/spritesheet/global.d.ts

The interface `Texture` in GLobalMixins is mostly empty, its for mixins, so we cant really pass that interface to actual methods
Currently this fails:
```ts
new Sprite(resources['atlas'].textures['apple.png']);
```
Test: https://codesandbox.io/s/pixitilemap-typings-test-m5pb8?file=/src/index.ts 
Uncomment line 16, get an error

typings fix for LoaderResource texture

---

packages/core/src/geometry/Buffer.ts

`const geom = new Geometry().addAttribute('aVertexPosition', [/* blah */]);` supports normal arrays.
However, `geom.getBuffer('aVertexPosition').update([/* blah */])` does not.
This addition will make the API more uniform and less surprising.

Allow supplying arrays to Buffer.update()

---

packages/loaders/src/AppLoaderPlugin.ts

Found a small bug when trying to do a minimal install with core, loaders, ticker and utils. There was a dangling app reference in loaders that threw an error. This decouples these types.

Remove application dependency on loader

---

package-lock.json

Seems that the package-lock is not updated when Lerna does a bump. Need to find a better solution, but this is an update of the file. Might report to Lerna or do a postversion npm install.
Edit: Probably related to this bug https://github.com/lerna/lerna/issues/2832

package-lock.json not updated on version bumping

---

packages/core/src/textures/TextureSystem.ts
packages/core/test/TextureSystem.js

Little tweak to support the RGB Float format.
Number of if statements is getting a bit high - we could switch this up to use a hash map if it needs any more!
test included..

add support for RGB Float

---

package-lock.json
packages/text/src/Text.ts

Fixes #7344
This way the text lines are not aligned to the top. The result looks similar to the HTML example and it does not seem to break when `lineHeight` is set to 0.

Fix text linePositionY

---

scripts/injectGlobalMixins.ts

Want to have a namespace called `PIXI` just like `v5`. It's easy to do some custom configuration in `vscode`.
Now: 
https://unpkg.com/browse/pixi.js@6.0.2/index.d.ts
```ts
export {}
```
This PR will replace it with:
```ts
export as namespace PIXI;
```

Add the export namespace to the declaration file

---

packages/mixin-cache-as-bitmap/src/index.ts

Restore original alpha value of cached node, otherwith we corrupt node state and alpha will be missed while not changed outside after first calling a  `_initCachedDisplayObject`
Fix #7432

fix: Restore original `alpha` value for cacheAsBitmap 

---

packages/canvas/canvas-display/global.d.ts
packages/canvas/canvas-graphics/global.d.ts
packages/canvas/canvas-mesh/global.d.ts
packages/canvas/canvas-sprite/global.d.ts
packages/mixin-cache-as-bitmap/global.d.ts
packages/mixin-get-child-by-name/global.d.ts
packages/mixin-get-global-position/global.d.ts

Follow up to #7451
Conversation context #7444
This change makes the global mixins non-optional. Some of these were optional that shouldn't be.

Fix GlobalMixins to be avoid issues with strictNullChecks

---

packages/sprite-tiling/src/TilingSprite.ts
packages/sprite-tiling/test/index.js

Fixes TilingSprite.from usage with a Texture parameter

---

.github/workflows/nodejs.yml

The weird test failures in #7475 happened to overlap with the release of npm 7.12.0 yesterday. I have pinned our CI to 7.11.2 until this can be resolved.
Fixes #7475

Fixes unit-test failures from npm@7.12.0

---

packages/canvas/canvas-mesh/src/CanvasMeshRenderer.ts

The math is flawed: https://www.pixiplayground.com/#/edit/i57Nv699UIsCI3y5wczPd. Fixed it.

Fix Mesh.canvasPadding

---

packages/core/src/textures/resources/VideoResource.ts

Fixes #7400
This will help in debugging (so developers don't think there's a listener leak in disposed VideoResources)

Set _isConnectedToTicker to false when disposing VideoResource

---

packages/core/src/shader/utils/uniformParsers.ts

Fixes #7421 
This basically matches what we had in `UBO_TO_SINGLE_SETTERS` when you passed an array instead of `Matrix`.
You can verify the fix by using this branch's build in https://replit.com/@SukantPal/UBOs#main.js and remove the `toArray` here (tested this locally)

Fix UBO handling mat3 Matrix uniforms

---

packages/core/src/geometry/Geometry.ts
packages/core/test/Geometry.js

Fixes #7456
Add the size of the currently geometry to the vertex offset (instead of the last geometry). That means the vertices of the next geometry will get the current offset in the out-geometry.

Fix geometry merging when geometries are of different sizes

---

packages/core/src/filters/FilterSystem.ts
packages/core/test/FilterSystem.js

Fixes #7468 
Use floating-point equality test instead

Fix filter-system frame rounding precision-issue

---

packages/core/src/textures/GLTexture.ts

Swap the default values of `GLTexture.type` and `GLTexture.internalFormat`, because it's the wrong way around.
```
GL_UNSIGNED_BYTE = 5121
GL_RGBA          = 6408 
```

Fix default type and internalFormat of GLTexture

---

packages/graphics/src/utils/buildRoundedRectangle.ts

Fixes #7515 
~~There was a similar hack in v4 that somehow got removed although the comment was still there! This applies a similar workaround to v6. If someone has a better idea how to fix, welcome! I believe this is an earcut issue ultimately.~~ Found a better hack-less solution.
Broken (v6.0.4)
https://jsfiddle.net/bigtimebuddy/kphz6o8e/
Fixed (fix/rounded-rect-max-radius)
https://jsfiddle.net/bigtimebuddy/9pneg8Lb/

Fix regression in RoundedRectangle

---

packages/graphics/src/GraphicsGeometry.ts

fix: https://github.com/pixijs/pixijs/issues/7512
Fix filling color and textureId attributes for un-batched rendering mode.
Bug reproduce on all versions since 5.*
https://www.pixiplayground.com/#/edit/G8DSY5iggOY3xtR4mRzxA

Fix: Graphics color/textureId filling

---

packages/core/src/shader/utils/getAttributeData.ts

Fix for:
https://github.com/pixijs/pixijs/issues/7526
We can't activate built-in attributes, but they represented in `activeAttributeList`

Ignore built-in attributes that start with 'gl_'

---

.github/workflows/nodejs.yml

Needed to fix the publishing workflow for the following reasons:
* npm publishes should happen after a release is officially published on GitHub, so release/notes/etc are always available before being on npm on CDN. 
* would like to synchronize around the GitHub publish as being the official publishing event
* this change introduces a way to publish prereleases to a different dist-tag (so I can publish v6.1.0-rc)
* in general, simplifies the action `if` conditions, which were complicated

Add automated publishing case for prereleases

---

package-lock.json
packages/filters/filter-color-matrix/src/ColorMatrixFilter.ts

Added `tint(color, multiply)` method to ColorMatrixFilter. It transforms the matrix to achieve an effect similar to the `tint` field of sprites. This was a feature discussed on slack.
(no ColorMatrixFilter specific tests exist)

Added `tint(color, multiply)` method to ColorMatrixFilter.

---

packages/text/src/Text.ts

Fixes #7551 
Since resolution basically scales the Text's canvas, it makes sense to multiply the canvas dimensions _after_ rounding it - where the rounded dimensions are natural 1x scale dimensions.
(before) https://jsfiddle.net/ShukantPal/29Lz8xej/
(after) https://jsfiddle.net/ShukantPal/Lkbqvs0y/

Fix canvas resizing in Text when resolution is not 1

---

packages/compressed-textures/src/loaders/CompressedTextureLoader.ts

Fixes #7554 
Replace error log with warning log.

Warn instead of error log when compressed textures are not available

---

packages/core/src/textures/BaseTexture.ts
packages/text/src/Text.ts

Fixes #7540 
This change will make the vertical gradient handle cases in which consecutive lines overlap. It will calculate the midpoint between the prior line's bottom and next line's top and check if they are in increasing order; if not, it will set the gradient stop at their midpoint (for both prior & next line). There are two cases for this - previous line's bottom and current line's top, current line's bottom and next line's top.
(before) [https://pixijs.io/pixi-text-style/#%7B%22s...](https://pixijs.io/pixi-text-style/#%7B%22style%22%3A%7B%22fill%22%3A%5B%22white%22%2C%22red%22%5D%2C%22fontSize%22%3A86%2C%22lineHeight%22%3A50%2C%22padding%22%3A10%7D%2C%22text%22%3A%22Hello%5CnWorld%22%2C%22background%22%3A%22%23000000%22%7D.)
| lineHeight=66px | lineHeight=50px |
| ---------------- …

Fix Text vertical gradient so that it handles overlapping lines

---

packages/compressed-textures/src/loaders/CompressedTextureLoader.ts

This changes the documentation for the compressed loader.
I don't know why the old docs talk about the manifest filename being required to contain `compressed-texture` in the name and the json format being different.
Rewrote it to better reflect what the code expects.
I wanted to comment this on #7584 but work got in the way and it got merged because I could do it 😅 
Rewrote the documentation of `compressed-loader` because the old one was incorrect (probably outdated).

Fixed wrong information on the compressed-loader docs

---

test/index.ts
test/packages.ts

This change groups unit-tests together by package name. This should make it easier to identify the source of problems, especially where some tests names might overlap, in the case of mixins or canvas packages.
```
@pixi/canvas-mesh
NineSlicePlane
✓ should be renderable with renderTexture in canvas
@pixi/canvas-renderer
CanvasMaskManager
✓ should work on all graphics masks inside container
✓ should set correct transform for graphics
CanvasRenderer
✓ should default context to rootContext
✓ should allow clear() to work despite no containers added to the renderer
✓ should update transform in case of temp parent
@pixi/app
Application
✓ should generate application
✓ register a new plugin, then destroy it
✓ should remove canvas when destroyed
✓ should not destroy children by default
✓ should …
```

Group unit-tests together by package name

---

test/index.ts

Small platform bug running execFileSync on Windows machines that prevented running of unit-tests.

Fix running unit-tests on Windows

---

packages/basis/src/Basis.ts
packages/core/src/shader/GLProgram.ts
packages/display/src/DisplayObject.ts
packages/mesh-extras/src/geometry/PlaneGeometry.ts

There were a few private classes popping up in the docs, as well as some classes not part of `PIXI`.  This tidies this up.
Before: https://pixijs.download/dev/docs/index.html
After: https://pixijs.download/fix/docs-cleanup/docs/index.html

Fix minor documentation errors

---

packages/events/global.d.ts
packages/events/src/EventBoundary.ts
packages/events/src/FederatedEventTarget.ts
packages/interaction/global.d.ts

Fixes #7611
Interaction and Events had incongruent overlapping types because cursor was different. This resolves that issue.

Fix overlapping types of events and interaction

---

packages/core/src/framebuffer/FramebufferSystem.ts
packages/core/test/RenderTexture.tests.ts

This fixes a severe bug in `Framebuffer.forceStencil` that in combination with filters had the effect that stencil masks didn't work at all. `forceStencil` calls `enableStencil`, which invalidates the framebuffer. So when the first stencil mask is drawn, `forceStencil` is called, and the current framebuffer is invalidated. Then the filter textures are bound and afterwards the render target again. But since it was invalided, `updateFramebuffer` is called: the stencil buffer is reinitialized and therefore wiped.
Before the multisample fix PR `updateFramebuffer` failed to resize/update the stencil buffer. That bug canceled the bug in `forceStencil`. `forceStencil` must not invalidate the framebuffer, but only create and attach the stencil buffer if necessary. This was fixed by replacing …

Fix bug in FramebufferSystem.forceStencil

---

packages/core/src/AbstractRenderer.ts

Follow-up to #7440, converts the options for `generateTexture` into object instead of parameters. 
```ts
renderer.generateTexture(displayObject, scaleMode, resolution, region)
```
With the addition of `multisample` option, this should become an object, having more than a few options is quite cumbersome.
```ts
renderer.generateTexture(displayObject, { scaleMode, resolution, region, multisample });
```
This is much more flexible and allows you to only set a single parameter without having to add a bunch of undefineds.
```ts
renderer.generateTexture(displayObject, { multisample: MSAA_QUALITY.MEDIUM });
renderer.generateTexture(displayObject, { region: new Rectangle(100, 100, 200, 500) });
```

Convert optional generateTexture args to options

---

packages/core/src/AbstractRenderer.ts

Issue brought up in #7633 and follow-up to #7629.
Workaround for underlying issue https://github.com/webdoc-labs/webdoc/issues/133
Broken: https://pixijs.download/dev/docs/PIXI.Renderer.html#generateTexture (show deprecated only)
Fixed: https://pixijs.download/fix/generate-texture-docs/docs/PIXI.Renderer.html#generateTexture (show non-deprecated only)

Workaround webdoc issue with overloading and inheritance

---

packages/graphics/src/Graphics.ts
packages/graphics/test/Graphics.tests.ts

Fix #7620 so that Graphics drawn with `lineTo()` and completed with `closePath()` don't have to be rendered to be interacted with.

Fix #7620 - Interaction with unrendered Graphics

---

packages/core/src/Renderer.ts
packages/core/test/Renderer.tests.ts

Fixes #7628.
I probably made a mess overriding the method: I copied all the method definitions from `AbtractRenderer`. But I noticed that the new version `generateTexture` doesn't show up in the `Renderer` [docs](https://pixijs.download/dev/docs/PIXI.Renderer.html); only the deprecated version for some reason.

Blit in Renderer.generateTexture

---

packages/core/src/Renderer.ts

This adds the multisample property to `Renderer`, which returns the number of msaa samples of the canvas.
The documentation of `gl.getParameter(gl.SAMPLES)` is somewhat limited (at least I didn't find much with respect to the webgl canvas), but I tested it in Firefox and Chrome, and it works.
This is much better and much more convenient than the following, which I used in #7618 and proposed in #7441. Also since the `antialias` parameter is merely a hint that can be ignored by the browser the following code isn't even correct technically.
```js
if (renderer.gl.getContextAttributes().antialias) {
multisample = MSAA_QUALITY.HIGH;
} else {
multisample = MSAA_QUALITY.NONE;
}
```
Also the default framebuffer msaa samples at least on my machine in Firefox and Chrome is 4; so HIGH samples would …

Add multisample property to Renderer

---

packages/core/src/textures/TextureSystem.ts
packages/core/test/TextureSystem.tests.ts

Binding an invalid texture does nothing at the moment, i.e. the texture bindings don't change. Consequently, the last bound texture is used instead: [example](https://www.pixiplayground.com/#/edit/BLiI4gXywBluF0E6IJXJa). I assume this is not intended. It should bind an empty texture.

Bind empty if texture is invalid

---

packages/mixin-cache-as-bitmap/src/index.ts

This was something I included in #7441 at first, but then removed it. Now we have `Renderer.multisample`, so it can be done correctly.
The default multisample is still `NONE`.

Add automatic multisample selection option to cacheAsBitmap

---

packages/events/src/EventSystem.ts

`removeEvents` was not setting the `eventsAdded` back to false and thus, the first check on `addEvents` was returning early, making it impossible to re-add the events.

@pixi/events: removeEvents() now sets eventsAdded to false

---

packages/core/src/geometry/GeometrySystem.ts

Fixes #7674
There was a reference to Buffer without import which was adding node types inappropriately.

Remove node types from leaking in core package

---

packages/accessibility/package.json
packages/accessibility/src/AccessibilityManager.ts
packages/mixin-cache-as-bitmap/global.d.ts
packages/mixin-cache-as-bitmap/package.json
packages/mixin-cache-as-bitmap/src/index.ts

Remove CanvasRenderer types from mixin-cache-as-bitmap and accessibility

---

packages/spritesheet/src/Spritesheet.ts

Typings fix: Spritesheet.parse method now accepts a list of textures as…an argument for the callback
When using spritesheet parse method, the client now do the following to get the textures in callback
```js
spritesheet.parse((textures: Texture[]) => {
console.log(textures);
});
```

Typing fix

---

packages/core/src/shader/utils/getAttributeData.ts

fix for: #7775 
`startsWith` not exist on IE11, replace onto `indexOf() === 0`

Fix degradaton on IE11

---

packages/accessibility/src/accessibleTarget.ts

This fixes a minor type convenience issue: `accessibleChildren`'s type is defined as `true` (with `undefined` being allowed via `Partial`), and although this works fine, it's a `boolean` in practice, and the overly strict type can lead to more verbose/non-idiomatic code, e.g.
```ts
container.accessibleChildren = someCondition ? true : undefined; // valid
```
vs
```ts
container.accessibleChildren = !!someCondition; // Type 'boolean' is not assignable to type 'true | undefined'
```
- ~[ ] Tests and/or benchmarks are included~ N/A
- ~[ ] Documentation is changed or added~ N/A

Fix accessibleChildren type

---

packages/core/src/mask/StencilSystem.ts

The bit mask returned by `_getBitwiseMask` doesn't seem to make a lot of sense. Maybe it's a leftover from a previous implementation. So I removed it.
Bonus bug fix: `gl.clearStencil(0)` needs to be before `gl.clear(gl.STENCIL_BUFFER_BIT)` not after.

Remove StencilSystem._getBitwiseMask

---

packages/canvas/canvas-sprite/src/CanvasSpriteRenderer.ts
packages/canvas/canvas-sprite/test/.eslintrc.json
packages/canvas/canvas-sprite/test/CanvasSpriteRenderer.tests.ts

Move
`if (!texture.valid) return; `
so that it comes before the call to 
`texture._frame.width `
This prevents a crash when destroying the texture of a sprite currently being rendered.

Move texture.valid check

---

package-lock.json
package.json
packages/graphics/src/Graphics.ts

Unblocks #7787 
You can see that `Graphics.shader` no longer needs the explicit `@member` tag now.

Chore: Upgrade webdoc to 1.5.3 so we can strip out @member data-types

---

packages/core/src/filters/Filter.ts

This PR is an attempt to fix this issue that I've had with the PIXI Advanced Blur Filter (documented here: https://github.com/pixijs/filters/issues/301). I describe the issue in detail there, but here's a short summary:
`Filter` has a public property named `resolution`.  `AdvancedBloomFilter` overrides this property with an accessor named `resolution`. `AdvancedBloomFilter` maintains a private `_resolution` property which is set by this accessor (along with some other side-effects, which seems to be the whole purpose of using an accessor instead of a property).
However, as of https://github.com/microsoft/TypeScript/pull/37894, `tsc` now treats overriding a property with an accessor as an error.
This PR converts the definition of `resolution` in the base `Filter` class to an accessor to …

Convert Filter resolution from property to accessor

---

packages/spritesheet/src/SpritesheetLoader.ts
packages/spritesheet/test/SpritesheetLoader.tests.ts

Fix SpritesheetLoader to pass metadata to all loaded multipack resources, currently, metadata are used only to the first (parent) resource.
Related Issue: https://github.com/pixijs/pixijs/issues/7714

Fix spritesheetLoader to pass metadata to all loaded multipack resources (#7714)

---

packages/mesh/src/Mesh.ts
packages/mesh/test/Mesh.tests.ts

I added getter and setters for `Mesh.geometry`. I didn't see a reason why this property should be read only.

Make Mesh.geometry writable

---

packages/display/src/DisplayObject.ts
packages/display/test/DisplayObject.tests.ts

Multiple objects having the same mask is possible, but the code doesn't seem to be written with that in mind. `isMask` can easily end up being false even if the object is still used as a mask. The current implementation can cause problems if the mask object is before the object that is masked in the scene graph: the mask is rendered normally for one frame after isMask is set to false and renderable to true when the mask is removed from another object; isMask remains false, but renderable is set to false again by the mask system. Here a demo where the the mask is added and removed from some other object every frame and so the mask is rendered normally in the background. https://www.pixiplayground.com/#/edit/jC73hmNsD59Hgyp6kseVL. If the mask is after the all objects that use the mask in …

Allow multiple objects to have the same mask

---

packages/core/src/textures/resources/VideoResource.ts

Fixes #7810 
Since VideoResource extends BaseImageResource the `source` property is type `HTMLImageElement|HTMLCanvasElement|HTMLVideoElement|ImageBitmap` when we actually should be more specific. This change forces `source` as video element so remove the need to cast source.

VideoResource should override source type

---

packages/extract/src/Extract.ts

Hi there -- just a one-character fix for the type of `Extract.pixels` to align it with the documented parameter (according to the description it should be optional).
Unsure if there are applicable lints or tests -- unfortunately I'm just evaluating whether Pixi is a viable option so I don't have time to clone and run tests as noted in the checklist below. Hope your CI covers these cases!

Annotate Extract.pixels parameter as optional

---

packages/core/src/shader/utils/generateUniformsSync.ts

Fixes inactive `null`/`undefined` uniforms breaking uniforms sync generation.
Playground: https://www.pixiplayground.com/#/edit/HGD9TE6ISB-5ePVIvQOF8
`test` is an inactive uniform that is assigned `null`, which breaks the uniforms sync generation:
```
Uncaught TypeError: group.uniforms[i] is null
generateUniformsSync core.js:6941
createSyncGroups core.js:9230
syncUniforms core.js:9224
syncUniformGroup core.js:9214
bind core.js:9189
```

Fix uniforms sync generation of inactive null uniform

---

packages/core/src/geometry/Attribute.ts
packages/core/src/geometry/Geometry.ts

It currently says that `stride` is in floats, but that's not true. It's bytes:
https://github.com/pixijs/pixijs/blob/bf8f1edfb5da55133d581498760017c1ab886026/packages/core/src/geometry/GeometrySystem.ts#L519-L524

Fix Geometry/Attribute stride documentation

---

packages/core/src/shader/utils/generateProgram.ts
packages/core/src/shader/utils/getAttributeData.ts

Not sure why the attribute location are manually bound instead of using the locations the compiler/linker chose (`getAttribLocation`). Shaders with layout location specifiers do not work because of this (layout location specifiers cannot be overridden): https://www.pixiplayground.com/#/edit/GleYmYB2SrVtbDyw5Tlhv.

Fix attribute location

---

packages/prepare/src/BasePrepare.ts

Fix argument types of BasePrepare.upload() and BasePrepare.add() - they don't accept upload hooks, and do accept textures & containers (the DisplayObjectExtended covers sprites, text, and graphics).

Fix parameter typings of BasePrepare

---

.github/workflows/nodejs.yml
package-lock.json
package.json

Fixes #7964
This allows npm@>=7, but restricts usage when doing a release.

Check specific npm version when doing a release

---

packages/mixin-cache-as-bitmap/src/index.ts
packages/mixin-cache-as-bitmap/test/cacheAsBitmap.tests.ts

In initCachedDisplayObject, it adds padding from the first filter applied to the DisplayObject if the filters property is truthy, meaning it would attempt to do so even if filters was an empty array. This change checks that's not an empty array, preventing a crash in such a scenario.

Fix crash creating cached bitmap when filters is empty array

---

packages/core/src/mask/StencilSystem.ts

Fixes #6822.
I moved the stencil buffer clear to push out of pop so that the stencil buffer is cleared immediately after it is created and therefore cleared before it is used the first time. I assume that the stencil buffer may be in some sort of undefined state until it is cleared the first time, and that's why the stencil mask fails the first time something with a mask is rendered to the render texture. I couldn't find anything on default/initial stencil buffer (or render buffer) values, so I assume it's undefined.

Clear stencil buffer in push instead of pop

---

packages/math/src/shapes/Circle.ts

Fixed the documentation for radius member of `PIXI.Circle`. It said the default value of `radius` is `1` but it is actually `0`. If it's the other way round, that the documentation is correct and the default value is supposed to be `1` instead of `0` then I can make that change in a different PR.

Fix radius documentation for `PIXI.Circle`

---

packages/core/src/filters/FilterSystem.ts

This fixes legacy filters that use `filterArea`/`filterClamp` failing the first time they are used. The first time a filter is used, the `legacy` property is still undefined. This property is set after the filter is bound the first time. Until it is bound for the first time, we don't know whether it's a legacy filter, because `attributeData` isn't available yet. But we need to update the `filterArea` and `filterClamp` uniforms before that if it's a legacy filter. So the first time a filter is used we have to assume it's a legacy filter, otherwise `filterArea` and `filterClamp` are not updated, and the first render fails if it's a legacy filter.
Example that show that the glow filter fails the first time it's used: https://www.pixiplayground.com/#/edit/JprzRXPURW8S0JU3tuIQZ

Fix legacy filters failing the first time they are used

---

packages/ticker/src/Ticker.ts

fix comment for `_minElapsedMS` in Ticker.ts

typo fix in Ticker.ts

---

packages/graphics/src/Graphics.ts

Demo of failure: https://www.pixiplayground.com/#/edit/h0Qpfm3WlcSSgJP6FAvdG
I kept the check simple, but we could also add the same check as in `ScissorSystem.isMatrixRotated` if that is preferred.

Fix isFastRect returning true if the rectangle is rotated

---

packages/core/src/filters/FilterSystem.ts

It's a tiny optimization, but more importantly: we cannot allow `roundFrame` to continue with an empty `bindingSourceFrame`, because `frame` is NaN at the end otherwise, and that can't be good.
```js
transform
.translate(-bindingSourceFrame.x, -bindingSourceFrame.y)
.scale(
bindingDestinationFrame.width / bindingSourceFrame.width,   // <====
bindingDestinationFrame.height / bindingSourceFrame.height) // <====
.translate(bindingDestinationFrame.x, bindingDestinationFrame.y);
```

Skip rounding in FilterSystem.roundFrame if frame or bindingSourceFrame is empty

---

packages/text/src/Text.ts

Fixed the problem that the text display overlaps when inputting a character string in which pictograms are mixed while the letterSpacing option of ITextStyle is specified to be other than 0.
before:
after:

Fix the text display becomes strange, when emoji is entered with letterSpacing specified

---

packages/sprite/src/Sprite.ts
packages/sprite/test/Sprite.tests.ts

Currently `getLocalBounds` modifies and corrupts the `_bounds` of the sprite so that subsequent `getBounds(true)` calls return the local bounds instead of the global bounds. This PR fixes that.

Fix Sprite.getLocalBounds corrupting bounds

---

package-lock.json
packages/core/package.json

Adds `@types/offscreencanvas` dependency in the core package
OffscreenCanvas is referenced in the following packages:
* `@pixi/core`
* `@pixi/events`
* `@pixi/interaction`
* `@pixi/text`
Fixes #8174

Add OffscreenCanvas types as dependency

---

packages/core/src/renderTexture/BaseRenderTexture.ts

Fixes #8203
Uses a default object for constructor when creating BaseRenderTexture to keep from throwing an error when `RenderTexture.create()` is called without any arguments
Broken: https://pixiplayground.com/#/edit/WyW883F5ti4y0JuM538ap
Fixed: https://pixiplayground.com/#/edit/l2EClJqfIQW2U8aabLAcQ

Use a default object when creating a RenderTexture

---

packages/math-extras/global.d.ts

Fixes #8200 
Remove the **global.d.ts** typing for `divide` math-extras until it's implemented.

Temporarily remove math-extra divide

---

packages/core/src/textures/resources/BaseImageResource.ts

Fixes #7457.
Don't upload to the texture if the image/video resource isn't ready.

Check if image/video resource is ready for upload

---

packages/core/src/framebuffer/FramebufferSystem.ts

`gl.blitFramebuffer` are passed incorrect arguments: the source/destination rectangles are defined by two points and not x, y, width, height.

Fix blitFramebuffer

---

packages/core/src/renderTexture/RenderTexturePool.ts
packages/core/test/RenderTexturePool.tests.ts

Currently the render texture pool does not return a screen-sized render texture with some noninteger resolutions because of floating point inaccuracies. I added a small epsilon to the ceil in `getOptimalTexure` to fix that problem.

Fix rounding in getOptimalTexture

---

packages/events/src/FederatedEventTarget.ts
packages/interaction/src/interactiveTarget.ts

This is needed to be able to remove hitAreas again. Also, the default for hitArea is null, so this is now properly reflected in the type.
Added possible type `null` to `hitArea` of `InteractiveTarget` (that is extended by `DisplayObject`).

hitArea can also be null (fixing #8212)

---

packages/graphics/src/GraphicsGeometry.ts

Hole outlines are currently not rendered if the fill style is not visible, because `processHoles` is called in `processFill`: https://www.pixiplayground.com/#/edit/Ta76oELE3aRp8_YSQGyAp
After the change:

Fix hole outlines not rendering if fill style is not visible

---

packages/graphics/src/utils/buildPoly.ts

Line alignment of polygons currently depends on the orientation of the passed polygon/points: https://www.pixiplayground.com/#/edit/RmpbM3I1RvPlooXF8z1Kz.
The documentation says that 0 alignment is inner and 1 is outer. So the orientation of the points needs to be fixed.

Fix line alignment of polygons

---

packages/canvas/canvas-graphics/src/CanvasGraphicsRenderer.ts
packages/canvas/canvas-renderer/src/canvasUtils.ts
packages/core/src/textures/resources/VideoResource.ts
packages/loaders/src/Loader.ts
packages/loaders/test/fixtures/spritesheet.ts
packages/utils/src/color/hex.ts

[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.

refactor: replace deprecated String.prototype.substr()

---

packages/graphics/src/utils/buildCircle.ts

If the radius of a rounded rectangle is zero, the new implementation `buildCircle` produces this: 
After the fix:

Fix rounded rectangle with zero radius

---

package.json

#8274 passed the build even though `build:types` failed locally. This should prevent such a regression.

Chore: Add build:types to dist workflow

---

packages/settings/README.md

The example import statement on the README.md Usage of @pixi/settings 
before this commit:
```js
import * as settings from '@pixi/settings';
```
after this commit: 
```js
import { settings } from '@pixi/settings';
```
I checked it out that the latter is the right one. If someone import like the former, the changed values of pixi settings are not shared by other modules.

Update README.md of @pixi/settings to fix the example import statement

---

.github/stale.yml

We are being too aggressive with the Stale bot. People often make comments like "still an issue". This project doesn't get the level of activity for the default timeframes to be useful. I have extended the timeframes. If this is still an issue moving forward, I may consider removing stale all together.

Extending the amount of times for stale

---

README.md

We have decided to shift our online community focus to Discord away from Slack and Gitter.

Favor Discord for PixiJS community chat

---

packages/compressed-textures/src/loaders/CompressedTextureLoader.ts
packages/core/src/textures/Texture.ts
packages/loaders/src/LoaderResource.ts
packages/loaders/src/middleware/parsing.ts
packages/text/src/TextMetrics.ts

Fixes #6990
This change removes all the DOM calls at instantiation-time. As we work towards cleaning up the code to support Node.js rendering, this is an important first step to make sure DOM dependencies aren't called immediately. All code can now cleanly be require/import'd without barfing.

Chore: refactor DOM-based side effects

---

packages/spritesheet/src/Spritesheet.ts

we couldn't use the loader to develop on https://PixiTestbench.com since it's drag-n-drop with file blobs, so we needed to use the classes directly

add instructions for spritesheet without loader

---

packages/display/src/DisplayObject.ts

Clarify that the object's mask must be in the subtree of its parent in the docs, based on [this issue](https://github.com/pixijs/pixijs/issues/8372).

Clarify that the object's mask must be in the subtree of its parent in the docs

---

packages/core/src/mask/MaskData.ts
packages/core/src/mask/MaskSystem.ts
packages/core/src/mask/ScissorSystem.ts

This fixes two bugs:
- `maskObject.getBounds` must skip transform updates. Same reason as #8296.
- Before: https://www.pixiplayground.com/#/edit/b6M2O5ylXdDYqGdYfRTB5
- After: https://www.pixiplayground.com/#/edit/KwXtA13MO-k1vDmjuvQ6z
- If the same mask is used multiple times at different levels, `_scissorRect` gets corrupted and the scissor mask is not restored properly on pop.
- Before: https://www.pixiplayground.com/#/edit/DUNO0XixBNeJKvSVCnR8K
- After: https://www.pixiplayground.com/#/edit/cS-ujtnS4kKpisF3mNra8
I also removed the two `renderable` lines. They don't seem to have any purpose. `getBounds` doesn't require the object to be renderable.

Fix scissor mask bugs

---

packages/spritesheet/src/Spritesheet.ts
packages/spritesheet/src/SpritesheetLoader.ts
packages/spritesheet/test/SpritesheetLoader.tests.ts

Within the larger goal to modernize PixiJS, we'd like to remove some of the callback-style API designs and replace with Promises. Using Promises produce more readable code when used with async/await and is supported in modern browsers. 
Specifically, this change deprecates the callback on `Spritesheet.parse` and returns a Promise. This is backward compatible.
```js
// new API
await spritesheet.parse();
// deprecated API
spritesheet.parse(() => {});
```

Deprecate Callback for Spritesheet.parse

---

package-lock.json
packages/prepare/package.json
packages/prepare/src/BasePrepare.ts
packages/prepare/test/BasePrepare.tests.ts

The BasePrepare plugin had a callback for knowing when items had finished uploading/preparing. Changed this to a Promise-based API.
```js
// deprecated callback
renderer.plugins.prepare.upload(stage, () => {});
// new Promise-based api
await renderer.plugins.prepare.upload(stage);
```

BasePrepare's upload to be Promise-based

---

packages/spritesheet/test/Spritesheet.tests.ts
packages/text-bitmap/test/BitmapFontLoader.tests.ts
tools/integration-tests/test/Bounds.tests.ts
tools/integration-tests/test/getLocalBounds.tests.ts

There were a few instances in unit-tests that were throwing deprecation warnings. This upgrades these to be the most current API.

Chore: Resolve deprecation warnings in unit-tests

---

packages/core/src/textures/BaseTexture.ts

Added extra description to BaseTexture.fromBuffer docs. 
Resolves #8360

Clarified docs with BaseTexture.fromBuffer default options

---

packages/canvas-sprite/src/CanvasSpriteRenderer.ts
packages/canvas-sprite/test/CanvasSpriteRenderer.tests.ts

Fixing CanvasSpriteRenderer behaving differently to WebGL counterpart in regards to BaseTexture trimming. If a sprite's texture had custom frame, orig and trim, when using the canvas rendering, the resulting texture would have a wrong scaling. These fixes make it, that both canvas rendering and WebGL behave the same in this instance.
Bug can be reproduced here
https://www.pixiplayground.com/#/edit/8RST1GAiGaqPDUHDmKh8k

Fixing CanvasSpriteRenderer behaving differently to WebGL counterpart

---

packages/events/src/EventSystem.ts
packages/interaction/src/InteractionManager.ts

This is a small change to access the event target even if inside a shadowDOM context.  Before this 'click' and 'pointerup' events would not trigger inside a web component.  See relevant issues listed below.  The fix is implemented by accessing the first entry of `composedPath()` if it is available.  Otherwise it defaults to the previous implementation of `originalEvent.target`.  I didn't add tests to this as I'm unsure how to add a web component test case given the current test set up, but if you have any suggestions or recommendations as to how to create a test I would be happy to do so.
https://github.com/pixijs/pixijs/issues/8281
https://github.com/pixijs/pixijs/issues/7165

Fix Interactivity in ShadowDOM

---

packages/canvas-renderer/src/CanvasContextSystem.ts
packages/canvas-renderer/src/CanvasMaskSystem.ts
packages/canvas-renderer/src/CanvasObjectRendererSystem.ts
packages/canvas-renderer/src/CanvasRenderer.ts
packages/core/src/Renderer.ts
packages/core/src/background/BackgroundSystem.ts
packages/core/src/batch/BatchSystem.ts
packages/core/src/context/ContextSystem.ts
packages/core/src/extensions.ts
packages/core/src/filters/FilterSystem.ts
packages/core/src/framebuffer/FramebufferSystem.ts
packages/core/src/framebuffer/MultisampleSystem.ts
packages/core/src/geometry/BufferSystem.ts
packages/core/src/geometry/GeometrySystem.ts
packages/core/src/mask/MaskSystem.ts
packages/core/src/mask/ScissorSystem.ts
packages/core/src/mask/StencilSystem.ts
packages/core/src/plugin/PluginSystem.ts
packages/core/src/projection/ProjectionSystem.ts
packages/core/src/render/ObjectRendererSystem.ts
packages/core/src/renderTexture/GenerateTextureSystem.ts
packages/core/src/renderTexture/RenderTextureSystem.ts
packages/core/src/shader/ShaderSystem.ts
packages/core/src/startup/StartupSystem.ts
packages/core/src/state/StateSystem.ts
packages/core/src/textures/TextureGCSystem.ts
packages/core/src/textures/TextureSystem.ts
packages/core/src/view/ViewSystem.ts

Converts systems for Renderer and CanvasRenderer into extensions. Systems are now installed statically which helps unblock a handful of fixes. 
* Make EventSystem something that can be automatically installed in the bundle
* Fully deprecate interaction package
* Convert accessibility, extract, canvas-extract, prepare, canvas-prepare into systems

System Extensions

---

packages/canvas-renderer/src/utils/mapCanvasBlendModesToPixi.ts

Fixes #8457
- Replace incorrect `saturate` value for blend mode mapping with `saturation`
- ~Add `dom` lib to the `tsconfig.json` so we can use the `GlobalCompositeOperation` type to avoid this kind of error~ (needs ts 4.6+)

Fix incorrect `saturate` blend mode mapping

---

packages/assets/src/Assets.ts
packages/assets/src/cache/Cache.ts
packages/assets/src/cache/CacheParser.ts
packages/assets/src/cache/parsers/cacheSpritesheet.ts
packages/assets/src/cache/parsers/cacheTextureArray.ts
packages/assets/src/loader/Loader.ts
packages/assets/src/loader/parsers/LoaderParser.ts
packages/assets/src/loader/parsers/loadBasis.ts
packages/assets/src/loader/parsers/loadBitmapFont.ts
packages/assets/src/loader/parsers/loadDDS.ts
packages/assets/src/loader/parsers/loadJson.ts
packages/assets/src/loader/parsers/loadKTX.ts
packages/assets/src/loader/parsers/loadSpritesheet.ts
packages/assets/src/loader/parsers/loadTexture.ts
packages/assets/src/loader/parsers/loadTxt.ts
packages/assets/src/loader/parsers/loadWebFont.ts
packages/assets/src/resolver/Resolver.ts
packages/assets/src/resolver/parsers/spriteSheetUrlParser.ts
packages/assets/src/resolver/parsers/textureUrlParser.ts
packages/assets/src/resolver/types.ts
packages/assets/test/assets.tests.ts
packages/assets/test/cache.tests.ts
packages/core/src/extensions.ts

Converts the parsers to use the new extensions API
Also adds a `config` option to each parser in case you want some customizability. e.g. `preferWorker` in the `loadTexture` parser

Update asset parsers to use extensions API

---

packages/canvas-display/global.d.ts
packages/canvas-renderer/global.d.ts
packages/canvas-renderer/src/CanvasObjectRendererSystem.ts
packages/core/global.d.ts
packages/core/src/IRenderer.ts

Cleanup a few issues related to package boundaries and removed the import from `pixi.js`

Fix import issue in canvas-renderer

---

package-lock.json
packages/utils/package.json

> Changelog
>
> 2.2.4 (Jul 5, 2022)
>
> - Improved performance by 10–15%.
> - Fixed another rare race condition that could lead to an infinite loop.
> 
> 2.2.3 (Jul 8, 2021)
> 
> - Fixed a rare race condition that could lead to an infinite loop.
Shouldn't the latest version that matches the version constraint be automatically included before publishing? PIXI 6.4.2 was shipped with earcut 2.2.2, while 2.2.3 was already a year old and matches ^2.2.2.

Upgrade to earcut 2.2.4

---

packages/accessibility/src/AccessibilityManager.ts
packages/core/global.d.ts
packages/core/src/IRenderer.ts
packages/events/global.d.ts

Removes the need to cast as Renderer in accessibility by adding the EventSystem as an IRenderer member.

Chore: Remove Renderer cast in Accessibility

---

packages/assets/src/Assets.ts
packages/assets/src/resolver/parsers/index.ts
packages/assets/src/resolver/parsers/resolveSpriteSheetUrl.ts
packages/assets/src/resolver/parsers/resolveTextureUrl.ts
packages/assets/test/resolver.tests.ts

all the other parsers have a prefix e.g. `cacheX`/`loadX`
this PR just makes the resolver parsers consistent with that convention

Rename resolver parsers

---

packages/core/src/textures/resources/CubeResource.ts

This fixes an issue where Cubemap resources were not being reuploaded during a GL context loss, breaking those textures for any display objects relying on them. (#7272)

Fixes #7272 Cubemap resources not being reuploaded on GL context loss

---

packages/assets/src/cache/Cache.ts
packages/assets/src/loader/Loader.ts
packages/assets/src/resolver/Resolver.ts
packages/assets/test/cache.tests.ts
packages/assets/test/loader-compressed.tests.ts
packages/assets/test/loader.tests.ts
packages/assets/test/resolver.tests.ts

As a follow up to #8485 the add/remove parser functions have been removed
I also made all `_parser` properties private with a public getter for consistency

remove add/remove parsers

---

package.json

when running `npm run types` or `npm run build:types` if there was issues in the `d.ts` files it would block it
this just adds a little clean script to remove them

add script to clean types

---

bundles/pixi.js-node/package.json
rollup.config.js

Added simple change to the build steps to ignore a Rollup warning for node dependencies.

Fix Rollup warning, ignore used node dependencies

---

bundles/pixi.js-node/README.md
packages/core/src/extensions.ts

Fix node not initialising

---

package-lock.json
packages/settings/package.json

Partially fixes #8502 
This bundles the `ismobilejs` dependency, which avoids import issues because of the non-Node.js nature of the package. Honestly, bundling this into settings it's a bad idea because it's 1) very small and 2) is stable for our purposes.

Bundle ismobilejs into settings

---

packages/graphics/src/Graphics.ts
packages/graphics/src/utils/buildRoundedRectangle.ts
packages/text/src/Text.ts

The following flags were introduces in v6 as opt-ins to not be breaking. In v7, these become the default behavior. 
* `Graphics.nextRoundedRectBehavior` 
* `Text.nextLineHeightBehavior`

Remove nextRoundedRectBehavior and nextLineHeightBehavior

---

packages/app/src/ResizePlugin.ts
packages/settings/src/utils/isMobile.ts

Fixes #8516
* `@pixi/app` doesn't require CanvasRenderer for the ResizePlugin
* `ismobilejs` is now embedded, manually copied the types

Fix app and ismobilejs typings

---

packages/graphics/src/Graphics.ts

Sync things up with Polygon's points type (https://github.com/pixijs/pixijs/blob/dev/packages/math/src/shapes/Polygon.ts#L23) and allows the caller to pass objects satisfying `{ x: number, y: number }`.
Docs output:

Loosen drawPolygon path type with IPointData

---

packages/assets/src/resolver/Resolver.ts

The Assets Resolver basePath is prepended, not appended. Fixed the setter docs to say "prepend" instead of "append".

Fix Resolver basePath setter doc saying it will append (-> prepend)

---

packages/text-bitmap/src/BitmapText.ts

charRenderData.position.x has already include xOffset so you should decrease xAdvance by it

Fix incorrect BitmapText text width (#8432)

---

packages/assets/src/Assets.ts
packages/assets/test/assets.tests.ts

`loadBundle`'s `onProgress` event would fire for the individual assets per bundle, resulting in something like this when loading multiple bundles
`0.3, 0.6, 1, 0.5, 1`
~~This fix only counts when all the bundle loads and produces the expected output~~
~~`0.5, 1`~~
This fix now uses the total assets of all bundles. If 2 bundles are loaded, each containing 2 assets it produces this
`0.25, 0.5, 0.75, 1`

Fix loadBundle progress

---

packages/assets/src/loader/parsers/LoaderParser.ts
packages/assets/src/loader/parsers/loadBitmapFont.ts
packages/assets/src/loader/parsers/loadJson.ts
packages/assets/src/loader/parsers/loadSpritesheet.ts
packages/assets/src/loader/parsers/loadTxt.ts
packages/assets/src/loader/parsers/loadWebFont.ts
packages/assets/src/loader/parsers/textures/loadBasis.ts
packages/assets/src/loader/parsers/textures/loadDDS.ts
packages/assets/src/loader/parsers/textures/loadKTX.ts
packages/assets/src/loader/parsers/textures/loadSVG.ts
packages/assets/src/loader/parsers/textures/loadTexture.ts

This adds explicit priority for LoaderParsers so that generic things are always run after the more specific loaders.

Chore: Add LoaderParser Priority

---

packages/display/src/Container.ts

I fixed JSDoc of PIXI.DisplayObject#childRemoved. (The event was introduced by https://github.com/pixijs/pixijs/pull/5472)

Fix JSDoc of PIXI.DisplayObject#childRemoved

---

packages/assets/test/assets.tests.ts

The Assets test "should load texture array correctly" was a copy of the test "should unload bundles correctly". I've implemented the former to test Assets.load with an array of texture paths.
Existing implementation:
https://github.com/pixijs/pixijs/blob/ac965dd593f766a19ba9592e538a47f936f51739/packages/assets/test/assets.tests.ts#L266-L285 https://github.com/pixijs/pixijs/blob/ac965dd593f766a19ba9592e538a47f936f51739/packages/assets/test/assets.tests.ts#L321-L340

Implement test "should load texture array correctly"

---

packages/utils/src/path.ts
packages/utils/test/path.tests.ts

Fixes #8610
The path module didn't take into account a URL ending in an extension e.g `index.html`
it also didn't handle url params inside of a path
Example
```
Website URL:  http://www.exampleurl.com/mypage/index.html?variable=test
Asset Path:   img/logo.png
```
Before
```
Resolved URL: http://www.exampleurl.com/mypage/index.html?variable=test/img/logo.png
```
After
```
Resolved URL: http://www.exampleurl.com/mypage/img/logo.png
```

Fix relative path matching

---

bundles/pixi.js-node/src/adapter/loadNodeBitmapFont.ts
packages/assets/src/loader/parsers/loadBitmapFont.ts
packages/assets/test/assets/bitmap-font/split_font2.fnt
packages/assets/test/loader.tests.ts

When loading a split bitmap font the page order is not preserved leading to textures being swapped around

Fix split bitmap font loading

---

packages/canvas-sprite/src/CanvasSpriteRenderer.ts
packages/canvas-sprite/test/CanvasSpriteRenderer.tests.ts

During an update to the PIXI.js versions in use where I work, we observed newly broken canvas renderer rendering for textures where the `BaseTexture` is rotated - for example, if some textures were atlassed in a spritesheet and the texture packer decided to rotate a texture for whatever reason.
For example, this is screenshot from a canvas renderer running v6.5.2, where the red check pattern is taller than it is wide, the blue pattern is wider than it is tall, but they're [in a texture atlas where the blue pattern has been rotated](https://cdn.glitch.global/b31e8b57-49fc-4abc-8e9a-011e8602fd1f/canvas-atlas.png?v=1661423801783).
Prior to #8408 (v.6.5.0), this was not an issue.
I've prepared a demo website showing the issue in detail over here: https://living-checker-skull.glitch.me/
The …

Fixing CanvasSpriteRenderer to correctly render sprites with rotated base textures

---

packages/core/src/shader/utils/uniformParsers.ts

With this change it's possible to assign a texture unit to sampler uniforms.
Test: sampler uniform set to 0.
- Before: https://www.pixiplayground.com/#/edit/i4njik2hxu54d1_Q9dUaz
- After: https://www.pixiplayground.com/#/edit/AyA9fWlgnHl6EmBlHs3PQ

Allow integer as sampler uniform value

---

packages/assets/src/detections/index.ts
packages/assets/src/detections/parsers/detectAvif.ts
packages/assets/src/detections/parsers/detectDefaults.ts
packages/assets/src/detections/parsers/detectWebp.ts
packages/assets/src/detections/utils/detectUtils.ts
packages/assets/src/detections/utils/index.ts
packages/basis/src/loader/detectBasis.ts
packages/compressed-textures/src/loaders/detectCompressedTextures.ts

DetectionParser was not being consistent or providing guidance about how to implement `add` and `remove` methods. This PR clarifies how developers should implement formats, which is to return a new array and not mutate the argument.
This _mutates_ and _returns_.
```js
{ 
add: async (formats) => {
formats.push('xyz');
return formats;
},
remove: async(formats) => {
formats.splice(formats.indexOf('xyz'), 1);
return formats;
},
}
```
After this PR, this is much clearer.
```js
{ 
add: async (formats) => [...formats, 'zyx'],
remove: async(formats) => formats.filter(f => f !== 'zyx'),
}
```

Improve the data-flow for DetectionParser formats

---

packages/text-bitmap/src/BitmapFont.ts
packages/text-bitmap/src/BitmapText.ts

Bug: https://codesandbox.io/s/pixi-v6-bitmap-text-gray-square-rsp91x
Fixed: https://codesandbox.io/s/pixi-v6-bitmap-text-gray-square-fix-bf5k4l
Zoom out, see how gray squares appear
Two lines fix:
1. uFWidth should be 1.0 minimum, because if median is 0 then result should be 0 and not >0
2. mipmaps dont help with SDF textures, because SDF is linear and guarantees exact result if `scale > 1.0 / spread`. however if its bigger then even mipmaps wont help us, there's just not enough info.

Fix MSDF gray squares

---

package-lock.json
package.json
packages/assets/package.json
packages/assets/src/loader/types.ts

fixes #8646 and missing `alias` and `format` form `LoadAssets`

Fix Assets missing types

---

bundles/pixi.js-node/src/adapter/adapter.ts

I'm not sure if this is the approach you want to go with, but I've created this PR to highlight a bug I found with the new NodeAdapter.
The default export from the `gl` library doesn't give us a `WebGLRenderingContext`, instead it gives us a method `createContext`. You can see that [here](https://github.com/stackgl/headless-gl/blob/master/src/javascript/node-index.js#L129).
This means that in the current PIXI code, operations like [this one](https://github.com/michaeljherrmann/pixijs/blob/4975264a6ec65121751cbee2ce2cc77a80d34b9a/packages/core/src/mask/StencilSystem.ts#L28) are broken, because `STENCIL_TEST` is `undefined` (`.getWebGLRenderingContext()` is returning the function `createContext` and not an actual context).
So at first I thought we could just do `createContext()` but the …

fix node WebGLRenderingContext

---

packages/core/src/textures/resources/SVGResource.ts

Demo: https://www.pixiplayground.com/#/edit/Z7ws-I72Xaa0MCMmIVAle
Test doesnt work because of semicolon. If you try  to put semicolon in string, you'll get an error, so browser really cant parse it that way.

Fix svg resource test

---

packages/interaction/src/InteractionManager.ts

prevent pointer over firing on touch pointers as pointerOut doesn't fire on touch, this leads to the activeInteractionData filling up every time you touch the screen

pointer over broken on touch devices

---

packages/graphics/src/Graphics.ts
packages/mesh-extras/src/SimpleRope.ts
packages/sprite-tiling/src/TilingSprite.ts

#8636 
Added notes to the documentation where the wrap mode is forced to REPEAT.

Document forced wrap mode changes

---

packages/sprite-tiling/src/TilingSpriteRenderer.ts

The TilingSpriteRenderer was not getting installed resulting in the following error when trying to render a TilingSprite object:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'start')
at BatchSystem.setObjectRenderer (core.mjs:2406:26)
at TilingSprite._render (sprite-tiling.mjs:54:20)
at TilingSprite.render (display.mjs:777:12)
at Container.renderAdvanced (display.mjs:812:26)
at Container.render (display.mjs:773:12)
at Container.render (display.mjs:779:26)
at ObjectRendererSystem.render (core.mjs:6870:19)
at _Renderer.render (core.mjs:6120:25)
```

TilingSpriteRenderer should self-install

---

packages/events/src/EventSystem.ts

I noticed that FederatedMouseEvent [does include a `shiftKey` property](https://github.com/pixijs/pixijs/blob/dev/packages/events/src/FederatedMouseEvent.ts#L31), but it doesn't seem like this property was being transferred over from the corresponding native MouseEvent.  Simple fix!

Transfer the .shiftKey property from native -> federated mouse event

---

packages/canvas-sprite/src/CanvasSpriteRenderer.ts

Changes made in #8615 to fix one case of broken canvas rendering ended up breaking canvas rendering in a different way ([pixi-spine#460](https://github.com/pixijs/spine/issues/460)).
The fix I made previously didn't take into account the height/width swap required if a texture was rotated, and the fixes made in v6.5.0 were absolutely fine for this case.
I've prepared another demo site that covers all cases of the canvas rendering: https://vagabond-ambiguous-gerbera.glitch.me/
The previous red/blue atlas I used that had rotation but no trim remains, and a new purple/green atlas that has rotation and trim has been. Both were rendering correctly in v6.4, only one worked fine in 6.5.2 and 6.5.3, but both render correctly again with this fix applied.
I ran into difficulty trying to write a …

Fixing CanvasSpriteRenderer to correctly render sprites with rotated and trimmed base textures

---

package.json

I noticed that when we publish on GitHub Actions, types are generated _twice_. This is unnecessary as generating types is now part of the standard `npm run dist` action. There's no need to run it again. Pre-publishing types is a holdover before `build:types` was including with every action.

Fix building types twice when publishing

---

bundles/pixi.js-legacy/README.md
bundles/pixi.js/README.md

Fixed small formatting issue in the README.md file which is visible on NPM (how I discovered the bug).
There was a rogue `]` character, followed by a duplicate link to webpack.
| **Before** | <img width="584" alt="Screenshot 2022-09-30 at 20 06 05" src="https://user-images.githubusercontent.com/38284426/193339934-38326500-a29d-4917-8c58-b334a24daf66.png"> |
|---|---|
|  **After** ✨ | <img width="585" alt="Screenshot 2022-09-30 at 20 07 37" src="https://user-images.githubusercontent.com/38284426/193339947-39acffdf-b819-4936-b4bb-2fc8223409e0.png"> |

Fixed README webpack link formatting

---

packages/core/src/textures/resources/ImageResource.ts

In commit 02a186048e4cd7a24d517c4840af2e7578c68e14 `premultiplyAlpha` was changed to `alphaMode` and it broke the `createBitmap` use case when no alphaMode is specified (which is the default). Before a undefined

Fix createImageBitmap with null alphaMode

---

packages/core/src/textures/BaseTexture.ts

`Object.assign` modifies `defaultBufferOptions`: https://pixiplayground.com/#/edit/TFeCVbqcd1xDhZ1_RtL1j

Fix `fromBuffer`

---

packages/text-bitmap/src/BitmapText.ts
packages/text-bitmap/src/shader/msdf.frag

Trying to fix #8652 . 
`mipmaps dont help with SDF textures, because SDF is linear and guarantees exact result if scale > 1.0 / spread. however if its bigger then even mipmaps wont help us, there's just not enough info.`
this might be wrong. Needs testing from @insraq

Fix bitmapText frag alpha

---

packages/text-bitmap/src/BitmapText.ts

Fixes #8712
Broken: https://jsfiddle.net/bigtimebuddy/aL92zf0v/ (should see "2" and console crash)
Fixed: https://jsfiddle.net/bigtimebuddy/z8f2h7Lu/ (should see "1" and no console crash)

Fix dereferencing textures for BitmapText

---

bundles/pixi.js-legacy/README.md
bundles/pixi.js-node/README.md
bundles/pixi.js-node/src/adapter/adapter.ts
bundles/pixi.js-webworker/LICENSE
bundles/pixi.js-webworker/README.md
bundles/pixi.js-webworker/package.json
bundles/pixi.js-webworker/src/adapter.ts
bundles/pixi.js-webworker/src/index.ts
bundles/pixi.js/README.md
package-lock.json
packages/assets/src/loader/parsers/loadWebFont.ts
packages/assets/src/loader/parsers/textures/loadTexture.ts
packages/core/src/textures/resources/BaseImageResource.ts
packages/core/src/textures/resources/ImageBitmapResource.ts
packages/core/src/textures/resources/ImageResource.ts
packages/core/src/textures/resources/index.ts
packages/settings/src/adapter.ts

This PR adds `@pixi/webworker` bundle for Web Workers. This bundle is basicly `pixijs` with `@pixi/accessibility` & `@pixi/events` removed and `WebWorkerAdapter` added, enough for running small demos in Web Workers.
See also https://github.com/pixijs/examples/pull/158.
Related Issue: https://github.com/pixijs/pixijs/issues/7123
- Add `@pixi/webworker` bundle
- Add `IAdapter.getFontFaceSet()` to cover the difference between main thread and worker thread (`document.fonts` for main thread, `globalThis.fonts` for worker thread)
- `ImageBitmapResource` now recieve `string` in constructor, in order to support `Texture.from(url)` in Web Workers
- Other minor changes to make basic things work in Web Workers

Add @pixi/webworker bundle

---

packages/text-bitmap/src/BitmapText.ts

When `BitmapText.destroy()` is called, push the `PageMeshData` that are still in `this._activePagesMeshData` to `pageMeshDataPool`, so that more `PageMeshData` can be reused.

Recycle PageMeshData when BitmapText is destroyed

---

.eslintrc.json
packages/core/src/transformFeedback/TransformFeedback.ts
packages/core/src/transformFeedback/TransformFeedbackSystem.ts

Partially addresses formatting warnings in #8720
Adds a new lint warning to catch this in the future.
Follow-up to #8486

Fix doc formatting warnings with TransformFeedback

---

packages/app/src/Application.ts
packages/canvas-renderer/src/CanvasRenderer.ts
packages/core/src/IRenderer.ts
packages/core/src/Renderer.ts
packages/core/src/autoDetectRenderer.ts
packages/core/src/background/BackgroundSystem.ts
packages/core/test/Renderer.tests.ts
packages/settings/src/settings.ts
packages/utils/src/color/hex.ts
packages/utils/test/utils.tests.ts

* Adds `background` shorter alias for `backgroundColor` option in Renderer, CanvasRenderer, and Application
* Supports hex strings (e.g., "#ff0000")
* Supports color names (e.g., "red")
* Supports short-hand hex strings (e.g. "#f00")
```ts
const renderer = new Renderer({ background: 'red' });
const renderer = new Renderer({ background: '#f00' });
const renderer = new Renderer({ background: 'f00' });
const renderer = new Renderer({ background: '#ff0000' });
const renderer = new Renderer({ background: 0xff0000 });
```

Adds more user-friendly background option

---

packages/display/src/DisplayObject.ts
packages/display/test/DisplayObject.tests.ts

Similar to old PR #5021, with tests added.
Resolve #8716.
- Add `removeFromParent` method for `DisplayObject`
https://github.com/pixijs/pixijs/blob/b0720bc364c3b92f1b6142947c4dc403e64e9692/packages/display/src/DisplayObject.ts#L651-L655
- Add test for `DisplayObject.removeFromParent` in `DisplayObject.tests.ts`
- Fix some case problem in `DisplayObject.tests.ts` (`DisplayOBject` -> `DisplayObject`)

Add removeFromParent method for DisplayObject

---

packages/loaders/src/LoaderResource.ts

Add avif to `LoaderResource._loadTypeMap` and `LoaderResource._xhrTypeMap` for v6.x.
Fixes #8647.

Add avif image support for Loader

---

packages/core/src/textures/resources/VideoResource.ts

Fixes #8707 
Removes the `currentTime > 0` conditional check since it's not working on Firefox with MediaStream.
Broken: https://jsfiddle.net/bigtimebuddy/ah38w7y5/ (dev)
Fixed: https://jsfiddle.net/bigtimebuddy/fosvzgc0/ (this PR)
Also this seems to work fine with static video:
https://pixijs.io/examples/?v=fix-video-stream-playback#/sprite/video.js

Simplify conditions for identifying playing video

---

packages/utils/src/color/hex.ts

Clarified string2hex and rgb2hex examples in documentation, as string2hex documentation had been found confusing.
Fixes #8024.

Clarifying string2hex and rgb2hex examples in documentation (#8024)

---

packages/assets/src/loader/parsers/WorkerManager.ts
packages/assets/src/loader/parsers/textures/loadTexture.ts

Add `isImageBitmapSupported` method in `WorkerManager`, so that the `loadTextures.load()` won't fail on browser that support `createImageBitmap` in main thread but not worker threads.
Fixes #8738.
- Add `isImageBitmapSupported` method in `WorkerManager`
- `WorkerManager.loadImageBitmap` will `reject(e)` if error happens, instead of silently `resolve(null)`
- Check `response.ok` after `fetch()` and throw Error in order to get better error information
- Before
- After

Add isImageBitmapSupported in WorkerManager

---

packages/core/test/RenderTexture.tests.ts

`gl.readPixels(gl.RED, gl.FLOAT)` may fail in some environment (jest-electron on Mac M1 Pro for example), so use `gl.readPixels(gl.RGBA, gl.FLOAT)` as a workaround.
Fixes #8761.

Fix gl.readPixels failure in tests

---

packages/text-bitmap/src/BitmapText.ts
packages/text-bitmap/test/BitmapText.tests.ts

Fixes #8758.
- The `BitmapText` will trigger `updateText()` automatically when `validate()` if the `BitmapFont` it use is replaced
- See test `should update after font is replaced`
- If `BitmapText.fontSize` is `undefined` and the `BitmapFont` it uses is replaced, it will use the new size of `BitmapFont`, instead of the old value when it is constructed
- See test `should update fontSize when font is replaced if fontSize is undefined`
- See test `should not update fontSize when font is replaced if fontSize is defined`
- `BitmapFont.dirty` will become `false` after `updateText()`, so that if user calls `updateText()` externally, there won't be duplicated call to `updateText()` inside `BitmapFont`
- See test `should unset dirty after updateText`
Example: …

Auto update BitmapText when its font is replaced

---

packages/events/src/FederatedEventMap.ts

Adds the pointercancel event. https://developer.mozilla.org/en-US/docs/Web/API/Element/pointercancel_event 
Because touchcancel exists, it seems like pointercancel should be there.

Add missing events to FederatedEventMap

---

packages/graphics/src/utils/buildLine.ts
packages/graphics/test/Graphics.tests.ts

Update the logic in `buildNonNativeLine` to deal with 180 degree or nearly 180 degree corners, and add some tests for it.
Fixes #8751.
Example: https://pixiplayground.com/#/edit/E97IvI759l-TZekre5v5J
- By row: `lineTo + lineTo`, `lineTo + bezierCurveTo`, `bezierCurveTo + bezierCurveTo`
- By column: `MITER`, `BEVEL`, `ROUND`
Before:
- `Math.PI` (Missing round join, wrong topology for `lineTo + lineTo`)
- `Math.PI + 0.001` (Missing round join for `bezierCurveTo + bezierCurveTo`)
After:
- `Math.PI`
- `Math.PI + 0.001`

Fix round line join on 180 degree corner

---

packages/app/src/ResizePlugin.ts

Closes #8629 
Adds a render call immediately after resizing Application to avoid a frame flicker.
**Before:** https://codesandbox.io/s/resizeto-flickering-kv1w2r
**After:** https://codesandbox.io/s/resizeto-flickering-forked-syxlbw

Render Immediate After Resize

---

.github/workflows/nodejs.yml

After each release, I was having to manually upload the assets. Finally, sorted this in GitHub Actions and it's pretty easy. 
This change automatically adds the browser builds to the release on GitHub. This means that the version on pixijs.download, npm and GitHub release are all exactly the same.

Chore: Automatically upload assets to release

---

packages/mixin-cache-as-bitmap/src/index.ts

Changes the default to `null` (multisample of the renderer) to match the behavior of `cacheAsBitmapResolution`, which is by default the renderer's resolution.
This default behavior was part of #7441 originally but then changed to `MSAA_QUALITY.NONE` to be reevaluated for v7.

Change `cacheAsBitmapMultisample` default to `null`

---

.github/workflows/nodejs.yml

This change should be merged to coincide with the final v7 release. Sets the dist-tags for publishing v6 to be `latest-6.x` instead of `latest`. Also v6 no longer will update the `release` build on the CDN.

Move v6 into LTS, non-latest dist-tag

---

packages/core/package.json
packages/unsafe-eval/package.json
packages/unsafe-eval/src/bundle.ts

Closes #8791
* `@pixi/unsafe-eval` was missing the `lib` folder in the `files` list  of the **package.json**
* Removes the `@pixi/unsafe-eval` bundle.ts which is no longer used
* Clean up the `@pixi/core` file list, `dist` no longer needed here

Fix publishing unsafe-eval package

---

.github/workflows/nodejs.yml

* Removes codecov, we are no longer using this and it has been breaking our builds occasionally and not reporting to codecov.io correctly.
* Change npm install to be 8 instead of `>=7` to be more future proof
* Updated any action dependencies to the latest major versions

Chore: Cleanup action dependencies, remove Codecov

---

scripts/fixTypes.ts

Closes #8799
Output changes out from:
```ts
/// <reference types="@pixi/core/global" />
```
To:
```ts
/// <reference path="../global.d.ts" />
```
This is less confusing for TypeScript 4.7+ which is expecting a `global` exports in the package.json.

Convert types reference to relative path

---

scripts/fixTypes.ts

Follow-up to #8799
Pattern was not matching package names with `-` (hyphens)
```ts
/// <reference types="packages/sprite-tiling/global" />
```
Becomes
```ts
/// <references path="../global.d.ts" />
```

Hotfix Global Types

---

packages/events/src/FederatedEventTarget.ts

It overrides the signature of the `removeAllListeners` method on the `FederatedEventTarget` interface to make it compatible with Angular projects.
Fixes #8794

Fix compatibility between `zone.js` and `FederatedEventTarget`

---

packages/core/src/textures/resources/BaseImageResource.ts

VideoResource bug fix. Ensures we upload video changes once `play` has finished. When calling `play` on the video element readyState changes from 4 to 1 once playback has ended even though all of the data is buffered. This change takes this into account and allows us to upload video changes such as `currentTime` once playback has ended. See https://codesandbox.io/s/stoic-grass-rkhxl3?file=/src/index.js for working example.

VideoResource upload fix

---

packages/mesh/src/Mesh.ts
packages/sprite/src/Sprite.ts

How the heck we did miss it?
There are two problems in this code:
If sprite coord X < 0 it gets blurred, because rounding works differently for Left and Right parts, left is Ceil, right is Floor. Same with Y. I guess people who work with texts complained about that but we didnt understand the cause.
Second problem is that the code works only for resolution < 1, to round low-quality versions of sprites.
My suggestion is to merge this to v7, and then decide whether we want both fixes for v6 , or only remove (| 0) part, which fixes the negative values.
And Yes, `X-Files` label is back!

Fix negative coords for roundPixels

---

bundles/pixi.js-node/src/adapter/NodeCanvasElement.ts
bundles/pixi.js-node/src/adapter/adapter.ts
bundles/pixi.js-webworker/src/adapter.ts
packages/settings/src/ICanvas.ts

- Make `NodeCanvasElement` compatible with `ICanvas`, so that `NodeCanvasElement` can be convert into `ICanvas` without `as unknown`.
- Before: `new NodeCanvasElement(width, height) as unknown as ICanvas`
- After: `new NodeCanvasElement(width, height) as ICanvas`
- Add `ContextSettings` as the type of `ICanvas.getContext`'s `options` argument.

Fix: Make NodeCanvasElement compatible with ICanvas

---

packages/app/src/Application.ts
packages/core/src/IRenderer.ts
packages/core/src/autoDetectRenderer.ts

Since we are using ICanvas as a generic interface for OffscreenCanvas, HTMLCanvasElement and Node's canvas, we are getting a type error doing something pretty basic:
```ts
const app = new Application();
document.body.appendChild(app.view); // ERROR: Argument of type `ICanvas` is not assignable to type 'Node'
```
Current workaround is to cast:
```ts
document.body.appendChild(app.view as HTMLCanvasElement);
```
Use a template to specify the type of view.
```ts
const app = new Application<HTMLCanvasElement>();
```
```ts
const renderer = autoDetectRenderer<HTMLCanvasElement>();
document.body.appendChild(renderer.view);
```

Add view type as a template for IRenderer, Application

---

packages/display/src/DisplayObject.ts
packages/events/src/FederatedEventMap.ts

Hello,
these are just very minor changes to slightly improve DX:
1. Use labeled tuples
* A very minor improvement in DX:
Before the signature of fn was `fn: (args_0: PIXI.FederatedPointerEvent) => void`
* The syntax used requires TypeScript 4.1. If that's a problem I can replace it by just writing out the events by hand.
2. Add types for `*capture` events
* These seemed to be missing, I hope this wasn't intentional?
**Note**: The event `removedFrom` doesn't seem to be used anywhere (haven't found it in the docs and neither anywhere in the code). Shall I remove this from the types?

Event emitter types improvements

---

packages/canvas-renderer/src/CanvasRenderer.ts
packages/core/src/Renderer.ts
packages/events/src/EventSystem.ts
packages/events/test/EventSystem.tests.ts

Closes #8792
Closes #8804
There are uses cases like automatically adjusting the resolution based on the browser zoom. This automatically adjusts the Event's resolution as well.
* Adds setter for Renderer and CanvasRenderer's `resolution`

Add missing resolution setter for Renderer and CanvasRenderer

---

packages/core/src/textures/Texture.ts
packages/display/src/Container.ts
packages/graphics/src/Graphics.ts
packages/graphics/src/GraphicsGeometry.ts

- Add document for `GraphicsGeometry.bounds`
- Closes #8623
- Fix document for `childRemoved` event in `Container`
- Fix issue link in `Texture`'s document
- I believe the correct link should be #3085 instead of #3068
- Some other small fixes

Chore: Update document

---

package-lock.json
package.json
rollup.config.js

Related issue: https://github.com/bigtimebuddy/pixi-svg/issues/33
Issue found: https://codesandbox.io/s/pixijs-examples-events-hit-test-forked-h8eog8
```
ModuleNotFoundError
Could not find module in path: '@pixi/settings/lib/node_modules/ismobilejs/esm/index.js' relative to 
'/node_modules/@pixi/settings/lib/utils/isMobile.js'
```
I believe that codesandbox is having issues with preserveModules in Rollup. Specifically, the external dependencies that are bundled (e.g. ismobilejs) are added to a folder called `node_modules`. This PR changes that folder name to be `external`. Since `node_modules` implies something very specific, I don't think it's appropriate to use that here and may be messing up patterning matching with other tools that expect `node_modules` to be _actual_ modules.
Before: …

Change "lib/node_modules" to "lib/external" with preserveModules

---

bundles/pixi.js-node/package.json
bundles/pixi.js-node/src/adapter/adapter.ts
package-lock.json

I'm following up on [this PR](https://github.com/pixijs/pixijs/pull/8643) as the ideal fix we wanted required some updates to some dependencies. I've got those updates merged in [gl](https://github.com/stackgl/headless-gl/pull/236) and for it's [types](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62647).

Updating WebGLRenderingContext for node

---

packages/display/src/Container.ts

Culling didn't include the projection transform in its calculation.
Test: Generate texture from red square graphics with culling enabled.
- Before: https://pixiplayground.com/#/edit/hecuI3Ahv12g4l5Gw5Pcp
- After: https://pixiplayground.com/#/edit/AyuQKXBxkN8hz00FXfH13

Fix culling not working with projection transforms

---

package-lock.json
package.json
test/jest-global-setup.ts
test/jest-global-teardown.ts

Previously using `npm test` on Windows will report `Error: spawn http-server ENOENT` due to the difference on the shell between Windows and other Unix-like OS. Since I usually working on Windows, I modified the Jest setup & teardown script to make it working on Windows. Package `tree-kill` is introduced to properly kill the `http-server` on Windows, since `process.kill()` will only kill the shell but not the real `http-server` process.
See https://nodejs.org/api/child_process.html#spawning-bat-and-cmd-files-on-windows for more details.

Fix: Jest running on Windows

---

packages/core/src/filters/Filter.ts
packages/core/src/settings.ts
packages/filter-blur/src/BlurFilter.ts
packages/settings/src/settings.ts
packages/settings/test/settings.tests.ts

The creation of `settings` is one of my biggest API regrets. It has become a junk-drawer for a bunch of globals and defaults. Some of these should simply be static defaults in a single class. For instance, FILTER_RESOLUTION and FILTER_MULTISAMPLE, are only used in ONE place (i.e., Filter class), and should be located there. 
* Setting `settings.FILTER_RESOLUTION` becomes `Filter.resolution`
* Setting `settings.FILTER_MULTISAMPLE` becomes `Filter.multisample`
I will likely be doing several of these settings-related PRs.

Deprecate FILTER_* settings, move to Filter static members

---

packages/app/src/Application.ts
packages/canvas-renderer/src/CanvasRenderer.ts
packages/core/src/Renderer.ts
packages/core/src/context/ContextSystem.ts
packages/settings/src/settings.ts

Closes #8861
* Removes `useContextAlpha` from the Application, CanvasRenderer and Renderer options documentation
* Add deprecation flag to `useContextAlpha` in IRenderOptions
* Always set a default for `premultipliedAlpha` as this is now a required field
* Add deprecation warnings and fallback behavior for `useContextAlpha` with constructor arguments

Chore: Cleanup useContextAlpha deprecation

---

packages/graphics/src/Graphics.ts
packages/graphics/src/const.ts
packages/graphics/src/utils/ArcUtils.ts
packages/graphics/src/utils/BezierUtils.ts
packages/graphics/src/utils/QuadraticUtils.ts
packages/graphics/src/utils/buildLine.ts
packages/graphics/test/Graphics.tests.ts

This change is similar to my recent PRs #8868 and #8865 to relocate weirdly placed or named global settings as static members of relevant APIs. This one has been bothering me for awhile.
* Moves `GRAPHICS_CURVES`  to `Graphics.curves`
* Deprecates the unnecessary `IGraphicsCurvesSettings`
Before:
```js
import { GRAPHICS_CURVES } from 'pixi.js';
GRAPHICS_CURVES.adaptive = false;
```
After:
```js
import { Graphics } from 'pixi.js';
Graphics.curves.adaptive = false;
```

Deprecate GRAPHICS_CURVES, move to Graphics.curves

---

packages/constants/src/index.ts
packages/core/src/context/ContextSystem.ts
packages/core/src/framebuffer/FramebufferSystem.ts
packages/core/src/geometry/GeometrySystem.ts
packages/core/src/settings.ts
packages/core/src/shader/utils/getTestContext.ts
packages/core/src/textures/BaseTexture.ts
packages/settings/src/settings.ts
packages/settings/test/settings.tests.ts
packages/text-bitmap/src/BitmapFont.ts

Similar to #8865. Moving a handful of settings to BaseTexture, as they are only used there:
* `settings.WRAP_MODE` becomes `BaseTexture.defaultOptions.wrapMode`
* `settings.SCALE_MODE` becomes `BaseTexture.defaultOptions.scaleMode`
* `settings.MIPMAP_TEXTURES` becomes `BaseTexture.defaultOptions.mipmap`
* `settings.ANISOTROPIC_LEVEL` becomes `BaseTexture.defaultOptions.anisotropicLevel`
* Adds BaseTexture defaults `format`, `type`, `target`, `alphaMode` to `BaseTexture.defaultOptions`
The naming `defaultOptions` was chosen because it's already used in BitmapFont (to be consistent!)

Deprecate BaseTexture-related settings to BaseTexture.defaultOptions

---

rollup.config.js

Close #8874 
Deprecation warnings should be included when building with a bundler.
Users can use plugins (e.g., [@rollup/plugin-strip](https://www.npmjs.com/package/@rollup/plugin-strip)) for removing deprecations warnings, console logs and asserts.

Include DEBUG statements in module output

---

packages/core/src/batch/BatchRenderer.ts
packages/core/src/batch/canUploadSameBuffer.ts
packages/core/src/batch/maxRecommendedTextures.ts
packages/core/src/settings.ts
packages/core/test/BatchRenderer.tests.ts
packages/core/test/Renderer.tests.ts
packages/graphics/src/Graphics.ts
packages/graphics/src/GraphicsGeometry.ts
packages/settings/src/settings.ts
packages/settings/test/settings.tests.ts

Continuing progress to relocate settings that are only used in single places. This moves BatchRenderer static options.
* Removes `settings.SPRITE_BATCH_SIZE` to `BatchRenderer.batchSize`
* Removes `settings.SPRITE_MAX_TEXTURES` to `BatchRenderer.maxTextures`
* Removes `settings.CAN_UPLOAD_SAME_BUFFER` to `BatchRenderer.canUploadSameBuffer`
* Removes `BatchRenderer#MAX_TEXTURES` to `BatchRenderer#maxTextures`
* Moves `maxRecommendedTextures` to core
* Moves `canUploadSameBuffer` to core
* Replace `navigator` calls in `maxRecommendedTextures` to use the ADAPTER instead

Deprecate SPRITE_* & CAN_UPLOAD_SAME_BUFFER settings, move to BatchRenderer

---

packages/prepare/src/BasePrepare.ts
packages/prepare/src/settings.ts
packages/settings/src/settings.ts

* Removes `settings.UPLOADS_PER_FRAME` to `BasePrepare.uploadsPerFrame`

Move UPLOADS_PER_FRAME to BasePrepare

---

packages/display/src/Container.ts
packages/display/src/settings.ts
packages/settings/src/settings.ts

* Removes `settings.SORTABLE_CHILDREN` becomes `Container.defaultSortableChildren`
@Zyie I realized that some static member names are now matching instance members (`Container.sortableChildren` vs `Container.prototype.sortableChildren`, `BatchRenderer.maxTextures` vs `BatchRenderer.prototype.maxTextures`) is confusing and somewhat ambiguous with the docs, so I decided that static properties I'm going to prefix with `default`. Will go back and fix.

Deprecate SORTABLE_CHILDREN setting, move to Container

---

packages/settings/src/settings.ts
packages/ticker/package.json
packages/ticker/src/Ticker.ts
packages/ticker/src/settings.ts

* Remove `settings.TARGET_FPMS` becomes `Ticker.targetFPMS`
Decided not to name `targetFPMS` to `defaultTargetFPMS` because of how Ticker uses this property. It does not use it as a default, rather an environmental baseline for all tickers. There's currently no way to to adjust this per-Ticker.

Deprecated settings.TARGET_FPMS to Ticker.targetFPMS

---

packages/core/src/settings.ts
packages/core/src/textures/TextureGCSystem.ts
packages/settings/src/settings.ts
packages/settings/test/settings.tests.ts

* Removes `settings.GC_MODE` becomes `TextureGCSystem.defaultMode`
* Removes `settings.GC_MAX_IDLE` becomes `TextureGCSystem.defaultMaxIdle`
* Removes `settings.GC_MAX_CHECK_COUNT` becomes `TextureGCSystem.defaultCheckCountMax`

Deprecate GC settings

---

bundles/pixi.js-node/src/adapter/loadNodeBitmapFont.ts
packages/assets/src/Assets.ts
packages/assets/src/loader/Loader.ts
packages/assets/test/assets.tests.ts
packages/assets/test/loader.tests.ts
packages/compressed-textures/test/compressed-textures.tests.ts
packages/mesh-extras/test/SimplePlane.tests.ts
packages/mesh-extras/test/SimpleRope.tests.ts
packages/text-bitmap/src/loadBitmapFont.ts
packages/text-bitmap/test/BitmapFontLoader.tests.ts

The `Assets.load`, `Assets.get` and `Loader.load` used to return `Promise<T | Record<string, T>>` regardless of the type of the argument is `string` or `string[]`, this caused me to perform extra cast on the return value when using them. So I add overload signatures to these methods, now they will return a more exact type.
Old:
```ts
const texture = await Assets.load('textures/bunny.png') as Texture;
// type of `await Assets.load<Texture>('textures/bunny.png')` is Texture | Record<string, Texture>
```
New:
```ts
const texture = await Assets.load<Texture>('textures/bunny.png');
// type of `await Assets.load<Texture>('textures/bunny.png')` is Texture
```
The tests that use `Assets` or `Loader` are modified. Also some `import` arrangements are included.

Add overload signatures for Assets

---

packages/canvas-mesh/global.d.ts
packages/canvas-mesh/src/Mesh.ts
packages/canvas-mesh/src/settings.ts
packages/core/src/settings.ts
packages/mesh/src/Mesh.ts

* Removes `settings.MESH_CANVAS_PADDING` becomes `Mesh.defaultCanvasPadding`

Deprecate MESH_CANVAS_PADDING setting

---

packages/text/src/Text.ts

The `Text` used to use `Array.from` to split strings into code points, which is not enough for characters that is composed of multiple code points. Now that most of the browsers support [`Intl.Segmenter`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter/Segmenter) which can split strings into grapheme cluster, we can use it to split strings properly, and fallback to `[...string]` when it is not available. The segmenter function is provided as a static field `Text.graphemeSegmenter: (s: string) => string[]`, and users can set it to their own polyfill when needed.
See https://github.com/pixijs/pixijs/issues/5571#issuecomment-1324614159 for more context.

Feature: Add `Text.graphemeSegmenter` option

---

packages/assets/src/Assets.ts

There was a slight mismatch in names in https://github.com/pixijs/pixijs/pull/8826
Changes `Assets.preferWorker` to `Assets.preferWorkers` to match the `preferWorkers` property in the loadTexture.config.

Fix typo in preferWorkers API

---

packages/assets/src/Assets.ts

The resolver options in the AssetInitOptions never was used. 
The preferred way to change these things is:
* Use `extensions.add` (for `options.resolver.urlParsers`) 
* Use `Assets.resolver.prefer` (for `options.resolver.preferOrders`)

Cleanup unused Asset.init options

---

packages/core/global.d.ts
packages/core/src/settings.ts
packages/core/src/shader/Program.ts
packages/settings/src/settings.ts
packages/settings/test/settings.tests.ts

Likely the last PR for now of settings being migrated to classes.
* Moves `settings.PRECISION_FRAGMENT` to `Program.defaultFragmentPrecision`
* Moves `settings.PRECISION_VERTEX` to `Program.defaultVertexPrecision`

Deprecate precision settings to Program

---

packages/text/src/TextMetrics.ts

Closes #8860
**Broken**: https://jsfiddle.net/bigtimebuddy/zmfkoxe9/
**Fixed**: https://jsfiddle.net/bigtimebuddy/mh0qa1g2/
Our new lineHeight behavior didn't account for stroke with single-line text creating cut-off strokes.

Adjust height for single-lined stroked Text

---

packages/text/src/Text.ts

Added a static `defaultAutoResolution` and `defaultResolution` to `Text` that allows you to more easily set the resolution of your text 
Before: 
```ts
// renderer resolution 1
const app = new Application();
settings.RESOLUTION = 2;
// resolution is still 1 because of autoResolution
const text = new Text('hi');
```
After:
```ts
// resolution 1
const app = new Application();
Text.defaultResolution = 2;
Text.defaultAutoResolution = false;
// text resolution is now 2
const text = new Text('hi');
```
Also [here](https://jsfiddle.net/d53t27bg/) is an example of how text becomes crisper when renderer resolution is 1 and text is 2

Allow for easier overriding of text resolution 

---

packages/constants/src/index.ts
packages/core/src/filters/Filter.ts
packages/core/src/renderTexture/RenderTexturePool.ts
packages/core/src/shader/Program.ts
packages/display/src/settings.ts
packages/graphics/src/const.ts
packages/math/src/groupD8.ts
packages/settings/src/settings.ts
packages/text/src/const.ts
packages/ticker/src/const.ts
packages/utils/src/color/premultiply.ts
packages/utils/src/const.ts

Documentation cleanup to remove `@constant` which is not a thing in webdoc.
Clarified in some places with `@readonly`.

Chore: Remove constant tag from documentation

---

bundles/pixi.js-node/src/adapter/adapter.ts
bundles/pixi.js-webworker/src/adapter.ts
packages/settings/src/ICanvasRenderingContext2D.ts
packages/settings/src/adapter.ts
packages/text/src/Text.ts
packages/text/src/TextMetrics.ts

- `Text.graphemeSegmenter` is moved to `TextMetrics.graphemeSegmenter`, so that we can use it in `TextMetrics.wordWrapSplit`
- Fortunately there is no new release since #8893, so no breaking change :)
- `Text.experimentalLetterSpacing` is moved to `TextMetrics.experimentalLetterSpacing`
- Add `IAdapter.getCanvasRenderingContext2D`
- Fix `TextMetrics.wordWrap`, now it support characters with multiple code points
- Before: https://pixiplayground.com/#/edit/xFjAqYprZeC30XfEqbK_5
- After: https://pixiplayground.com/#/edit/MPDAY7vYU-o3zgYn_FOf2
- After (with `TextMetrics.experimentalLetterSpacing = true`): https://pixiplayground.com/#/edit/THqQ6nbHZmXDyqSnZBoEk
- See also https://github.com/pixijs/pixijs/issues/5571#issuecomment-1328875757
- Move static initialization that is outside of …

Chore: Cleanup Text and TextMetrics

---

packages/canvas-renderer/src/CanvasRenderer.ts

Closes #8924
If the `view` option was set for CanvasRenderer, it was not getting passed to the ViewSystem.
**Broken**: https://jsfiddle.net/bigtimebuddy/trj3g907/ (v7.0.4)
**Fixed**: https://jsfiddle.net/bigtimebuddy/t1u9678x/ (this PR)

Missing view option to CanvasRenderer

---

packages/app/src/Application.ts
packages/canvas-renderer/src/CanvasRenderer.ts
packages/core/src/AbstractRenderer.ts
packages/core/src/Renderer.ts

* Closes issue [#8073](https://github.com/pixijs/pixijs/issues/8073)
* Co-authored by @sunveer2001 and @MasonJason23
* Documented the `transparent` option in the AbstractRenderer.ts, Renderer.ts, and Application.ts files. Included explanation of what the transparent option does: it sets the member `backgroundAlpha` to 0 or 1, given a value of false or true, respectively. As the member `transparent` is deprecated, it is not necessary to include these changes beyond the 6.x documentation.

Added `transparent` option to 6.x docs

---

packages/accessibility/test/AccessibilityManager.tests.ts
packages/app/src/Application.ts
packages/canvas-extract/src/CanvasExtract.ts
packages/canvas-prepare/src/CanvasPrepare.ts
packages/canvas-renderer/src/CanvasContextSystem.ts
packages/canvas-renderer/src/CanvasRenderer.ts
packages/canvas-renderer/src/canvasUtils.ts
packages/canvas-renderer/src/utils/canUseNewCanvasBlendModes.ts
packages/events/src/EventSystem.ts
packages/extract/src/Extract.ts
packages/mixin-cache-as-bitmap/src/index.ts
packages/spritesheet/test/spritesheetAsset.tests.ts
packages/text-bitmap/src/utils/drawGlyph.ts
packages/text-bitmap/src/utils/generateFillStyle.ts
tools/integration-tests/test/Bounds.tests.ts
tools/integration-tests/test/Container.tests.ts

Follow up #8619.
Change some imports from `@pixi/math`, `@pixi/settings`, `@pixi/utils` to `@pixi/core`, mainly some `ICanvas` stuff. ~Also some import sorting is included.~

Chore: Cleanup core dependencies

---

packages/utils/src/media/trimCanvas.ts
packages/utils/test/trimCanvas.tests.ts

Optimize `trimCanvas`, using the implementation in https://gist.github.com/timdown/021d9c8f2aabc7092df564996f5afbbf. Also a new test for trimming empty canvas is added.
Closes #8815.

Optimize trimCanvas

---

packages/text/src/Text.ts
packages/text/src/TextStyle.ts

* Add `TextStyle.defaultStyle` to expose the default options, usefully for changing defaults globally
```js
TextStyle.defaultStyle.fontFamily = 'Times';
const style = new TextStyle();
console.log(style.fontFamily); // Times
````
* Add documentation for `ITextStyle`
* Properly document the default values of the TextStyle
* Webdoc does not support `type` so some of our types needed to documented better (e.g., `TextStyleAlign` becomes `'left'|'center'|'right'|'justify'`)
**v7.0.4**
* [TextStyle](https://pixijs.download/v7.0.4/docs/PIXI.TextStyle.html)
**PR**
* [TextStyle](https://pixijs.download/chore/text-style-docs/docs/PIXI.TextStyle.html)
* [ITextStyle](https://pixijs.download/chore/text-style-docs/docs/PIXI.ITextStyle.html)

Expose TextStyle's defaultStyle, document ITextStyle

---

.gitignore
package.json

Chore: Add ESLint cache

---

bundles/pixi.js-webworker/src/adapter.ts
packages/text/src/TextMetrics.ts

- `WebWorkerAdapter.getCanvasRenderingContext2D` should return `OffscreenCanvasRenderingContext2D`.
- `TextMetrics.experimentalLetterSpacingSupported` is lazy evaluated, so that it can use the correct `ADAPTER`.
Fixes #8938.
Broken: https://pixijs.io/examples/?v=dev#/offscreen-canvas/web-worker.js
Fixed: https://pixijs.io/examples/?v=fix/8938#/offscreen-canvas/web-worker.js

Fix: getCanvasRenderingContext2D in Web Worker

---

packages/core/src/IRenderer.ts

`IRenderer.generateTexture` should return `RenderTexture` instead of `void`.
Fixes #8947.

Fix: IRenderer.generateTexture should return RenderTexture

---

packages/assets/src/Assets.ts
packages/assets/src/loader/Loader.ts

Closes #8819
Make it explicit not to fetch assets in the onProgress callback.

Clarify the onProgress design limitations in docs

---

packages/assets/src/Assets.ts
packages/assets/src/resolver/Resolver.ts
packages/assets/test/assets.tests.ts
packages/assets/test/resolver.tests.ts

Adds support for default url params via the init function.
```
await Assets.init({
defaultSearchParams: {
foo: 'bar',
chicken: 'nuggets',
},
});
const bunnyTexture = await Assets.load('bunny.png'); // url = bunny.png?foo=bar&chicken=nuggets
```

Add defaultSearchParams option to Assets

---

packages/events/src/EventSystem.ts

When `WheelEvent` is triggered by scrolling with mouse wheel, reading `WheelEvent.deltaMode` before `deltaX`/`deltaY`/`deltaZ` on Firefox will result in `WheelEvent.DOM_DELTA_LINE (1)`, while reading `WheelEvent.deltaMode` after `deltaX`/`deltaY`/`deltaZ` on Firefox or reading in any order on other browsers will result in `WheelEvent.DOM_DELTA_PIXEL (0)`.
Therefore, we need to read `WheelEvent.deltaMode` after `deltaX`/`deltaY`/`deltaZ` in order to make its behavior more consistent across browsers.
Fixes #8970.
Example (Use Firefox, scroll the mouse wheel on the right and see result in console):
- **Before**: <https://www.pixiplayground.com/#/edit/-0JdGEPsmMGlNkGUYw0ed>
- **After**: <https://www.pixiplayground.com/#/edit/03E9XWNqQPJMSXzoIfdbb>

Fix: WheelEvent.deltaMode consistency

---

packages/canvas-renderer/src/CanvasRenderer.ts
packages/canvas-renderer/test/CanvasRenderer.tests.ts
packages/core/src/IRenderer.ts
packages/core/src/Renderer.ts
packages/core/test/Renderer.tests.ts

While working on https://github.com/pixijs/graphics-smooth I noticed that the Renderer use to save a reference to the constructor options in v6. I have re-added this. It's helpful for debugging to conditional rendering based on options.

Expose options for Renderers

---

README.md
bundles/pixi.js-legacy/README.md
bundles/pixi.js-webworker/README.md
bundles/pixi.js/README.md
packages/basis/README.md
packages/graphics-extras/README.md
packages/math-extras/README.md
packages/unsafe-eval/README.md

Follow up #8827. Users may be confused about how to use browser build version of plugins (#9019), so I add examples for it in package's `README.md`. This will show up on the <https://npmjs.com> pages, and it can be helpful for users.
(The CDN URL in `/README.md` was wrong, caused by the different directory structure between v6 and v7. Now it is fixed.)

Add CDN Install section in READMEs for browser builds

---

packages/text/src/TextMetrics.ts

A text with font size 0 breaks everything at the moment.
Chrome:
```
Uncaught DOMException: Failed to execute 'getImageData' on 'OffscreenCanvasRenderingContext2D': The source width is 0.
```
Firefox:
```
Uncaught DOMException: Index or size is negative or greater than the allowed amount
```
- Before: https://pixiplayground.com/#/edit/cIjE5gOXYJNVBBJXXBaMS
- After: https://pixiplayground.com/#/edit/25iy0k7gKs0e11mp9mbMC

Fix `TextMetrics.measureFont` breaking if passed a font with size 0

---

bundles/pixi.js-node/README.md

The `@pixi/node` package is amazing! However, it is quite tricky to setup; especially when most js programmers are used to running `npm i` and everything just works. I have added a some more information to the README to hopefully aid in getting setup with the package.
- Fixed inconsistent header sizing in README
- Added section to fix `unable to auto-detect a suitable renderer`
- Added section with example Dockerfile to setup a complete environment for the example 🐳

`@pixi/node` README.md improvements (Dockerfile example + `vxfb` install)

---

packages/spritesheet/src/spritesheetAsset.ts
packages/spritesheet/test/spritesheetAsset.tests.ts

Follow up #8887. I intentionally skipped the `spritesheetAsset` in #8887 to avoid conflict with #8859, but now #8859 is closed, so I'm going to do that in this PR.

Improve typing for `loader.load()` in spritesheetAsset

---

packages/utils/src/media/trimCanvas.ts

This should do a relative import. Was producing build errors like this:
```
packages/utils/src/index.ts → packages/utils/lib, packages/utils/lib...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
@pixi/utils (imported by packages/utils/src/media/trimCanvas.ts)
created packages/utils/lib, packages/utils/lib in 51ms
```

Update trimCanvas.ts import

---

bundles/pixi.js-node/src/filters.ts
bundles/pixi.js-node/src/index.ts
bundles/pixi.js-webworker/src/filters.ts
bundles/pixi.js-webworker/src/index.ts
bundles/pixi.js/src/filters.ts
bundles/pixi.js/src/index.ts
packages/core/src/filters/Filter.ts
packages/filter-alpha/src/AlphaFilter.ts
packages/filter-blur/src/BlurFilter.ts
packages/filter-blur/src/BlurFilterPass.ts
packages/filter-color-matrix/src/ColorMatrixFilter.ts
packages/filter-displacement/src/DisplacementFilter.ts
packages/filter-fxaa/src/FXAAFilter.ts
packages/filter-noise/src/NoiseFilter.ts

An issue came up recently using `importmap` with `pixi-filters` (see https://github.com/pixijs/filters/pull/365) that is fixed by this PR.
We created this synthetic namespace `filters` for adding all the display object filters. We have generally removed all of these namespace from project except for filters. Removing filters seems like a good idea and consistent with recent changes.
Deprecate the `filters` namespace export for the bundles:
* `pixi.js`
* `pixi.js-legacy`
* `@pixi/node`
* `@pixi/webworker`
* [API Documentation](https://pixijs.download/deprecate-filters-namespace/docs/PIXI.filters.html)
* [Example](https://jsfiddle.net/bigtimebuddy/15qbzo6e/)

Deprecate filters namespace

---

packages/canvas-renderer/src/CanvasRenderer.ts
packages/core/src/Renderer.ts

There are some duplicate definitions in `Renderer` and `CanvasRenderer`:
https://github.com/pixijs/pixijs/blob/bd4b997e510a7528e89c5868b71c558987ead15c/packages/core/src/Renderer.ts#L38-L42
https://github.com/pixijs/pixijs/blob/bd4b997e510a7528e89c5868b71c558987ead15c/packages/canvas-renderer/src/CanvasRenderer.ts#L38-L42
It seems that they were accidentally introduced when merging #8425 and #8427, and should be removed.

Chore: Remove some duplicate definitions

---

packages/assets/src/Assets.ts
packages/assets/src/loader/parsers/textures/loadSVG.ts

Based off this issue https://github.com/pixijs/pixijs/issues/8592, I noticed that SVG support for the Assets loader was supposed to be implemented in 6.5.2. It _was_ implemented here https://github.com/pixijs/pixijs/pull/8574, but I think I noticed an issue that it's not actually available for use because it's not added to the list of parsers.
I'm struggling to npm install and run these commands myself.

Add SVG Assets parser to list of parsers

---

packages/core/src/settings.ts

Fix some typos in deprecation messages added in 7.1.0: `BaseTeture` -> `BaseTexture`

Fix: Typos in deprecation messages

---

packages/events/global.d.ts
packages/events/src/EventBoundary.ts
packages/events/src/FederatedEventMap.ts
packages/events/src/FederatedEventTarget.ts
packages/events/test/EventSystem.tests.ts

This PR add 3 new events `globalpointermove`, `globaltouchmove`, and `globalmousemove`
These move events behave like the old interaction system, and is the equivalent of setting `events.rootBoundary.moveOnAll`
This PR also fixes an issue with `displayObject.addEventListener` types not being correctly assigned in the `global.d.ts` file

Add global move events

---

packages/events/src/EventBoundary.ts

This PR fixes the issue where if you start your interaction outside the bounds of a DisplayObject then release inside of the DisplayObject the `pointerout` event would fire along with the `pointerover` event
Now only the `pointerover` event fires
Fixes #9062

pointerout fired when interaction started outside of object

---

package.json
packages/core/src/batch/BatchTextureArray.ts
packages/core/src/mask/MaskData.ts
packages/core/src/transformFeedback/TransformFeedback.ts
packages/core/src/transformFeedback/TransformFeedbackSystem.ts

Core was throwing a bunch of build errors (`Circular dependency` and `Unresolved dependencies`) because things inside of `@pixi/core` were importing from itself. This changes these imports to be relative.
Example Error:
```
packages/core/src/index.ts → packages/core/lib, packages/core/lib...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
@pixi/core (imported by packages/core/src/mask/MaskData.ts)
created packages/core/lib, packages/core/lib in 660ms
bundles/***/src/index.ts → bundles/***/lib, bundles/***/lib...
created bundles/***/lib, bundles/***/lib in 16ms
bundles/***/src/index.ts → bundles/***/dist/***, bundles/***/dist/pixi.mjs...
(!) Circular dependency
packages/core/lib/index.mjs -> packages/core/lib/settings.mjs -> …
```

Fix circular dependencies in build process

---

packages/core/src/textures/resources/ImageBitmapResource.ts

Users using `create-react-app` + PixiJS are continuously facing problem with transpilation (#8733, #8824 and #9064). Let me explain the details.
In #8698 I added code below in `ImageBitmapResource.constructor`:
<https://github.com/pixijs/pixijs/blob/2f12f4ee46fd17ef5b0ab2eb6bc23f1d03295f76/packages/core/src/textures/resources/ImageBitmapResource.ts#L62-L73>
This looks good, and when releasing it will be transpiled by `esbuild`:
```js
var __super = (...args) => {
super(...args);
};
if (typeof source === "string") {
__super(ImageBitmapResource.EMPTY);
this.url = source;
} else {
__super(source);
this.url = null;
}
```
([Source code of related logic in esbuild here.](https://github.com/evanw/esbuild/blob/5fe21253ee75fb4c5ea395a0877b2a5ab51c3575/internal/js_parser/js_parser_lower.go#L3064-L307 …

Fix: Workaround for transpilation failure with create-react-app

---

packages/text-bitmap/src/BitmapFont.ts
packages/text-bitmap/src/BitmapText.ts

Closes #9082 
v7.1.0:
https://jsfiddle.net/bigtimebuddy/xot0qn1c/
This PR:
https://jsfiddle.net/bigtimebuddy/jekt7vyn/
_Top: HTML, Middle: PIXI.Text, Bottom: PIXI.BitmapText w/ BitmapFont_

Fix xadvance calculating when rendering BitmapText

---

packages/extract/src/Extract.ts
packages/extract/test/Extract.tests.ts

Currently the `Extract#canvas` and `Extract#pixels` doesn't consider the `renderer.multisample`, and this results in the extracted image being rendered without anti-aliasing (#8757), so I add support for multisample in Extract. Also the common part of `Extract#canvas` and `Extract#pixels` ate moved to a separate function `Extract#_rawPixels`.
Example (Left: Direct rendering; Right: Extracted image):
- Before: <https://pixiplayground.com/#/edit/dvxrRjI2Kb7SIIz1vNGcA>
- After: <https://pixiplayground.com/#/edit/jhGoI3tGmcRxrQ_hzCdi->
Fix for v6.x is in #9103.

Fix: Extract should use multisample

---

packages/extract/package.json
packages/extract/src/Extract.ts
packages/extract/test/Extract.tests.ts

Follow up #9102.
Example (Left: Direct rendering; Right: Extracted image):
- Before: <https://pixiplayground.com/#/edit/KV6JEp2oLzZoEC5ZYUbBU>
- After: <https://pixiplayground.com/#/edit/G5ZiCEToxK4nFSAB-T5fz>
Fixes #8757.

Fix: Extract should use multisample (for v6.x)

---

packages/canvas-renderer/src/CanvasRenderer.ts
packages/core/src/Renderer.ts

In #9010 renderer options were added, however the reference to the options was set after the plugins/systems got initialised, so they could not be used

Fix renderer options not being passed to plugins

---

packages/assets/src/loader/parsers/loadWebFont.ts

Fixes #8990 
I believe the `onLine` check was a legacy hack from the Goodboy days of the loader to fix an ie11 issue
We don't need this check in pixi

Remove navigator.onLine check

---

packages/app/src/Application.ts
packages/canvas-renderer/src/CanvasRenderer.ts
packages/core/src/AbstractRenderer.ts
packages/core/src/Renderer.ts
packages/core/src/autoDetectRenderer.ts
packages/settings/src/settings.ts

Follow up #9120, trying to cleanup `IRendererOptions` related documents for v6.x branch.
Document preview:
- `IRendererOptions` ~Before~ | [After](https://pixijs.download/chore/renderer-options-docs-v6.x/docs/PIXI.IRendererOptions.html)
- `AbstractRenderer` [Before](https://pixijs.download/v6.5.9/docs/PIXI.AbstractRenderer.html#constructor) | [After](https://pixijs.download/chore/renderer-options-docs-v6.x/docs/PIXI.AbstractRenderer.html#constructor)
- `Renderer` [Before](https://pixijs.download/v6.5.9/docs/PIXI.Renderer.html#constructor) | [After](https://pixijs.download/chore/renderer-options-docs-v6.x/docs/PIXI.Renderer.html#constructor)
- `CanvasRenderer` [Before](https://pixijs.download/v6.5.9/docs/PIXI.CanvasRenderer.html#constructor) | …

Chore: Cleanup document for renderer options (for v6.x)

---

packages/canvas-mesh/global.d.ts
packages/core/global.d.ts
packages/display/global.d.ts
packages/prepare/global.d.ts
packages/ticker/global.d.ts

One of the deprecated settings in 7.1.0 wasn't updated in display global.d.ts correctly.

Fix deprecation docs for global Settings mixins

---

.github/workflows/nodejs.yml
package-lock.json
package.json

@vikpe pointed this out
Would probably be good to get on 18 LTS version for the project.

Chore: Bump required Node.js to 18+

---

packages/color/src/Color.ts
packages/color/test/Color.tests.ts

Closes #9144 
Validation: 
https://jsfiddle.net/bigtimebuddy/84ug5tsh/

Fix: Ensure Color internal integer is refreshed when multiplying

---

packages/color/src/Color.ts
packages/color/test/Color.tests.ts

Closes #9146
Invalidates Color's `value` property (to `null`) when using `multiply` or `round` methods.

Fix: Invalid Color value when using multiply or round methods

---

package.json
rollup.config.js

Follow-up to #9125 (remove Lerna)
Closes https://github.com/pixijs/examples/issues/116
**Broken**: https://pixijs.io/examples/#/graphics/simple.js (black screen)
**Fixed**: https://pixijs.io/examples/?v=fix/optional-packages#/graphics/simple.js

Fix building of optional packages

---

package-lock.json
package.json
rollup.config.js
scripts/prepublish.ts
test/packages.ts

I forked workspaces-run (`@pixi/workspaces-run`) which is essentially the same thing, but supports `orderByDeps` with relative links (which we recently added). I removed the hacks. Hopefully if the original maintainer updates `workspaces-run`, I'll move back to that.

Chore: Use workspaces-run fork and orderByDeps

---

packages/assets/src/cache/CacheParser.ts
packages/assets/src/loader/parsers/LoaderParser.ts
packages/color/src/Color.ts
packages/core/src/geometry/Buffer.ts
packages/core/src/renderTexture/BaseRenderTexture.ts
packages/core/src/textures/Texture.ts
packages/core/src/textures/resources/BufferResource.ts
packages/core/src/textures/resources/CanvasResource.ts
packages/core/src/textures/resources/CubeResource.ts
packages/events/global.d.ts
packages/events/src/EventSystem.ts
packages/events/src/EventTicker.ts
packages/events/src/FederatedEventTarget.ts
packages/graphics/src/Graphics.ts
packages/graphics/src/const.ts
packages/spritesheet/src/Spritesheet.ts
packages/text-html/src/HTMLText.ts
packages/text-html/src/HTMLTextStyle.ts

I'm also doing some document cleanup recently. In case of conflict with #9161, I put it here.
- Add `@since 7.2.0` for new things in v7.2.0
- Add some missing `@memberof PIXI` (No more `.html` with out `PIXI.` prefix in `dist/docs`!)
- Add `@type {PIXI.EventsTickerClass}` for `EventsTicker` (Webdoc can't determine its type)
- Remove some unused `@interface` (`SharedArrayBuffer`, `OffscreenCanvas`, may come from old code and they are not being used anymore)
- Other minor fixes

Docs: Cleanup document

---

packages/events/src/EventBoundary.ts
packages/events/test/EventBoundary.tests.ts
packages/events/test/EventSystem.tests.ts

This PR fixes 2 issues
- the global move events fired even if a display object is not interactive
- if you set a child to be interactive, the parent would still receive the events even if it was not interactive
```
const sprites = new PIXI.Container();
sprites.interactive = false
// previously this would still fire
sprites.on('pointermove', ()=>{
console.log('move')
})
app.stage.addChild(sprites);
const totalSprites = 30;
for (let i = 0; i < totalSprites; i++) {
const dude = PIXI.Sprite.from('https://pixijs.io/examples/examples/assets/maggot_tiny.png');
dude.interactive = true
sprites.addChild(dude);
}
```
This should also help fix #9156

Fix: events firing when they shouldn't

---

packages/color/src/Color.ts
packages/color/test/Color.tests.ts
packages/core/src/batch/BatchRenderer.ts
packages/graphics/src/GraphicsGeometry.ts
packages/mesh/src/MeshMaterial.ts
packages/particle-container/src/ParticleRenderer.ts
packages/sprite-tiling/src/TilingSpriteRenderer.ts
packages/utils/src/color/premultiply.ts
packages/utils/test/utils.tests.ts

* `utils.premultiplyRgba`
* `utils.premultiplyTint`
* `premultiplyTintToRgba`
* `Color.premultiply` (applies a premultiply alpha transform to color)
* `Color.toPremultiplied` (get the current color as an integer with alpha)

Refactor premultiply utilities to the Color class

---

package-lock.json
package.json
rollup.config.js
scripts/prepublish.ts
test/packages.ts

Fast follow-up to #9163 to replace `@pixi/workspaces-run@1.0.2` with `workspaces-run@1.0.2`

Chore: Update workspaces-run package

---

packages/core/src/shader/utils/uniformParsers.ts

This PR alows devs to pass the color object as a uniform property and it get uploaded accordingly
eg:
```
const fragmentSrc = `
uniform vec4 inputColor;
void main() {
gl_FragColor = vec4(inputColor);
}`;
const color = new Color('yellow');
const uniforms = { 
inputColor: color,
};
```

Add ability to set Color object on `vec3` or `vec4` uniforms

---

packages/display/src/DisplayObject.ts
packages/events/global.d.ts
packages/events/src/EventBoundary.ts
packages/events/src/EventSystem.ts
packages/events/src/FederatedEventTarget.ts
packages/events/test/EventBoundary.tests.ts
packages/events/test/EventSystem.tests.ts

We have now decided to fully deprecate `interactive` and move to using `eventMode` to describe the new interaction types
For backwards compatibility we map `interactive = false` to `eventMode = 'auto` and `interactive = true` to `eventMode = 'static'`
#9167 should be closed in favour of this as i believe i moved everything over from it

Deprecate interaction for eventMode

---

packages/assets/src/loader/parsers/textures/loadTextures.ts

Fixes #9158 
Adds 2 new options for `loadTextures` to allow the user to prefer `createImageBitmap` and set `crossOrigin`

Feat: Add new config options for loadTextures

---

rollup.config.js

Currently there are two problems when bundling `@pixi/color`:
1. Files from `colord/plugins/names` are accidentally bundled into `@pixi/color`, see <https://github.com/pixijs/pixijs/issues/9189#issuecomment-1437309750>.
2. The `Color.mjs.map` file becomes invalid for some reason, causing jsDeliver failed to bundle esm package, see <https://github.com/jsdelivr/jsdelivr/issues/18469#issuecomment-1438494155>:
```json5
{"version":3,"file":null,"sources":[null],"sourcesContent":[null],/* ... */}
```
After fixing the first problems, the source map become normal magically:
```json5
{"version":3,"file":"Color.mjs","sources":["../src/Color.ts"],"sourcesContent":[/* ... */],/* ... */}
```
(Maybe a bug of Rollup?)
This PR fixes these problems. Replace #9191, fixes #9189.

Bundle @pixi/color correctly

---

packages/color/src/Color.ts
scripts/filterTypeScriptErrors.ts

Ref #8852.
There are two major changes:
1. setter of `value`:
```diff
- set value(value: ColorSource)
+ set value(value: ColorSource | null)
{
// ...
}
```
Or there will be an error:
```
error TS2380: The return type of a 'get' accessor must be assignable to its 'set' accessor type
Type 'null' is not assignable to type 'ColorSource'.
```
Set `value` to `null` still throw an `Error`. Not sure if this is the best way to handle this.
2. `toUint8RgbArray`, `toRgbArray` and `toArray`:
```diff
- toArray<T extends (number[] | Float32Array) = number[]>(out?: T): T
+ toArray(): number[];
+ toArray<T extends (number[] | Float32Array)>(out: T): T;
+ toArray<T extends (number[] | Float32Array)>(out?: T): T
{
// ...
}
```
This typing improvement prevents usage like `color.toArray<Float32Array>()`.

Add strict null checks to @pixijs/color

---

packages/assets/global.d.ts
packages/assets/package.json
packages/assets/src/Assets.ts
packages/assets/src/index.ts
packages/assets/src/loader/parsers/LoaderParser.ts
packages/assets/src/loader/parsers/textures/loadTextures.ts
packages/assets/test/assets.tests.ts

* Adds `Asset.setPreferences` and `Assets.init` property `preferences` which allow setting Loader configs. 
```ts
await Assets.init({
preferences: {
preferWorkers: false,
preferCreateImageBitmap: false,
crossOrigin: '',
}
});
```
Or:
```ts
Assets.setPreferences({
preferWorkers: false,
preferCreateImageBitmap: false,
crossOrigin: '',
});
```
* Adds `AssetPreferences` type, that has a GlobalMixin for extensibility.
* Deprecates `Asset.preferWorkers` property, use `Assets.setPreferences` instead
* https://pixijs.download/feature/asset-preferences/docs/index.html

Provide extensible Asset preferences

---

packages/graphics/src/Graphics.ts
packages/graphics/test/Graphics.tests.ts

* Adds support for ColorSource to `tint` in Graphics
```ts
const graphics = new Graphics();
graphics.tint = 'red';
```
https://jsfiddle.net/bigtimebuddy/4kdbg3n9/

Support ColorSource with Graphics tint

---

packages/canvas-mesh/src/CanvasMeshRenderer.ts
packages/canvas-mesh/src/NineSlicePlane.ts
packages/mesh/src/Mesh.ts
packages/mesh/src/MeshMaterial.ts
packages/mesh/test/Mesh.tests.ts
packages/text-bitmap/src/BitmapText.ts
packages/text-bitmap/src/BitmapTextStyle.ts
packages/text-bitmap/test/BitmapText.tests.ts

Support ColorSource for Mesh & BitmapText `tint`
```ts
const mesh = new Mesh();
mesh.tint = 'red';
```
Example:
https://jsfiddle.net/bigtimebuddy/4L6yebdx/

Support ColorSource with Mesh & BitmapText tint

---

packages/canvas-sprite-tiling/src/TilingSprite.ts
packages/canvas-sprite/src/CanvasSpriteRenderer.ts
packages/sprite/src/Sprite.ts
packages/sprite/test/Sprite.tests.ts

Support ColorSource for Sprite `tint`
```ts
const sprite = new Sprite();
sprite.tint = 'red';
```
Example:
https://jsfiddle.net/bigtimebuddy/beroq52x/

Support ColorSource with Sprite tint

---

packages/particle-container/src/ParticleContainer.ts
packages/particle-container/test/ParticleContainer.tests.ts

Support ColorSource for ParticleContainer `tint`
```ts
const container = new ParticleContainer();
container.tint = 'red';
```
Example:
https://jsfiddle.net/bigtimebuddy/4m3vqhe1/

Support ColorSource with ParticleContainer tint

---

packages/events/src/EventBoundary.ts
packages/events/test/EventBoundary.tests.ts

Call `removeListener` on listeners registered with `once` in `EventBoundary#notifyListeners`, so that it can match the behavior of `EventEmitter#emit` (<https://github.com/primus/eventemitter3/blob/b99e3efb9d62392c7c7275d2f98d3d9dbc9b368f/index.js#L159-L216>).
Fixes #9195.

Fix: Listeners registered with EventEmitter#once should only trigger once

---

.github/workflows/nodejs.yml

In our previous prereleases, tags weren't getting updated correctly. For instance, here's 7.2.0-beta.2
https://github.com/pixijs/pixijs/actions/runs/4244955704/jobs/7379807833#step:18:19
Publish command was:
```
npm publish --dist-tag prerelease
```
Should be:
```
npm publish --tag prerelease
```

Chore: Fix prerelease tag

---

packages/core/src/IRenderer.ts

`Irenderer` currently lists `resolution` as `readonly` but the `Renderer` implementation has a setter for `resolution`: https://github.com/pixijs/pixijs/blob/dev/packages/core/src/Renderer.ts#L459

Resolution isn't readonly in current renderer implementation

---

package-lock.json
package.json
packages/settings/package.json
packages/settings/src/utils/isMobile.ts
rollup.config.js

Move `ismobilejs` from `devDependencies` to `dependencies`, so that it will not be bundled into `@pixi/settings` and generating invalid source maps (see <https://unpkg.com/browse/@pixi/settings@7.2.0-beta.2/lib/external/ismobilejs/esm/>).
Also remove `rollup-plugin-rename-node-modules`, since there is no bundled dependency now.
Fixes #9189.

Chore: Remove all dependencies from module bundles

---

packages/canvas-sprite-tiling/src/TilingSprite.ts

https://github.com/pixijs/pixijs/blob/699b515bed7a0c4ea2429f46e94def5286704e90/packages/canvas-sprite-tiling/src/TilingSprite.ts#L120-L128
`lt` (`tileTransform.localTransform`) already contains `tileScale` (which is actually `tileTransform.scale`), so there is no need to multiply it again. (It is introduced in #8059.)
- Before: <https://jsfiddle.net/bigtimebuddy/n3g78rdm/>
- After: <https://jsfiddle.net/SuperSodaSea/w6bosd8v/>
Fixes #9205.

Fix: TilingSprite#tileScale inconsistency between WebGL and Canvas

---

package.json
scripts/filterTypeScriptErrors.ts

Add packages that already have no error with strict null checks to the filter in `scripts/filterTypeScriptErrors.ts`:
- `bundles/pixi.js/`
- `bundles/pixi.js-legacy/`
- `packages/canvas-text/`
- `packages/constants/`
- `packages/filter-alpha/`
- `packages/filter-displacement/`
- `packages/filter-fxaa/`
- `packages/filter-noise/`
- `packages/mixin-get-global-position/`
- `packages/settings/`
- `packages/text-html/`
- `packages/unsafe-eval/`
Also `types:strict` is added back to `npm run dist` (so we can check it easily on CI), but now it will not break the build when error occurs (`types:strict` will not exit with non-zero code).

Add strict null checks to packages with no errors

---

packages/canvas-renderer/src/CanvasRenderer.ts
packages/core/src/Renderer.ts

I suddenly realized that `app.renderer.type` is always `undefined`. This PR fixes this issue.

Fix: Renderer#type not available

---

packages/mesh-extras/src/geometry/RopeGeometry.ts

Prevent dividing by zero in `RopeGeometry#updateVertices`, so that the vertex data won't contain NaN that behave strangely on some devices.
- Before: <https://www.pixiplayground.com/#/edit/lf3-od11oJHrVZsocPxWw>
- After: <https://www.pixiplayground.com/#/edit/jvybc3FllLh2dOOz6mv5K>
Fixes #9179.

Fix: Prevent NaN in RopeGeometry vertex data

---

packages/canvas-extract/package.json
packages/canvas-extract/src/CanvasExtract.ts
packages/extract/global.d.ts
packages/extract/src/Extract.ts
packages/prepare/global.d.ts

Closes #9207
* Fix: Ensure `prepare` and `extract` extensions are available from `IRenderer`
```ts
import { Application, Renderer } from 'pixi.js';
const app = new Application();
(app.renderer as Renderer).extract.base64(); // throws type error without cast
```
```ts
import { Application } from 'pixi.js';
const app = new Application();
app.renderer.extract.base64();
```

Fix: Ensure prepare and extract systems are available from IRenderer

---

packages/settings/src/ICanvas.ts

I'm encountering errors like this in my project with `"exactOptionalPropertyTypes": true, "skipLibCheck": false`:
```
node_modules/.pnpm/@pixi+settings@7.2.0-beta.4/node_modules/@pixi/settings/lib/ICanvas.d.ts:43:18 - error TS2430: Interface 'ICanvas' incorrectly extends interface 'Partial<EventTarget>'.
Types of property 'addEventListener' are incompatible.
Type '{ (type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions | undefined): void; <K extends keyof WebGLContextEventMap>(type: K, listener: (this: ICanvas, ev: WebGLContextEventMap[K]) => any, options?: boolean | ... 1 more ... | undefined): void; } | undefined' is not assignable to type '(type: string, callback: EventListenerOrEventListenerObject | null, options?: boolean | …
```

Fix: TypeScript error with ICanvas

---

README.md
bundles/pixi.js-legacy/README.md
bundles/pixi.js-webworker/README.md
bundles/pixi.js/README.md

Force cache bust for the banner. GitHub caches this request.
This replaces with our new branding

Cache bust banner image

---

packages/events/src/EventBoundary.ts

Closes #9241
* Fix missing `shiftKey` in FederatedEvent
Broken: https://pixiplayground.com/#/edit/f8EPRf3qJ9NGiyxMo01og
Fixed: https://jsfiddle.net/bigtimebuddy/9L2oub3q/

Fix missing shiftKey copy from originalEvent

---

packages/events/global.d.ts
packages/events/src/EventBoundary.ts
packages/events/src/EventBoundaryTypes.ts
packages/events/src/EventSystem.ts
packages/events/test/EventSystem.tests.ts

Changes:
- We can now turn on/off different interactions through renderer settings
I've conceptualised these as `move`, `globalMove`, `click`, and `wheel`
```ts
/**
* The event types that are enabled by the EventSystem
* @type {object}
* @readonly
* @since 7.2.0
* @property {boolean} move - Enables pointer events associated with pointer movement:
* - `pointermove` / `mousemove` / `touchmove`
* - `pointerout` / `mouseout`
* - `pointerover` / `mouseover`
* @property {boolean} globalMove - Enables global pointer move events:
* - `globalpointermove`
* - `globalmousemove`
* - `globaltouchemove`
* @property {boolean} click - Enables pointer events associated with clicking:
* - `pointerup` / `mouseup` / `touchend` / 'rightup'
* - `pointerupoutside` / `mouseupoutside` / `touchendoutside` / …
```

Fix: interaction performance

---

packages/unsafe-eval/src/install.ts

Remove the `unsafeEvalSupported()` check in `selfInstall()` of @pixi/unsafe-eval, it will cause error when require-trusted-types-for is enabled. We already don't check this before #8805, so it should be ok.
Fixes #9248.

Fix: Remove the check when installing @pixi/unsafe-eval

---

packages/events/src/EventSystem.ts
packages/events/test/EventSystem.tests.ts

In pixi v6 there was `interaction.mouse` which allowed you to get the global position of the mouse without listening to an event
This PR exposes this data as `events.pointer`

Feature: Expose global pointer event data

---

packages/assets/src/loader/parsers/loadJson.ts
packages/assets/src/loader/parsers/loadTxt.ts
packages/assets/src/loader/parsers/textures/loadSVG.ts
packages/assets/test/assets.tests.ts

Support loading SVG / JSON / TXT assets from data URLs.
- TXT: `text/plain`
- JSON: `application/json`
- SVG: `image/svg+xml`
Closes #9256.

Support loading SVG / JSON / TXT assets from data URLs

---

packages/text-bitmap/src/shader/msdf.frag

Hi, i am working on app where i need to draw zoomable node graphs. And in order to make text look good and work fast with big number of nodes, I decided to switch to BitmapText with MSDF Fonts.
After some testing I noticed, that text became less readable compared to PIXI.Text.
I have exactly same problem in one of my previous projects, where I made my own text rendering using MSDF. The problem is in fragment shader that doesn't take in account blending gamma correction. My change make it more valid, not 100% but goodenough from perception point of view.
Text rendering, especially on small sizes and low dpi (non-retina) has many pitfals, and one of them - gamma correction. To make text look good and readable, you must use gamma corrected blending. Otherwise, text wouldn't be readable if …

Make MSDF fragment shader "alpha" more like it was "coverage"

---

packages/events/src/FederatedEvent.ts

[TypeScript 5.0](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/) is out now. I tried it out with PixiJS (with `"skipLibCheck": false`) and found several errors:
<details>
<summary><b>package.json</b></summary>
```json
{
"dependencies": {
"pixi.js": "^7.2.0"
},
"devDependencies": {
"typescript": "^5.0.2"
}
}
```
</details>
<details>
<summary><b>tsconfig.json</b></summary>
```json
{
"compilerOptions": {
"moduleResolution": "node",
"target": "esnext",
"esModuleInterop": true,
"skipLibCheck": false
}
}
```
</details>
<details>
<summary><b>index.ts</b></summary>
```ts
import * as PIXI from 'pixi.js';
```
</details>
Run:
```bash
npm i
npx tsc
```
And we got the error message:
```
node_modules/@pixi/events/lib/FederatedEvent.d.ts(123,5): error TS2416: Property 'AT_TARGET' …
```

Fix: TypeScript 5.0 compatibility

---

packages/events/src/EventBoundary.ts
packages/events/test/EventSystem.tests.ts

Fixes #9271 
There was a slight oversight where I accidently pruned DisplayObjects with masks and hit areas but we can't prune these on pointermove

Fix global move event with custom hit areas and masks

---

packages/color/src/Color.ts
packages/color/test/Color.tests.ts

Closes #9277
Copy the value internally and do a deep compare before re-setting. 
This avoids situations like this:
```js
const value = [0, 0, 0];
const color = new Color(value);
value[0] = 1;
color.setValue(value);
console.assert(color.red === 1); // v7.2.1 would be false, red would still be 0
```

Fix: Clone and deep equal the Color's value when setting

---

packages/color/src/Color.ts
packages/color/test/Color.tests.ts

Using a value for `this.alpha` on a Graphics object over 1 would crash the app
A common use case is using a tween to fade the alpha and depending on the ease the number can go above/below 0-1
```
await gsap.to(this, {
alpha: 1, // alpha to 1
ease: Back.easeOut.config(1.7),
});
```

Fix passing unclamped values to Color

---

packages/events/src/EventBoundary.ts
packages/events/test/EventSystem.tests.ts

Fixes: #9284
before:  https://jsfiddle.net/0dwogvej/
after:  https://codesandbox.io/s/pixi-js-sandbox-forked-5d3688
I have split the hit test functions into 2. This had two benefits, the first being that it is easier to understand the logic without needing a bunch of conditional checks, the other is that now there is zero performance penalty when turning off global move events as it will just use the normal hit testing when turned off

Fixes over/out events for objects with custom hit areas

---

packages/assets/src/BackgroundLoader.ts
packages/basis/src/Basis.ts
packages/canvas-renderer/src/CanvasRenderer.ts
packages/core/src/IRenderer.ts
packages/core/src/background/BackgroundSystem.ts
packages/core/src/context/ContextSystem.ts
packages/core/src/startup/StartupSystem.ts
packages/core/src/view/ViewSystem.ts
packages/display/src/DisplayObject.ts

Couple of small doc changes
Main change is that `BackgroundSytemOptions` is deprecated for the correct spelling

Misc doc changes

---

packages/color/src/Color.ts

The current `Color.round` does absolutely nothing. No rounding at all.
I assume that's how the rounding is supposed to be. Should the alpha component be rounded too?

Fix `Color.round`

---

.github/workflows/trigger-website-build.yml

Adds pr reference and pr merge sha to the repository dispatch payload for informational purposes - it's added to the resulting commit message when a new `pixi-versions.json` file is written during the `update-dev` workflow for `beta.pixijs.com`

Add additional payload properties to trigger-website-build workflow

---

packages/color/src/Color.ts

`Color.shared.setValue(...)` shouldn't produce any garbage if possible as it might be called every frame multiple times.

Avoid object creation in `Color.normalize`

---

packages/assets/src/loader/parsers/loadWebFont.ts
packages/assets/test/loadWebFont.tests.ts

Wrap font family names in quotes that are not consists of valid [CSS ident-tokens](https://www.w3.org/TR/css-syntax-3/#ident-token-diagram), they will fail to load in Firefox if used directly.
For example, `getFontFamilyName('Press_Start_2P.woff2') === '"Press Start 2p"'`.
Fixes #9286.

Fix: Wrap non CSS ident-token font names in quotes

---

packages/core/src/IRenderer.ts

Closes #9308
* Adds `background` property to IRenderer
* Adds `autoDensity` property to IRenderer

Fix: Add background and autoDensity types to IRenderer

---

packages/canvas-renderer/src/utils/canUseNewCanvasBlendModes.ts

Cache the value of the can-use-blend-mode check. It shows up in my stack traces more than I'd like to, I have many small canvas elements.

fix: cache can-use-blend-mode value

---

packages/canvas-extract/src/CanvasExtract.ts
packages/core/src/framebuffer/FramebufferSystem.ts
packages/core/test/FramebufferSystem.tests.ts
packages/core/test/GenerateTextureSystem.tests.ts
packages/core/test/Renderer.tests.ts
packages/extract/src/Extract.ts
packages/extract/test/Extract.tests.ts

- After `.blit(blitFramebuffer)` the `blitFramebuffer` is bound and so the `READ_FRAMEBUFFER` binding must be the `blitFramebuffer`. Otherwise we cannot read from it even though it is the bound framebuffer.
- The second render texture isn't necessary: we can read from the blit framebuffer.
- I allowed extraction from multisampled render texture by binding the blit framebuffer. The render texture needs to be blit before the extraction call of course.
- If the multisample of the renderer is used for the generated texture, then so should be the resolution of the renderer. But shouldn't `generateTexture` itself use the the renderer's resolution/multisample automatically then? Doesn't make sense to me if extract does but `generateTexture` doesn't.
Test (antialias and resolution 2):
- Before: …

Use the resolution of the renderer for the generated render texture in `Extract._rawPixels`

---

packages/core/src/textures/BaseTexture.ts
packages/core/test/BaseTexture.tests.ts

If `options` was given, the detected `type` never made it to the base texture.
`width` and `height` we don't need to add to the options. The `BufferResource` resizes the texture immediately.
If `type` is in the `options`, it replaces the auto detected `type`.

Fix `BaseTexture.fromBuffer` creating float texture with the wrong type

---

packages/canvas-extract/src/CanvasExtract.ts
packages/canvas-extract/test/CanvasExtract.tests.ts
packages/extract/src/Extract.ts
packages/extract/test/Extract.tests.ts
packages/settings/src/ICanvas.ts

- 3d2d89c9d6ad1a6fe6bfb78fec5a2a4dc10d9d8f: `canvas.toBlob` instead of `toDataURL` blocks the main thread for a shorter duration.
- 4a2ff59114c9f015b9c96f7f1c04fd4e53c331c2: Improves performance (~50ms => ~42ms in my test). The `getImageData` is unnessecary.
- 4b2ce461ddd34465d27a138ed245c7eaf9d876ca: Improves performance even more (~42ms => ~34ms in my test).

Extract performance improvements

---

packages/compressed-textures/src/resources/BlobResource.ts
packages/core/src/textures/resources/ImageBitmapResource.ts
packages/core/src/textures/resources/ImageResource.ts
packages/core/src/textures/resources/Resource.ts
packages/core/src/textures/resources/SVGResource.ts
packages/core/src/textures/resources/VideoResource.ts

Another call to `BlobResource.load` shouldn't load the data again.
Changed the return type of all Resource.load implementations to `Promise<this>` to make it consistent.
Added explicit `| null` to the types of some of members/parameters of `BlobResource`

Prevent `BlobResource.load` from loading the data multiple times

---

packages/assets/src/Assets.ts
packages/events/package.json
packages/events/src/FederatedEventTarget.ts

* Fix `@pixi/utils` shouldn't be included in assets or events. These were likely added recently due to deprecation auto-import.
cc @miltoncandelero

Fix utils dependencies in assets and events

---

packages/core/src/renderTexture/RenderTextureSystem.ts
packages/core/test/RenderTexture.tests.ts
packages/core/test/RenderTextureSystem.tests.ts

Fixed: Clear color is not premultiplied if `premultipliedAlpha`/`PMA`.

Premultiply clear color if render target has premultiplied alpha

---

packages/canvas-extract/test/CanvasExtract.tests.ts
packages/extract/src/Extract.ts
packages/extract/test/Extract.tests.ts

`Extract.pixels` does not y-flip the pixels currently, which means that the pixels are returned in the wrong orientation if extracted from the renderer. We should always receive the same pixels whether we extract from the display object, extract from a render texture the object was rendered to, or extract from the renderer the object was rendered to. `CanvasExtract.pixels` already passes the included test.

Flip pixels in `Extract.pixels` if extracted from the renderer

---

packages/canvas-renderer/src/canvasUtils.ts
packages/color/src/Color.ts

* Deprecates `canvasUtils.roundColor`
* Deprecates `Color.round`
There was an opportunity to simplify the code and remove the rounding (which didn't work anyway prior to #9294). Removes a bunch of redundant inline code for convert an int to hex string.
* https://codesandbox.io/s/pixi-js-sandbox-forked-sqlly9

Deprecate the round and roundColor methods

---

packages/canvas-extract/src/CanvasExtract.ts
packages/extract/src/Extract.ts

I think `ICanvas.base64` and `ICanvas.image` should have the `frame` parameter that `ICanvas.canvas` and `ICanvas.pixels` have too.
It might be prettier if `frame` was the second parameter for all 4, but then we need to add some overloading to not break anything.

Add frame parameter to `IExtract.base64` and `IExtract.image`

---

packages/text-html/src/HTMLTextStyle.ts

* Adds the ability to define [`display` property](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display) when loading fonts for HTMLText

Add HTMLTextStyle font load option for display

---

packages/core/src/textures/TextureSystem.ts
packages/core/src/textures/utils/mapInternalFormatToSamplerType.ts
packages/core/test/TextureSystem.tests.ts

The `samplerType` shouldn't be `FLOAT` for integer textures.

Set `GLTexture.samplerType` based on the internal format

---

packages/core/src/framebuffer/FramebufferSystem.ts
packages/core/src/framebuffer/GLFramebuffer.ts

I don't have a benchmark, but I assume that should be more efficient.

Create a `DEPTH_STENCIL` buffer only if depth is enabled

---

packages/core/src/renderTexture/BaseRenderTexture.ts

Fixed `BaseRenderTexture.framebuffer` not showing up in the docs too.

Add `BaseRenderTexture.multisample`

---

packages/particle-container/src/ParticleContainer.ts

Replace `class ParticleContainer extends Container<Sprite>` with `class ParticleContainer<T extends Sprite = Sprite> extends Container<T>`, so that users can specify the type of `ParticleContainer`'s children.
Closes #9348.

Add generic type variable for ParticleContainer

---

packages/graphics/src/styles/LineStyle.ts
packages/graphics/test/Graphics.tests.ts

Fix: `LineStyle.reset()` does not reset `cap`, `join`, and `miterLimit`

---

packages/canvas-renderer/src/CanvasRenderer.ts
packages/core/src/IRenderer.ts
packages/core/src/Renderer.ts
packages/core/src/renderTexture/GenerateTextureSystem.ts

`Extract` uses the renderer's resolution and multisample. I think `extract.pixels(generateTexture(object))` and `extract.pixels(object)` should give the same result.
`IGenerateTextureOptions.resolution` already made the claim that it defaults to the renderer's resolution, but that wasn't the case (`PIXI.settings.RESOLUTION` was the default):
>   The resolution / device pixel ratio of the texture being generated. Optional defaults to Renderer resolution.

Default to the renderer's resolution/multisample in `generateTexture`

---

packages/canvas-extract/src/CanvasExtract.ts
packages/canvas-extract/test/CanvasExtract.tests.ts
packages/core/src/renderTexture/GenerateTextureSystem.ts
packages/core/test/GenerateTextureSystem.tests.ts
packages/extract/src/Extract.ts
packages/extract/test/Extract.tests.ts

No need to make the generated render texture larger than it needs to be.

Generate frame-sized render texture for extraction

---

packages/core/src/textures/resources/VideoResource.ts

[`requestVideoFrameCallback`](https://wicg.github.io/video-rvfc/) isn't available everywhere unfortunately: https://caniuse.com/?search=requestVideoFrameCallback. If it is, we should use it to avoid unnecessary uploads each frame.

Use `requestVideoFrameCallback` to auto update `VideoResource` if possible

---

packages/extract/src/Extract.ts

Changed base64 method documentation to match method name "Extract.canvas", not nonexistent "Extract.getCanvas" method.

Fix typo in Extract.base64 documentation

---

packages/assets/src/loader/parsers/textures/loadTextures.ts
packages/core/src/textures/resources/ImageBitmapResource.ts
packages/core/test/ImageBitmapResource.tests.ts

Add `ownsImageBitmap` for `ImageBitmapResource` and `IImageBitmapResourceOptions`. When it is `true`, the `ImageBitmapResource`'s underlying `ImageBitmap` will be disposed (`this.source.close()` is called); otherwise the `ImageBitmap` will not be disposed.
If the `ownsImageBitmap` option is not set by user:
- When `source` is `ImageBitmap`, `ownsImageBitmap` will be `false` by default.
- When `source` is `string` (a URL), `ownsImageBitmap` will be `true` by default.
`loadTextures` is also updated: when `loadTextures` is using `ImageBitmap`, the `resourceOptions.ownsImageBitmap` will be set to `true` when creating the `BaseTexture` if this option is not set by user.
Fixes #9403.
- Before (disposed): <https://www.pixiplayground.com/#/edit/cW1MglcpTHTH_ViEEj4YJ>
- After (not disposed): …

Add ownsImageBitmap for ImageBitmapResource

---

packages/text/src/TextMetrics.ts

An extra `leading` need to be added to `TextMetrics`' height to get the correct result.
- Before: <https://pixiplayground.com/#/edit/aK-uHfQkxW1Tr2bxI0c6n>
- After: <https://pixiplayground.com/#/edit/eHg-yNE0Gq2GE8YCbdAMe>
Fixes #9410.

Fix: Text being cropped when leading is not 0

---

packages/utils/src/index.ts
packages/utils/src/network/determineCrossOrigin.ts
packages/utils/src/url.ts

This is related to #9413, where I proposed to replace `url` dependency with native API.

Replace `url` dependency with modern URL API

---

packages/core/src/textures/TextureGCSystem.ts

If a texture doesn't have a resource, we shouldn't GC it, because we cannot reupload it. Only textures that are rendered to don't have a resource, but they don't have to be `BaseRenderTexture`s necessarily. For example, textures added to a framebuffer with `addColorTexture`/`addDepthTexture` aren't.

Don't GC textures that don't have a resource

---

packages/compressed-textures/src/resources/BlobResource.ts
packages/compressed-textures/src/resources/CompressedTextureResource.ts
packages/core/src/textures/BaseTexture.ts
packages/core/src/textures/Texture.ts
packages/core/src/textures/resources/BufferResource.ts
packages/core/test/BufferResource.tests.ts

Without control over the unpack alignment, we cannot upload a buffer resource that has a pixel row size in bytes isn't a multiple of 4, which is the default unpack alignment.

Add `BufferResource.unpackAlignment`

---

packages/assets/src/loader/parsers/textures/loadSVG.ts

`asset` is the SVG string, not the URL.

Fix the resource URL set by `loadSVG`

---

packages/text-bitmap/src/BitmapFont.ts

This pull request backports the changes introduced in #9496 to the v6 branch.
The original pull request, [#9496](https://github.com/pixijs/pixijs/pull/9496), added an option to skip kerning generation in the `BitmapFont.from` method. This feature provides a performance enhancement by reducing the computational overhead when generating bitmap fonts, particularly in scenarios where the kerning information isn't required.
The changes involve introducing a new 'skipKerning' property in the `IBitmapFontOptions` interface. When this property is set to `true`, the kerning calculation loop is bypassed, resulting in a performance gain.
This backport is important for users who are still on the v6 version of PixiJS and could benefit from the performance improvements.
- [ ❌ ] Tests and/or benchmarks …

Backport: Add skipKerning option to BitmapFont in v6

---

packages/text-bitmap/src/BitmapFont.ts

This pull request addresses the suggestion in issue [#8246](https://github.com/pixijs/pixijs/issues/8246), adding an option to skip the generation of kernings in the `BitmapFont.from` method.
The brute force kerning method was introduced in PR [#6888](https://github.com/pixijs/pixijs/pull/6888). This method can be computationally intensive, especially for larger character sets. 
By adding an option to bypass this step, developers can reduce the computational overhead when generating bitmap fonts, particularly in cases where the kerning information isn't required.
The changes involve adding a new property in the `IBitmapFontOptions` interface to allow skipping the kerning generation step. If this option is set to `true`, the method will bypass the kerning calculation loop, resulting in a …

Add option to skip kerning generation in BitmapFont

---

packages/text-html/src/HTMLText.ts
packages/text-html/test/HTMLText.tests.ts

Added console warn for situations when text bounds width or height is larger then defaultMaxWidth or defaultMaxHeight parameter

Add warn for large expanse of text

---

packages/assets/src/loader/parsers/textures/utils/createTexture.ts
packages/assets/test/loadVideo.tests.ts
packages/core/src/textures/BaseTexture.ts
packages/core/test/BaseTexture.tests.ts

Resources of loaded SVGs and videos are not destroyed currently because the resource is created outside of `BaseTexture`. The same is true for the `BufferResource` created in `BaseTexture.fromBuffer`.

Fix: Mark resources of loaded textures as internal so that they are destroyed when unloaded

---

packages/assets/src/cache/Cache.ts
packages/assets/src/loader/parsers/textures/utils/createTexture.ts
packages/assets/test/assets.tests.ts
packages/core/src/textures/BaseTexture.ts

We do not want to remove the asset from the cache when the texture is disposed. A texture could be disposed without being destroyed.
We also need to remove the asset from the asset cache.

Fix: Remove the asset from the asset cache and the loader promise cache when the texture is destroyed

---

packages/spritesheet/src/Spritesheet.ts
packages/spritesheet/src/spritesheetAsset.ts

Add type inference for the Spritesheet atlas data. It makes using Spritesheets much easier for those using plain objects as an atlas.
- `.toString()` in line 330 is explained at the end of [this](https://www.typescriptlang.org/docs/handbook/2/keyof-types.html) section of the TypeScript docs.
- `S` for the type parameter following existing code style https://github.com/pixijs/pixijs/blob/356abaaad852b248f0aa3f6873f5d7d2a56e3a50/packages/core/src/textures/BaseTexture.ts#L49

Add Spritesheet type inference

---

packages/unsafe-eval/src/syncUniforms.ts
packages/unsafe-eval/test/unsafe-eval.tests.ts

Fixes crash with boolean uniforms when using the unsafe-eval package.
Fixes #9303 
Also removed some unreachable code that made it confusing to debug. The GLSL_TO_SINGLE_SETTERS function array had a function for floats that had the same typo as the function for bools, but would never be run since floats are handled further down. The same is the case for several other types, so I see no reason to leave them in.
This file could use some work in general, it should be kept in sync with the mainline shader code in the core package. I see there are some types that have special handling in shader/utils/uniformParsers that are not handled in this one. 
Added a basic test just for floats and bools. The test will crash with an exception as described in #9303 if the fix is not applied and passes …

Fix: crash in unsafe-eval uniformSync and remove unreachable code

---

packages/events/src/EventBoundary.ts
packages/events/src/EventSystem.ts
packages/events/src/FederatedEvent.ts
packages/events/src/FederatedMouseEvent.ts

Fixes #9407 
I've replaced the `TouchEvent` for the `PixiTouch` interface which is what actually gets passed as the `nativeEvent`

Replace TouchEvent with PixiTouch interface

---

packages/core/src/textures/resources/BaseImageResource.ts
packages/core/src/textures/resources/VideoResource.ts

Reverted #8806: The fix doesn't work in Firefox. It spams a bunch of warnings and produces flickering black frames when the `currentTime` is changed. Open the example provided by #8806 (https://codesandbox.io/s/stoic-grass-rkhxl3?file=/src/index.js) in Firefox to observe this issue.
```
WebGL warning: tex(Sub)Image[23]D: Resource has no data (yet?). Uploading zeros.
WebGL warning: drawElementsInstanced: TEXTURE_2D at unit 0 is incomplete: The dimensions of `level_base` are not all positive. 
```
Instead I added a `seeked` event handler that updates the resource. Note though that the example provided by #8806 does not work after this change because the `currentTime` is updated so fast (every frame) that the `readyState` is 1 in `upload` even though in the previous `seeked` event the …

Fix: Update `VideoResource` on `seeked`

---

packages/core/src/textures/resources/AbstractMultiResource.ts
packages/core/src/textures/resources/ImageResource.ts
packages/core/src/textures/resources/SVGResource.ts
packages/core/src/textures/resources/VideoResource.ts

Only `resize` on load does not emit an update if the width and height of the resource have already been set correctly. In this case the texture is not updated and may remain blank.
Example: View in Firefox. Once #9441 is merged, the before will fail in Chrome as expected too.
- Before: https://pixiplayground.com/#/edit/OeZYTU7uvEGa06eBnbFe2 (first frame is not loaded)
- After: https://pixiplayground.com/#/edit/1ct9gCmWuOfIinadRTpgX (first frame is loaded)

Fix: Update resource on load

---

packages/assets/src/Assets.ts
packages/assets/test/detections.tests.ts

While i was looking at #9530 I noticed we are doing something wrong with the detection logic.
When a user sets `texturePreferrences.format` it completely overrides all default formats. What we should be doing instead is adding these user defined formats to the start of the array, and the others can be used as fallbacks
This issue also meant if you defined a preferred format like this: `['png', 'avif']`, something like pixi sound detections would never be added
This does also mean that using `texturePreferrence.format = ['mp3', 'ogg', 'pmg', 'jpg']` is something you can do, so maybe we should deprecate this option and just use `preferredFormat = [...]` instead, since it has nothing to do with textures explicitly
Also while i was here is did add the `skipDetections` option from #9530

Fixes formats not being added correctly

---

package.json
scripts/fixPublish.ts

Fixes #9544 and #9108
This is a more permanent solution so we won't get bit by publishing v6 in the future.

Fix: Publishing latest v6 dist-tag for deprecated v7 packages

---

README.md

The "Flash vs HTML" link most certainly does not point to anything relevant any more.
<details>
<summary>flashvhtml.com is now a parked domain</summary>
The page looks about like this as of now:
</details>

Remove a dead link

---

packages/core/src/view/ViewSystem.ts

Fixes #9429
The default value of `RENDER_OPTIONS.resolution` should be undefined. This way it will fallback to `settings.RESOLUTION` in the ViewSystem constructor.
Broken: https://jsfiddle.net/bigtimebuddy/tmg2u8rL/
Fixed: https://jsfiddle.net/bigtimebuddy/vjLx02tp/

Default Renderer fallback to settings.RESOLUTION

---

packages/core/src/textures/BaseTexture.ts
packages/core/test/TextureSystem.tests.ts

Fixed: `BaseTexture`s remained `valid` after destruction.

Set `valid` to false if the `BaseTexture` is destroyed

---

packages/core/src/textures/resources/VideoResource.ts

By adding the mute option to videoresource, we can trick chrome into autoplaying without user interaction. 
The loop flag is just because it's nice to have (i.e. it is not needed for the autoplay trick)
Default implementation is unchanged. If you don't set the variables, everything works as it did before.
assets needed (taken from a random site on the internet) [mp4](https://robertcooper.me/mclovin.mp4), [webm](https://robertcooper.me/mclovin.webm)
```ts
Assets.add("mp4", "mclovin.mp4", {resourceOptions:{muted:true, loop:true}});
Assets.add("webm", "mclovin.webm", {resourceOptions:{muted:true, loop:true}});
Assets.add("mp4-default", "mclovin copy.mp4"); // copies just to avoid the cache
Assets.add("webm-default", "mclovin copy.webm"); // copies just to avoid the cache …
```

feat(core): VideoResource autoplay in chrome

---

packages/assets/src/loader/parsers/textures/loadVideo.ts
packages/assets/src/loader/parsers/textures/utils/createTexture.ts
packages/core/src/textures/resources/VideoResource.ts

Video loading may never resolve, because the video load can be suspended by the browser (`suspend` event). It seems that the browser is free to just suspend the video loading and seems to do that frequently if other assets are loaded at the same time. Spamming `videoElement.load()` in `onsuspend` seems to eventually make the video load, but only after a significant delay. Using `fetch` and a blob URL fixes this issue. We should probably have something in `VideoResource` to handle `suspend` events, but I'm not entirely sure what the correct approach would be.

Use fetch to load video textures

---

.github/workflows/nodejs.yml

This reduces the time on GitHub Actions by about 25-30s.
In this example you can see that `npm ci` is skipped, but everything else runs as expected:
* https://github.com/pixijs/pixijs/actions/runs/5834931462/job/15825689762
* https://github.com/pixijs/pixijs/actions/runs/5835018814/job/15825776476
It's important to note that cache are only maintained per-branch or per-PR. So a cold run happens with new branches or new PRs.

Chore: Cache node_modules in GitHub Actions

---

packages/display/src/DisplayObject.ts
packages/display/test/DisplayObject.tests.ts

fix #9600.
when calling the `getLocalBounds` method, assign the parent node's `worldAlpha` value to `_tempDisplayObjectParent` so that the `updateTransform` method can correctly calculate the `worldAlpha`.

fix: worldAlpha becomes abnormal

---

packages/color/src/Color.ts

Changes colord type imports to use types file set in its package.json.
Fixes `ColorSource` being `any` in TypeScript 5.1.6 when using `module:"ESNext"` and `moduleResolution:"Bundler"` tsconfig settings.

Fixed colord type imports

---

packages/spritesheet/src/Spritesheet.ts

This PR expands the types on spritesheet data. Most people are likely importing their spritesheet atlases from external JSON files, and thus will never run into an issue. That said, this change is valuable for those who are generating spritesheet atlases programmatically at runtime and are running into Typescript errors.
FWIW, none of these types are used within Pixi, but they **are** used within other applications and libraries. If they're not added, we'll have to generate 2 separate structures to support Pixi and other tools.
The following optional keys have been added based on the spritesheet atlas JSON output generated by [Aseprite](https://www.aseprite.org/):
* `meta.app`: A string representing the app used to generate the spritesheet atlas.
* `meta.format`: The color space used in …

Expand spritesheet types

---

packages/events/src/EventSystem.ts

When support touch events , Only when `pointerType` is touch is filtered. When using a Apple pencil on iPad, `onPointerDown`、`onPointerMove` and `onPointerUp` will be called twice.
So use `['touch', 'pen'].includes((nativeEvent as PointerEvent).pointerType` instead of  ` (nativeEvent as PointerEvent).pointerType === 'touch'` to fix it.

fix: both touch and point events were called when using Apple pencil

---

packages/assets/src/loader/Loader.ts
packages/assets/src/loader/parsers/textures/utils/createTexture.ts
packages/assets/test/assets.tests.ts
packages/core/src/textures/BaseTexture.ts
packages/core/src/textures/Texture.ts

- Added `Texture.destroyed` property
- Added `destroyed` event to `Texture`
- Forced the destruction of the base texture if the texture of the asset is destroyed. Currently, if the texture is destroyed without the `destroyBase` flag, then the destroyed texture remains in the asset cache and the base texture/resource is not destroyed.

Add the `Texture.destroyed` property/event. Log a warning if a `Texture` managed by `Assets` is destroyed but its `BaseTexture` is not

---

packages/text-bitmap/src/formats/TextFormat.ts
packages/text-bitmap/src/formats/XMLFormat.ts
packages/text-bitmap/src/formats/XMLStringFormat.ts
packages/text-bitmap/src/formats/index.ts

When using `PIXI.BitmapFont.install` with XML as a string. It gives this error:
```
cannot use 'in' operator to search for "getElementsByTag..." in "<?xml version=\"1..."
```
This code allows to reproduce the issue:
https://codesandbox.io/s/bitmapfont-from-string-64l8r5
Fixes: https://github.com/pixijs/pixijs/issues/9640
- Improve type declaration and fix the type error.
- I guess a better type declaration is a better fit to cover this issue than a unit test.
- Tests don't seem to work on my computer (but `npm run types` is passing)

Fix an exception when installing a BitmapFont from an XML as a string

---

src/rendering/graphics/shared/GraphicsView.ts
src/rendering/mesh/shared/MeshView.ts
src/rendering/renderers/shared/View.ts
src/rendering/scene/LayerGroup.ts
src/rendering/scene/utils/buildInstructions.ts
src/rendering/scene/utils/validateRenderables.ts
src/rendering/sprite/shared/SpriteView.ts
src/rendering/text/TextView.ts
src/tiling-sprite/TilingSpriteView.ts
tests/scene/DummyView.ts

using `type` always confused me as it didn't really mean anything. So i think changing it to `renderPipeId` makes it a bit clearer

rename type to renderPipeId

---

src/rendering/text/bitmap/utils/resolveCharacters.ts

Fixes #9660 
`resolveCharacters` has a safety check to ensure it never returns an empty set of characters. However, for empty strings, that is the expected result. I've added an escape at the top of the function for this special check.
This will allow empty `Text` display-objects to render without any measurement issues.

Allow resolveCharacters to return empty set for empty strings

---

packages/sprite/src/Sprite.ts

Rounding of vertices is missing in `Sprite.calculateTrimmedVertices`.

Fix: Round `Sprite` vertices in `calculateTrimmedVertices` if `roundPixels`

---

src/scene/graphics/shared/GraphicsContext.ts
src/scene/text/canvas/CanvasTextSystem.ts
src/scene/text/html/HTMLTextSystem.ts
src/scene/text/html/utils/getPo2TextureFromSource.ts

fixes #9701.
Premultiply Alpha was not set on the texture we were writing to. 
[example](https://codesandbox.io/s/pixi-js-sandbox-forked-zkfc8h?file=/index.js)

Text premultiply alpha issue

---

src/accessibility/AccessibilityMixins.d.ts
src/accessibility/accessibilityTarget.ts
src/events/EventsMixins.d.ts
src/events/FederatedEventTarget.ts
src/scene/SceneMixins.d.ts
src/scene/container/Container.ts
src/scene/container/container-mixins/effectsMixin.ts
src/scene/container/container-mixins/findMixin.ts
src/scene/container/container-mixins/measureMixin.ts
src/scene/container/container-mixins/onRenderMixin.ts
src/scene/container/container-mixins/sortMixin.ts
src/scene/container/utils/definedProps.ts
src/scene/graphics/shared/Graphics.ts
src/scene/mesh-extras/NineSlicePlane.ts
src/scene/mesh-extras/NineSliceSprite.ts
src/scene/mesh/shared/Mesh.ts
src/scene/sprite-tiling/TilingSprite.ts
src/scene/sprite/Sprite.ts
src/scene/text/Text.ts
src/scene/text/TextView.ts
tests/scene/Container.tests.ts
tests/tiling-sprite/TilingSprite.test.ts

Adding first pass at constructor options for scene objects
```js
const container = new Container({
children: [
new Sprite({
texture: Texture.WHITE,
tint: 'red',
x: 100,
y: 100,
width: 200,
height: 200,
anchor: { x: 0.5, y: 0.5 },
alpha: 0.8,
})
]
});
```
example: https://codesandbox.io/s/pixi-js-sandbox-forked-dpl4f9?file=/index.js

v8 Constructor Options

---

src/accessibility/AccessibilitySystem.ts
src/app/Application.ts
src/events/EventSystem.ts
src/rendering/renderers/gl/GlRenderTargetSystem.ts
src/rendering/renderers/gl/context/GlContextSystem.ts
src/rendering/renderers/shared/system/AbstractRenderer.ts
src/rendering/renderers/shared/view/ViewSystem.ts

update the app api to be consistent. Now `canvas` is used everywhere instead of the mix between canvas, view, and element

Change element to canvas

---

src/assets/AssetExtension.ts
src/assets/loader/Loader.ts
src/assets/loader/parsers/LoaderParser.ts

load parsers should give themselves a name, otherwise a user can't forcibly select them when loading

Warn if load parser doesn't have a name

---

src/events/EventBoundary.ts

removed the `passive` check in `testHitFn` as it is incorrect
we don't care if it is passive or not if the parent is interactive and we already do this check in the recursive functions
this is also an issue in v7, so will look to back port this

Fix passive interaction

---

packages/assets/src/loader/parsers/loadWebFont.ts
packages/assets/test/assets.tests.ts

In `loadWebFont`, if the URI is already valid, do not call `encodeURI` to avoid it being accidentally encoded twice.
Fixes #9705.

Fix: loadWebFont: Don't encodeURI if already valid

---

src/app/Application.ts
src/rendering/renderers/gl/WebGLRenderer.ts
src/rendering/renderers/gpu/WebGPURenderer.ts
src/rendering/renderers/shared/system/AbstractRenderer.ts
src/rendering/renderers/types.ts
src/settings/adapter/ICanvas.ts

this PR allows you to better set the type of renderer and canvas you are using in your app
```
const app = new Application<Renderer<HTMLCanvasElement>()
app.canvas // HTMLCanvasElement
```
this also works with just initialising a renderer
```
const webgl = new WebGLRenderer<HTMLCanvasElement>()
const webgpu = new WebGPURenderer<HTMLCanvasElement>()
```

type change: update Application to accept Renderer as a type

---

src/assets/cache/Cache.ts
src/extensions/Extensions.ts
src/rendering/init.ts
src/rendering/renderers/shared/texture/Texture.ts
src/rendering/renderers/shared/texture/sources/BufferImageSource.ts
src/rendering/renderers/shared/texture/sources/CanvasSource.ts
src/rendering/renderers/shared/texture/sources/ImageSource.ts
src/rendering/renderers/shared/texture/sources/TextureSource.ts
src/rendering/renderers/shared/texture/sources/VideoSource.ts
src/rendering/renderers/shared/texture/sources/resourceToTexture.ts
tests/renderering/extract/Extract.test.ts
tests/renderering/textures/Textures.test.ts

This PR changes how `Texture.from` works now
- added `autoDetectResource` which returns a `TextureSource`
- added `resourceToTexture` that automatically detect the resource, generates a texture, and caches it
- `Texture.from` now accepts any source, including a buffer and calls `resourceToTexture`
- all `TextureSource`'s are now extensions so they can do some auto detecting
- `BufferImageSource.from` removed as converting the format is now part of the constructor
- `Cache` now allows you to add anything as a key, not just a string

Add resource to texture function

---

packages/core/src/textures/resources/VideoResource.ts

Regression of #9374.
In Chrome (I wasn't able to reproduce it in Firefox) I'm unable to resume a paused video if the `play()` call is preceded by an assignment to `currentTime`. Even this fails to resume the video playback:
```js
source.currentTime = source.currentTime;
source.play();
```
In the `play` event (`_onPlayStart()`) the `readyState` isn't necessarily greater than 2 (the example above gives me 1) and so `_isSourceReady()` is false and consequently `_isSourcePlaying()` too. If that is the case, the `_configureAutoUpdate()` call does not register the ticker / frame callback.
I don't think we need to consider the `readyState` of the video in `_isSourcePlaying()`. We are not uploading frames while `readyState <= 1`.

Fix resuming video playback not working

---

packages/core/src/shader/utils/getMaxFragmentPrecision.ts

According to the [documentation](https://developer.mozilla.org/en-US/docs/Web/API/WebGLShaderPrecisionFormat/precision), WebGLRenderingContext.getShaderPrecisionFormat() can return `null` if an error occurs. This scenario is not handled currently.

Fix: Handle getShaderPrecisionFormat error

---

packages/events/src/EventBoundary.ts

The previous code had a logical error where it was checking isInteractiveTarget twice in the if condition.

Fix: logical condition in code for adding interactive elements

---

packages/assets/src/resolver/Resolver.ts
packages/assets/src/resolver/parsers/resolveTextureUrl.ts
packages/assets/test/resolver.tests.ts
packages/compressed-textures/src/loaders/resolveCompressedTextureUrl.ts

Fixes #9758
Favor using `utils.path.extname(url).slice(1)` to extract the file format instead of `url.split('.').pop()`. It's a more consistent way to ignore the query string and hash parameters.

Fix: Resolve the asset format with query parameters

---

src/compressed-textures/ktx/worker/KTXWorker.ts

KTXWorker `onmessage` listen is global, some tools like vite also send message `type: 'messsage'`.
We should be compatible for it.
messageHandlers[message] will be undefined.

Fix: adapt KTXWorker messageHandlers

---

src/rendering/renderers/gl/GlEncoderSystem.ts
src/rendering/renderers/gl/buffer/GlBufferSystem.ts
src/rendering/renderers/gl/shader/GlProgram.ts
src/rendering/renderers/gl/texture/GlTextureSystem.ts
src/rendering/renderers/gpu/BindGroupSystem.ts
src/rendering/renderers/gpu/GpuColorMaskSystem.ts
src/rendering/renderers/gpu/GpuEncoderSystem.ts
src/rendering/renderers/gpu/GpuStencilSystem.ts
src/rendering/renderers/gpu/buffer/GpuBufferSystem.ts
src/rendering/renderers/gpu/pipeline/PipelineSystem.ts
src/rendering/renderers/gpu/renderTarget/GpuRenderTargetSystem.ts
src/rendering/renderers/gpu/shader/GpuProgram.ts
src/rendering/renderers/gpu/texture/GpuTextureSystem.ts
src/rendering/renderers/shared/buffer/Buffer.ts
src/rendering/renderers/shared/extract/GenerateTextureSystem.ts
src/rendering/renderers/shared/renderTarget/GlobalUniformSystem.ts
src/rendering/renderers/shared/system/AbstractRenderer.ts
src/scene/container/LayerSystem.ts
src/scene/text/bitmap/AbstractBitmapFont.ts
src/scene/text/bitmap/BitmapFont.ts
src/scene/text/bitmap/DynamicBitmapFont.ts
src/scene/text/canvas/CanvasTextMetrics.ts
src/utils/types.ts

When destroying read only types this syntax is a little simpler to use:
`(this.readOnlyProperry as null) = null;`

remove `Writeable` type from the code base

---

src/scene/sprite/SpriteView.ts

This PR removes the dynamic addition and removal of update events for textures for performance optimization. During benchmarks, it was observed that about 70% of the rendering time was spent on managing these listeners, particularly when running the BunnyMark test where textures change every frame.
Performance Improvements
By eliminating this overhead, we've managed to surpass the performance levels of v7.
Caveats
The downside is that any modifications to a texture (e.g., changing the frame) will not be immediately reflected in sprites using that texture. To see the changes, developers will need to either:
Reassign the texture to the sprite, or
Call onUpdate() manually.
Rationale
This trade-off is justified as developers are more likely to swap textures on sprites every frame than to …

remove the texture listener on sprite view

---

src/compressed-textures/basis/worker/BasisWorker.ts
src/compressed-textures/dds/parseDDS.ts
src/compressed-textures/ktx/worker/KTXWorker.ts
src/rendering/renderers/shared/texture/sources/TextureSource.ts

`premultiply-alpha-on-upload` is a better default mode, as it is used by most textures users might create on the.

set default alpha mode to `premultiply-alpha-on-upload`

---

src/rendering/batcher/gpu/BatchGeometry.ts
src/rendering/renderers/shared/buffer/Buffer.ts
src/scene/graphics/shared/GraphicsContextSystem.ts
tests/renderering/Buffer.test.ts

add a function that lets devs update the data whilst allso setting the size. 
Also added new property, `shrinkToFit` which if false will not shrink the GPU buffer if the data becomes smaller.
added tests to ensure it works like a boss

v8 add `setDataWithSize` to `Buffer`

---

src/rendering/renderers/shared/LayerRenderable.ts
src/rendering/renderers/shared/ProxyRenderable.ts
src/rendering/renderers/shared/Renderable.ts
src/scene/container/Container.ts
src/scene/container/LayerGroup.ts
src/scene/container/LayerPipe.ts
src/scene/container/utils/mixColors.ts
src/scene/container/utils/updateLayerGroupTransforms.ts
src/scene/graphics/shared/BatchableGraphics.ts
src/scene/graphics/shared/GraphicsPipe.ts
src/scene/mesh/shared/BatchableMesh.ts
src/scene/mesh/shared/MeshPipe.ts
src/scene/sprite/BatchableSprite.ts
tests/scene/transform-tint.tests.ts

Container color + alpha handled a little better now
previously the alpha and colors were stored in one single ABGR value. This made the code a little more complex, and also lost precision of the alpha during conversion.
eg: 
```
container.alpha = 0.5
// 
console.log(container.alpha) // 0.4943234234
```
this PR addresse that by storing the values seperatly.

split color to bgr + alpha properties

---

src/rendering/renderers/shared/LayerRenderable.ts

this was causing the updated layer renderable to not be able to find its gpu counterpart as it is stored against on the orignal containers uid.

Fix layer renderable uid assignment

---

src/scene/container/Container.ts
src/scene/container/bounds/getGlobalBounds.ts
src/scene/container/bounds/getLocalBounds.ts
tests/scene/getGlobalBounds.tests.ts
tests/scene/getLocalBounds.tests.ts

Adds a `boundsArea` to `Container`
allows devs to optimise measurements by managing thjis rectangle themselves if they wish. 
Setting this stops Pixi from measuring all the children inside the container.

v8 add `boundsArea`

---

src/scene/sprite-tiling/TilingSprite.ts
src/scene/sprite-tiling/shader/TilingSpriteShader.ts

easy one!
Allows for the following constructor style:
```
const tilingSprite = new TilingSprite(texture);
```

allow tiling sprite constructor to accept a texture

---

src/rendering/renderers/gl/texture/GlTextureSystem.ts
src/rendering/renderers/gpu/texture/GpuTextureSystem.ts

should catch any issues where a texture may have been unloaded,
but then access a gpu texture is required before its uploaded again in the render loop

v8 little tweaks for texture unloading

---

packages/display/src/DisplayObject.ts
packages/display/test/Container.tests.ts

We shouldn't set `sortDiry` of the parent container to true if the `zIndex` is not changed by the assignment.

Don't set `sortDirty` to true if the `zIndex` doesn't change

---

packages/spritesheet/src/Spritesheet.ts

Removes the `?` on the `animations` key of the `ISpritesheetData` type. This is because it results in the type `Record<never, ...>` for the `Spritesheet` class member `animations` [here](https://github.com/Nearoo/pixijs/blob/503605c14078bd66f8a7d0a14bfba2b47b05184b/packages/spritesheet/src/Spritesheet.ts#L180), making it impossible to use `animations` without type error in typescript.
The reason for this is that `animation` of `ISpritesheetData` is of type `Record<keyof S['animations'], Texture[]>`, where, due to the `?`, `keyof S['animations']` will evaluate to `undefined & utils.Dict<string[]>`, which is `never`. 
Since `Spritesheet.animations` is always initialized ([here](https://github.com/Nearoo/pixijs/blob/503605c14078bd66f8a7d0a14bfba2b47b05184b/packages/spritesheet/src/Spritesheet …

Fix type error in `ISpritesheetData`

---

src/accessibility/AccessibilitySystem.ts

Resolves [ticket](https://github.com/orgs/pixijs/projects/2/views/4?pane=issue&itemId=46755362).
- JSDoc seems to infer that the `KEY_CODE_TAB` const after the namespace declaration is its default value. Here we can simply ignore it.

Docs: Remove Accessibility Namespace Default Value

---

src/rendering/renderers/shared/texture/Texture.ts

hey @Zyie! Heard `Texture.WHITE` was giving us jip!
After a chat with @bigtimebuddy, we realised it did not need to be created from a canvas and instead could be created from a Buffer.
Hope this helps to solve the Webworker issues!

adjust texture.WHITE creation

---

src/rendering/batcher/gl/GlBatchAdaptor.ts
src/rendering/high-shader/shader-bits/globalUniformsBit.ts
src/rendering/renderers/gl/WebGLRenderer.ts
src/rendering/renderers/gl/shader/GlShaderSystem.ts
src/rendering/renderers/gpu/WebGPURenderer.ts
src/rendering/renderers/shared/renderTarget/GlobalUniformSystem.ts
src/rendering/renderers/shared/system/AbstractRenderer.ts

Part one of my phased approach to get WebGL working
this PR makes UBOs optional - the only places they are being used in webGL2 is in the global uniforms.

v8 webGL - allow ubos to be optional

---

package-lock.json
packages/assets/package.json

This issue is being thrown installing 7.3.2.
`@pixi/utils` should only be imported by core or things core imports. From the reset of the packages `utils` is something thats imported from `core`.
```
warning "pixi.js > @pixi/assets@7.3.2" has unmet peer dependency "@pixi/utils@7.3.2".
```

Chore: Remove peer utils from assets

---

packages/assets/src/Assets.ts

Hello Pixijs team,
Asset from document it should be `Assets` same as export then,
I've change comment for docs `Asset` => `Assets` 
Thank you

Fix: Assets comment change Asset => Assets

---

packages/spritesheet/src/Spritesheet.ts
packages/spritesheet/test/Spritesheet.tests.ts

In type `ISpritesheetData`, the type of `meta.scale` is `string`, which fits the output Json of TexturePacker.
```
"meta": {
"app": "https://www.codeandweb.com/texturepacker",
"version": "1.0",
"image": "building1.png",
"format": "RGBA8888",
"size": {"w":128,"h":126},
"scale": "0.5",
"smartupdate": "$TexturePacker:SmartUpdate:1cb0f14cbdd5e7bcecd332ecd0eaa9f7:8acde9d234ecca966a410602c71bffad:6046b8eb706ddefaa771c33ceb7cb6d5$"
}
```
However, when using pixijs/assetpack to generate spritesheets, the output `scale` type is `number`.
```
"meta": {
"app": "http://github.com/odrick/free-tex-packer-core",
"version": "0.3.4",
"image": "spritesheet.png",
"format": "RGBA8888",
"size": {
"w": 134,
"h": 126
},
"scale": 1
}
```
Pass the Json to `Spritesheet` constructor
```javascript
const sheet = new …
```

Add number type support to `scale` field of `ISpritesheetData` 

---

src/assets/AssetExtension.ts
src/assets/Assets.ts
src/assets/cache/parsers/cacheTextureArray.ts
src/assets/detections/parsers/detectAvif.ts
src/assets/detections/parsers/detectDefaults.ts
src/assets/detections/parsers/detectMp4.ts
src/assets/detections/parsers/detectOgv.ts
src/assets/detections/parsers/detectWebm.ts
src/assets/detections/parsers/detectWebp.ts
src/assets/loader/parsers/LoaderParser.ts
src/assets/loader/parsers/loadJson.ts
src/assets/loader/parsers/loadTxt.ts
src/assets/loader/parsers/loadWebFont.ts
src/assets/loader/parsers/textures/loadSVG.ts
src/assets/loader/parsers/textures/loadTextures.ts
src/assets/loader/parsers/textures/loadVideoTextures.ts
src/assets/resolver/parsers/resolveTextureUrl.ts
src/assets/types.ts
src/spritesheet/spritesheetAsset.ts

Enhance docs for assets.
Moved "Assets" info into "assets.html" as it was confusing on the main "assets" page header and more appropriate there. Linked to it.
Removed a lot of references to "This will be added automatically if `pixi.js/assets` is imported"
- There is no clear general explanation of the docs on how to custom load the library
- Feels like this API documentation should just focus on describing what things are rather than build composition details

enhance assets documentation

---

src/color/Color.ts

Enhance color documentation.
Ignored `Color.shared` as its a temp object which I believe is more for internal use than something users need to worry about. The object could also be mutated between the user setting its values and internal code running.

enhance color documentation

---

src/rendering/batcher/shared/Batcher.ts
src/rendering/renderers/gpu/GpuEncoderSystem.ts
src/rendering/renderers/shared/geometry/Geometry.ts
src/scene/graphics/shared/BatchableGraphics.ts
src/scene/mesh/shared/BatchableMesh.ts
src/scene/sprite/BatchableSprite.ts
tests/renderering/batch/Batcher.test.ts
tests/renderering/batch/checkCanUseTexture.tests.ts
tests/visual/scenes/compressed-textures/dds.scene.ts

Adds support for `Uint16Array` as an indexBuffer type
if a batch is smaller than 10000ish (which is most often the case!) 
we should use `Uint16Array` as they are half the size of `Uint32Arrays`.

v8 add support for uint16

---

src/rendering/renderers/shared/system/AbstractRenderer.ts
src/scene/container/bounds/getFastGlobalBounds.ts
src/scene/container/utils/buildInstructions.ts
tests/scene/getGlobalFastBounds.tests.ts

local transform, filters and masks are now taken into account when an item is rendered. Much like v7

fix for transform to behave like v7

---

.eslintrc.json
package-lock.json
package.json
packages/assets/package.json
packages/basis/src/TranscoderWorkerWrapper.ts
packages/basis/src/loader/BasisParser.ts
packages/canvas-graphics/src/utils/PolygonUtils.ts
packages/canvas-renderer/src/CanvasContextSystem.ts
packages/canvas-renderer/src/CanvasObjectRendererSystem.ts
packages/color/src/Color.ts
packages/compressed-textures/src/const.ts
packages/core/src/geometry/Buffer.ts
packages/core/src/mask/MaskData.ts
packages/core/src/state/StateSystem.ts
packages/core/test/FramebufferSystem.tests.ts
packages/events/src/EventTicker.ts
packages/events/src/FederatedEventMap.ts
packages/events/test/EventSystem.tests.ts
packages/graphics/src/Graphics.ts
packages/graphics/src/index.ts
packages/settings/package.json
packages/settings/src/ICanvas.ts
scripts/prepublish.ts

Fixes #9842
* `@types/css-font-loading-module` was out-of-date
* Fix any eslint issues as a result of upgrading config
* Requires upgrading to TypeScript v5
* Requires upgrading eslint toolchain and dependencies
* Move a bunch of default eslint rules to external config

Fix: Support building with TypeScript 5 with no errors

---

packages/utils/src/path.ts
packages/utils/test/path.tests.ts

fixes: #9393
https://github.com/pixijs/pixijs/pull/8614 introduced a bug that caused any segment that ended in a file extension to be handled differently. This PR now explicitly allows you to define what extensions should be handled differently with the default being `['.html']`
The `.html` default is because the original issue was around how these two urls are the same when `Assets` does its `path.toAbsolute` when setting a `basePath`
`http://example.com/index.html` and `http://example.com/`

Fix: path.join incorrectly joining urls that contain periods

---

src/rendering/renderers/shared/renderTarget/RenderTarget.ts

fix issue with setting 
`TextureSource.defaultOptions.autoGenerateMipmaps = true;`
this breaks the depthTextures used in the RenderTarget

fix depthTexture issue

---

src/maths/point/ObservablePoint.ts
src/scene/container/Container.ts
src/scene/sprite-tiling/TilingSprite.ts
src/scene/sprite/Sprite.ts
src/scene/text-html/HTMLTextPipe.ts
src/scene/text/Text.ts
src/utils/misc/Transform.ts
tests/math-extras/Point.tests.ts
tests/math/ObservablePoint.tests.ts
tests/scene/DummyView.ts
tests/scene/transform-tint.tests.ts

this should prevent clashes for other libs in the future.
onUpdate is a very common function name, and as ours internal - figured we prefix it with an _

v8 rename `onUpdate` to `_onUpdate`

---

src/utils/path.ts
tests/renderering/utils/path.test.ts

Fix: path.join incorrectly joining urls that contain periods (v8)

---

src/filters/Filter.ts
src/rendering/renderers/shared/shader/Shader.ts

adds `Shader.from` and also makes the types for Shader more explicit
e.g
```ts
// error: must have a gl or gpu program
new Shader({
resources: {}
});
// error: must have a gl or gpu program
new Shader({
group: {}
});
// error: cant have resources and groups both defined
new Shader({
resources: undefined,
groups: undefined
glProgram: undefined,
gpuProgram: undefined,
});
```

chore: add shader.from

---

src/events/FederatedEventTarget.ts
tests/events/EventSystem.tests.ts

port of the #10047 and #10046 prs

Feat: Add signal and once option to addEventListener

---

packages/spritesheet/src/Spritesheet.ts
packages/spritesheet/src/spritesheetAsset.ts
packages/spritesheet/test/spritesheetAsset.tests.ts

This PR add new features for [spritesheetLoader](https://github.com/pixijs/pixijs/blob/c04c09c50874fef9296555af23e25fe58cc808a9/packages/spritesheet/src/spritesheetAsset.ts#L92) that helps control loading of spritesheet image (for example if you want to manage progress or resolution/format by yourself).
Features:
1. Use preloaded texture via `{data: {texture: myTexture}}` instead of loading texture using imagePath
2. Use image custom filename via `{data: {imageFilename: 'myFilename.2x.avif'}}` instead of jsonFile.meta.image
PR Checklist:

Add data.texture and data.imageFilename to spritesheetLoader

---

packages/runner/src/Runner.ts
packages/runner/test/Runner.tests.ts

I migrated my TypeScript project from Signals to Runner, and it's amazing! However, I thought that adding some type safety to it wouldn't hurt.
The feature is 100% backward compatible. The previous syntax will continue working.
Here's the new syntax for the instantiation of type-safe Runner:
``` typescript
let runner: Runner<'update', [number]>;
// This won't work because the function name 'update' is expected
runner = new Runner('destroy');
// This is fine
runner = new Runner('update');
// This won't work because the number is expected
runner.emit("10");
// This is fine
runner.emit(10);
// This won't work because provided object does not contain 'update' key
runner.add({
destroy: function() {
// Destroy the game
},
});
// This is fine
runner.add({
update: function(time) {
// Update my …
```

Feature: Make Runner type-safe

---

packages/runner/src/Runner.ts
packages/runner/test/Runner.tests.ts
scripts/filterTypeScriptErrors.ts

Ref https://github.com/pixijs/pixijs/issues/8852
To resolve the strict null check error in `packages/runner/src/Runner.ts`, I modified the `destroy` method to set each property value from null to an empty array or an empty string.
I also considered making each property nullable, but decided not to change the type for the following reasons:
- If I make each property nullable, it would require implementing null check processing in the calling code, leading to broader implications.
- There is currently no handling in the calling code to anticipate cases where the property value might be null.

Add strict null checks to @pixijs/runner

---

packages/extensions/src/index.ts
packages/extensions/test/extensions.tests.ts
scripts/filterTypeScriptErrors.ts

Ref https://github.com/pixijs/pixijs/issues/8852
To resolve the strict null check error in `packages/extensions/src/index.ts`, I have added a null check when using the nullable value `ExtensionFormat['name']`.
```diff
- map[extension.name] = extension.ref;
+ if (extension.name)
+ {
+   map[extension.name] = extension.ref;
+ }
```
Furthermore, empty objects were forcefully converted to the Record types using the 'as' keyword.
This led to type mismatches in certain areas, so I have now used 'Partial' to appropriately set the type for the empty objects.
```diff
- _addHandlers: {} as Record<ExtensionType, ExtensionHandler>,
+ _addHandlers: {} as Partial<Record<ExtensionType, ExtensionHandler>>,
```

Add strict null checks to @pixi/extensions

---

src/scene/sprite/SpritePipe.ts

Codesandbox would alway error out when it tries to reload the page as `gpuSprite` is undefined.

Fix: gpu sprite being undefined

---

src/rendering/renderers/shared/shader/utils/uniformBufferParsers.ts

little tweak so using Color as a filter value works in WebGPU

Fix: allow Color to be used as a filter value in WebGPU

---

packages/events/src/FederatedEventTarget.ts
packages/events/test/EventSystem.tests.ts

The initial implementation for signal support wrapped the provided listener function to add an additional check for the signal's state. This made it impossible to manually remove the listener by calling off() as there was no way to get a reference to the wrapped listener function. Luckily, this additional check was superfluous given the single threaded nature of JavaScript's event loop.

fix: calling FederatedEventTarget.off() with original listener now works when using signal

---

src/scene/text/Text.ts

Fixes a bug in 8.0.0-rc.1 that caused an error when creating a `Text` object using the `anchor` option.
```
TypeError: Cannot set properties of undefined (setting 'x')
219 |     set anchor(value: PointData)
220 |     {
> 221 |         this._anchor.x = value.x;
|                       ^
222 |         this._anchor.y = value.y;
223 |     }
224 |
at Text.set anchor [as anchor] (src/scene/text/Text.ts:221:23)
at assignWithIgnore (src/scene/container/utils/assignWithIgnore.ts:17:24)
at new Container (src/scene/container/Container.ts:564:25)
at new Text (src/scene/text/Text.ts:169:9)
```
- [?] Tests passed (`npm run test`)
- There's a test failing for me in the text test file but I think it's unrelated and fails in the same way both with and without the change

Fix: prevent error when creating text with anchor option

---

package.json
scripts/utils/exports.ts
src/rendering/init.ts

It seems that webpack behaves differently to some of the other bundlers i've been testing on and it requires me to set the `index.ts` file as a side effect in order to include the `browserExt` and `webworkerExt`

Fix: environment extensions being treeshaken

---

src/events/FederatedEventTarget.ts
tests/events/EventSystem.tests.ts

fix: calling FederatedEventTarget.off() with original listener now works when using signal 

---

src/scene/container/utils/buildInstructions.ts

Oops, looks like effects were happening twice - once on the rendr group and on the render group parent - causing weirdness.
Update buildInstructions keep effects on the render group itself, rather than both itself and its parent.

v8 Fix render effects issue

---

src/rendering/renderers/gpu/renderTarget/GpuRenderTargetAdaptor.ts
src/rendering/renderers/shared/texture/sources/CanvasSource.ts
src/rendering/renderers/shared/view/ViewSystem.ts
src/scene/container/utils/buildInstructions.ts
src/scene/text/Text.ts
src/scene/text/TextStyle.ts

- Set default text tint to white
- fix up transparency for WebGPU

Fix: transparency for WebGPU and default tint for BitmapText

---

src/scene/text/Text.ts
src/scene/text/TextStyle.ts
tests/renderering/text/BitmapText.tests.ts
tests/visual/scenes/text/bitmap-text.scene.ts

This PR fixes a couple of issues with TextStyle
- the setters did not have the logic that was in the constructor
- dropShadow is now fully supported as either a bool or an object and will apply defaults if a partial style is provided
- stroke now checks for `_originalStroke` instead of `_originalFill`
- when converting from v7 drop shadow options the default settings are now applied 
This PR also fixes the issue where bitmap texts fill was always being set to white

Fix: issues with TextStyle getter/setters and BitmapText default fill

---

jest.config.js
src/filters/FilterSystem.ts
src/rendering/renderers/gl/texture/GlTextureSystem.ts
tests/visual/tester.ts
tests/visual/visuals.test.ts

- we now just extract a canvas directly and then use that same canvas to save / compare pixels etc.
- renderers are now reused, so one of each is created as required. However if a test requires custom init options, then a new instance of a renderer with the specific options is created (and subsiquently destroyed).
- this new set up Highlighted a couple of bugs that have also been fixed
- this should run through the tests a a lot quicker now.

Tweaks to visual tests

---

src/scene/container/container-mixins/measureMixin.ts
tests/display/Container.Visual.tests.ts

This PR adds the ability to set the width/height of a container in one go which reduces the number of `getLocalBounds` calls that get made
```ts
new Container()
.setSize(100) // 100, 100
.setSize(100, 150) // 100, 150
.setSize({width: 100}) // 100, 100
.setSize({width: 100, height: 150}) // 100, 150
```
There is also a `getSize()` with an optional `out` property to get the width/height of a container without the additional calls as well

Feat: add ability to set width/height of Container together

---

packages/spritesheet/src/Spritesheet.ts
packages/spritesheet/src/spritesheetAsset.ts
packages/spritesheet/test/Spritesheet.tests.ts
packages/spritesheet/test/spritesheetAsset.tests.ts

This was a request that was made via Discord. 
The use-case is that we have a global `TextureCache` and a global `Assets` cache and collisions of textures can easily happen with an app that's a little more complex. Sometimes there's a need to be more specific when loading multiple atlases that might share the same texture name. This change allows users to optionally provide a cachePrefix that prepended to texture IDs whenever adding to TextureCache or Assets' Cache.
* Adds `cachePrefix` option to Spritesheet
* Adds options for Spritesheet constructor
* General cleanup of Spritesheet tests to unload assets better
```ts
import { Assets } from 'pixi.js';
await Assets.load({
src: './atlas.json', // contains "background" texture
data: { cachePrefix: 'atlas.json/' }
});
await Assets.load({
src: …
```

Add: Spritesheet option cachePrefix

---

src/rendering/batcher/gpu/BatchGeometry.ts
src/rendering/renderers/gl/shader/program/extractAttributesFromGlProgram.ts
src/rendering/renderers/gl/shader/program/generateProgram.ts
src/scene/mesh/shared/MeshGeometry.ts

Upgrade to the Geometry meant that shader locations are now being allocated automatically. Actual shader locations differ across browsers.
This PR should now not force the locations in the geometry.

Fix: attribute locations not being set automatically

---

src/rendering/renderers/gpu/shader/GpuProgram.ts
src/scene/mesh/gl/GlMeshAdaptor.ts
src/scene/mesh/gpu/GpuMeshAdapter.ts
tests/visual/scenes/mesh/fully-custom-mesh.scene.ts

- add visual test
the webGL ones will be upside down - this is actually correct as rendering to a texture in WebGL causes it to be inverted.
We handle this automatically with our transform uniforms, but as this example does not use them.. they come out flipped!

Fix: auto assignment of gpu pixi groups

---

src/rendering/mask/stencil/StencilMaskPipe.ts
src/rendering/renderers/shared/extract/GenerateTextureSystem.ts

- fixes little mask issue when sub rendering a container
- added adoc for resolution in `generateTexture`

Fix: masks not working correctly when sub rendering a container

---

src/compressed-textures/basis/worker/basis.worker.ts
src/compressed-textures/ktx/worker/ktx.worker.ts

Fix: remove eval in workers

---

src/scene/container/RenderContainer.ts

allow devs to either provide a render function or override it by extending the class:
```
import { RenderContainer } from 'pixi.js';
// extend the class
class MyRenderContainer extends RenderContainer
{
render(renderer)
{
renderer.clear({
clearColor: 'green', // clear the screen to green when rendering this item
});
}
}
// override the render method
const renderContainer = new RenderContainer(
(renderer) =>  {
renderer.clear({
clearColor: 'green', // clear the screen to green when rendering this item
});
});
```

Fix: allow render function in RenderContainer to be overridable

---

src/rendering/renderers/gpu/buffer/GpuBufferSystem.ts
src/unsafe-eval/init.ts

- Fixed a small issue when updating buffers on WebGPU
- Fixed issue with UnsafeEval overriding incorrect functions 
tests are a bit of a pain here as WebGPU does not currently work in the CLI. Sorry about that!

Fix: WebGPU buffer update logic

---

global.d.ts
package-lock.json
package.json
packages/assets/src/loader/parsers/WorkerManager.ts

Bump **@pixi/webworker-plugins** to [0.3.0](https://github.com/pixijs/webworker-plugins/releases/tag/v0.3.0), this prevent `ReferenceError` when using **@pixi/node**.
Fixes #10170, fixes pixijs/node#15.

Bump @pixi/webworker-plugins to 0.3.0

---

package.json
scripts/utils/exports.ts
src/rendering/init.ts
src/rendering/renderers/shared/texture/Texture.ts
src/rendering/renderers/shared/texture/utils/textureFrom.ts
src/scene/text-html/HTMLTextRenderData.ts
src/scene/text-html/HTMLTextSystem.ts
src/scene/text-html/utils/getFontCss.ts
src/scene/text-html/utils/getSVGUrl.ts
src/scene/text-html/utils/measureHtmlText.ts
tests/renderering/text/getFontCss.tests.ts

fixes circular dependancies in the code

Fix: circular deps

---

src/scene/container/Container.ts
tests/scene/scene.tests.ts

fixes an issue where removeChild() an item that did not belong to that object would null the parent in v8

Fix: removeChild bug

---

src/scene/container/container-mixins/effectsMixin.ts
tests/scene/filter-effect.tests.ts

Follow up to #10238
I think this was an over-sight. Any input to `filters` shouldn't get frozen. For example:
```ts
import { Container, NoiseFilter, AlphaFilter } from 'pixi.js';
const container = new Container();
const myFilters = [new NoiseFilter()];
container.filters = myFilters;
myFilters.push(new AlphaFilter()); // in v8.0.0 this didn't work because `myFilters` was frozen
container.filters.push(new AlphaFilter()); // Still throws an error!
container.filters = myFilters; // Promote re-assignment
```

Fix: Respect the user-input for filters and don't freeze

---

src/scene/text/AbstractText.ts
src/scene/text/Text.ts
tests/renderering/text/Text.tests.ts

fixes a small issue when changing text value multiple times before rendering was not returning correct width / height
with test

Fix: text measurement issue

---

src/scene/text-html/HTMLTextPipe.ts

HTMLText now updates correctly if the scene is static

Fix: html text was not rendering all the time

---

src/rendering/renderers/gl/shader/program/preprocessors/addProgramDefines.ts

Chrome 78 and older do not parse shader source correct when single quote is present inside the comment and produce and error message: shaderSource: string not ASCII

Fix: shader preprocessor to support older chrome versions

---

src/environment/canvas/ICanvasRenderingContext2D.ts

Fixes #9765 
By excluding `letterSpacing` from `CanvasTextDrawingStyles`, this will now cleanly inherit.

Fix: ICanvasRenderingContext2D extending letterSpacing

---

src/rendering/renderers/gl/GlBackBufferSystem.ts

GlBackBufferSystem
Just a typo in the vertex shader that did not prevent the program to work correctly.

Fix: typo in the vertex shader of the bigTriangleProgram

---

src/scene/container/destroyTypes.ts
src/scene/text/AbstractText.ts
tests/renderering/text/Text.tests.ts

Text style is not destroyed by default now - which make more sense (a bit like texture and texture sources)
to destroy the style you can now do:
```
fixes #10328
myText.destroy(true);
// or more granuler
myText.destroy({style:true});
```
fixes #10328

Fix: allow for optional destruction of textStyle

---

src/rendering/renderers/gl/texture/GlTextureSystem.ts
src/rendering/renderers/gl/texture/utils/applyStyleParams.ts
src/rendering/renderers/shared/texture/TextureStyle.ts

GlTextureSystem optimisation:
When first creating a texture and applying its samples - we can skip setting the params that are the same as the defaults. 
this speeds up texture creation. from the cpu side by reducing the need to change the default.
I also set the default to texture style to `repeat`. Which makes more sense now that its supported by WebGL2 and WebGPU for all textures (we also have a catch for this edge case in WebGL 1 already, so its safe!)
It will alls mean textures will just tile by default when being used in shaders - which is more in line with standard expectations. 
This change won't affect anything like sprites etc

Fix: performance for setting textures in WebGL

---

src/rendering/renderers/shared/texture/TextureMatrix.ts
src/scene/mesh/shared/BatchableMesh.ts
src/scene/sprite-nine-slice/NineSliceGeometry.ts
src/scene/sprite-nine-slice/NineSliceSprite.ts

We had previously adjusted the mesh to take into account sprite sheets.
Nine Slice Sprite was also doing this work - so uvs were being multiplied twice.
easy fix at least!

Fix: NineSliceSprite not rendering correctly when used with a spritesheet texture

---

src/rendering/renderers/shared/texture/TextureMatrix.ts
src/scene/mesh/shared/BatchableMesh.ts
src/scene/sprite-nine-slice/NineSliceGeometry.ts
src/scene/sprite-nine-slice/NineSliceSprite.ts

follow up to #10357
we currently are not applying the default settings to a nineslicesprite and missing the `textureBoarder` implementation from v7

Fix: apply nineslice defaults correctly

---

src/scene/mesh/shared/MeshPipe.ts
tests/renderering/mesh/Mesh.test.ts

When destroying Mesh that can't be batched, `MeshPipe` fails to return `gpuMesh` to pool since it's undefined. Checking that `_gpuBatchableMeshHash` contains a mesh with given uid before trying to return it to pool fixes the issue.

Fix: Mesh.destroy throws error when not using batch mode

---

src/rendering/renderers/gl/GlStencilSystem.ts

when a context loss happens all WebGL state is reset.
I was not reseting our stencil cache on context loss, so it was not updating accordingly.
it does now!

Fix: stencil mask not resetting correctly on context loss

---

src/filters/defaults/noise/noise.frag

NoiseFilter seed and scale uniforms are being ignored in the fragment shader code, it uses constants instead. This change is based on the fragment shader code in pixi v7.

Fix: NoiseFilter ignoring uniforms

---

src/rendering/renderers/shared/texture/TextureStyle.ts

this is a better default, as it handles lack of precision in a better way

Fix: default address mode

---

src/maths/shapes/Polygon.ts
tests/math/Polygon.tests.ts

- `strokeContains` method of `Polygon` checks `this.closePath` boolean value to skip last line segment or not skip
- Issue #10303 is related.

Fix: `Polygon.__proto__.strokeContains` skips checking last line segment when `this.closePath` false

---

src/rendering/renderers/autoDetectRenderer.ts

After seeing the feedback from the commmunity (and seeing some of this first hand) I think it would be best in the short term to make the WebGL renderer the default.
There are two main reasons:
- WebGL is generally more performant at the fundamental level for most of PixiJS's use cases right now. (this makes sense as Browser have had a lot more time to be optimise WebGL than they have WebGPU). An example of this is uploading a texture, WebGL is just that little bit quicker!
- WebGL is more stable. Whilst the chrome implementation seems ok, browsers like FF are a lot more unstable. With quirks and issues at the WebGPU layer.
Not worried about both of these being resolved in time, but for now I think most users would prefer stable over bleeding edge (especially if there is no current perf …

Fix: Change WebGL to default renderer

---

src/utils/misc/Transform.ts
tests/math/Transform.tests.ts

Fixes issue where rotation was not updating the uvs correctly without calling `_onTilingSpriteUpdate`
fixed with test!
example: https://www.pixiplayground.com/#/edit/-FkV3enddtHBC00QIzYrv

Fix: tiling sprite transform not updating correctly

---

src/environment-browser/BrowserAdapter.ts
src/environment-webworker/WebWorkerAdapter.ts
src/environment/adapter.ts
src/rendering/renderers/gl/context/GlContextSystem.ts
src/rendering/renderers/gl/texture/utils/mapFormatToGlInternalFormat.ts
src/utils/browser/isWebGLSupported.ts

fixes an issue where we were looking for a WebGL2Context even if it does not exist.
This PR removes the `getWebGL2RenderingContext`. It then renames `getWebGLRenderingContext` -> `getWebGL1RenderingContext` 
With that instead of checking if somthign is WebGL2, we can check if is not WebGL1.

Fix: webgl-1 support

---

src/rendering/renderers/shared/texture/sources/VideoSource.ts

Fix: requestVideoFrameCallback being called on wrong object

---

src/scene/sprite/Sprite.ts
tests/renderering/sprite/Sprite.test.ts

Sprite will now use the defaultAnchor property on a Texture if it is present.
Test added!
fixes #10398

Fix: apply defaultAnchor for sprite if present

---

src/scene/container/Container.ts
tests/scene/getLocalBounds.tests.ts

When removing a child - the local bounds cache we not always being invalidated. This has now been addressed so that when removing / adding a child we explicitly invalidate the cache of the local bounds. 
fixes #10451

Fix: issue with local bounds cache not being invalidated when a child is removed

---

src/scene/text-bitmap/BitmapFont.ts
tests/renderering/text/BitmapFont.tests.ts

Adds support for sub-textures when creating bitmap font objects via `new BitmapFont()`.
Resolves https://github.com/pixijs/pixijs/issues/10482.

Fix: sub-textures on `BitmapFont` regression

---

src/scene/text/canvas/CanvasTextSystem.ts

Fixes #10493 . When clearing the texture for reuse, I was not inclding the padding as part of the area that needed clearing. Easy fix at least!

Fix: padding issue on text

---

src/maths/point/pointInTriangle.ts
src/scene/mesh/shared/Mesh.ts

I was not taking into account a mesh may not have an index buffer when running contains point. This has now been addressed. I also optimised the checks by using a pointInTriangle functions, which is faster than copying to a temp poly and testing that.
fixes #10485

Fix: containsPoint on Mesh if no index buffer is set

---

src/rendering/renderers/gl/renderTarget/GlRenderTargetAdaptor.ts

The render target system's copyToTexture assumes that if the source render surface is a canvas, then it must be the main framebuffer. But this is false if someone is trying to copy from a secondary or offscreen canvas.
This change uses a direct comparison with the main canvas to check whether to use the default framebuffer instead.
For a bug repro, see this JSFiddle
https://jsfiddle.net/ShukantPal/vwrh51qs/27/
I've verified locally that this fix causes the gradient to paint correctly. @bigtimebuddy Do we still deploy a public build URL for GitHub branches? (so that I can create a fiddle that works correctly using this branch's build)

Fix: bind to default framebuffer only when copying from main canvas

---

src/rendering/renderers/autoDetectRenderer.ts

Fix: Throw error when no Renderer is available

---

src/advanced-blend-modes/OverlayBlend.ts

fix the overlay blend mode
The overlay mode uses base as the judgment condition. After modification, the display is consistent with Photoshop.

Fix: overlay blend mode to be consistent with photoshop

---

src/scene/container/RenderGroup.ts
tests/renderering/scene/RenderGroupSystem.test.ts

When converting an item to a render group - its onRender function was being called in both its own render group (correct!) 
and its parent render group (incorrect!). This resulted in onRender being called twice for render groups in some scenarios.
This PR address the issue.
Fixes #10432

Fix: onRender being called twice when converted to a renderGroup

---

src/events/EventBoundary.ts
src/rendering/mask/MaskEffectManager.ts
src/scene/container/Container.ts
src/scene/container/container-mixins/effectsMixin.ts

After simplifying filters, figured why not do the same for Masks! This just removes the interim object and just sets the effect directly on the property.

fix: simplify masking

---

src/scene/text-bitmap/BitmapFontManager.ts
tests/renderering/text/BitmapFontManager.test.ts

`BitmapFontManager.getLayout` fails when called with text containing unicode characters due to `String.split('')` splitting multichar unicode characters, e.g. `'👍'.split('') === ['\uD83D', '\uDC4D']`. The spread operator on the other hand respects unicode.

fix: unicode support for BitmapFontManager

---

src/spritesheet/Spritesheet.ts

Fix missing commas in the documentation of Spritesheet.ts

---

src/scene/text/Text.ts
tests/renderering/text/Text.tests.ts

When getting the bounds of text or using width / height. the padding was not being taken into account on the bottom and right sides. Easy fix, with test! 
fixes #10500

Fix: Text bounds calculation with padding

---

src/rendering/renderers/shared/renderTarget/RenderTargetSystem.ts
tests/renderering/RenderTargetSystem.test.ts

Right now, `getRenderTarget(canvas)` returns null because of how the canvas is converted into a `TextureSource`.
In the code, `getCanvasTexture` returns a texture, but the 2 if conditions in `getRenderTarget` only handle render targets and texture sources.
This change updates it so that a canvas is converted into a canvas source, not a texture.

Fix: handling of getRenderTarget when passing in a canvas

---

src/events/EventBoundary.ts
src/filters/FilterEffect.ts
src/rendering/mask/MaskEffectManager.ts
src/rendering/mask/alpha/AlphaMaskPipe.ts
src/rendering/renderers/shared/blendModes/BlendModePipe.ts
src/scene/container/Container.ts
src/scene/container/container-mixins/effectsMixin.ts

This PR simplifies the filter mixin a little bit. In the process it also fixes #10524.

Fix: Filter hitArea not updating

---

src/scene/container/container-mixins/effectsMixin.ts
tests/scene/mask.test.ts

Fixes a little regression bug when doing the following:
```
thing.mask = mask;
thing.mask = null;
thing.mask = mask; // would throw as mask effect refference was not removed.
```

fix mask issue when setting to null and back

---

.github/workflows/pull-name.yml

I've been consistently renaming pr's to follow the `chore/fix/feat/breaking` convention to make generating the release notes easier
This PR just adds a workflow to block a merge if the title isn't correct

chore: add pr name checker

---

src/events/EventBoundary.ts
src/events/EventBoundaryTypes.ts
src/events/EventsMixins.d.ts
src/events/FederatedEvent.ts
src/events/FederatedEventTarget.ts
src/events/deprecatedTypes.ts
src/scene/container/Container.ts

Ok so this PR was a fun rabbit hole 😄 
The main overview of what this PR is actually changing is that i have removed the abstraction of `IFederatedEventTarget` in favour of just using `Container`. `IFederatedContainer` is still mixed into the `Container`, which means that all types should work as before. 
I believe this change reflects a more accurate description of what object is stored in an `FederatedEvent`.
The benefits of this is that we don't need to do any typescript magic that decouples the two different implementations of `EventEmitter` e.g
This
```ts
export interface Container<C extends ContainerChild>
extends Omit<PixiMixins.Container<C>, keyof EventEmitter<ContainerEvents<C> & AnyEvent>>,
EventEmitter<ContainerEvents<C> & AnyEvent> { }
```
Becomes this
```ts
export interface …
```

fix: event mixin types

---

src/scene/graphics/shared/GraphicsContext.ts
tests/renderering/graphics/Graphics.test.ts

Fixes an issue where clearing the graphics object mid draw was not removing previous instructions.
All good now!
fixes #10550

fix: graphics clear not clearing mid path.

---

src/events/EventBoundary.ts

Interaction wasn't checking if the container is measurable or in the build which meant that some masks where being included in the interaction checks

fix: masks interfering with interaction

---

src/rendering/renderers/shared/shader/UniformGroup.ts
src/rendering/renderers/shared/shader/types.ts

Added a check to `UniformGroup` that ensures only valid uniform types are used:
`Error: Uniform type doopboopMatrix100x100 is not supported. Supported uniform types are: f32, i32, vec2<f32>, vec3<f32>, vec4<f32>, mat2x2<f32>, mat3x3<f32>, mat4x4<f32>, mat3x2<f32>, mat4x2<f32>, mat2x3<f32>, mat4x3<f32>, mat2x4<f32>, mat3x4<f32>`

chore: add better error checking for unsupported shader uniform types

---

src/rendering/renderers/gl/texture/uploaders/glUploadImageResource.ts
src/scene/graphics/shared/GraphicsContext.ts
src/scene/graphics/shared/GraphicsContextSystem.ts
src/scene/graphics/shared/GraphicsPipe.ts
tests/renderering/graphics/Graphics.test.ts

Fixes a graphics leak, where we were re-adding the graphcis object onDestroy event on each rebuild - rather than just the once on init. This PR fixes it.
There was also a second update list that was not being cleared (or used!) so i removed it.
fixes #10549

fix: event leak in graphics pipe

---

src/scene/container/Container.ts
src/scene/container/RenderGroup.ts
tests/renderering/scene/Container.test.ts

Added a destroy function to renderGroup and also made sure it is called when the container that owns it is destroyed.
fixes #10533

fix: destroy renderGroups

---

src/rendering/renderers/autoDetectRenderer.ts
src/rendering/renderers/shared/system/AbstractRenderer.ts
src/rendering/renderers/shared/system/SharedSystems.ts

Fixes: #10366 and #10554
We now move the loading the environment into `AbstractRenderer`, which populates all of the render pipes, into the `init` call. Tis allows the renderer to be created correctly without using `autoDetectRenderer`
I also tidied up a few interfaces so now the types extend the correct things

fix: allow renderers to be created without autoDetectRenderer

---

src/assets/resolver/parsers/resolveJsonUrl.ts
tests/assets/Resolver.tests.ts

the `resolveJsonUrl` is a more general version of the spritesheet resolver so should have a lower priority

fix: spritesheet resolver not working

---

src/assets/Assets.ts
src/scene/text-bitmap/init.ts

fixes: #10397
moving the asset parsers into Assets allows us to load bitmap fonts before calling `await renderer.init()`
this only adds a few kb to the bundle size, so not a major impact in doing this

fix: allow bitmap fonts to be loaded before renderer init

---

src/scene/text/TextStyle.ts
tests/renderering/text/TextStyle.tests.ts

fixes issues with `strokeThickness` and `fillGradientStops` not being converted correctly for deprecation

fix: Text deprecation not converting correctly

---

src/compressed-textures/dds/const.ts
src/filters/defaults/blur/const.ts
src/rendering/renderers/shared/renderTarget/GlobalUniformSystem.ts
src/rendering/renderers/shared/shader/utils/uniformParsers.ts
src/rendering/renderers/shared/system/AbstractRenderer.ts

I've exported several types which are dependencies of other types. Not exporting these types causes issues when using Pixi's types for dynamic type generation elsewhere, as the library exports other types that depend on them. This is necessary for the new version of `@pixi/react`, where we're dynamically generating types from Pixi's core types.
1. Clone the [test repo](https://github.com/trezy-studios/pixi-type-export-rtc)
2. Install dependencies (`npm i`)
3. Run the build command (`npm run build`)
4. Observe the errors:
<details><summary>Error</summary>
```shell
> pixi-type-export-rtc@0.0.0-development build
> tsc
index.js:4:4 - error TS4084: Exported type alias 'Foo' has or is using private name 'D3D10_RESOURCE_DIMENSION' from module …
```

fix: export type dependencies

---

src/scene/graphics/shared/FillTypes.ts
src/scene/graphics/shared/Graphics.ts
src/scene/graphics/shared/GraphicsContext.ts
src/scene/graphics/shared/buildCommands/buildLine.ts
src/scene/graphics/shared/svg/SVGParser.ts
src/scene/graphics/shared/utils/buildContextBatches.ts
src/scene/graphics/shared/utils/convertFillInputToFillStyle.ts
src/scene/text-html/HtmlTextStyle.ts
src/scene/text-html/utils/textStyleToCSS.ts
src/scene/text/TextStyle.ts
src/scene/text/canvas/utils/getCanvasFillStyle.ts
src/scene/text/utils/generateTextStyleKey.ts
tests/graphics/GraphicsFill.tests.ts
tests/renderering/graphics/Graphics.test.ts

- fixes the issue where setting a `FillPattern` or a `FillGraident` directly did not work e.g
```ts
const gradient = new FillGradient(0, 0, 200, 0);
new TextStyle({
stroke: gradient,
})
```
- split the types up to clearly separate fill and stroke styles
- moved the types for strokes/fills into a separate file as `GraphicsContext` is already pretty large
- deprecated `FillStyleInputs` in favor of splitting into `FillInput` and `StrokeInput` for better types. Also `FillStyleInputs` contained stroke styles, which meant you got the wrong typings when using `.fill()`

fix: fills/strokes not being set correctly

---

src/scene/sprite-tiling/TilingSpritePipe.ts

Fixes #10603 . When validating a tiling sprite - it was assuming the batchable element exists. Which would not be the case if it had not been rendered yet

fix: tiling sprite crash

---

src/rendering/renderers/shared/extract/GenerateTextureSystem.ts

Fixes #10610 . Mipmaps were not being generated on creation when using generateTexture. This tweak fixes that!

fix: issue with empty mipmaps

---

src/scene/graphics/shared/Graphics.ts

fixes an issue where `graphics.fill('red')` would be marked as deprecated

fix: graphics.fill type

---

src/events/EventTicker.ts

fixes: https://github.com/pixijs/pixijs/issues/10441
fixes: https://github.com/pixijs/pixijs/issues/10131
before: https://www.pixiplayground.com/#/edit/exDzbrsXsLvgdbWm0iZFG
after: https://www.pixiplayground.com/#/edit/cbfMQ_YRzBPNtwevahYkW
I can't find a good way of adding a test for this fix as the way we emulate pointer events in our tests is not the exact same as how a browser does it, due to `pointerId` being different, but the demo above does show the over event only firing once

fix: events firing twice when using dynamic mode

---

src/rendering/renderers/gl/renderTarget/GlRenderTargetAdaptor.ts

Closes #10652 
Makes sure the `depthStencilRenderBuffer` gets resized when `renderTarget.depth` is enabled but not `renderTarget.stencil`.

fix: Ensure `depthStencilRenderBuffer` gets resized when render target has depth enabled

---

.github/workflows/pull-unit.yml
.github/workflows/pull-visuals.yml
.github/workflows/push.yml
.github/workflows/release.yml

Updates the pull/push workflows to using concurrency and updates the release workflow to use the latest action version to avoid node 16 warnings

chore: update workflows

---

src/rendering/renderers/gpu/buffer/GpuBufferSystem.ts

A buffer was being re-added to the managed buffers when it was growing. This PR fixes it so that it only ends up in there once. 
fixes #10619

fix: GpuBufferSystem Managed Buffers

---

src/scene/sprite/Sprite.ts
src/scene/text/AbstractText.ts

Fixes passing 0 `width`/`height` not change the width/height to 0.
```js
new PIXI.Sprite({ width: 0 }).width // should be 0
new PIXI.Text({ height: 0 }).height // should be 0
```

fix: passing 0 width/height to AbstractText/Sprite constructor

---

src/maths/shapes/Ellipse.ts

Missing `out` parameter in `Ellipse#getBounds`.

fix: Ellipse#getBounds ignoring out parameter

---

src/rendering/high-shader/shader-bits/generateTextureBatchBit.ts

The `maxTextures` isn't passed through to the helper methods.

fix: maxTextures argument of generateTextureBatchBit

---

src/rendering/renderers/shared/instructions/RenderPipe.ts

It doesn't look like `instructionSet` is ever passed to `updateRenderable`.

chore: remove instructionSet parameter from updateRenderable

---

src/rendering/renderers/shared/instructions/RenderPipe.ts

It doesn't look like `validateRenderable ` can actually be optional:
https://github.com/pixijs/pixijs/blob/ece3e0068a9c969deb24456559f033f0f4b466ee/src/scene/container/utils/validateRenderables.ts#L18

chore: make validateRenderable nonoptional

---

src/rendering/batcher/shared/Batcher.ts

I noticed that we missing adding `||=` in two places in #10711. And also we need to clear `bindGroup` if it comes from the pool, I think.

fix: Batch Pooling follow-up

---

src/culling/Culler.ts
src/scene/container/Container.ts
tests/scene/culler.test.ts
tests/scene/transform-visibility.tests.ts

- Fixed: Assigning `culled` to false made `culled` true and vice versa.
- Fixed: If a previously `cullable` object was made non-`cullable`, the `culled` state would not be reset by `Culler`.
- Removed `culled` as one of the `ContainerOptions`, because `culled` is not part of the public API (it is tagged `@ignore`).

fix: culling issues

---

src/scene/graphics/shared/fill/FillGradient.ts
tests/renderering/text/TextStyle.tests.ts

FillGradient doesn't support alpha:
* https://jsfiddle.net/bigtimebuddy/yo6e04u3/ (v8.2.2)
* https://jsfiddle.net/bigtimebuddy/3zvjr5qt/ (patched)

fix: Support alpha colors on FillGradient

---

src/scene/graphics/shared/path/ShapePath.ts

I found this while working on https://github.com/ShukantPal/pixi-essentials/pull/107
This fixes an issue where `_ensurePoly` called after closing a polygon without a transform matrix set. This can happen if `lineTo` is called after `fill`.
For a reproduction, please see:
https://jsfiddle.net/ShukantPal/25g6jrth/

fix: Check if transform is set on lastShape before dereferencing

---

src/rendering/batcher/shared/Batcher.ts
src/rendering/renderers/shared/buffer/Buffer.ts
src/rendering/renderers/shared/buffer/BufferResource.ts
src/rendering/renderers/shared/instructions/InstructionSet.ts
src/rendering/renderers/shared/renderTarget/RenderTarget.ts
src/rendering/renderers/shared/shader/UniformGroup.ts
src/rendering/renderers/shared/texture/Texture.ts
src/rendering/renderers/shared/texture/sources/TextureSource.ts
src/rendering/renderers/shared/view/View.ts
src/scene/container/Container.ts
src/scene/graphics/shared/GraphicsContext.ts
src/scene/graphics/shared/fill/FillGradient.ts
src/scene/graphics/shared/fill/FillPattern.ts
src/scene/graphics/shared/path/GraphicsPath.ts

If custom pipes are expected to be implemented the same way as PIXI pipes, we need `uid` to be part of the public API.
I made all `uid`s public and readonly.

chore: make uid members public

---

src/scene/mesh/shared/Mesh.ts

Not sure if the `| null` is really required, but I think we want `shader` to be `null` if not assigned in the constructor instead of `undefined`. At least we probably shouldn't allow both `undefined` and `null` to represent "no shader", I think.

chore: make Mesh#shader nullable

---

src/rendering/renderers/shared/instructions/RenderPipe.ts

Returning `true` triggers the rebuild:
https://github.com/pixijs/pixijs/blob/f2de870a1bd976adf324b9baf7f60ecfd8f58da8/src/scene/container/utils/validateRenderables.ts#L18

fix: validateRenderable documentation

---

src/app/Application.ts
src/app/TickerPlugin.ts
src/prepare/PrepareBase.ts
src/rendering/renderers/shared/texture/Texture.ts
src/rendering/renderers/types.ts

PR is dedicated to fixing issues mentioned in [issues/10663](https://github.com/pixijs/pixijs/issues/10663) and a few other small mistakes in docs that I've noticed along the way
1 commit
[https://github.com/pixijs/pixijs/commit/104c18bce4a1c44c59e4dc7337a95205d97b0511](https://github.com/pixijs/pixijs/commit/104c18bce4a1c44c59e4dc7337a95205d97b0511)
fixes [rendering.PrepareBase.html#constructor](https://pixijs.download/release/docs/rendering.PrepareBase.html#constructor) - renderer param in constructor is in text instead of in table
2 commit
[https://github.com/pixijs/pixijs/commit/0972c0b8b1a046f493f6a900c776f4103c11a592](https://github.com/pixijs/pixijs/commit/0972c0b8b1a046f493f6a900c776f4103c11a592)
fixes [rendering.Texture.html#constructor](https://pixijs.download/release/docs/render …

fix: inconsistencies in docs (10663)

---

src/scene/mesh/shared/Mesh.ts
src/scene/mesh/shared/MeshPipe.ts

I understand correctly, we should be able to the use `Mesh` itself as the instruction.

chore: optimize Mesh instructions

---

src/filters/defaults/blur/BlurFilter.ts

Follow-up to #10807
* Fixes the `horizontal` property flipped on BlurFilterPass in BlurFilter
https://jsfiddle.net/bigtimebuddy/8amzg2f9/
https://jsfiddle.net/bigtimebuddy/gk4rxca0/

fix: Blur Dimensions Flipped

---

src/rendering/renderers/shared/texture/RenderableGCSystem.ts
src/rendering/renderers/shared/texture/TextureGCSystem.ts
tests/renderering/RenderablesGC.test.ts

this pr fixes a couple of typos 
- deprecates `textureGCAMaxIdle` for `textureGCMaxIdle`
- renames `renderablesGCMaxUnusedTime` to `renderableGCMaxUnusedTime`
- renames `renderablesGCActive` to `renderableGCActive`
only the texture var needs to be deprecated as the other two have only been merged into dev

fix: naming for gc system properties

---

src/scene/mesh/shared/Mesh.ts

We can't batch the mesh if the state is not compatible (i.e. depth testing or culling is enabled) with the state of the batch adaptor.
Test: https://pixiplayground.com/#/edit/I-ClpYRQc0VGfi6NiEY5Z
Or perhaps we should make `Mesh#state` private/internal? Not sure if we even want to allow all possible states with Mesh?

fix: don't batch Mesh with incompatible state

---

src/scene/container/utils/buildInstructions.ts

we changed the structure of these functions without deprecating them resulting in the spine repo no longer working

fix: deprecation for buildInstruction and collectAllRenderables

---

src/rendering/renderers/shared/renderTarget/RenderTargetSystem.ts

Fix issue where TextureSource is not removed from internal map when destroyed
Resolves https://github.com/pixijs/pixijs/issues/10578

fix: Remove TextureSource from internal map when destroyed

---

src/scene/view/View.ts

In #10812 we moved the `bounds` object into a shared class but we didn't set the default bounds, which means it defaulted to `infinity`. This has resulted in filters not being applied correctly as the result of `getFastGlobalBounds` is now incorrect
I have not been able to boil this down into a visual test as the error comes from one of our games and it seems to be some combination of nested things that is causing the issue but here is the before/after 
before: 
after: 
and here is the bounds values before the above PR:
https://github.com/pixijs/pixijs/blob/24d857ef7cfed25d49c83806b7186a1f04aa2c06/src/scene/sprite-nine-slice/NineSliceSprite.ts#L99
https://github.com/pixijs/pixijs/blob/24d857ef7cfed25d49c83806b7186a1f04aa2c06/src/scene/sprite/Sprite.ts#L83

fix: filters not being applied correctly

---

src/scene/sprite-nine-slice/NineSliceSprite.ts
src/scene/view/View.ts
tests/renderering/sprite/Sprite.test.ts

fix: NineSliceSprite destroy crashing app

---

src/scene/container/Container.ts
src/scene/sprite-nine-slice/NineSliceSprite.ts
src/scene/sprite-tiling/TilingSprite.ts
src/scene/sprite/Sprite.ts
src/scene/text/AbstractText.ts

previously we didn't override get/set size for `TilingSprite` or `NineSliceSprite` when we should have been
I also just tidied up the implementation of get/setSize in `Container`/`Sprite`/`Text`

fix: setSize not overridden for all objects

---

src/filters/FilterSystem.ts

Much smoother now! the issue was that the padding was not rounded - which meant that for resolutions that where not whole numbers, a small precision was introduced that scaled with each render pass of a filter. Adjusted the order so that padding is added at the end and rounded.
fixes #10809

fix: Filter jittering using fractional resolutions

---

src/rendering/renderers/gpu/renderTarget/GpuRenderTargetAdaptor.ts

After trying out the WebGPU debugger, it showed that we createView each time a render target is bound. Tweaked it to use the  `getTextureView` instead. This way we don't create a new view each time!

fix: avoid creating new view in WebGPU

---

src/filters/defaults/blur/BlurFilterPass.ts

This PR clears the texture fully the first time we render using a blur filter. This will stop the previous usage from bleeding into the new one
Fixes #10808

fix: Bleed on blur filter 

---

src/rendering/renderers/gpu/renderTarget/GpuRenderTargetAdaptor.ts

Reverts pixijs/pixijs#10875
Unsure why CI didn't catch this but the above PR breaks the `mipmap-render-texture` test for webgpu

chore: Revert "fix: avoid creating new view in WebGPU"

---

src/rendering/batcher/shared/Batcher.ts
src/rendering/batcher/shared/DefaultBatcher.ts
src/rendering/batcher/shared/DefaultShader.ts
src/scene/graphics/shared/BatchableGraphics.ts
src/scene/graphics/shared/GraphicsPipe.ts
src/scene/mesh/shared/BatchableMesh.ts
src/scene/mesh/shared/MeshPipe.ts
src/scene/sprite-nine-slice/NineSliceSpritePipe.ts
src/scene/sprite-tiling/TilingSpritePipe.ts
src/scene/sprite/BatchableSprite.ts
src/scene/sprite/SpritePipe.ts
src/scene/text-html/HTMLTextPipe.ts
src/scene/text/canvas/CanvasTextPipe.ts
tests/renderering/batch/checkCanUseTexture.tests.ts

extracted default shader
- Whilst im here in batcher land, figured it would be good to do a pass on some of the batcher property names. anything with a `_` prefix is a prop managed by the batcher, whilst anything else should be user defined.
- I also put some stronger types in for the `BatchableQuadElement` and `BatchableMeshElement`. 
- extracted `DefaultShader` from `DefaultBatcher`, making things a bit more readable!
- created `DefaultBatchableQuadElement` and `DefaultBatchableMeshElement` so they contain the props that onnly they care about. Making`DefaultBatchableElement` and `DefaultBatchableElement` more generic.

chore: fix up batch property names

---

src/rendering/renderers/shared/texture/Texture.ts

refactor: Rename 'Asset' to 'Assets' and add missing 'await' in asynchronous functions

chore: Update docs typo in Texture Assets example

---

src/color/Color.ts
tests/color/Color.test.ts

On `Color.ts` value setter normalize this._value once cloned so the original value is not modified.
Closes #10882

fix: Color value setter normalizes cloned value

---

src/rendering/renderers/gl/context/GlContextSystem.ts
src/rendering/renderers/gl/renderTarget/GlRenderTargetAdaptor.ts
src/rendering/renderers/shared/renderTarget/RenderTargetSystem.ts
src/rendering/renderers/shared/system/AbstractRenderer.ts
src/rendering/renderers/shared/texture/sources/CanvasSource.ts
src/rendering/renderers/shared/view/ViewSystem.ts

WebGPU has a pretty awesome feature, basically you can use a single render to draw to many canvases on the dom. It has one context and then treats each canvas as a texture to be rendered too. This is super nice and brings a few usful things:
- shared resources across canvas (different gl contexts are sand boxed)
- no limit to how many canvases can be rendered to (there is a limit to how many gl contexts can exist on the dom)
This PR fixes thees WebGL limitations by introducing a new property called `multiView`. If this is true, the WebGL renderer will behave exactly as the WebGPU renderer does and render to the canvas' with no fuss!  
```
const renderer = await autoDetectRenderer({
multiView:true 
})
// render to a canvas on the dom
renderer.render({
container,
target: canvasOnDom1
})
// …
```

feat: add multiview to webgl rendering

---

src/scene/text-bitmap/BitmapFontManager.ts
src/scene/text-bitmap/BitmapTextPipe.ts
src/scene/text-bitmap/utils/getBitmapTextLayout.ts
tests/renderering/text/BitmapFontManager.test.ts

Closes #10893 
Adds a `trimEnd` option to `BitmapFontManager.measureText` to control whether or not whitespaces at the end of each lines are trimmed when calculating the text layout. By default it will keep trimming the whitespaces since in multi-line text trailing whitespaces should not cause a line break.

feat: Add option to `BitmapFontManager.measureText` to measure text with trailing whitespaces

---

src/ticker/Ticker.ts

fixed typo of scaler to scalar in docs

chore: Fix typo in Ticker

---

src/rendering/renderers/shared/texture/Texture.ts
src/rendering/renderers/shared/texture/utils/getCanvasTexture.ts
src/rendering/renderers/shared/view/ViewSystem.ts
tests/renderering/textures/VideoSource.test.ts

Adds a generic for Texture to specify the TextureSource type. This can help eliminate some type-casting.
```ts
const texture = new Texture();
const source = texture.source as CanvasSource;
```
```ts
const texture = new Texture({
source: new CanvasSource({
resource: canvas,
})
});
const source = texture.source; // CanvasSource
```

feat: Add generics Texture for TextureSource type

---

src/scene/graphics/shared/BatchableGraphics.ts
src/scene/graphics/shared/GraphicsPipe.ts

Fixes #10927. Needed to null the renderable property when sticking the BatchableGraphics back into the Pool for later reuse. 
Tried to add a visual test, but was proving a bit tricky to replicate in the visual testing env!

fix: graphics issue

---

src/events/EventBoundary.ts
src/events/EventSystem.ts

Fix #9749
Reset `defaultPrevented` when allocating events. This makes subsequent events behave correctly after `preventDefault()` has been called.

fix: Reset defaultPrevented in Events

---

src/scene/text-bitmap/BitmapText.ts

fixes: #10668
just adding a warning that you cant change the resolution of a bitmap text

fix: warn when trying to change BitmapText resolution

---

src/scene/text-bitmap/DynamicBitmapFont.ts

Assign canvas width to clear its context is not working for OffscreenCanvas. Change to use clearRect instead.
fix #10951

fix: DynamicBitmapFont destroy cleanup

---

src/rendering/renderers/gl/renderTarget/GlRenderTargetAdaptor.ts

In my work on @pixi-essentials/svg, I was seeing that copying from a canvas to a render texture was not working using `renderer.renderTarget.copyToTexture`, even though the signature accepts canvas sources. I traced it to PixiJS assigning the canvas texture a `null` framebuffer on binding to WebGL. This is because it incorrectly assumes that a canvas input must be the main canvas.
https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/bindFramebuffer
> A [WebGLFramebuffer](https://developer.mozilla.org/en-US/docs/Web/API/WebGLFramebuffer) object to bind, or [null](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/null) for binding the [HTMLCanvasElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement) or …

fix: Set framebuffer to null only when canvas source matches main canvas

---

src/scene/text-html/HTMLTextSystem.ts
src/scene/text-html/utils/getTemporaryCanvasFromImage.ts

#10962 introduced a bug where html text did not render correctly as we returned the canvas to the pool before using the result

fix: html text not rendering in WebGPU

---

src/scene/container/CustomRenderPipe.ts

fixes the issue where the `RenderableGCSystem` is calling `destroyRenderable` on the `CusomtRenderPipe` but it does not exist

fix: custom render pipe crashing with gc

---

src/rendering/renderers/gl/buffer/GlBufferSystem.ts
src/rendering/renderers/gl/geometry/GlGeometrySystem.ts
src/rendering/renderers/gl/shader/GlShaderSystem.ts
src/rendering/renderers/gl/texture/GlTextureSystem.ts
src/rendering/renderers/gpu/BindGroupSystem.ts
src/rendering/renderers/gpu/GpuUniformBatchPipe.ts
src/rendering/renderers/gpu/buffer/GpuBufferSystem.ts
src/rendering/renderers/gpu/texture/GpuTextureSystem.ts
src/rendering/renderers/shared/SchedulerSystem.ts
src/rendering/renderers/shared/renderTarget/RenderTargetSystem.ts
src/rendering/renderers/shared/texture/RenderableGCSystem.ts
src/scene/graphics/shared/GraphicsContextSystem.ts
src/scene/graphics/shared/GraphicsPipe.ts
src/scene/mesh/shared/MeshPipe.ts
src/scene/sprite-nine-slice/NineSliceSpritePipe.ts
src/scene/sprite-tiling/TilingSpritePipe.ts
src/scene/sprite/SpritePipe.ts
src/scene/text-bitmap/BitmapTextPipe.ts
src/scene/text-html/HTMLTextPipe.ts
src/scene/text/canvas/CanvasTextPipe.ts
src/utils/data/clean.ts
tests/renderering/UniformBatch.test.ts

Replacement for #10793
In PixiJS we make use of hashes to map data to things like renderables within pipes. To keep things efficinat we do not use 'delete' when an item needs to be removed, instead we simply set the property to null. Over time (with lots of destroy / create) the hashes could grow to be pretty large.
To prevent hashes from growing to large this PR introduces two new methods to the `RenderableGCSystem` that allow it to schedule clean up operations for hashes and arrays.

feat: clean hashes and arrays

---

src/scene/particle-container/shared/ParticleContainer.ts

the warning in the particle container causes a lot of spam as getting the bounds of its parent also logs this warning
so i have removed it and placed it in the description instead

fix: particle container warning spam

---

src/scene/container/Container.ts
tests/renderering/particle-container/ParticleContainer.test.ts

fixes #10999
Avoid removeChildren being called in container.super.destroy if the length of the children is 0. This is always the case for particle container, and so will stop the issuse from happening.
Added some tests to particle container too, to cover this and a few other things!

fix: particle container issue

---

package.json
src/scene/sprite-nine-slice/NineSliceSpritePipe.ts

fixes #11002
This will ensure that when resurrrected, the nineslice sprite renders correctly. Went for this approach, as did not want the pipe to explicitly set the `didViewUpdate` property, as it should only be reading that prop to keep the data flow simple.

fix: nineslice garbage collector bug

---

src/scene/particle-container/shared/Particle.ts

Add tint fallback of `Particle`, the same behavior of `Container`

fix: set tint fallback of Particle

---

src/scene/text-bitmap/DynamicBitmapFont.ts

fix #11019
Use the actual texture size calculated from the canvas in `pageData.canvasAndContext` instead of using `this._textureSize` to fill up the blanks and reduce the size of the resource.
From
To

fix: avoid blank space in the DynamicBitmapFont resource

---

README.md

On the website if you go to Header->API->v.8.x it still shows the readme for v7.
This is the only place where I found this content, is this used for v8 only? 
Or where does this page come from: https://pixijs.download/release/docs/index.html
- [x ] Tests passed (`npm run test`)

chore: Update Readme for v8

---

src/scene/graphics/shared/GraphicsContext.ts
tests/renderering/graphics/Graphics.Bounds.test.ts

When stroke instruction is used, bounds are extended by width of the stroke.
It should use alignment not hardcoded 0.5 multiplier.
Before this change, the element has increased size even if the alignment is set to 1 and stroke is inside of the original shape which should not affect bounds.

fix: stroke should use alignment when extending bounds

---

src/scene/graphics/shared/utils/convertFillInputToFillStyle.ts

Ensure we clone the matrix of a graphcis texture fill, as this is modified internally. Not cloning it was causing strange side effects. 
[Example](https://www.pixiplayground.com/#/edit/loZfVFhDhbueDEPSESGrn)
Step 1 - show the application in landscape
Step 2 - resize the window so the app is in portrait
Step 3 - resize the window so the app is in landscape

fix: Issue with texture matrix corrupting on graphics fill

---

src/scene/container/Container.ts
tests/scene/RenderGroup.tests.ts

Fixes an issue where adding a child to its existing parent that has render group enabled will not cause the scene to rebuild. 
Added a test to cover this situation too.
fixes #11039

fix: re-parent on render group issue

---

src/filters/FilterSystem.ts
tests/visual/scenes/filters/clip-top-viewport/clip-to-viewport.scene.ts

Fixes an issue where if a filter has a higher resolution than the root render target it was causing the bounds to be cropped. 
I also updated an existing test to cover this use case.
fixes #11051

fix: clipToViewport filter cropping at higher resolutions

---

src/rendering/renderers/shared/texture/sources/CanvasSource.ts

Removed incorrect (both canvas.height/width were checking against pixelWidth!) and redundant condtion, since `resizeCanvas` already has the correct condition in place for skipping resizing if the canvas is already the correct size.

fix: remove redundant/incorrect condition

---

src/scene/graphics/shared/fill/FillGradient.ts
tests/graphics/GraphicsFill.tests.ts

Silly us, we were creating the texture for the gradient each frame. This is no longer the case, create once use - often!
fixes #10936 and #11059

fix: FillGradient leak

---

src/rendering/renderers/gl/buffer/GlBuffer.ts
src/rendering/renderers/gl/buffer/GlBufferSystem.ts
src/rendering/renderers/gl/shader/GenerateShaderSyncCode.ts
src/rendering/renderers/gl/shader/GlProgram.ts
src/rendering/renderers/gl/shader/GlShaderSystem.ts
src/rendering/renderers/gl/shader/utils/createUboElementsSTD40.ts
src/rendering/renderers/gl/shader/utils/generateArraySyncSTD40.ts
src/rendering/renderers/gpu/shader/utils/generateArraySyncWGSL.ts
src/rendering/renderers/shared/buffer/Buffer.ts
src/rendering/renderers/shared/shader/UboSystem.ts
src/rendering/renderers/shared/shader/types.ts
src/rendering/renderers/shared/shader/utils/createUboSyncFunction.ts
src/rendering/renderers/shared/shader/utils/uboSyncFunctions.ts
tests/renderering/createUBOElementsSTD40.test.ts

Redo of #10738 on dev branch
WebGL UBO doesnt work in v8 at all, here's the fix that makes real app work. The app that can use all UBO slots in the same frame and sometimes need TransformFeedback
1. [STD140](https://www.oreilly.com/library/view/opengl-programming-guide/9780132748445/app09lev1sec2.html) , called sometimes STD40 in our code, never worked in pixi the right way. We managed to ignore smaller impl from threejs, and wrote something .. strange, that someimtes skips 8 floats to put next `vec3f`. Now it works.
2. Thing that puts Uniform Buffers into special slots was broken. "ok, first UBO exists, there's location. Second UBO? its not activated, lets use.. random location, maybe the same as first UBO"
3. It also does not account for buffers that can be used in TransformFeedback - …

fix: webgl uniform buffers (#10738)

---

src/scene/container/container-mixins/cacheAsTextureMixin.ts

- add docs to interface
Small PR to add backwards compatability for v7 cacheAsBitmap.

chore: add cacheAsBitmap deprecation

---

src/scene/container/RenderGroupPipe.ts

Fixes up cacheAsTexture so that it does not take into account the alpha of itself when rendering.

fix: cacheAsTexture so that it does not take into account the alpha of itself

---

.github/workflows/push.yml
scripts/types/fixTypes.ts

Closes #10464 
Our custom **fixTypes.ts** script was not handling Windows paths correctly with `glob`. Glob says: 
> Glob patterns should always use `/` as a path separator, even on Windows systems
Because we are using `process.cwd()`, this meant that mixins weren't getting added correctly causing type-chaos on dts-bundle.

fix: Window support for fixing types script

---

.eslintrc.json
src/rendering/renderers/gl/state/GlStateSystem.ts
src/rendering/renderers/shared/texture/RenderableGCSystem.ts
src/scene/container/utils/updateRenderGroupTransforms.ts
src/utils/data/clean.ts
tests/events/EventSystem.tests.ts

Follow-up to #11103 by enforcing assignment operators with an ESLint warning. Found a few other instance of operator assignments to be fixed up.

chore: Prefer operator assignment

---

src/filters/FilterSystem.ts
src/scene/container/RenderGroupPipe.ts
tests/visual/scenes/container/cache-as-texture.scene.ts

Fixes two issues
- when exporting a lower (or higher) resolution texture the bounds of the item were cliiped wrong if there was a filter in the exported items as the resolution was not being taken into account. 
- when using cacheAsTexture with antialiasing the texture was not rendering as the final blit call was not there. (test updated to accomodate this)

fix: a few render bugs

---

src/rendering/renderers/shared/extract/ExtractSystem.ts

When I tried to shard an image from a very large container, there was a serious memory leak

fix: Memory leak during canvas extraction

---

src/rendering/renderers/shared/texture/Texture.ts
src/scene/mesh/shared/MeshPipe.ts
src/scene/sprite-nine-slice/NineSliceSpritePipe.ts
src/scene/sprite-tiling/TilingSpritePipe.ts
src/scene/sprite/SpritePipe.ts
tests/renderering/sprite/Sprite.test.ts

there was a bug where swaping a textures source may not have triggered and update to the batches. This PR fixes that.
Test added too!
Updated the docs a bit too.

fix: Swapping texture source

---

src/assets/Assets.ts

Small comment fix, just adding the missing `.` in `bunny{png,webp}`, which should match the `bunny.png` and `bunny.webp` in the same comment.
(Currently, it's kinda confusing, I thought we need to put file ext like that and Pixi will add them automatically, i.e. `bunny{png,webp}` to `bunny.png` and `bunny.webp` but it's not)
This should fix the [online docs](https://pixijs.download/dev/docs/assets.Assets.html) too.

chore: update `Assets.ts` comment for src file ext

---

eslint.config.mjs
package.json

fixes the ignore list for eslint and also the fixes the watch command to remove the removed `postbuild` script

chore: fix lint ignore and watch script

---

src/rendering/renderers/shared/instructions/InstructionSet.ts
src/rendering/renderers/shared/texture/RenderableGCSystem.ts
src/rendering/renderers/shared/view/View.ts
src/scene/container/RenderGroup.ts
src/scene/container/__tests__/DummyView.ts
src/scene/container/utils/buildInstructions.ts
src/scene/view/ViewContainer.ts

Fixes up the `RenderableGC` class. A little bit of refactoring and tweaking to ensure it correctly destroys only what it needs to. I also added better documentaion. 
fixes #11135

fix: RenderableGC incorrectly cleaning up objects that are still in use 

---

src/assets/loader/parsers/loadWebFont.ts

- Since changed font name when caching, can't find that font from it font family name.

fix: unload family font caching

---

jest.config.js
src/scene/container/RenderGroup.ts
src/scene/container/__tests__/RenderGroup.test.ts

fixes a small issue that would not immediatly update the tints of children after calling `enableRenderGroup()`.

fix: flags not being updated after all enableRenderGroup

---

src/maths/__tests__/Circle.test.ts
src/maths/__tests__/Ellipse.test.ts
src/maths/__tests__/Polygon.test.ts
src/maths/__tests__/Rectangle.test.ts
src/maths/__tests__/RoundedRectangle.test.ts
src/maths/shapes/Circle.ts
src/maths/shapes/Ellipse.ts
src/maths/shapes/Polygon.ts
src/maths/shapes/Rectangle.ts
src/maths/shapes/RoundedRectangle.ts
src/maths/shapes/ShapePrimitive.ts
src/maths/shapes/Triangle.ts
src/scene/graphics/__tests__/Graphics.Bounds.test.ts
src/scene/graphics/shared/GraphicsContext.ts
src/scene/graphics/shared/path/ShapePath.ts

Alignment for stroke is not used in strokeContains() methods, result of the function should vary depend on alignment.

fix: strokeContains should use alignment

---

README.md

This pull request includes a small change to the `README.md` file. 
The change corrects the URL for the PixiJS Create CLI. Currently it redirects to a [404 page](https://github.com/pixijs/pixijs/blob/dev/pixijs.io/create-pixi)

fix: correct broken link to PixiJS Create CLI in README.md

---

src/events/FederatedPointerEvent.ts

As of TypeScript 5.7 the `PointerEvent` interface has added the [`altitudeAngle`]() and [`azimuthAngle`]() properties causing errors for users on that version of TypeScript. This PR adds them.
Closes #11145.

feat: Add `altitudeAngle` and `azimuthAngle` to `FederatedPointerEvent`

---

package.json
src/rendering/renderers/gl/buffer/GlBufferSystem.ts
src/rendering/renderers/gl/geometry/GlGeometrySystem.ts
src/rendering/renderers/gl/shader/GlShaderSystem.ts
src/rendering/renderers/gl/state/GlStateSystem.ts
src/rendering/renderers/gl/texture/GlTextureSystem.ts
src/rendering/renderers/shared/renderTarget/RenderTargetSystem.ts
src/rendering/renderers/shared/system/AbstractRenderer.ts

Add resetState() method to AbstractRenderer
This PR adds a new resetState() method to the AbstractRenderer class that allows developers to reset PixiJS's internal rendering state. This is particularly useful when integrating PixiJS with other WebGL libraries or frameworks that modify the WebGL context state.
When using PixiJS alongside other WebGL renderers (like Three.js), the WebGL context state can get out of sync since multiple renderers are modifying it. The resetState() method provides a clean way to reset PixiJS's internal state caches and ensure correct rendering after external WebGL state modifications.
WebGPU does not really rely on state as much and so does not require any changes!
```ts
// Reset Three.js state
threeRenderer.resetState();
// Render Three.js scene …
```

feat: add a `resetState` function to allow integration with other WebGL libraries

---

packages/assets/src/cache/Cache.ts
packages/assets/test/assets.tests.ts

We were checking the wrong value when testing if an asset is different, resulting in a bunch of warnings for things like spritesheets

Fix: incorrect cache warning check

---

packages/canvas-sprite/src/CanvasSpriteRenderer.ts

This addresses issue https://github.com/pixijs/pixijs/issues/11021
When trying to setup canvas mode using pixi v7.4.2, I've been getting badly rendered images when they are rotated in a spritesheet.
I came across issue https://github.com/pixijs/spine/issues/460, and found that the patch to fix that issue is missing from the 7.x branch (https://github.com/pixijs/pixijs/pull/8679/files). I forked the code example from 460 and set it up the way I have setup the pixi application in my app to demonstrate the issue here: https://codesandbox.io/p/sandbox/vigorous-rain-tlrf68.
Adding the code from 8679 fixed the issue for me when testing locally.

Apply #8679 to 7.x branch

---

src/rendering/renderers/shared/system/AbstractRenderer.ts

Fixed a little issue where clearBeforeRender property was not being respected by the renderer.

fix: clearBeforeRender not being respected

---

src/rendering/renderers/__tests__/Extract.test.ts
src/rendering/renderers/gl/texture/GlTextureSystem.ts
src/rendering/renderers/gl/texture/uploaders/glUploadImageResource.ts

Fixes an issue where `gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL` was not being set for any upload that is not an image.
Moved this check to outside of the image upload function and into GlTextureSystem.

fix: issue with premultiply alpha and non image based uploading

---

src/rendering/renderers/shared/texture/TexturePool.ts

Turns off the GC for pooled textures. This was causing horrible weird bugs.

fix: turn of garbage collection for pool

---

package.json
src/rendering/batcher/gl/GlBatchAdaptor.ts
src/rendering/renderers/shared/shader/Shader.ts
src/utils/data/uid.ts

An alternative to #11194 (thanks for the intial PR and debugging @davidetan, made this very easy to make). This fixes different batch shaders being bound incorrectly the first time they are used

fix: different batch shaders being bound incorrectly the first time they are used

---

src/assets/loader/__tests__/Loader.test.ts
src/assets/loader/parsers/textures/loadTextures.ts

Added error handling when using Image to upload images. Currently, in this mode, Promise will never be allowed (for example, in the case of an incorrect url)

fix: loadTextures.load add onerror for Image case

---

src/rendering/renderers/shared/texture/Texture.ts

changes "an texture" to "a texture"
Fixes a typo in the documentation.
None applicable.

fix: Typo in documentation Texture.ts

---

src/scene/text/canvas/CanvasTextMetrics.ts

Updates the example in CanvasTextMetrics documentation to use the correct `CanvasTextMetrics` class instead of the outdated `TextMetrics`.
Fixes #11205

chore: update CanvasTextMetrics example to use correct class

---

src/compressed-textures/dds/parseDDS.ts

Each dimension must be aligned to a multiple of 4 for BC formats. If a dimension isn’t a multiple of 4, round up to the nearest multiple of 4
Each dimension must be aligned to a multiple of 4 for BC formats. If a dimension isn’t a multiple of 4, round up to the nearest multiple of 4.
Current calculated values in dev
Renderer only show the dds image in maximum size, but using any of mipmap no work because the warning
File used:
[acolyteofchayulaascendancy.zip](https://github.com/user-attachments/files/18455270/acolyteofchayulaascendancy.zip)

fix: DDS BC format need Alignment Blocks

---

package.json
scripts/utils/exports.ts
src/gif/init.ts
src/index.ts

We are currently not exporting the new gif classes and this PR allows for them to be imported like this:
```ts
import { GifSprite } from 'pixi.js/gif' // asset extension is added automatically 
// use gif
```

fix: gif export

---

src/accessibility/AccessibilitySystem.ts
src/rendering/renderers/shared/system/SharedSystems.ts

A couple of things slipped through the #11107 PR 
- accessibility system being added to shared systems resulting is causing circular type issues
- default options for accessibility system being nested incorrectly

fix: accessibility system being added to shared systems

---

src/scene/sprite-animated/AnimatedSprite.ts

Adds several of `AnimatedSprite`'s configurable options to its constructor options. This allows the following properties to be set when creating a new `AnimatedSprite`:
* `animationSpeed`
* `loop`
* `onComplete`
* `onFrameChange`
* `onLoop`
* `updateAnchor`

feat: add configurable props to `AnimatedSpriteOptions`

---

src/scene/sprite-animated/AnimatedSprite.ts
src/scene/sprite-animated/__tests__/AnimatedSprite.test.ts

Adds `autoPlay` to the constructor options of `AnimatedSprite`. Passing this when creating an `AnimatedSprite` allows the animation to be started without having to call `.play()` after instantiation.

feat: add `autoPlay` to `AnimatedSprite`

---

src/rendering/renderers/gl/renderTarget/GlRenderTargetAdaptor.ts
src/rendering/renderers/shared/renderTarget/RenderTargetSystem.ts

I ended up reverting this change. As  the copyToTexture use case is not really somthing devs should be doing as there are more efficient ways to deal with this! I added a note on the function to make that clear too.
To fix this would introduce some unnecassery complexity imo. But happy to discuss if people feel im wrong! Thanks!
Fixes #11168

fix: multiview rendering

---

src/scene/sprite-nine-slice/NineSliceSprite.ts
src/scene/sprite-nine-slice/NineSliceSpriteMixins.d.ts
src/scene/sprite-nine-slice/__tests__/NineSliceSprite.test.ts
src/scene/sprite-tiling/TilingSprite.ts
types/PixiMixins.d.ts

This pull request focuses on fixing the bounds calculation and enhancing the test coverage for the `NineSliceSprite` and `TilingSprite` classes.
* [`src/scene/sprite-nine-slice/NineSliceSprite.ts`](diffhunk://#diff-a4e272501ec4d6d11a1e7a36db50ea22626b8a5da500d9a4c234dfba174a050dL355-R359): Corrected the calculation of `minX`, `maxX`, `minY`, and `maxY` to ensure accurate bounds for the `NineSliceSprite` class.
* [`src/scene/sprite-tiling/TilingSprite.ts`](diffhunk://#diff-61def0fe2af7c28af1990483047578d8b9abcaaba48a626c0a65877f8c11660cL429-R433): Adjusted the calculation of `minX`, `maxX`, `minY`, and `maxY` to fix the bounds for the `TilingSprite` class.
* [`src/scene/sprite-nine-slice/__tests__/NineSliceSprite.test.ts`](diffhunk://#diff-d230732fb0b9c4a83afbe74da8898d945a6204b2a01e70a10d1 …

fix: tiling sprite and nine slice sprite bounds being negative

---

package.json
scripts/fixDistTags.ts

I've been having to manually run this script after releases. After doing 7.4.3 release today, I  decided we should add it to the publishing workflow.

chore: Fix tags upon release

---

src/rendering/renderers/shared/texture/sources/CanvasSource.ts
src/rendering/renderers/shared/view/ViewSystem.ts

Closes #10993 
* Fixes startup crash (or calling `resizeCanvas()`) when using `autoDensity` with an OffscreenCanvas

fix: Ignore autoDensity for OffscreenCanvas

---

src/rendering/renderers/gl/context/GlContextSystem.ts
tests/visual/scenes/compressed-textures/restore-context.scene.ts

After restoring the context, you usually need to reactivate or reinitialize any WebGL extensions manually because they are not automatically restored.
This is related to https://github.com/pixijs/pixijs/issues/11247 and possibly another issues concerning context restoration.

fix: Restore gl extensions state on context restore

---

src/scene/graphics/shared/fill/FillGradient.ts

Right now, aliases are not converted to relative imports during build. This causes invalid imports to appear in the final .d.ts files. One of them is the `PointData` import in `FillGradient` (you can see it [here](https://unpkg.com/browse/pixi.js@8.8.1/lib/scene/graphics/shared/fill/FillGradient.d.ts#L3), for example).
So I replaced the alias import of `PointData` with a relative one and also made it fully type-only

fix: don't use alias for `PointData` import

---

src/rendering/renderers/gl/texture/GlTextureSystem.ts
src/rendering/renderers/shared/texture/__tests__/GLTextureSystem.test.ts

fix: reset premultiply alpha state on resetState call and update WebGL settings

---

src/scene/container/__tests__/Container.test.ts
src/scene/container/container-mixins/childrenHelperMixin.ts

Fix issue where when destroying a container - the children were not being removed from the render layers. 
Added test too.
fixes #11373

fix: render layer detachment when destroying.

---

babel.config.js
jest.config.js
package-lock.json
package.json
tsconfig.json

I want to update earcut to v3.0.0 because I have a project that makes their own `earcut` global that conflicts with the 2.0.0 era global `earcut` variable with TypeScript typings.
Wrangling with Jest unfortunately took most of the time because apparently its support for node module dependencies written in ESM is lacking. If anyone knows of a better way I'm all ears!

feat: update Earcut to v3.0.0

---

src/scene/text-bitmap/BitmapFont.ts

This updates the BitmapFont doc to match the new signature for 8.x. The `BitmapFont.install(...)` part of the example wasn't updated from 7.x.

chore: Update BitmapFont.ts doc for 8.x

---

src/maths/__tests__/ObservablePoint.test.ts
src/maths/point/ObservablePoint.ts

- add Jest spec checking `ObservablePoint.toString()` outputs current coordinates
- `npm test` *(fails: run-s not found)*

fix: ObservablePoint toString

---

src/scene/text-html/HTMLTextStyle.ts
src/scene/text-html/__tests__/HTMLTextStyle.test.ts

Fixes cloning of css overrides and tag styles in HTMLTextStyle.
Ensures that cloned styles have independent copies of css overrides
and tag styles.
Also, ensures that cssOverrides is initialized as an empty array
instead of relying on the nullish coalescing operator.

fix: HTMLTextStyle clone and css overrides assignment

---

src/assets/loader/parsers/textures/loadVideoTextures.ts

This fixes bug #10633, tested on both an iPad and iPhone. load() is not called on the video element at all when autoload is false and preload is true.

fix: iOS issue loading video when autoplay is false and preload is true.

---

.vscode/settings.json
src/scene/particle-container/shared/Particle.ts
src/scene/particle-container/shared/__tests__/Particle.test.ts

* Fix: Always normalize Particle's `tint` input as RGB format, even for integers.
Closes #11478

fix: remove special number casing for particle tint

---

.vscode/settings.json
package-lock.json
package.json
src/maths/shapes/Circle.ts
src/maths/shapes/Ellipse.ts
src/maths/shapes/Polygon.ts
src/maths/shapes/Rectangle.ts
src/maths/shapes/RoundedRectangle.ts
src/maths/shapes/Triangle.ts
src/rendering/renderers/gl/WebGLRenderer.ts
src/scene/__docs__/scene-text-overview.md
src/scene/graphics/shared/FillTypes.ts
src/scene/text-bitmap/BitmapFontManager.ts
src/scene/text-html/HTMLText.ts
src/scene/text/Text.ts

Updates TypeDoc to the latest version. This fixes the issue of random frag/vert files appearing in the docs.
Updates documentation for `alignment` and `textureStyle`. fixes #11494

chore: update typedoc and minor doc fixes

---

src/assets/loader/parsers/textures/loadSVG.ts
src/rendering/renderers/gl/texture/utils/getSupportedGlCompressedTextureFormats.ts
src/utils/browser/detectVideoAlphaMode.ts

Addresses: https://github.com/pixijs/pixijs/issues/11545#issuecomment-3077774625
* Replaces `document.createElement('canvas')` with `DOMAdapter.get().createCanvas()`
cc @UlyssesZh

fix: Add missing createCanvas calls

---

typedoc.json

Fixes #11535
Thanks for pointing out this option @UlyssesZh

fix: Boost classes in the docs search results

---

src/scene/text/TextStyle.ts
src/scene/text/__tests__/TextStyle.test.ts

Fixes: #10595
Corrects the fillGradientStops implementation in TextStyle when converting from v7 to v8 styles.
One thing to note is that unlike v7, v8 needs to have the number of fills match the number of stops. I don''t think we should be back porting the v7 implementation here, so I have added a warning for when they don't match

fix: fillGradientStop logic in TextStyle

---

src/scene/graphics/__tests__/Graphics.Destroy.test.ts
src/scene/graphics/shared/GraphicsContext.ts
src/scene/graphics/shared/fill/FillGradient.ts
src/scene/graphics/shared/fill/FillPattern.ts

Fixes: #11218
Ensures proper destruction of resources associated with Graphics and fills, preventing memory leaks.
This change introduces `destroy` methods to `FillGradient` and `FillPattern` to release their textures and other resources.
The GraphicsContext now utilizes these destroy methods when cleaning up fills during its own destruction.
A new test case is added to verify the correct destruction behavior.

fix: resource leak in Graphics and fills

---

src/scene/sprite-animated/AnimatedSprite.ts
src/scene/sprite-animated/__tests__/AnimatedSprite.test.ts

Fixes: #11407
Ensures that all textures associated with the AnimatedSprite are properly destroyed.
This prevents memory leaks when the sprite is no longer needed.
Addresses an issue where textures were not being disposed when the AnimatedSprite was destroyed with the `texture` option.

fix: AnimatedSprite destroy method

---

src/assets/Assets.ts
src/assets/__tests__/Assets.test.ts
src/assets/__tests__/bundle.test.ts

Fixes: #10981
The progress is now correctly reported for both individual assets and asset bundles.

fix: progress tracking for asset bundles

---

src/rendering/renderers/shared/view/ViewSystem.ts

Fixes: #11592
Texture in ViewSystem retains the detached canvas from being collected by GC.

fix: destroy texture during ViewSystem cleanup to prevent resource leaks

---

src/scene/graphics/shared/GraphicsContext.ts

Currently, every attempt to access the Graphics(GraphicsContext) boundaries causes them to be recalculated, regardless of whether the content has changed.

fix: reset bounds dirty flag in GraphicsContext to prevent recalculations on each access

---

src/scene/sprite-tiling/TilingSprite.ts
src/utils/logging/deprecation.ts

Fixes: #9491, #10216
- Added `quiet` and `noColor` options to control global deprecation message behavior for more flexible usage.
- Replaced `warn` method with `deprecation` in `TilingSprite`.
I chose names `quiet` and `noColor` instead of `silence` and `simple` (suggested in the issue), just because they are pretty common in software development (especially in CLI).  
Introduced API:
```ts
import { deprecation } from 'pixi.js';
// Supresses deprecation warnings
deprecation.quiet = true;
// Removes color formatting from deprecation messages
deprecation.noColor = true;
```

feat: suppression and colorization options for deprecation message

---

.github/workflows/stack-blitz-publish.yaml

Just a minor fix that prevents publishing to StackBlitz in any fork repository.

chore: conditionally disable StackBlitz publish workflow on non-origin repositories

---

src/rendering/renderers/shared/shader/UniformGroup.ts
src/rendering/renderers/shared/shader/__tests__/UniformGroup.test.ts

Improve error message in UniformGroup when users attempt to use unsupported `array<type, size>` syntax.
Previously, users would get a generic error listing all supported types. Now they get a specific, actionable error message explaining the correct syntax to use instead.
**Before:**
```
Uniform type array<i32, 100> is not supported. Supported uniform types are: f32, i32, vec2, vec3, vec4, mat2x2, mat3x3, mat4x4, mat3x2, mat4x2, mat2x3, mat4x3, mat2x4, mat3x4
```
**After:**
```
Uniform type array<i32, 100> is not supported. Use type: 'i32', size: 100 instead.
```
**Changes made:**
- Added regex detection for `array<type, size>` pattern in UniformGroup constructor
- Extract inner type and size from array syntax and suggest correct format
- Added comprehensive tests covering various array …

fix: improve error message for array uniform syntax

---

src/events/FederatedEventTarget.ts

When using `strictNullChecks`, TypeScript differentiates between `undefined` and `null`. For codebases using this Pixi in the latest version was producing the following error:
>  Interface '[...].Container<C>' incorrectly extends interface 'PixiMixins.Container<C>'
>   Types of property 'parent' are incompatible
>     Type 'Container<ContainerChild> | null' is not assignable to type 'Container<ContainerChild> | undefined'
This PR widens the `parent` type in `IFederatedContainer` (from which `PixiMixins.Container` extends) in order to fix this issue.

fix: Fix incompatible `parent` type on `IFederatedContainer`

---

src/scene/text-bitmap/utils/getBitmapTextLayout.ts

BitmapText now renders empty lines of text as it is supposed to. You can see attached images of before and after.
Fixes https://github.com/pixijs/pixijs/issues/10463

fix: applying nextLine to BitmapTextLayout so it renders newlines properly

---

package-lock.json
package.json
src/scene/text-bitmap/BitmapFontManager.ts
src/scene/text/__tests__/TextMetrics.test.ts
src/scene/text/canvas/CanvasTextMetrics.ts

Introduces caching mechanisms for bitmap font layouts and canvas text metrics to reduce redundant calculations.
This code was from the original cache text PR: #11505, split out to make reviewing easier

feat: add LRU cache for text measuring

---

src/scene/text/TextStyle.ts
src/scene/text/canvas/CanvasTextSystem.ts
src/scene/text/utils/generateTextStyleKey.ts

Ensures that filter arrays are treated as read-only within the text style, preventing unintended external
modifications.
This code was from the original cache text PR: #11505, split out to make reviewing easier

fix: make text filters immutable

---

src/rendering/renderers/gpu/GpuEncoderSystem.ts

`setVertexBuffer` expect to get a number as index but right now it's a string. 
It works fine in browser, but in ReactNative with react-native-wgpu it leads to an error.

fix: cast index type to number as it required by setVertexBuffer

---

.huskyrc

I occasionally use GitHub Desktop to manage commits, but it was complaining about husky:
> .husky/pre-commit: line 4: npx: command not found husky - pre-commit hook exited with code 127 (error) husky - command not found in PATH=/Applications/GitHub Desktop.app/Contents/Resources/app/git/libexec/git-core:/usr/bin:/bin:/usr/sbin:/sbin
Solution found here: 
https://github.com/typicode/husky/issues/912

fix: supports husky to run without PATH

---

src/unsafe-eval/particle/generateParticleUpdatePolyfill.ts

Fix unsafe-eval `generateParticleUpdatePolyfill` for updated function signature.
The polyfill did not match the original function signature and thus caused `filter is not a function` errors.

fix: unsafe-eval particle update polyfill

---

src/app/__tests__/Application.test.ts
src/rendering/renderers/gpu/shader/BindGroup.ts
src/scene/graphics/shared/BatchableGraphics.ts

Originally reported on discord: [message](https://discord.com/channels/734147990985375826/1143191340230914068/1413101088680317030)
Fixes issue with graphics double destroying the batcher. The batcher is already getting tidied up as its part of its own pool
Adds a test case to verify that all children, including graphics, sprites, and text, are destroyed when the destroy method is called with the appropriate options.

fix: application destroy for graphics

---

src/prepare/PrepareBase.ts
src/prepare/PrepareSystem.ts
src/prepare/__tests__/PrepareSystem.test.ts
src/scene/text/canvas/BatchableText.ts
src/scene/text/canvas/CanvasTextSystem.ts

Fixes: #11613
- BatchableText now verifies that the texture exists before trying to return it.
- PrepareSystem now does not throw an error if it's destroyed before all items from the queue are uploaded.

fix: destroy of prepared but not rendered text should not throw an error

---

src/assets/Assets.ts
src/assets/__docs__/assets-overview.md
src/assets/__tests__/Assets.test.ts
src/assets/__tests__/bundle.test.ts
src/assets/loader/Loader.ts
src/assets/loader/__tests__/Loader.test.ts

Adds load options for configuring asset loading behavior, including retry strategies and error handling.
Provides a new `LoadOptions` interface with properties for:
- Progress and error callbacks
- Failure handling strategies ('throw', 'skip', 'retry')
- 'throw': Immediately throw an error and stop loading (default)
- 'skip': Skip the failed asset and continue loading others
- 'retry': Retry loading the asset a specified number of times  
- Retry attempt count and delay
example:
```ts
const options: LoadOptions = {
strategy: 'retry',
retryCount: 5, // Retry up to 5 times
};
await Assets.load('unstable-asset.png', options);
```
```ts
await Assets.init({
basePath,
loadOptions: { strategy: 'skip', onError: (error, asset) => console.log(error, asset.url) },
});
Assets.addBundle('testBundle', …
```

feat: add asset loading strategies

---

src/rendering/renderers/gl/geometry/GlGeometrySystem.ts

While working on a project using webgl instanced rendering with varying instance counts, I found one instance of the geometry would always be rendered even when `geometry.instanceCount = 0`, with the same behaviour for negative instance counts.
From a look through the source, it seemed to be due to a conditional in the GlGeometrySystem draw method that would always fall back to a drawElements/drawArrays call for all instanceCount values less than 2. This also led to webgl render errors in cases where instance attribute buffers would be empty when no instances were expected to be drawn.
I'm currently using the following patch in my project which fixes the issue so I think this is on the right track.
```ts
const app = new Application();
await app.init({ background: "#011d4c", resizeTo: …
```

fix: modify conditional to skip draw call when instanceCount < 1

---

src/scene/text/canvas/CanvasTextPipe.ts

Fixes: #11675 
- Text bounds may be influenced by several factors unrelated to direct text/style changes, so we must update them accordingly. The same approach is already in place for `HTMLTextPipe`.

fix: ensure `updateTextBounds` is called regardless of style and resolution change

---

src/events/FederatedEventTarget.ts
src/scene/container/Container.ts
src/scene/container/container-mixins/childrenHelperMixin.ts
src/scene/container/container-mixins/collectRenderablesMixin.ts
src/scene/container/container-mixins/getFastGlobalBoundsMixin.ts
src/scene/layers/RenderLayer.ts
src/scene/layers/__tests__/RenderLayer.test.ts
src/scene/particle-container/shared/ParticleContainer.ts
src/scene/view/ViewContainer.ts

Currently it is possible to provide a `IRenderLayer` as an argument to the `Container`'s `addChild` but it is not possible to provide it as an element of `children` in `ContainerOptions`.
Before this patch the following gives a typescript error:
```ts
new Container({
children: [
new RenderLayer(),
]
})
```
while
```ts
const container = new Container();
container.addChild(new RenderLayer());
```
works without typescript type error. With this change both of these cases work.
This change will also have the following side effect:
```ts
// Before patch
const parentContainer = new Container<ContainerChild>();
for (const childContainer of parentContainer.children) {
// Calling container method on childContainer is always possible
childContainer.getGlobalTint()
}
// After patch
const …
```

fix: Allow IRenderLayer as part of the ContainerOptions children array

---

src/accessibility/AccessibilitySystem.ts

Fixes: #11698
Ensures event listeners are properly removed to prevent crash.
Stores bound function references for event listeners and uses these to properly remove the listeners.
This also ensures that unless you explicitly enable the accessibility system the `keydown` listener is not added. This can be through init options or calling setAccessibilityEnabled

fix: removes accessibility system event listeners correctly

---

src/math-extras/MathExtraMixins.d.ts
src/math-extras/__tests__/Point.test.ts
src/math-extras/pointExtras.ts

Added a vector rotation method to the Point and ObservablePoint classes in `math-extras`
Includes types, tests, and docs
Related question:
Is there a way to generate type data for the files like `pointExtras.d.ts` and `rectangelExtras.d.ts` ? 
You can currently do stuff like `import { multiplyScalar } from '@pixi/math-extras/lib/pointExtras.js'` but it is missing type data. This would let you import and mixin only the methods you are using

feat: added rotate to Point math-extras
